<?php
/**
* @name       index.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of website
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function() {
	
	$('#ddlrouteseq_chzn .chzn-drop .chzn-search input[type="text"]').focus();
	$('#ddlrouteseq_chzn').addClass('chzn-container-active');
	
	$('#ddltablet_synmode').change(function(){
		synmode(this.value);
	})
	
	<?php if($this->formdata['ddltablet_synmode'] != 2) {	
			echo "$('#txttimeinterval').val(''); $('#divint').hide();";
		} else {
			echo "synmode(2)";
		}
	?>
});


function synmode(cval)
{
	if(cval == '2') {
		$('#divint').show();
	}
	else {
		$('#txttimeinterval').val('');
		$('#divint').hide();
	}
}
</script>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="admin_index_index">
<form method="post" action="" class="validate" validate=validate>
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_administration.png">
        <h3><?php echo $this->translate->_('Basic Setup');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btncancel" id="btncancel"></div>
    
    <?php if($this->checkaccess("update")) { ?>
        <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    <?php } ?>

    </div>
</div>
    <div class="content no-padding with-actions" style="min-height:350px;">
	        <div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
	    <label class="_25_1 padding_0 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Route Sequence').''.$this->colan;?>
	    </label>
            <div class="_30_1 ">
		<select id="ddlrouteseq" name="ddlrouteseq">

                        <?php
			    for($i=0;$i<count($this->routeseq);$i++)
			    {
			?>
				<option value="<?php echo $this->routeseq[$i]['id'];?>" <?php echo ($this->routeseq[$i]['id'] == $this->formdata['ddlrouteseq']) ? 'selected' : ''; ?> ><?php echo $this->routeseq[$i]['val'];?></option>
			<?php } ?>

		</select>
            </div>
	    <div class="_5 margin_top_5">
                <input type="checkbox" id="chkprevdayupl" name="chkprevdayupl" value="1" <?php echo ($this->formdata['chkprevdayupl'] == 1) ? 'checked' : ''; ?> >
            </div>
	    <label class="_30 margin_top_12 text_align">
		<?php echo $this->translate->_('Allow Previous Day Upload Sync');?>
	    </label>	    
        </div>
	<div class="_100">
	    <label class="_25_1 padding_0 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Route Journey Plan').''.$this->colan;?>
	    </label>
            <div class="_30_1 ">
		<select id="ddljourneyplan" name="ddljourneyplan">

                    <?php
			    for($i=0;$i<count($this->journeyplan);$i++)
			    {
			?>
				<option value="<?php echo $this->journeyplan[$i]['id'];?>" <?php echo ($this->journeyplan[$i]['id'] == $this->formdata['ddljourneyplan']) ? 'selected' : ''; ?> >
                                    <?php echo $this->journeyplan[$i]['val'];?>
                                </option>
			<?php } ?>
		</select>
            </div>
	    <div class="_5 margin_top_5">
                <input type="checkbox" id="chkprepfileupl" name="chkprepfileupl" value="1" <?php echo ($this->formdata['chkprepfileupl'] == 1) ? 'checked' : ''; ?> >
            </div>
	    <label class="_30 margin_top_12 text_align">
		<?php echo $this->translate->_('Allow Import Sync After Upload Sync');?>
	    </label>
	    
	</div>
	
	<div class="_100">
	    <label class="_25_1 padding_0 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Inventory Load Transfers').''.$this->colan;?>
	    </label>
            <div class="_30_1 ">
		<select id="ddltransinv" name="ddltransinv">
            <?php for($i=0;$i<count($this->transinv);$i++)
			    {
			?>
				<option value="<?php echo $this->transinv[$i]['id'];?>" <?php echo ($this->transinv[$i]['id'] == $this->formdata['ddltransinv']) ? 'selected' : ''; ?> >
                    <?php echo $this->transinv[$i]['val'];?>
                </option>

			<?php } ?>
			</select>
            </div>
	    <div class="_5 margin_top_3">
                <input type="checkbox" id="chkresfileday" name="chkresfileday" value="1" <?php echo ($this->formdata['chkresfileday'] == 1) ? 'checked' : ''; ?>>
            </div>
	    <label class="_30 margin_top_12 text_align">
		<?php echo $this->translate->_('Restrict Multiple Import Sync');?>
	    </label>	   
	</div> 
	<div class="_100">
	    <label class="_25_1 padding_0 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Tablet Transaction Sync Mode').''.$this->colan;?>
	    </label>
	    <div class="_30_1 ">
			<select id="ddltablet_synmode" name="ddltablet_synmode">
				<option value="">--- Select ---</option>
				<option value="1" <?php if($this->formdata['ddltablet_synmode'] == 1) { echo 'selected';}?>><?php echo $this->translate->_('Online'); ?></option>
				<option value="2" <?php if($this->formdata['ddltablet_synmode'] == 2) { echo 'selected';}?>><?php echo $this->translate->_('Batch'); ?></option>
				<option value="3" <?php if($this->formdata['ddltablet_synmode'] == 3) { echo 'selected';}?>><?php echo $this->translate->_('Manual'); ?></option>
			</select>
	    </div>
	    <div class="_5 margin_top_5">
                <input type="checkbox" id="chksalesmancust"  name="chksalesmancust" value="1" <?php echo ($this->formdata['chksalesmancust'] == 1) ? 'checked' : ''; ?>>
            </div>
	    <label class="_30 margin_top_12 text_align">
		<?php echo $this->translate->_('Allow Multiple Salesman To Visit A Customer');?>
	    </label>	    
        </div>
	<?php /*
	<div class="_100">
	    <label class="_25_1 padding_0 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Average Parameter %').''.$this->colan;?>
	    </label>
	    <div class="_30_1 ">
			<input name="txtavgpara" id="txtavgpara" maxlength="4" class="margin_top_5 number" type="text" value="<?php echo $this->formdata['txtavgpara'];?>">
		</div>	    
	</div>
		  */ ?>

	<div class="_100">
	    <label class="_25_1 padding_0 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Mis Report').''.$this->colan;?>
	    </label>
	    <div class="_30_1 ">
			<input name="txtmisrpt" id="txtmisrpt" class="margin_top_5" type="text" value="<?php echo $this->formdata['txtmisrpt'];?>">
		</div>	    
	</div>
	<div class="_100" id="divint">
	    <label class="_25_1 margin_top_10 label_text_align">
		<?php echo $this->translate->_('Tablet Transaction Sync time interval').''.$this->colan;?>
	    </label>
            <div class="_30_1">
                <input name="txttimeinterval" id="txttimeinterval" maxlength="5" class="margin_top_5" type="text" value="<?php echo $this->formdata['txttimeinterval'];?>">
            </div>
    </div>
	<div class="_100 space_20"></div>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="hdnweekday" name="hdnweekday" value="<?php echo $this->formdata['cnt']; ?>">
</form>
</div> <!-- End of .box -->
</div>