<?php
/**
* @name       index.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of website
*/
?>
<div class="clean"></div>
<div class="grid_12">
<?php /*
 * <div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li class="current">
		    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"index","action"=>"index"),"default", true);?>"><?php echo $this->overview?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"index","action"=>"setupset"),"default", true);?>"><?php echo $this->setting;?></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
*/ ?>
<div class="box">
<form method="post" action="">
<div class="header">
        <div class="_50_3 back_btn">
	    <img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_administration.png">
	    <h3><?php echo $this->setting?></h3>
	</div>
	<div class="_50_3">
	    <div class="_10 save_btn"><input class="border_none" type="button" value="" name="btncancel" id="btncancel"></div>
	    <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
	</div>
</div>

    <div class="content no-padding with-actions">
	        <div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100">
            <label class="_40 margin_top_15 text_align_right">
                <?php echo $this->transactionid.''.$this->required;?>
            </label>
            <div class="_50">
                <input name="txtcode" id="txtcode" type="text" class="required text_align">
            </div>
        </div>
	<div class=" _100">
            <label class="_40 margin_top_15 text_align_right">
                <?php echo $this->hhc_import_file_path.''.$this->required;?>
            </label>
            <div class="_50">
                <input name="txtcode" id="txtcode" type="text" class="required text_align">
            </div>
        </div>
	<div class=" _100">
            <label class="_40 margin_top_15 text_align_right">
                <?php echo $this->hhc_download_file_path;?>
            </label>
            <div class="_50">
                <input name="txtcode" id="txtcode" type="text" class="required text_align">
            </div>
        </div>
	<div class=" _100">
            <label class="_40 margin_top_15 text_align_right">
                <?php echo $this->hhc_upload_file_path;?>
            </label>
            <div class="_50">
                <input name="txtcode" id="txtcode" type="text" class="required text_align">
            </div>
        </div>
	<div class=" _100">
            <label class="_40 margin_top_15 text_align_right">
                <?php echo $this->hhc_export_file_path;?>
            </label>
            <div class="_50">
                <input name="txtcode" id="txtcode" type="text" class="required text_align">
            </div>
        </div>
	<div class=" _100">
            <label class="_40 margin_top_15 text_align_right">
                <?php echo $this->hhc_backup_file_path;?>
            </label>
            <div class="_50">
                <input name="txtcode" id="txtcode" type="text" class="required">
            </div>
        </div>
	<div class=" _100">
            <label class="_40 margin_top_15 text_align_right">
                <?php echo $this->copy_prepare_fileto;?>
            </label>
            <div class="_50">
                <input name="txtcode" id="txtcode" type="text" class="required  text_align">
            </div>
        </div>
	<div class=" _100">
            <label class="_40 margin_top_15 text_align_right">
                <?php echo $this->copy_sesion_fileto;?>
            </label>
            <div class="_50">
                <input name="txtcode" id="txtcode" type="text" class="required  text_align">
            </div>
        </div>
    </div>
<!--    <div class="actions">
        <div class="actions-left">&nbsp;</div>
        <div class="actions-right">
            <input type="submit" id="btnsubmit" name="btnsubmitsetting" value="<?php echo $this->initialise_variables;?>">
        </div>
    </div>-->
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</form>
</div> <!-- End of .box -->