<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?> 
<table id="search" ></table>
<div id="pagersr"></div>
<style>
  @media print { @page { margin: 0; } 
   body { margin: 1.6cm; } }
</style>
<script  type="text/javascript">
 
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({
   	url:base_url+"/reports/transactiondepositsummary/depositsum/",
	datatype: "json",
   		colNames:['<?php echo $this->translate->_('Route');?>','<?php echo $this->translate->_('Transaction Date');?>',
	'<?php echo $this->translate->_('Customer');?>',
	'<?php echo $this->translate->_('Receipt');?>',
	'<?php echo $this->translate->_('Type');?>',
	'<?php echo $this->translate->_('Immediate Cash');?>',
	'<?php echo $this->translate->_('Immediate Cheque');?>',
	'<?php echo $this->translate->_('Total');?>'],
	colModel:[
	
		{name:'routecode',index:'routecode', width:150},
		{name:'transactiondate',index:'transactiondate', width:120},
		{name:'CustomerCode',index:'CustomerCode', width:350},
		{name:'invoicenumber',index:'invoicenumber', width:120},
		{name:'trantype',index:'trantype', width:120},		
		{name:'immediatecash',index:'immediatecash', width:120,summaryType:'sum', formatter: 'number',align:"right",formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
		{name:'immediatecheck',index:'immediatecheck', width:120,summaryType:'sum', formatter: 'number',align:"right",formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
        {name:'total',index:'total', width:150,summaryType:'sum', formatter: 'number',align:"right",formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }}
		
		
		
		
		
	],
    <?php if($this->session->lang == "ar_AR") { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
   	pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
    footerrow : true,
	userDataOnFooter : true,
   	altRows : false,
    grouping:false,
    groupingView :
    {
        groupField : ['routecode'],
        groupColumnShow : [true],
        groupCollapse : true,
        groupOrder: ['asc']
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});

</script>
<br>
<br>
<div class="btmtable" style="padding-top:100px">
 <div style="  width: 100%;" >
	<span style="padding-left:50%;">
	 
	________________________
	</span>
	<span style="padding-left:5%">
	________________________

	</span>
	</div>
	 <div style="  width: 100%;" >
	<span style="padding-left:50%;">
	
	Salesman Signature
	</span>
	<span style="padding-left:10%">
	Account Signature

	</span>
	</div>
<div>