<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">

jQuery("#search").jqGrid({        
   	url:base_url+"/reports/transactionpaymentsummary/paymentsum/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route');?>','<?php echo $this->translate->_('Type');?>','<?php echo $this->translate->_('Transaction Date');?>','<?php echo $this->translate->_('Transaction Time');?>','<?php echo $this->translate->_('Salesman Code');?>','<?php echo $this->translate->_('Customer Code');?>','<?php echo $this->translate->_('Customer Name');?>','<?php echo $this->translate->_('Invoice Number');?>','<?php echo $this->translate->_('MOP');?>','<?php echo $this->translate->_('Total Invoice Amount');?>','<?php echo $this->translate->_('Immediate CASH Payment');?>','<?php echo $this->translate->_('Immediate Cheque Payment');?>','<?php echo $this->translate->_('AR CASH Collection');?>','<?php echo $this->translate->_('AR Cheque Collection');?>','<?php echo $this->translate->_('Outstanding Balance Amount');?>'],
   	colModel:[
   		{name:'routecode',index:'routecode', width:100},
		{name:'hocode',index:'hocode', width:200},
		{name:'transactiondate',index:'transactiondate', width:90},
		{name:'transactiontime',index:'transactiontime', width:70},
        {name:'salesmancode',index:'salesmancode', width:70},
        {name:'customercode',index:'customercode', width:90},
        {name:'customername',index:'customername', width:250},
        {name:'invoicenumber',index:'invoicenumber', width:90},
        {name:'mop',index:'mop', width:50},
        {name:'totalinvoiceamount',index:'totalinvoiceamount', width:75, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
        {name:'immediatecash',index:'immediatecash', width:75, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
        {name:'immediatecheck',index:'immediatecheck', width:75, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
        {name:'arcash',index:'arcash', width:75, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
        {name:'archeck',index:'archeck', width:75, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
        {name:'artotalpaid',index:'artotalpaid', width:75, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }}		
		
   	],
	<?php if($this->css == 'ar_') { ?>
		direction :"rtl",
	<?php } ?>	
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
    rowList:eval(RP_ROWLISTSHOW),
  //  loadonce:true,
    pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,        
	groupingView :
        {
            groupField : ['routecode','hocode','transactiondate'],
            groupColumnShow : [false,false,true],
            groupCollapse : true,
            groupOrder: ['asc','asc','asc'] ,
            groupSummary : [false,false,true],
            groupDataSorted : true,
            showSummaryOnHide: true,
	    groupText : ['','<b style="text-transform: uppercase;">{0}</b>','']
        }
});
jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);
jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});
</script>