<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">

jQuery("#search").jqGrid({        
   	url:base_url+"/reports/distributionchecksummary/distributioncheckdata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route');?>',
		  '<?php echo $this->translate->_('Item Code');?>',
		  '<?php echo $this->translate->_('Description');?>',
		  //'<?php echo $this->translate->_('Price');?>',
		  '<?php echo $this->translate->_('Customer Code');?>',
		  '<?php echo $this->translate->_('Customer Nmae');?>',
		 // '<?php echo $this->translate->_('Cut-off');?>',
		 // '<?php echo $this->translate->_('Max Qty');?>',
		  //'<?php echo $this->translate->_('Location');?>',
		  //'<?php echo $this->translate->_('Quantity');?>',
		  '<?php echo $this->translate->_('SHELF');?>',
		  '<?php echo $this->translate->_('Image');?>'
		 // '<?php echo $this->translate->_('STORE');?>',
		  //'<?php echo $this->translate->_('Expiry Date');?>'
		  ],
   	colModel:[
   		{name:'routecode',index:'routecode', width:100},
		{name:'actualitemcode',index:'actualitemcode', width:100},
		{name:'itemdescription',index:'itemdescription', width:200},
		//{name:'defaultsalesprice',index:'defaultsalesprice', width:100},
		{name:'caseprice',index:'caseprice', width:100},
		{name:'defaultsalesprice1',index:'defaultsalesprice1', width:100},
		//{name:'cutoff_qty',index:'cutoff_qty', width:100},
		//{name:'max_qty',index:'max_qty', width:100},
		//{name:'location1',index:'location1', width:100},
		//{name:'unitspercase',index:'unitspercase', width:100},
		{name:'location1',index:'location1', width:100},
		{name:'imagename',index:'', width:100}//,
		//{name:'location2',index:'location2', width:100},
		//{name:'expiry_date',index:'expiry_date', width:100},
		//{name:'expiry_date',index:'expiry_date', width:75, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
   	],
	<?php if($this->css == 'ar_') { ?>
		direction :"rtl",
	<?php } ?>	
	height: 'auto',
	width: 'auto',
	rowNum:eval(RP_NOOFRECORDSHOW),
	rowList:eval(RP_ROWLISTSHOW),
	//  loadonce:true,
	pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,        
	groupingView :
        {
            groupField : ['routecode'],
            groupColumnShow : [true],
            groupCollapse : true,
            groupOrder: ['asc'] ,
            groupSummary : [true],
            groupDataSorted : true,
            showSummaryOnHide: true,
	    groupText : ['','<b style="text-transform: uppercase;">{0}</b>','']
        },
	gridview: true,
	rowattr: function (rd) {
		//console.log(rd);
		var location1 = rd.location1.split('/');
		/*var location2 = rd.location2.split('/');
		//console.log(location1+' '+location2);
		//if (rd.cutoff_qty < rd.unitspercase) {
		if(location1 < rd.cutoff_qty || location2 < rd.cutoff_qty)
		{
			return {"style": "background:red"};
		}*/
	}
});
jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);
jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});
</script>