<?php
/**
*
* @name       adddailysalesmanload.phtml
* @since      1 feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$batch_detail_url = $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"batchdetails"), "default", true);
?>
<script type="text/javascript">
	
	var batch_st		= '<?php echo $this->batch_status;?>';
	var decimalplaces	= '<?php echo $this->decimalplaces;?>';
	
	$(document).ready(function() {
		
		<?php if($this->params['id'] > 0) { ?>
			loaddata('<?php echo $this->itemgrid; ?>','item-grid');
		<?php } ?>
		<?php if($this->formdata['isposted'] == 1) { ?>
			$("#edit_time_disable").find('input,select').attr('disabled','disabled');
			$('select').trigger('liszt:updated');
		<?php } ?>	
		
		$('#btndatapost').click(function() {
			$("#txtbatchno").removeClass('required');
			$("#ddlitem").removeClass('required');
			$('#ddlitem').trigger('liszt:updated');
		})
		
		$('#sbtnadd').click(function() {
			
			if($("#frmdet").valid())
			{
				var url 	= base_url+'/inventory/transaction/adddepotinventorygrid/';
				var values = $('#frmdet').serialize();
				
				$.ajax({
					url:url,
					data :values+'&add=yes',
					type:'post',
					beforeSend: function() {
						$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
					},
					success:function(data) {
						$("#loader").html('');
						$("#txtcases").val('');
						$("#txtpieces").val('');
						$("#txtcaseprice").val('');
						$("#txtsalesprice").val('');
						$("#txtupc").val('');
						$("#txtbatchno").val('');
						$("#txtexpdate").val('');
						$("#ddlitem").val('');
						
						//$("#txttransactiondate").val('');
						//$("#ddlfromdepot").val('');
						//$("#ddltodepot").val('');						
						$('select').trigger('liszt:updated');						
						$("#hdnid").val(data);
						<?php if(strstr($this->itemgrid,'/key/')) { ?>
							loaddata('<?php echo $this->itemgrid; ?>','item-grid');
						<?php } else { ?>
							loaddata('<?php echo $this->itemgrid; ?>/key/'+data,'item-grid');
						<?php } ?>
					}
				})
			}
		})			
		
		$('#ddlitem').change(function() {
			var item_val = $('#ddlitem').val();
			getiteminfo(item_val);
		})
	})
	
	function getiteminfo(item_id)
	{
		$("#txtupc").val('');
		$("#txtcaseprice").val('');
		$("#txtsalesprice").val('');		
		
		if(item_id > 0 )
		{
			//var url 		= base_url+'/home/index/getiteminfo/itemid/'+item_id;
			//var allow_entry = 0;
			//$.ajax({
			//	url:url,
			//	data:$("#frmdet").serialize(),
			//	type:'post',
			//	beforeSend: function() {
			//		$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
			//	},
			//	success:function(data)
			//	{	
			//		var item_info = JSON.parse(data);
			//		if (item_info == '')
			//		{
			//			return false;
			//		}					
			//		if(typeof(item_info[0]) == 'object')
			//		{
			//			var temp1 	= Number(item_info[0][0]['caseprice']);
			//			var temp1 	= temp1.toFixed(decimalplaces);
			//			var temp2 	= Number(item_info[0][0]['defaultsalesprice']);
			//			var temp2 	= temp2.toFixed(decimalplaces);						
			//			var temp4 	= Number(item_info[0][0]['defaultgoodreturnprice']);
			//			var temp4 	= temp4.toFixed(decimalplaces);
			//			var temp5 	= Number(item_info[0][0]['defaultgoodreturncaseprice']);
			//			var temp5 	= temp5.toFixed(decimalplaces);
			//			
			//			$("#txtupc").val(item_info[0][0]['unitspercase']);
			//			$("#txtcaseprice").val(temp1);
			//			$("#txtsalesprice").val(temp2);						
			//			$("#hdnretprice").val(temp4);
			//			$("#hdnretcaseprice").val(temp5);
			//			
			//			$("#loader").html("");
			//		}
			//	}
			//})
			var url 		= base_url+'/home/index/getiteminfo/itemid/'+item_id;
			var allow_entry = 0;
			$.ajax({
				url:url,
				data:$("#frmdet").serialize(),
				type:'post',
				beforeSend: function() {
					$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
				},
				success:function(data)
				{	
					var item_info = JSON.parse(data);
					if (item_info == '') {
						return false;
					}					
					if(typeof(item_info[0]) == 'object')
					{
						var temp1 	= Number(item_info[0][0]['caseprice']);
						var temp1 	= temp1.toFixed(decimalplaces);
						var temp2 	= Number(item_info[0][0]['defaultsalesprice']);
						var temp2 	= temp2.toFixed(decimalplaces);						
						var temp4 	= Number(item_info[0][0]['defaultgoodreturnprice']);
						var temp4 	= temp4.toFixed(decimalplaces);
						var temp5 	= Number(item_info[0][0]['defaultgoodreturncaseprice']);
						var temp5 	= temp5.toFixed(decimalplaces);
						
						$("#txtupc").val(item_info[0][0]['unitspercase']);
						$("#txtcaseprice").val(temp1);
						$("#txtsalesprice").val(temp2);
						$("#hdnretprice").val(temp4);
						$("#hdnretcaseprice").val(temp5);
						
						allow_entry = item_info[0][0]['allowbatchentry']
						
						if(batch_st == 1 && allow_entry == 1) {
							$('#txtexpdate').val('');
							$('#txtexpdate').addClass('required');
							$('#txtbatchno').addClass('required');
							
							$( "#txtexpdate" ).datepicker({
								dateFormat: 'dd-mm-yy'
							});
							
							$('#txtbatchno').attr('readonly',false);
							$('#txtbatchno').val('');
							$("#txtexpdate").datepicker("enable");
						}
						else if(batch_st == 1) {
							$('#txtexpdate').removeClass('required');
							$('#txtbatchno').removeClass('required');
							
							$('#txtbatchno').attr('readonly',true);
							$('#txtbatchno').val('NONE');
							$('#txtexpdate').val('31-12-2099');
							$("#txtexpdate").datepicker("disable");
						}
						$("#loader").html("");
					}
				}
			})
		}
	}
</script>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>

<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>


<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<form id="frmdet" name="frmdet" class="validate" novalidate action="<?php echo $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"adddepotinventory"), "default", true);?>" method="post">
<div class="box" id="inventory_transaction_adddepotinventory">
<div class="header">
    <div class="_50_3 back_btn">
		<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_inventory_mag.png">
		<h3><?php echo $this->translate->_('Depot Inventory')?></h3>
	</div>
    <div class="_50_3">
		<div class="_10 save_btn">
			<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"depotinventory"), "default", true);?>')" >
		</div>
		<?php if($this->params['id'] > 0 && $this->formdata['isposted'] != 1) { ?>
		<div class="_10 save_btn">
			<input class="border_none" type="submit" value="" name="btndatapost" id="btndatapost">
		</div>
		<?php } ?>
    </div>
</div>

<div class="clear"></div>
<div class="clear"></div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
               <li>
			    <a href="<?php echo $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"depotinventory"),"default", true);?>"><?php echo $this->translate->_('Overview'); ?></a>
			</li>
			<li class="last-child">
			    <a href="<?php echo $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"adddepotinventory"),"default", true);?>"><b><?php echo $this->translate->_('Details'); ?></b></a>
			</li>
            </ul>
        </li>
    </ul>
</div>
</div>

<div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div id="edit_time_disable">
		<div class="_100 ">
			<label class="_25 margin_top_12 label_text_align">
				<?php echo $this->translate->_('DepotInventory No.')." ".$this->colan;?>
			</label>
			<div class="_25">
				<input type="text" name="txtdepotinvno" id="txtdepotinvno" readonly="readonly" value="<?php echo $this->formdata['depotinvtranskey']; ?>"/>
			</div>
			<label class="_25 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Posted Status').''.$this->colan;?>
			</label>
			<div class="_25">
				<input type="text" name="txtpostedstatus" id="txtpostedstatus" value="<?php if(isset($this->formdata['isposted'])) { echo ($this->formdata['isposted'] == 1) ? 'Posted' : 'Not Posted'; } ?>" readonly="readonly" />
			</div>
		</div>
		<div class="_100">
			<label class="_25 margin_top_12 label_text_align">
				<?php echo $this->translate->_('From Depot').''.$this->required;?>
			</label>
			<div class="_25">
				<select id="ddlfromdepot" name="ddlfromdepot" class="required">
			<option value="">--- Select ---</option>
			<?php
				for($i=0;$i<count($this->fromdepot);$i++)
				{
			?>
				<option value="<?php echo $this->fromdepot[$i]['id'];?>" <?php echo ($this->fromdepot[$i]['id'] ==  $this->formdata['fromdepot'] )? 'selected': ''; ?> ><?php echo $this->fromdepot[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>
		<label class="_25 margin_top_12 label_text_align">
			<?php echo $this->translate->_('To Depot').''.$this->required;?>
		</label>
				<div class="_25">
				   <select id="ddltodepot" name="ddltodepot" class="required">
			<option value="">--- Select ---</option>
			<?php
				for($i=0;$i<count($this->todepot);$i++)
				{
			?>
				<option value="<?php echo $this->todepot[$i]['id'];?>" <?php echo ($this->todepot[$i]['id'] ==  $this->formdata['todepot'] )? 'selected': ''; ?> ><?php echo $this->todepot[$i]['val'];?></option>
			<?php } ?>
			</select>
				</div>
			</div>
			<div class="_100">
		<label class="_25 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Transaction Date').''.$this->colan;?>
		</label>
		<div class="_25">
		   <input type="text"  name="txttransactiondate" id="txttransactiondate"  value="<?php echo $this->formdata['transactiondate']; ?>"  readonly="readonly"  />
		</div>
		<label class="_25 margin_top_12 label_text_align">
		   &nbsp;
		</label>
				<div class="_25 margin_right_1">
				   &nbsp;
				</div>
			</div>
		</div>
</div>
<div class="content with-actions min_height_10">
    <div class="_100 margin_top_25">
		<?php if($this->formdata['isposted'] != 1) { ?>	
		<fieldset>
			<legend><?php echo $this->translate->_('Add Item');?>:</legend>
				<div class="_100">
					<label class="_13 margin_top_12 label_text_align">
						 <?php echo $this->translate->_('Item')." ".$this->required;?>
					</label>
					<div class="_25_1">
						<select id="ddlitem" name="ddlitem"  class="required" onchange="getiteminfo(this.value)">
							<option value="">--- Select ---</option>
							<?php
								for($i=0;$i<count($this->item);$i++)
								{
							?>
								<option value="<?php echo $this->item[$i]['id'];?>" ><?php echo $this->item[$i]['val'];?></option>
							<?php } ?>
						</select>
					</div>
					<label class="_15_2 margin_top_12 label_text_align">
						<?php echo $this->translate->_('UPC').''.$this->colan;?>
					</label>
					<div class="_13 margin_left_right_1  margin_right_3_1">
						<input type="text" value="" readonly name="txtupc" id="txtupc" class="number ">
					</div>
				</div>
				<div class="_100">			
					<label class="_13 margin_top_12 label_text_align">
						<?php echo $this->translate->_('Case Price')." ".$this->colan;?>
					</label>
					<div class="_13 margin_right_2_2">
						<input type="text" value="" name="txtcaseprice" readonly="readonly" id="txtcaseprice" class="">
					</div>
					<label class="_13 margin_top_12 label_text_align">
						 <?php echo $this->translate->_('Sales Price').''.$this->colan;?>
					</label>
					<div class="_13 margin_right_2_2">
						<input type="text" value="" name="txtsalesprice" readonly="readonly" id="txtsalesprice" class="">
					</div>					
					<label class="_13 margin_top_12 label_text_align">
						<?php echo $this->translate->_('Batch')." ".$this->colan; ?>
					</label>
					<div class="_13 margin_right_2_2">
						<input type="text" value="" name="txtbatchno" id="txtbatchno" maxlength="20">
					</div>					
				</div>
				<div class="_100">
					<label class="_13 margin_top_12 label_text_align">
						<?php echo $this->translate->_('Cases')." ".$this->colan;?>
					</label>
					<div class="_13 margin_right_2_2">
						<input maxlength="4" type="text" value="" name="txtcases" id="txtcases" class="number" >
					</div>			
					<label class="_13 margin_top_12 label_text_align">
						<?php echo $this->translate->_('Pieces')." ".$this->colan;?>
					</label>
					<div class="_13 margin_right_2_2">
						<input maxlength="4" type="text" value="" name="txtpieces" id="txtpieces" class="number">
					</div>			
					<label class="_13 margin_top_12 label_text_align">
						<?php echo $this->translate->_('Expiry Date').''.$this->colan; ?>
					</label>
					<div class="_13 margin_right_2_2">
						<input type="text" value="" name="txtexpdate" id="txtexpdate" readonly="readonly">
					</div>
					<div class="_5"><input type="button" value="<?php echo $this->translate->_('ADD');?>" id="sbtnadd" name="sbtnadd"></div>			
				</div>
		</fieldset>
		<?php } ?>
	    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
    </div>
    <div class="_100">
    <div id="loader"></div>
		<div id="item-grid"> <!--grid load here --> </div>
    </div>	
</div>
</div> <!-- End of .box -->
</form>
</div>
<script type="text/javascript">
$(window).load(function() {
    $(function() {		
		$( "#txtexpdate" ).datepicker({
			dateFormat: 'dd-mm-yy'
		});
    });
});
</script>