<?php
/**
* @name       addgrn.phtml
* @since      13 feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script type="text/javascript">
var batch_st		= '<?php echo $this->batch_status;?>';
var decimalplaces	= '<?php echo $this->decimalplaces;?>';

$(document).ready(function(){
	
	$( "#txtexpdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
	
	<?php if($this->params['id'] > 0) { ?>
		loaddata('<?php echo $this->itemgrid; ?>','item-grid');
		fillitemcombo('<?php echo $this->formdata['fromdepot']; ?>');		
	<?php } ?>
	
	
	$('#sbtnadd').click(function(){
		
		if($('#ddlfromdepot').val() == $('#ddltodepot').val()) {
			jAlert('From Depot And To Depot Must Be Different.');
			return false;
		}
		
		if($("#hdnvalidate").val() == 1)
		{
			if(parseFloat($("#txtrelcases").val()) > parseFloat($("#txtavlrelcases").val())) {
				jAlert('Released Cases Must Be Lower Then The Available Released Cases');
				return false;
			}
			if(parseFloat($("#txtrelpcs").val()) > parseFloat($("#txtavlrelpcs").val())) {
				jAlert('Released Pieces Must Be Lower Then The Available Released Pieces');
				return false;
			}
			if(parseFloat($("#txtholdcases").val()) > parseFloat($("#txtavlhldcases").val())) {
				jAlert('Hold Cases Must Be Lower Then The Available Hold Cases');
				return false;
			}
			if(parseFloat($("#txtholdpcs").val()) > parseFloat($("#txtavlhldpcs").val())) {
				jAlert('Hold Pieces Must Be Lower Then The Available Hold Pieces');
				return false;
			}
		}
		
		if($("#frmdet").valid())
		{
			var url 	= base_url+'/inventory/transaction/addgrngrid/';
			var values = $('#frmdet').serialize();
			
			$.ajax({
				url:url,
				data :values+'&add=yes',
				type:'post',
				beforeSend: function() {
					$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
				},
				success:function(data) {
					$("#loader").html('');
					$("#txtcases").val('');
					$("#txtpieces").val('');
					$("#txtcaseprice").val('');
					$("#txtsalesprice").val('');
					$("#txtupc").val('');
					$("#txtbatchno").val('');
					$("#txtexpdate").val('');
					$("#ddlitem").val('');
					
					$("#txtrelcases").val('');
					$("#txtrelpcs").val('');
					$("#txtholdcases").val('');
					$("#txtholdpcs").val('');
					$("#txtavlrelcases").val('');
					$("#txtavlrelpcs").val('');
					$("#txtavlhldcases").val('');
					$("#txtavlhldpcs").val('');					
					
					$('select').trigger('liszt:updated');						
					$("#hdnid").val(data);
					<?php if(strstr($this->itemgrid,'/key/')) { ?>
						loaddata('<?php echo $this->itemgrid; ?>','item-grid');
					<?php } else { ?>
						loaddata('<?php echo $this->itemgrid; ?>/key/'+data,'item-grid');
					<?php } ?>
				}
			})
		}
	});	
	$('#ddlfromdepot').change(function(){
		
		
		$.blockUI();
			fillitemcombo(this.value);
		$.unblockUI();
	});
	$('#ddlitem').change(function(){
		
		var depotid = $('#ddlfromdepot').val();
		var itemid 	= this.value;
		$.blockUI();
			getiteminfo(depotid,itemid);
		$.unblockUI();
	});	
})

	

function fillitemcombo(depotid)
{
	$('#ddlitem').html('');
	$('#ddlitem').val('');
	$('#ddlitem').trigger('liszt:updated');
	if(depotid > 0)
	{
		var  url = base_url+'/inventory/transaction/fillitemcombo/depotid/'+depotid;
		$.ajax({
			url:url,
			data:$("#frmdet").serialize(),
			type:'post',
			success:function(data) {
				var item_info = JSON.parse(data);
				if (item_info == '')
				{
					return false;
				}
				if(typeof(item_info[0]) == 'object')
				{
					$('<option/>').val('').html('--- Select ---').appendTo('#ddlitem');
					for (i=0;i<item_info[0].length;i++) {
						$('<option/>').val(item_info[0][i]['id']).html(item_info[0][i]['val']).appendTo('#ddlitem');
					}
				}
				$('#ddlitem').trigger('liszt:updated');
			}
		})
	}
}
function getiteminfo(depotid,itemid)
{
	$("#txtupc").val('');
	$("#txtavlrelcases").val('');
	$("#txtavlrelpcs").val('');
	$("#txtavlhldcases").val('');
	$("#txtavlhldpcs").val('');
	
	if(itemid > 0 && depotid > 0)
	{
		var url 		= base_url+'/inventory/transaction/getitemqtyinfo/itemid/'+itemid+'/depotid/'+depotid;
		var allow_entry = 0;
		$.ajax({
			url:url,
			data:$("#frmdet").serialize(),
			type:'post',			
			success:function(data)
			{	
				var item_info = JSON.parse(data);
				if (item_info == '') {
					return false;
				}
				
				if(typeof(item_info[0]) == 'object')
				{
					$("#txtupc").val(item_info[0][0]['unitspercase']);
					
					if(typeof(item_info[1]) == 'object') {
						$("#txtavlrelcases").val(item_info[1][0]['availablecases']);
						$("#txtavlrelpcs").val(item_info[1][0]['availablepieces']);
						$("#txtavlhldcases").val(item_info[1][0]['holdcases']);
						$("#txtavlhldpcs").val(item_info[1][0]['holdpieces']);
						$("#hdnvalidate").val(1);
					} else {
						$("#txtavlrelcases").val(0);
						$("#txtavlrelpcs").val(0);
						$("#txtavlhldcases").val(0);
						$("#txtavlhldpcs").val(0);
						$("#hdnvalidate").val(0);
					}
					
					allow_entry = item_info[0][0]['allowbatchentry'];
					
					if(batch_st == 1 && allow_entry == 1) {
						$('#txtexpdate').val('');
						$('#txtexpdate').addClass('required');
						$('#txtbatchno').addClass('required');
						
						$( "#txtexpdate" ).datepicker({
							dateFormat: 'dd-mm-yy'
						});
						
						$('#txtbatchno').attr('readonly',false);
						$('#txtbatchno').val('');
						$("#txtexpdate").datepicker("enable");
					}
					else if(batch_st == 1) {
						$('#txtexpdate').removeClass('required');
						$('#txtbatchno').removeClass('required');
						
						$('#txtbatchno').attr('readonly',true);
						$('#txtbatchno').val('NONE');
						$('#txtexpdate').val('31-12-2099');
						$("#txtexpdate").datepicker("disable");
					}
				}
			}
		})
	}
}
</script>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>

<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>


<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<form id="frmdet" name="frmdet" class="validate" novalidate action="<?php echo $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"addgrn"), "default", true);?>" method="post">
<div class="box" id="inventory_transaction_addgrn">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_inventory_mag.png">
        <h3><?php echo $this->translate->_('Goods Receipt')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"grn"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn"><!--<input class="border_none" type="submit" value="" name="btnsave" id="btnsave">-->&nbsp;</div>
    </div>
</div>

<div class="clear"></div>
<div class="clear"></div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
               <li>
			    <a href="<?php echo $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"grn"),"default", true);?>"><?php echo $this->translate->_('Overview'); ?></a>
			</li>
			<li class="last-child">
			    <a href="<?php echo $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"addgrn"),"default", true);?>"><b><?php echo $this->translate->_('Details'); ?></b></a>
			</li>
            </ul>
        </li>
    </ul>
</div>
</div>

<div class="content with-actions min_height_10">

	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
	    <div class="_100 ">
		<label class="_25 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Code')." ".$this->colan;?>
		</label>
		<div class="_25">
                     <input type="text" name="txtcode" id="txtcode" value="<?php echo $this->formdata['grheaderid'];?>"/>
		</div>
		<label class="_25 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Date').''.$this->colan;?>
		</label>
                <div class="_25">
                     <input type="text" name="txtdate" id="txtdate" readonly="readonly" value="<?php echo $this->formdata['date'];?>"/>
                </div>
            </div>

	    <div class="_100">
		<label class="_25 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('From Depot').''.$this->required;?>
		</label>
		<div class="_25">
                    <select id="ddlfromdepot" name="ddlfromdepot" class="required depotchange">
			<option value="">--- Select ---</option>
			<?php
			    for($i=0;$i<count($this->fromdepot);$i++)
			    {
			?>
				<option value="<?php echo $this->fromdepot[$i]['id'];?>" <?php echo ($this->fromdepot[$i]['id'] ==  $this->formdata['fromdepot'] )? 'selected': ''; ?> ><?php echo $this->fromdepot[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
		<label class="_25 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('To Depot').''.$this->required;?>
		</label>
                <div class="_25">
                   <select id="ddltodepot" name="ddltodepot" class="required depotchange">
			<option value="">--- Select ---</option>
			<?php
			    for($i=0;$i<count($this->todepot);$i++)
			    {
			?>
				<option value="<?php echo $this->todepot[$i]['id'];?>" <?php echo ($this->todepot[$i]['id'] ==  $this->formdata['todepot'] )? 'selected': ''; ?> ><?php echo $this->todepot[$i]['val'];?></option>
			<?php } ?>
		    </select>
                </div>
            </div>
            <div class="_100">
		<label class="_25 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Remark').''.$this->colan;?>
		</label>
		<div class="_25">
		   <textarea name="txtremark" id="txtremark"><?php echo $this->formdata['remark'];?></textarea>
		</div>
		<label class="_25 margin_top_12 label_text_align">
		   &nbsp;
		</label>
                <div class="_25">
                   &nbsp;
                </div>
            </div>
    </div>

<div class="content with-actions min_height_10">
    <div class="_100 margin_top_25">
	 <fieldset>
	    <legend><?php echo $this->translate->_('Add Item');?>:</legend>
	    <div class="_100">
		<label class="_20 margin_top_12 label_text_align">
		     <?php echo $this->translate->_('Item')." ".$this->required;?>
		</label>
		<div class="_25">
		     <select id="ddlitem" name="ddlitem" class="required">
			<option value="">--- Select ---</option>
			<?php
			    for($i=0;$i<count($this->item);$i++)
			    {
			?>
				<option value="<?php echo $this->item[$i]['id'];?>" <?php echo ($this->item[$i]['id'] ==  1 )? 'selected': ''; ?>><?php echo $this->item[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
		<label class="_20 margin_top_12 label_text_align margin_right_1">
		    <?php echo $this->translate->_('UPC')." ".$this->colan;?>
		</label>
		<div class="_15 margin_right_1">
		    <input type="text" value="" name="txtupc" id="txtupc" readonly>
		</div>
	    </div>
	    <div class="_100">
			<label class="_20 margin_top_10 label_text_align">
				<?php echo $this->translate->_('Available Release Qty.').''.$this->colan;?>
			</label>
			<div class="_10_2 margin_right_1">
				<input type="text" value="" name="txtavlrelcases" id="txtavlrelcases" readonly="readonly" class="margin_top_5" >
			</div>		
			<div class="margin_left_right_2_2 _10_2">
				<input type="text" value="" name="txtavlrelpcs" id="txtavlrelpcs" readonly="readonly" class="margin_top_5" />
			</div>
			<div class="_2 margin_right_2_2">&nbsp;</div>
			<label class="_20 margin_top_10 label_text_align">
				<?php echo $this->translate->_('Available Hold Qty.').''.$this->colan;?>
			</label>
			<div class="_10_2 margin_right_1">
				<input type="text" value="" name="txtavlhldcases" id="txtavlhldcases" readonly="readonly" class="margin_top_5" />
			</div>
			<div class="margin_left_right_2_2 _10_2">
				<input type="text" value="" name="txtavlhldpcs" id="txtavlhldpcs" readonly="readonly" class="margin_top_5" />
			</div>
		</div>
        <div class="_100">
			<label class="_20 margin_top_10 label_text_align">
				<?php echo $this->translate->_('Released Qty.').''.$this->colan;?>
			</label>
			<div class="_10_2 margin_right_1">
				<input type="text" value="" name="txtrelcases" id="txtrelcases" class="number margin_top_5">
			</div>
			<div class="margin_left_right_2_2 _10_2">
				<input type="text" value="" name="txtrelpcs" id="txtrelpcs" class="number margin_top_5">
			</div>
			<div class="_2 margin_right_2_2">&nbsp;</div>
			<label class="_20 margin_top_10 label_text_align">
				<?php echo $this->translate->_('Hold Qty').''.$this->colan;?>
			</label>
			<div class="_10_2 margin_right_1">
				<input type="text" value="" name="txtholdcases" id="txtholdcases" class="number margin_top_5">
			</div>
			<div class="margin_left_right_2_2 _10_2">				
				<input type="text" value="" name="txtholdpcs" id="txtholdpcs" class="number margin_top_5">
			</div>
	    </div>
		<div class="_100">
			<label class="_20 margin_top_10 label_text_align">
				<?php echo $this->translate->_('Batch No.').''.$this->colan;?>
			</label>
			<div class="_25 margin_right_1">
				<input type="text" value="" name="txtbatchno" id="txtbatchno" class="margin_top_5">
			</div>
			<label class="_20 margin_top_10 label_text_align">
				<?php echo $this->translate->_('Expiry Date')." ".$this->colan;?>
			</label>
			<div class="_25 margin_right_1">
				<input type="text" value="" name="txtexpdate" id="txtexpdate" readonly="readonly" class="margin_top_5">
			</div>
			<div class="_5 margin_right_1">
				<input type="button" value="<?php echo $this->translate->_('ADD');?>" id="sbtnadd" name="sbtnadd" class="margin_top_5" >
			</div>
	    </div>
	</fieldset>
        <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
		<input type="hidden" id="hdnvalidate" name="hdnvalidate" value="0" />		
    </div>
    <div class="_100">
<div id="loader"></div>
<div id="item-grid"> <!--grid load here --> </div>

    </div>
</div>

</div> <!-- End of .box -->
</form>
</div>