<?php
/**
* @name       addcustomerpromo.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');

/* $this->headScript()->appendFile($this->baseUrl().'/public/js/jquery.prettyPhoto.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/public/css/prettyPhoto.css'); */
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}

</style>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="inventory_transaction_batchdetails">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post" target="_parent">
<div class="header ">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_inventory_mag.png">
        <h3><?php echo $this->translate->_('Batch Details');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="closepopup();">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>

<div class="content with-actions min_height_10">
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<div class="clear"></div>
    </div>

    <div class="_100 margin_top_10">

 <fieldset>
	    <legend>Add Item:</legend>
	    <div class="_100">
		<label class="_35_1 margin_top_15 label_text_align">
		     <?php echo $this->translate->_('Item')." ".$this->required;?>
		</label>
		<div class="_25 margin_right_1">
		     <select id="ddlitem" name="ddlitem" class="required">
			<option value="">--- Select ---</option>
			<?php
			    for($i=0;$i<count($this->item);$i++)
			    {
			?>
			<option value="<?php echo $this->item[$i]['id'];?>">
                            <?php echo $this->item[$i]['val'];?>
                        </option>
			<?php } ?>
		    </select>
		</div>
                <div class="_35">
                    &nbsp;
                </div>
	    </div>
	    <div class="_100">
                <label class="_35_1 margin_top_15 label_text_align">
		    <?php echo $this->translate->_('Batch Number')." ".$this->required;?>
		</label>
		<div class="_25 margin_right_1">
		    <input type="text" value="" name="txtbatchnumber" id="txtbatchnumber" class="required">
		</div>
                <div class="_35">
                    &nbsp;
                </div>
	    </div>
             <div class="_100">
                <label class="_35_1 margin_top_15 label_text_align">
                        <?php echo $this->translate->_('Expiry Date').''.$this->colan;?>
                    </label>
                    <div class="_25 margin_right_1">
                        <input type="text" value="" name="txtexpdate" id="txtexpdate" >
                    </div>
                 <div class="_35">
                    &nbsp;
                </div>
            </div>
            <div class="_100">
                <label class="_35_1 margin_top_15 label_text_align">
		    <?php echo $this->translate->_('Cases')." ".$this->required;?>
		</label>
		<div class="_25 margin_right_1">
		    <input type="text" value="" name="txtlcases" id="txtlcases" class="required">
		</div>
                <div class="_35">
                    &nbsp;
                </div>
            </div>

	    <div class="_100">
		<label class="_35_1 margin_top_15 label_text_align">
		     <?php echo $this->translate->_('Units').''.$this->colan;?>
		</label>
		<div class="_25 margin_right_1">
		    <input type="text" value="" name="txtunits" id="txtunits">
		</div>
                <div class="_35">
                    &nbsp;
                </div>
	    </div>
	    <div class="_100">
		<label class="_35_1 margin_top_15 label_text_align">
		     &nbsp;
		</label>
		<div class="_25 margin_right_1">
		    <input type="submit" value="<?php echo $this->translate->_('ADD');?>" id="sbtnadd" name="sbtnadd">
		</div>
                <div class="_35">
                    &nbsp;
                </div>
	    </div>


	</fieldset>

    </div>

    <div class="clear"></div>
    <div class="clear"></div>
	<div class="_100">
	    <?php echo $this->partial('datagrid.phtml', $this); ?>

	</div>
<!--            <div class="_100">-->
<!--                <label class="_80 margin_top_15 label_text_align">-->
<!--		     &nbsp;-->
<!--		</label>-->
<!--                 <div class="_20 margin_top_15 margin_bottom_10">-->
<!--		                         <input type="submit" value="<?php echo $this->translate->_('Save');?>" id="sbtnadd" name="sbtnadd">-->
<!--                 </div>&nbsp;&nbsp;-->
<!--                 	<div class="_50 margin_top_15 margin_bottom_10">-->
<!--                            <input type="submit" value="<?php echo $this->translate->_('Cancel');?>" id="sbtnadd" name="sbtnadd">-->
<!--                        </div>-->
<!--             </div>-->
    <div class="clear"></div>
    <div class="clear"></div>

</div>
</form>
</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
     $(function() {
	$( "#txtexpdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });

    $("a[class^='ico edit']").prettyPhoto({animation_speed:'fast',theme:'light_rounded', allowresize: false});

    $("#btncancel").click(function() {
	parent.eval('$.prettyPhoto.close()');
    });
});

</script>
