
<?php
/**
* @name       dailysalesmanload.phtml
* @since      1 feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');



$date = $this->date != '' ? $this->date : date('d-m-Y');
?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="grid_12">
    <div class="box">        
		<form name="frmoverview" id="frmoverview" action="" method="post">
			<input type="hidden" id="hdDelete" name="hdDelete" value="" />
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_inventory_mag.png" class="margin_top_7">
		<h3><?php echo $this->translate->_('Daily Salesman Load');?></h3>
	    </div>
	    <div class="_50_3">
		<!--<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnexport" id="btnexport"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint"></div>-->
		<?php if ($this->disableadd == false) { ?>
		<?php if($this->checkaccess("delete")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" name="btndelete" id="btndelete"></div><?php } ?>
		<?php if($this->checkaccess("update")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnedit" name="btnedit"></div><?php } ?>
		<?php if($this->checkaccess("insert")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnadd" name="btnadd" onclick="winloc('<?php echo $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"adddailysalesmanload"), "default", true);?>')"></div><?php } ?>
		<?php } ?>
	    </div>
        </div>
        <!--</form>-->
 <!--<form id="frmserch" name="frmsearch" action=" " method="post">-->
	<div class="_100" style="text-align:center">
           
		<div class="_20 label_text_align margin_top_7">&nbsp;</div>
		<div class="_20 label_text_align margin_top_7"><label class="advance_search_css"><?php echo $this->translate->_('Select Date').''.$this->colan;?></label></div>
		<div class="_20 label_text_align margin_right_2_2"><input type="text" id="txtdate" name="txtdate" value="<?php echo $date;?>" class="margin_zero"></div>
		<div class="_5 margin_right_2_2"><input type="submit" name="btnload" id="btnload" value="<?php echo $this->translate->_('OK'); ?>" class="margin_zero"></div>
		<div class="_10"><input type="submit" name="btnreset" id="btnreset" value="<?php echo $this->translate->_('RESET'); ?>" class="margin_zero"></div>
		<div class="_30">
		    &nbsp;
		</div>
        <div class="_15">
            &nbsp;
        </div>           
	</div>
	<div class="clear space_20"></div>
	<?php if($this->total_record > 0) { ?>
	    <div class="_20 margin_0"><input type="button" name="btnchngst" id="btnchngst" value="<?php  echo $this->translate->_('CHANGE LOAD STATUS'); ?>"></div>
	<?php } ?>
	<div class="clear"></div>
	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
		 </form>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
<script type="text/javascript">

$(document).ready(function(){

    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });	
    $('#btnchngst').click(function() {
	var str = '';
	$('#table-example input[type="checkbox"]:checked').each(function() {
	    if(parseInt($(this).val()) > 0) {
		str  += $(this).val()+'_';
	    }
	});
	
	if(!str){
	    jAlert('Please Select Record To Change Load Status.');
	    return false;
	} else {
	    window.location= base_url+'/inventory/transaction/dailysalesmanload/chngst/1/ids/'+str;			
	}
    });
});
</script>