<?php
/**
* @name       depotstock.phtml
* @since      7 feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<div class="grid_12">
    <form id="frmoverview" name="frmoverview" class="validate" novalidate action="" method="post">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
				<img src="<?php echo $this->baseUrl()?>/public/images/icon_inventory_mag.png" class="margin_top_7">
				<h3><?php echo $this->translate->_('Stock Status');?></h3>
			</div>
			<div class="_50_3">
				<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint"></div>
			</div>
        </div>
	<div class="_100">
		<div class="_20 label_text_align margin_top_7">&nbsp;</div>
		<div class="_30 label_text_align margin_top_10"><?php echo $this->translate->_('Depot/Branch')." ".$this->required;?></div>
		<div class="_30 margin_left_right_1">
            <select id="ddldepot" name="ddldepot" onchange="$('form').submit();">
				<option value="0">--- ALL Depot ---</option>
				<?php
					for($i=0;$i<count($this->depot);$i++)
					{
				?>
					<option value="<?php echo $this->depot[$i]['id'];?>" <?php if($this->depot[$i]['id'] == $this->depotcode) { echo 'selected';} ?> ><?php echo $this->depot[$i]['val'];?></option>
				<?php } ?>
		    </select>
		</div>
	</div>
	<div class="clear"></div>
	<div class="clear"></div>
        <div class="_100">
	<?php
                    echo $this->partial('datagrid.phtml', $this);
             ?>
        </div>
        <div class="clear"></div>
    </div> <!-- End of .box -->
      </form>
</div> <!-- End of .grid_12 -->
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>