
<?php
/**
* @name       depotdamageexpiry.phtml
* @since      6 feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="grid_12">

    <form name="frmoverview" id="frmoverview" action="" method="post">
        <input type="hidden" id="hdDelete" name="hdDelete" value="" />
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_inventory_mag.png" class="margin_top_7">
		<h3><?php echo $this->translate->_('Depot Damage/Expiry');?></h3>
	    </div>
	    <div class="_50_3">
		<!--<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnexport" id="btnexport"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint"></div>-->
		<?php if($this->checkaccess("delete")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" name="btndelete" id="btndelete"></div><?php } ?>
		<?php if($this->checkaccess("update")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnedit" name="btnedit"></div><?php } ?>
		<?php if($this->checkaccess("insert")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnadd" name="btnadd" onclick="winloc('<?php echo $this->url(array("module"=>"inventory","controller"=>"transaction","action"=>"adddepotdamageexpiry"), "default", true);?>')"></div><?php } ?>
	    </div>
        </div>

	<div class="_100">
		<div class="_20 label_text_align margin_top_7">&nbsp;</div>
		<div class="_20 label_text_align margin_top_7"><label class="advance_search_css"><?php echo $this->translate->_('Select Date').''.$this->colan;?></label></div>
		<div class="_20 label_text_align margin_right_1"><input type="text" id="txtdate" name="txtdate" class="margin_zero" value="<?php echo $this->date;?>"></div>
		<div class="_10 "><input type="submit" name="btnload" id="btnload" value="<?php echo $this->translate->_('OK'); ?>" class="margin_zero"></div>
		<div class="_30">
		    &nbsp;
		</div>


	<div class="clear space_20"></div>
	<div class="clear"></div>
	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
        </div>
    </div> <!-- End of .box -->
    </form>
</div> <!-- End of .grid_12 -->
<script type="text/javascript">
$(window).load(function() {
    $(function() {
		$( "#txtdate" ).datepicker({
			dateFormat: 'dd-mm-yy'
		});
    });
});
</script>