
<?php
/**
* @name       startofday.phtml
* @since      1 feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
</style>

<div class="grid_12">
    <div class="box">
          <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_inventory_mag.png" class="margin_top_7">
		<h3><?php echo $this->translate->_('Close The Day');?></h3>
	    </div>
        </div>
	<div class="clear"></div>
	<div class="clear"></div>

          <form id="frmsearch" name="frmsearch" class="validate" novalidate action="" method="post">
            <div class="content with-actions">
                <div class="_100 margin_top_50" style="text-align:center">
                    <div class="space_50">
                    <div class="_20 label_text_align margin_top_7">&nbsp;</div>
                    <div class="_20 label_text_align margin_top_7 margin_right_1"><?php echo $this->translate->_('Date')." ".$this->required;?></div>
                    <div class="_20 label_text_align"><input type="text" id="txtdate" name="txtdate" value="<?php echo date('d-m-Y');?>" class="required margin_zero"></div>
                   <div class="_10 margin_top_3"><input type="button" name="btnload" id="btnload" value="<?php echo $this->translate->_('OK'); ?>" class="margin_zero"></div>
                    <div class="_30">
                        &nbsp;
                    </div>
                    </div>
                </div>
            </div>
        </form>
	<div class="clear space_20"></div>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>
