<script type="text/javascript">
$(document).ready(function(){
	$('#btnselect').click(function(){
		
		var ids = '';		
		var len = $("#table-example input[type='checkbox'][name='chk[]']:checked").length;
		
        if(len > 1) {
            jAlert('Please Select Only One Record.');
        }
        else if(!len) {
            jAlert('Please Select Record.');
        } else {			
			var did  = $("input[name='chk[]']:checked").val();
			parent.eval('batchinfo("'+did+'")');
			parent.eval('$.prettyPhoto.close()');
        }
	})
	
	$('#table-example tr th').removeClass("sorting_desc");
})	
</script>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<form name="frmoverview" id="frmoverview" action="" method="post">
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png" class="margin_top_7">
		<h3><?php echo $this->title?></h3>
	    </div>
	    <div class="_50_3">&nbsp;</div>
        </div>
	<div class="_100" id="batchinfo" style="overflow-x:auto;height:250px;">
		<?php echo $this->partial('datagrid.phtml', $this); ?>
	</div>
	<?php if($this->datacounter > 0) { ?>
	<div class="_100">
		<div class="_50">&nbsp;</div>
		<input type="button" id="btnselect" name="btnselect" value="ADD" />
	</div>
	<?php } ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>