<style>
.margin_zero {margin-top:0px !important;}
</style>

<form name="frmoverview" id="frmoverview" action="" method="post">
    <input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_datamanagement.png" class="margin_top_7">
		<h3><?php echo $this->title?></h3>
	    </div>
	
        </div>
	<div class="clear"></div>
	<div class="clear"></div>

	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>