/*
SQLyog Community v13.3.1 (64 bit)
MySQL - 8.0.21 : Database - sfa_enhance
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`sfa_enhance` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

/*Table structure for table `customermaster` */

DROP TABLE IF EXISTS `customermaster`;

CREATE TABLE `customermaster` (
  `customercode` bigint NOT NULL AUTO_INCREMENT,
  `type` int NOT NULL DEFAULT '0',
  `headofficecode` bigint DEFAULT '0',
  `routecode` bigint DEFAULT '0',
  `streetcode` bigint DEFAULT '0',
  `districtcode` bigint DEFAULT '0',
  `locationcode` bigint DEFAULT '0',
  `customersequence` bigint DEFAULT '0',
  `customername` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `customeraddress1` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `customeraddress2` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `customerphone` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `balance` decimal(18,5) DEFAULT '0.00000',
  `channelcode` bigint DEFAULT '0',
  `customercategory` bigint DEFAULT '0',
  `pricingkey` bigint DEFAULT '0',
  `promotionkey` bigint DEFAULT NULL,
  `authorizeditemgrpkey` int DEFAULT '0',
  `messagekey1` bigint DEFAULT '0',
  `messagekey2` bigint DEFAULT '0',
  `invoicepaymentterms` int DEFAULT NULL,
  `invoiceretailoption` int DEFAULT '0',
  `invoicepriceoverride` int DEFAULT '0',
  `invoiceretailoverride` int DEFAULT '0',
  `invoiceformatoption` int DEFAULT '0',
  `invoiceextensionopt` int DEFAULT '0',
  `invoicedsdpromptopt` int DEFAULT '0',
  `invoicecopies` int DEFAULT '0',
  `salesinputoprion` int DEFAULT '0',
  `returnsinputoption` int DEFAULT '0',
  `invoiceinputstyle` int DEFAULT '0',
  `onhandspromptopt` int DEFAULT '0',
  `inventoryselectopt` int DEFAULT '0',
  `invencontaineropt` int DEFAULT '0',
  `queuedreportoption` int DEFAULT '0',
  `loyalitykey` int DEFAULT NULL,
  `surveykey` bigint DEFAULT '0',
  `itemmustkey` bigint DEFAULT NULL,
  `contactname` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `customertype` varchar(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `callfrequency` int DEFAULT '0',
  `routenumber` int DEFAULT '0',
  `arbcustomernameshort` varchar(200) DEFAULT NULL,
  `arbcustomername` varchar(250) DEFAULT NULL,
  `arbcustomeraddress1` varchar(150) DEFAULT NULL,
  `arbcustomeraddress2` varchar(150) DEFAULT NULL,
  `hhccustomernameshort` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `hhccustomername` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `hhccustomeraddress1` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `hhccustomeraddress2` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `allowbeyondlimit` int DEFAULT '0',
  `tclimit` int DEFAULT '0',
  `activecustomer` int DEFAULT '0',
  `creditlimitdays` int DEFAULT '0',
  `created` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `cdat` datetime DEFAULT NULL,
  `modified` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `mdat` datetime DEFAULT NULL,
  `forcehand` int DEFAULT '0',
  `renteddisplay` int DEFAULT NULL,
  `installedchiller` int DEFAULT '0',
  `monthlydepreciation` double(8,0) DEFAULT NULL,
  `typeofgiveaway` int DEFAULT '0',
  `giveawayflag` int DEFAULT '0',
  `lastvisiteddate` datetime DEFAULT NULL,
  `memo1` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `memo2` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `tcsubtype` int DEFAULT '0',
  `rentperc` int DEFAULT '0',
  `customeraddress3` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `customercity` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `customerstate` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `customerzip` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `authorizeditemlistctl` int DEFAULT '0',
  `invoicepriceprint` int DEFAULT '0',
  `messagekey3` int DEFAULT '0',
  `messagekey4` int DEFAULT '0',
  `messagekey5` int DEFAULT '0',
  `messagekey6` int DEFAULT '0',
  `orderformat` int DEFAULT '0',
  `enableupcprint` int DEFAULT '0',
  `enabledelayprint` int DEFAULT '0',
  `printsequence` int DEFAULT '0',
  `enablepriceeditinvs` int DEFAULT '0',
  `enablesellprevious` int DEFAULT '0',
  `enablesuggestsales` int DEFAULT '0',
  `enableautofillreturns` int DEFAULT '0',
  `enableautofilldamaged` int DEFAULT '0',
  `enablesigcapture` int DEFAULT '0',
  `enablereturnstrxn` int DEFAULT '0',
  `enableexchangetrxn` int DEFAULT '0',
  `enabledamagedreturns` int DEFAULT '0',
  `enablearcollection` int DEFAULT '0',
  `enablesurveyaudit` int DEFAULT '0',
  `enabledelivinstruct` int DEFAULT '0',
  `enableinvoicecomment` int DEFAULT '0',
  `invoicedetailentry` int DEFAULT '0',
  `orderdetailentry` int DEFAULT '0',
  `forcestockcapture` int DEFAULT '0',
  `enablepromotrxn` int DEFAULT '0',
  `alternatecode` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `creditlimit` double(18,4) DEFAULT NULL,
  `allowcashoncreditexceed` int DEFAULT '0',
  `arbcustomeraddress3` varchar(150) DEFAULT NULL,
  `templateindicator` int DEFAULT '0',
  `templatename` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `arbcontactname` varchar(100) DEFAULT NULL,
  `printlanguageflag` int DEFAULT '0',
  `quantumno` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `lostplacementdelivs` int DEFAULT '0',
  `newplacementdelivs` int DEFAULT '0',
  `currencycode` bigint DEFAULT '0',
  `histmaxdeliveries` int DEFAULT '0',
  `arcustomertype` int DEFAULT NULL,
  `custtaxkey1` int DEFAULT '0',
  `custtaxkey2` int DEFAULT '0',
  `custtaxkey3` int DEFAULT '0',
  `customertaxid` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `customertaxidoptions` int DEFAULT '0',
  `outletsubtype` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `volume` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `enablegovtaxnote` int DEFAULT '0',
  `forwardcoverfactor` double(8,0) DEFAULT NULL,
  `enablepromoeditinvs` int DEFAULT '0',
  `enableaddlpromoinvs` int DEFAULT '0',
  `badcreditcustomer` int DEFAULT '0',
  `enableduplicateprinting` int DEFAULT '0',
  `numoutstandinginv` int DEFAULT '0',
  `enablefocprinting` int DEFAULT '0',
  `promooptions` int DEFAULT '0',
  `groupcode` int DEFAULT '0',
  `forceposcheck` int DEFAULT '0',
  `ancustomercode` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `printoutletitemcode` int DEFAULT '0',
  `reportprintcontrol` int DEFAULT '0',
  `invoicelimiter` int DEFAULT '0',
  `exclusiveopmode` int DEFAULT '0',
  `returnpromotionkey` bigint DEFAULT '0',
  `invoiceformat` int DEFAULT '0',
  `liquorlicprint` int DEFAULT '0',
  `enablepromoeditords` int DEFAULT '0',
  `enableaddlpromoords` int DEFAULT '0',
  `enableaddlpromoinvoices` int DEFAULT '0',
  `enableposequipment` int DEFAULT '0',
  `enablesalestrxn` int DEFAULT '0',
  `enableadvancepayment` int NOT NULL DEFAULT '0',
  `printcheckdetails` int DEFAULT '0',
  `tcspecialdiscount` double(18,4) DEFAULT '0.0000',
  `spldiscountdays` int DEFAULT '0',
  `arabiccustomercity` varchar(100) DEFAULT NULL,
  `threshholdlimit` double(8,0) DEFAULT NULL,
  `discountkey` int DEFAULT '0',
  `enforcepromotion` int DEFAULT '0',
  `gpcustcode` bigint DEFAULT '0',
  `cashonlypromo` int DEFAULT '0',
  `roundnetamount` int DEFAULT '0',
  `roundingoffvalue` int DEFAULT '0',
  `partialcollection` int DEFAULT '0',
  `transactiontype` int DEFAULT '0',
  `enabledraftcopy` int DEFAULT '0',
  `enablebuybackfree` int DEFAULT '0',
  `enablecpd` int DEFAULT '0',
  `enablepaymentsel` int DEFAULT '0',
  `gpsdata` int DEFAULT '0',
  `fixedlatitude` decimal(18,10) DEFAULT '0.0000000000',
  `fixedlongitude` decimal(18,10) DEFAULT '0.0000000000',
  `rentkey` bigint DEFAULT '0',
  `startdate` datetime DEFAULT NULL,
  `enddate` datetime DEFAULT NULL,
  `definitionvalue` double(8,0) DEFAULT NULL,
  `runningvalue` double(8,0) DEFAULT NULL,
  `rentcontrol` int DEFAULT '0',
  `disablebalanceupdate` int DEFAULT '0',
  `enablecreditlimit` int DEFAULT '0',
  `autosettlecollection` int DEFAULT '0',
  `enableinvoicecopy` int DEFAULT '0',
  `pobox` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `shoptelephonenumber` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `shopfaxnumber` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `ownername` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `ownerlandlinenumber` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `ownermobilenumber` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `contactpersonlandlinenumber` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `contactpersonmobilenumber` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `contactpersonemail` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `purchasemanagername` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `purchasemanagerlandlinenumber` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `purchasemanagermobilenumber` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `purchasemanageremail` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `warehousemanagername` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `warehousemanagerlandlinenumber` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `warehousemanagermobilenumber` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `warehousemanageremail` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `expirylimit` double(8,0) DEFAULT NULL,
  `exprunningvalue` double(8,0) DEFAULT NULL,
  `distributionkey` bigint DEFAULT '0',
  `gpssavecount` int DEFAULT '0',
  `graceperiod` int DEFAULT '0',
  `reportcustcode` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT '0',
  `enablerental` int DEFAULT '0',
  `enableautofillsales` int DEFAULT NULL,
  `enablebatchselection` int DEFAULT NULL,
  `barcode` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `division` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT '0',
  `gracelimit` decimal(18,4) DEFAULT '0.0000',
  `visualcode` int DEFAULT NULL,
  `distribution_check_id` bigint DEFAULT NULL,
  `price_survey_id` bigint DEFAULT NULL,
  `advertisecode` int DEFAULT NULL,
  `enablereturnpassword` int DEFAULT '0',
  `statementdays` int DEFAULT '0',
  `creditltgraceamount` decimal(18,4) DEFAULT '0.0000',
  `DivisionCode` varchar(10) DEFAULT NULL,
  `Territory` varchar(50) DEFAULT NULL,
  `Class` varchar(50) DEFAULT NULL,
  `Region` varchar(50) DEFAULT NULL,
  `Cust_Disc_Code` varchar(50) DEFAULT NULL,
  `Transaction_Anals3` varchar(50) DEFAULT NULL,
  `Alpha` varchar(50) DEFAULT NULL,
  `Transaction_Anals2` varchar(50) DEFAULT NULL,
  `Control` varchar(50) DEFAULT NULL,
  `Grouping_Code` varchar(20) DEFAULT NULL,
  `Outlet_Quality` varchar(20) DEFAULT NULL,
  `OldestInvoiceDate` date DEFAULT NULL,
  `Analysis2` varchar(10) DEFAULT NULL,
  `ALTERNATEROUTECODE` varchar(10) DEFAULT NULL,
  `ALTERNATEPRICINGKEY` varchar(30) DEFAULT NULL,
  `chaincode` varchar(5) DEFAULT NULL,
  `itemmapkey` int DEFAULT NULL,
  `mslcategory` int DEFAULT NULL,
  `enforcemsl` smallint DEFAULT NULL,
  `custemail` varchar(50) DEFAULT NULL,
  `CreditTerms` varchar(10) DEFAULT NULL,
  `allowed_radius` decimal(18,4) DEFAULT NULL,
  `applytax` int DEFAULT '0',
  `traname` varchar(20) DEFAULT NULL,
  `tranamearabic` varchar(20) DEFAULT NULL,
  `taxregistrationnumber` varchar(20) DEFAULT NULL,
  `anpflag` int DEFAULT '0',
  `taxcardno` varchar(100) DEFAULT NULL,
  `crno` varchar(100) DEFAULT NULL,
  `NRP_FLAG` varchar(2) DEFAULT NULL,
  `saleslimitflag` int DEFAULT '0',
  `minsaleslimit` double(18,4) DEFAULT '0.0000',
  `maxsaleslimit` double(18,4) DEFAULT '0.0000',
  `invpromoyn` int DEFAULT '0',
  `invpromoplan` varchar(50) DEFAULT NULL,
  `combopromoyn` int DEFAULT NULL,
  `combopromoplan` int DEFAULT NULL,
  `rebateprintyn` varchar(50) DEFAULT '0',
  `ccid` varchar(50) DEFAULT NULL,
  `channel` varchar(50) DEFAULT NULL,
  `customerfacetime` int DEFAULT '0',
  PRIMARY KEY (`customercode`),
  UNIQUE KEY `u_alternatecode` (`alternatecode`),
  KEY `FK_CustomerMaster_PromotionKey` (`promotionkey`),
  KEY `FK_CustomerMaster_RouteMaster` (`routecode`),
  KEY `channel` (`channel`),
  CONSTRAINT `FK_CustomerMaster_PromokeyHeader` FOREIGN KEY (`promotionkey`) REFERENCES `promokeyheader` (`promotionkey`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_CustomerMaster_RouteMaster` FOREIGN KEY (`routecode`) REFERENCES `routemaster` (`routecode`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=320732114 DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
