<?php $this->translate = Zend_Registry::get('Zend_Translate'); ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
    <input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box">
        <div class="header">
        <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_org.png" class="margin_top_4">
		<h3><?php echo $this->title?></h3>
	    </div>
	    <div class="_50_3">
		<div class="_30 save_btn"><input class="border_none" type="button" value="Start IMPORT" name="importsync" id="importsync"></div>
		
	    </div>
        </div>
       
		</div>
		 <div class="_100">
			<div class="_20">&nbsp;</div>
			<div class="_20 label_text_align margin_top_12">
				<label class="advance_search_css"><?php echo $this->translate->_('Select Date').''.$this->colan;?>
				</label>
			</div>
			<div class="_20 label_text_align margin_right_1">
				<input type="text" id="txtdate" name="txtdate"
					value="<?php echo $this->date; ?>">
			</div>
			<div class="_10 margin_top_5 ie7marginright">
				<input type="submit" name="btnload" id="btnload"
					value="<?php echo $this->translate->_('OK'); ?>"
					class="margin_zero">
			</div>
		</div>
		<div class="clear"></div>
		<div id="StatusUpdate"
			style="margin: 10px 0 10px 0; background-color: white;">
			<div id="Loadingcontainer" style="display: none;text-align:center;">
				<img
					src="<?php echo $this->baseUrl()?>/public/images/ajax-loader-bar.gif">
			</div>
		</div>
	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
		$( "#txtdate" ).datepicker({
			dateFormat: 'dd-mm-yy'
		});
    });
});
</script>