<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({
   	url:base_url+"/reports/cashchequecollection/cashchequecollectiondata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route Code');?>','<?php echo $this->translate->_('Payment Type');?>','<?php echo $this->translate->_('Transaction Type');?>','<?php echo $this->translate->_('Document Number');?>','<?php echo $this->translate->_('Customer Number');?>','<?php echo $this->translate->_('Customer Name');?>','<?php echo $this->translate->_('Bank Name');?>','<?php echo $this->translate->_('Cheque Date');?>','<?php echo $this->translate->_('Cheque Number');?>','<?php echo $this->translate->_('Amount');?>'],
   	colModel:[
		{name:'routecode',index:'routecode', width:120},
   		{name:'mop',index:'mop', width:90},
        {name:'trantype',index:'trantype', width:90},
		{name:'receiptnumber',index:'receiptnumber', width:90},
        {name:'code',index:'code', width:90},
        {name:'customername',index:'customername', width:250},
        {name:'banknames',index:'bankname', width:250},
        {name:'checkdate',index:'checkdate', width:90},
		{name:'checknumber',index:'checknumber', width:90},
        {name:'amountpaid',index:'amountpaid', width:90,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'}
	],
	<?php if($this->css == 'ar_') { ?>
		direction :"rtl",
	<?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
   	pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
   	altRows : false,
    grouping:true,
    footerrow : true,
	userDataOnFooter : true,
    groupingView :
    {
        groupField : ['routecode','mop'],
        groupColumnShow : [false,false],
        groupCollapse : true,
       // groupText : ['','<b>Total Deposit For {0} : {1}</b>','<b>Total Deposit {0} : {1}</b>','<b>Total {0} : {1}</b>'],
        groupOrder: ['asc','asc'],
        groupSummary : [false,true],
        groupDataSorted : true
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});

</script>