<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">

jQuery("#search").jqGrid({        
   	url:base_url+"/reports/targetandcommission/targetdata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route Name');?>','<?php echo $this->translate->_('Salesman Name');?>','<?php echo $this->translate->_('From Date & To Date');?>','<?php echo $this->translate->_('Target On');?>','<?php echo $this->translate->_('Target Group');?>','<?php echo $this->translate->_('Value');?>','<?php echo $this->translate->_('Commission');?>','<?php echo $this->translate->_('Incentive %');?>','<?php echo $this->translate->_('Incentive');?>','<?php echo $this->translate->_('Achieved');?>','<?php echo $this->translate->_('Status');?>' ],
   	colModel:[
		{name:'routecode',index:'routecode', width:100 , align:"center"},		
		{name:'salesmanname1',index:'salesmanname1', width:200, align:"center"},  
		{name:'fromdate',index:'fromdate', width:200, align:"center"},		
        {name:'targettype',index:'targettype', width:100, align:"center"},
		{name:'packagedescription',index:'packagedescription', width:100, align:"center"},				
        {name:'quantity',index:'quantity', width:100, formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"},
        {name:'commision',index:'commision', width:100, formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"},
		{name:'insentivepercent',index:'insentivepercent', width:100, formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"},
		{name:'insentive',index:'insentive', width:100, formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"},
		{name:'achievedamount',index:'achievedamount', width:100, formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"},
		{name:'targetstatus',index:'targetstatus', width:100, formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"}
   	],
    <?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
    rowList:eval(RP_ROWLISTSHOW),
  //  loadonce:true,
    pager: '#pagersr',   
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:false,        
	groupingView :
        {
            groupField : ['routecode','fromdate'],
            groupColumnShow : [false,false],
            groupCollapse : true,
            groupOrder: ['asc','asc'] ,
            groupSummary : [true],
            showSummaryOnHide: false
        }
	
});
jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);
jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
</script>