<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Cash Description
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');

?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="basic_index_bank">
<?php if(SFA_Message::isSetMsg()) {  ?>
<div class="alert error">
    <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
</div>
<?php } ?>
<form method="post" action="" class="validate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_basics.png">
	<h3><?php echo $this->translate->_('Bank Master');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"basic","controller"=>"index","action"=>"bank"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li>
		    <a href="<?php echo $this->url(array("module"=>"basic","controller"=>"index","action"=>"bank"),"default", true);?>"><?php echo $this->overview?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"basic","controller"=>"index","action"=>"addbank"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>

    <div class="content no-padding with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
             <label class="_36 margin_top_10 label_text_align">
                <?php echo $this->translate->_('Code').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtcode" id="txtcode" type="text" readonly="readonly" class="required number" value="<?php echo $this->formdata['txtcode']?>" >
            </div>
        </div>
        <div class="_100">
             <label class="_36 margin_top_10 label_text_align">
                <?php echo $this->translate->_('Alternate Code').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtaltcode" id="txtaltcode" maxlength="50" type="text" class="required" value="<?php echo $this->formdata['txtaltcode']?>" >
            </div>
        </div>
        <div class="_100">
             <label class="_36 margin_top_10 label_text_align">
                <?php echo $this->translate->_('Name').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtname" id="txtname" type="text" maxlength="50" class="required" value="<?php echo $this->formdata['txtname']?>" />
            </div>
        </div>
	<div class="_100 ">
             <label class="_36 margin_top_10 label_text_align">
                <?php echo $this->translate->_('Name ('.$this->sec_lang.')').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtname_arb" id="txtname_arb" maxlength="50" class="arb_text_align" type="text" value="<?php echo $this->formdata['txtname_arb']?>" />
            </div>
        </div>
	<div class="_100 ">
             <label class="_36 margin_top_10 label_text_align">
                <?php echo $this->translate->_('A/C Number').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input class="number" name="txtacno" id="txtacno" maxlength="18" type="text" value="<?php echo $this->formdata['txtacno']?>" />
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Type').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddltype" name="ddltype">
                    <option value=""></option>
		    <option <?php echo $this->formdata['ddltype'] == '1' ? 'selected' : ''; ?> value="1">Deposit</option>
		    <option <?php echo $this->formdata['ddltype'] == '2' ? 'selected' : ''; ?> value="2">Customer</option>
		</select>
            </div>
        </div>	
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Status').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlstatus" name="ddlstatus">
		    <option <?php echo $this->formdata['ddlstatus'] == '1' ? 'selected' : ''; ?> value="1"><?php echo $this->translate->_('Active');?></option>
		    <option <?php echo $this->formdata['ddlstatus'] == '0' ? 'selected' : ''; ?> value="0"><?php echo $this->translate->_('Inactive');?></option>
		</select>
            </div>
        </div>
	<?php if($this->params["edit"]=="yes") { ?>
	<div class="_100">
		<label class="_36 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Created Date').''.$this->colan;?>
		</label>
		<div class="_50 margin_top_12 date_color margin_right_1"><?php echo $this->formdata['createddate']; ?></div>
    </div>
	<?php } ?>
	
	
	<div class="_100">&nbsp;</div>
	<div class="_100">&nbsp;</div>
	<div class="_100">&nbsp;</div>
    </div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</form>
</div> <!-- End of .box -->
</div>