<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add depot manager description
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="basic_index_depotmanager">
<form method="post" action="" novalidate="novalidate" class="validate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_basics.png">
        <h3><?php echo $this->translate->_('Branch/Depot Manager')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"basic","controller"=>"index","action"=>"depotmanager"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"basic","controller"=>"index","action"=>"depotmanager"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"basic","controller"=>"index","action"=>"adddepotmanager"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
    <div class="_100">
	<div class="clean"></div>
    </div>
    <div class="_100">
	<label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Code').''.$this->required;?>
	</label>
	<div class="_50 margin_right_1">
	    <input name="txtcode" id="txtcode" type="text" readonly="readonly"	class="required" value="<?php echo $this->formdata['txtcode']; ?>">
	</div>
    </div>
    <div class="_100">
	 <label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Alternate Code').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input name="txtaltcode" id="txtaltcode" type="text" class="text_align"  maxlength="50" value="<?php echo $this->formdata['txtaltcode']; ?>">
	</div>
    </div>
    <div class="_100">
	 <label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Name').''.$this->required;?>
	</label>
	<div class="_50 margin_right_1">
	    <input name="txtname" id="txtname" type="text" class="required" maxlength="50"  value="<?php echo $this->formdata['txtname']; ?>"/>
	</div>
    </div>
    <div class="_100 ">
	 <label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Name ('.$this->sec_lang.')').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input name="txtcom_arab" id="txtcom_arab" type="text"  maxlength="50" class="arb_text_align" value="<?php echo $this->formdata['txtcom_arab']; ?>"/>
	</div>
    </div>
    <div class="_100">
	<label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Parent Company').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <select id="ddlparent_com" name="ddlparent_com">
		<option value="">--- Select ---</option>
	    <?php
		for($i=0;$i<count($this->parent_company_data);$i++)
		{
		    ?>		    
			<option <?php echo $this->parent_company_data[$i]['id'] == $this->formdata['ddlparent_com'] ? 'selected' : ''; ?> value="<?php echo $this->parent_company_data[$i]['id']; ?>"><?php echo $this->parent_company_data[$i]['val'];?></option>
		    <?php
		}
	    ?>
	    </select>
	</div>
    </div>
    <div class="_100">
	 <label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Status').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <select id="ddlstatus" name="ddlstatus">
		<option <?php echo '1' == $this->formdata['ddlstatus'] ? 'selected' : ''; ?> value="1"><?php echo $this->translate->_('Active');?></option>
		<option <?php echo '0' == $this->formdata['ddlstatus'] ? 'selected' : ''; ?> value="0"><?php echo $this->translate->_('Inactive');?></option>
	    </select>
	</div>
    </div>
    <?php if($this->params["edit"]=="yes") { ?>
    <div class="_100">
	    <label class="_36 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Created Date').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_top_10 date_color margin_right_1"><?php echo $this->formdata['createddate']; ?></div>
    </div>
    <?php } ?>    
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>">
</form>
</div> <!-- End of .box -->
</div>