<?php
$this->translate = Zend_Registry::get('Zend_Translate');?>
<script type="text/javascript">
$(window).load(function() {
	defaultHideFields();
    $(function() {
	$( "#txt_route_end_date" ).datepicker({	    
		dateFormat: 'dd-mm-yy',
            changeYear:true,
            yearRange: '-10:+15'
	});
	$( "#txt_route_start_date" ).datepicker({	    
		dateFormat: 'dd-mm-yy',
            changeYear:true,
            yearRange: '-10:+15'
	});
    });

});
$(document).ready(function() {
	
	 $('#ddlfilterbyreport').change(function(){
		 defaultHideFields();
				var DropVal = $('#ddlfilterbyreport').val();
				var url = base_url+"/reports/otherreport/reportparamlist/id/"+DropVal;
				var result;
				$.ajax({
					url:url,
					data:$("#thisform").serialize(),
					type:'post',
					beforeSend: function() {
						//$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
					},
					success:function(data){
						var reportparameters = JSON.parse(data);
						var spname = reportparameters['reportsp'];
						var routecodeshow = reportparameters['routecode'];
						var customershow = reportparameters['customer'];
						var itemcodeshow = reportparameters['itemcode'];
						var fromdateshow = reportparameters['fromdate'];
						var todateshow = reportparameters['todate'];
						var groupbyshow = reportparameters['groupby'];	
						var report_name = reportparameters['reportname'];
						
						
					
						$("#hdnreportname").attr('value',report_name);
						$("#hdnspname").attr('value',spname);
						if(routecodeshow == "1")
						{
							$( "#route_area" ).show();
							ddlfilterby();	
						}
						else{
							$("#hdncount_route").attr('value',"1");						
						}
						
						if(customershow == "1")
						{
							$( "#customer_area" ).show();
							ddlfilterbycustomer();
							var showchannel = '<?php echo $this->showchannel; ?>';							
							if( showchannel == "false")
							$("#ddlfilterbycustomer option[value='2']").remove();
							$('#ddlfilterbycustomer').trigger('liszt:updated');
						}	
						else{
							$("#hdncount_customer").attr('value',"1");
						}
						if(itemcodeshow == "1")
						{
							$( "#item_area" ).show();
							ddlfilterbyitem();							
						}
						else{
							$("#hdncount_item").attr('value',"1");							
						}
						if(fromdateshow == "1")
						{
							$( "#fromdate_area" ).show();								
						}else{
							$("#hdncount_from").attr('value',"1");							
						}
						if(todateshow == "1")
						{
							$( "#todate_area" ).show();								
						}else{
							$("#hdncount_to").attr('value',"1");							
						}
						if(groupbyshow != "")
						{
							$("#hdngroupby").attr('value',groupbyshow);
						}else{
							$("#hdncount_groupby").attr('value',"1");							
						}
					}
				})
			
		});
	
		$('#ddlfilterby').change(function(){
			ddlfilterby();
	});
	function ddlfilterby()
	{
		var access_val = $('#ddlfilterby').val();
			if(access_val > 0) {
                $("#route-grid-div").show();
				filluseraccessgrid(access_val);
			}
			else {
                $("#route-grid-div").hide();
				$('#route-grid').html('').removeAttr('style');
			}
	}
	$('#ddlfilterbycustomer').change(function(){
		
		ddlfilterbycustomer();
	});
	function ddlfilterbycustomer()
	{
		var access_val = $('#ddlfilterbycustomer').val();
			if(access_val > 0) {
                $("#customer-grid-div").show();
				fillcustomergrid(access_val);
			}
			else {
                $("#customer-grid-div").hide();
				$('#customer-grid').html('').removeAttr('style');
			}
	}
	
	$('#ddlfilterbyitem').change(function(){
		
		ddlfilterbyitem();
	});
	function ddlfilterbyitem()
	{
			var access_val = $('#ddlfilterbyitem').val();
			if(access_val > 0) {
                $("#item-grid-div").show();
				fillitemgrid(access_val);
			}
			else {
                $("#item-grid-div").hide();
				$('#item-grid').html('').removeAttr('style');
			}
	}
	
	
	
});
	
function filluseraccessgrid(access_val)
{
	$('#route-grid').html('');
	var  url = '<?php echo $this->routegrid; ?>'+'/key/'+access_val;
	$.ajax({
		url:url,
		data:{},
		type:'post',
		beforeSend: function() {
			$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
		},
		success:function(returndata){
			$('#route-grid').html(returndata).removeAttr('style');
            if($('#route-grid').height() > 200) {
                $('#route-grid').css({"height":"200px","overflow-y":"auto"});
            }
            
			$("#loader").html('');
		}
	});	
	

}

function fillcustomergrid(access_val)
{
	$('#customer-grid').html('');
	var  url = '<?php echo $this->customergrid; ?>'+'/key/'+access_val;
	$.ajax({
		url:url,
		data:{},
		type:'post',
		beforeSend: function() {
			$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
		},
		success:function(returndata){
			$('#customer-grid').html(returndata).removeAttr('style');
            if($('#customer-grid').height() > 200) {
                $('#customer-grid').css({"height":"200px","overflow-y":"auto"});
            }
            
			$("#loader").html('');
		}
	});	
}



function fillitemgrid(access_val)
{
	$('#item-grid').html('');
	var  url = '<?php echo $this->itemgrid; ?>'+'/key/'+access_val;
	$.ajax({
		url:url,
		data:{},
		type:'post',
		beforeSend: function() {
			$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
		},
		success:function(returndata){
			$('#item-grid').html(returndata).removeAttr('style');
            if($('#item-grid').height() > 200) {
                $('#item-grid').css({"height":"200px","overflow-y":"auto"});
            }
            
			$("#loader").html('');
		}
	});	
	

}


function addhidden()
{
    if($("#ddlfilterby").length > 0 && $("#ddlfilterby").val() != "")
    {
        if($("input[name='chk[]']:checked").length <= 0)
        {
            jAlert("Please Select "+$("#ddlfilterby option:selected").text());
            return false;
        }
    }
	 if($("#ddlfilterbycustomer").length > 0 && $("#ddlfilterbycustomer").val() != "")
    {
        if($("input[name='chk_customer[]']:checked").length <= 0)
        {
            jAlert("Please Select "+$("#ddlfilterbycustomer option:selected").text());
            return false;
        }
    }
	 if($("#ddlfilterbyitem").length > 0 && $("#ddlfilterbyitem").val() != "")
    {
        if($("input[name='chk_item[]']:checked").length <= 0)
        {
            jAlert("Please Select "+$("#ddlfilterbyitem option:selected").text());
            return false;
        }
    }
    return true;
}
function defaultHideFields()
{						$( "#route_area" ).hide();
						$( "#customer_area" ).hide();
						$( "#item_area" ).hide();
						$( "#fromdate_area" ).hide();
						$( "#todate_area" ).hide();
						$( "#route-grid-div" ).hide();
						$( "#customer-grid-div" ).hide();
						$( "#item-grid-div" ).hide();
						
						/*Following code for clear data*/
						$("#ddlfilterby").val('');
						$("#ddlfilterbycustomer").val('');
						$("#ddlfilterbyitem").val('');
						$('select').trigger('liszt:updated');
						
						
						$("#hdngroupby").val('');
						$("#hdnspname").val('');
						
						$("#hdncount_route").val('');
						$("#hdncount_customer").val('');
						$("#hdncount_item").val('');
						$("#hdncount_from").val('');
						$("#hdncount_to").val('');
						$("#hdncount_groupby").val('');
						
						
}

</script>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10" id="for_report_only">
<div class="box" id="report_basic_commstatus">
<form id="thisform" name="thisform" target="_blank" onsubmit="return addhidden();"  action="" class="validate"  method="post" >
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_reports.png">
        <h3><?php echo $this->translate->_('Other Reports');?></h3>
    </div>
 </div>
<div class="content with-actions min_height_10">
    <!--TOP RADIOS-->
   <div class="_100">
        <label class="_40_1 label_text_align margin_top_12">
            <?php  echo $this->translate->_('Select Report').''.$this->required; ?>
        </label>
        <div class="_30 margin_right_1">
            <select id="ddlfilterbyreport" name="ddlfilterbyreport" class="required">
            <option value="">--- Select ---</option>
            <?php
            for($i=0;$i<count($this->ddlfilterbyreport);$i++)
            {
            ?>
                <option value="<?php echo $this->ddlfilterbyreport[$i]['id'];?>"><?php echo $this->ddlfilterbyreport[$i]['val'];?></option>
            <?php } ?>
            </select>
        </div>
    </div>
	  
	<div class="_100" id="route_area">
            <label class="_40_1 label_text_align margin_top_12">
               <?php echo $this->translate->_('Filter By (Route)').''.$this->colan;?>
            </label>
            <div class="_30 margin_right_1">
               <select id="ddlfilterby" name="ddlfilterby">
               <option value="">--- All ---</option>
               <?php
               for($i=0;$i<count($this->filterby);$i++)
               {
               ?>
                   <option value="<?php echo $this->filterby[$i]['id'];?>"><?php echo $this->filterby[$i]['val'];?></option>
               <?php } ?>
               </select>
            </div>
 </div>
    <div class="_100" id="route-grid-div" style="display:none;">
            <label class="_25 margin_top_10 label_text_align">&nbsp;</label>
            <div id="loader">&nbsp;</div>
            <div class="_60" id="route-grid">
               &nbsp;
            </div>
        </div>
		
	   	<div class="_100" id="customer_area">
            <label class="_40_1 label_text_align margin_top_12">
               <?php echo $this->translate->_('Filter By (Customer)').''.$this->colan;?>
            </label>
            <div class="_30 margin_right_1">
               <select id="ddlfilterbycustomer" name="ddlfilterbycustomer">
               <option value="">--- All ---</option>
               <?php
               for($i=0;$i<count($this->filterbycustomer);$i++)
               {
               ?>
                   <option value="<?php echo $this->filterbycustomer[$i]['id'];?>"><?php echo $this->filterbycustomer[$i]['val'];?></option>
               <?php } ?>
               </select>
            </div>
 </div>
    <div class="_100" id="customer-grid-div" style="display:none;">
            <label class="_25 margin_top_10 label_text_align">&nbsp;</label>
            <div id="loader">&nbsp;</div>
            <div class="_60" id="customer-grid">
               &nbsp;
            </div>
    </div>	
		
		
		
   	<div class="_100" id="item_area">
            <label class="_40_1 label_text_align margin_top_12">
               <?php echo $this->translate->_('Filter By (Item)').''.$this->colan;?>
            </label>
            <div class="_30 margin_right_1">
               <select id="ddlfilterbyitem" name="ddlfilterbyitem">
               <option value="">--- All ---</option>
               <?php
               for($i=0;$i<count($this->filterbyitem);$i++)
               {
               ?>
                   <option value="<?php echo $this->filterbyitem[$i]['id'];?>"><?php echo $this->filterbyitem[$i]['val'];?></option>
               <?php } ?>
               </select>
            </div>
 </div>
    <div class="_100" id="item-grid-div" style="display:none;">
            <label class="_25 margin_top_10 label_text_align">&nbsp;</label>
            <div id="loader">&nbsp;</div>
            <div class="_60" id="item-grid">
               &nbsp;
            </div>
    </div>
   <div class="_100" id="fromdate_area">
	    <label class="_40_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('From Date').''.$this->colan;?>
	    </label>
	    <div class="_30 margin_right_1">
            <input name="txt_route_start_date" id="txt_route_start_date" maxlength="50" type="text"  value="<?php echo date('d-m-Y');?>" class="margin_top_5" >
	    </div>
    </div>
<div class="_100" id="todate_area">
	    <label class="_40_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('To Date').''.$this->colan;?>
	    </label>
	    <div class="_30 margin_right_1">
            <input name="txt_route_end_date" id="txt_route_end_date" maxlength="50" type="text"  value="<?php echo date('d-m-Y');?>" class="margin_top_5" >
	    </div>
    </div>
   
    <div class="clear space_20"></div>
    <div class="_100" id="ok_button">
	<div class="_45">&nbsp</div>
	<div class="_10_1">
	    <input type="submit" id="sub_ok" name="sub_ok" value="<?php echo $this->translate->_('OK');?>" />
	</div>
	
    </div>
         <div class="clear space_20"></div>
</div>
<input type="hidden" id="hdncount_route" name="hdncount_route" value="" />
<input type="hidden" id="hdncount_customer" name="hdncount_customer" value="" />
<input type="hidden" id="hdncount_item" name="hdncount_item" value="" />
<input type="hidden" id="hdncount_from" name="hdncount_from" value="" />
<input type="hidden" id="hdncount_to" name="hdncount_to" value="" />
<input type="hidden" id="hdncount_groupby" name="hdncount_groupby" value="" />

<input type="hidden" id="hdngroupby" name="hdngroupby" value="" />
<input type="hidden" id="hdnspname" name="hdnspname" value="" />
<input type="hidden" id="hdnreportname" name="hdnreportname" value="" />

</form>
</div> <!-- End of .box -->
</div>

