<?php
/**
 
 * @since      Class available since Pagignation
 * @version    Release: @1.0@
 * @author     HC [harsh@elantechnologies.com]
 * @author     MB [mayur.b@elantechnologies.com]
 * @copyright  Elan technologies
 *
 * Short description : Inserted pagignation with multi search and sort functionalities.
 *
 *
 */

$this->translate = Zend_Registry::get('Zend_Translate');

$this->paginator = $this->pagegridshow['paginator'];

$grid_js_settings =  $this->pagegridshow['datagrid']['settings'];

$grid_js_settings[] = $this->url();

$this->showdatagrid = $this->pagegridshow['datagrid'];

/*
 * Added stylesheet for paging
 */
$this->headLink()->appendStylesheet($this->baseUrl().'/public/css/pagegrid_style.css');


$datashowgrid = $this->showdatagrid['data'];

/*
 * Retrieve search parameters form values
 */
$this->searchvalues = $grid_js_settings['search_values'];

$Paginator_SearchDetails = new Zend_Session_Namespace('Paginator_SearchDetails');
$Paginator_Paging = new Zend_Session_Namespace('Paginator_Paging');

?>

<script type="text/javascript">
	var base_url = '<?php echo$this->baseurl();?>';
	/*
	* Hide show search box
	*/
	
	//$(document).ready(function(){
	//
	//	$('#grid_search_text').keyup(function(){
	//	
	//		$.ajax({
	//			url: "http://localhost/sfa/",
	//			type:"post",
	//			data: 'gosearch=' + $('#grid_search_text').val(), 
	//			success: function(data){
	//				alert(data);	
	//			}
	//		});
	//	});	
	//});
	
	function searchbox(obj) {
		if(obj == 'hide') {
		    $('#draggable').hide();
		    $('#table-searchall').show();
		    $('#table-showpages').show();
		    
		} else {
		    $('#draggable').show();
		    $('#table-searchall').hide();
		    $('#table-showpages').hide();
		}
	}
	
	/*
	* Reset button will redirect to current url
	*/
	function resetSearch() {
		
		$('.sefield').val('');
		$('#reset_val').val(1);
		$('#frmoverview').submit();		
	}
	
	/*
	* Added stylesheet for paging
	*/
	function addMore()
	{
		
		
		<?php
		$tmp = 0;
		$tempval = '';
		if(isset($this->showdatagrid['columns'])) {
			foreach($this->showdatagrid['columns'] as $key => $val)
			{
			    $tempval .= '<option value="'.$tmp.'">'.ucfirst($val).'</option>';
			    $tmp++;
			}		
		?>		
		var Searchbox_tmp = '<tr class="sf"><td class="fields" width="40%"><select class="chzn-done" name="field[]" >'; 
		Searchbox_tmp = Searchbox_tmp + '<?php echo $tempval; ?>';
		Searchbox_tmp = Searchbox_tmp + '</select></td><td class="ops" width="25%"><select class="default chzn-done" name="op[]" ><option value="eq">equal</option><option value="ne">not equal</option><option value="lt">less</option><option value="le">less or equal</option><option value="gt">greater</option><option value="ge">greater or equal</option><option value="bw">begins with</option><option value="bn">does not begin with</option><option value="in">is in</option><option value="ni">is not in</option><option value="ew">ends with</option><option value="en">does not end with</option><option value="cn">contains</option><option value="nc">does not contain</option></select></td><td class="data" width="25%" ><input type="text" style="" name="seachvalue[]" class="default vdata sea chzn-done"></td><td width="5%"  ><div class="ui-del ui-state-default ui-corner-all"><span class="ui-icon ui-icon-minus" onclick="$(this).parent().parent().parent().remove()">';
		Searchbox_tmp = Searchbox_tmp + '<img src="'+base_url+'/public/pagegrid_images/remove.png" alt="remove" />';
		Searchbox_tmp = Searchbox_tmp + '</span></div></td><td width="5%" ><div class="ui-add ui-state-default ui-corner-all"><span class="ui-icon ui-icon-plus" onclick="addMore();">';
		Searchbox_tmp = Searchbox_tmp + '<img src="'+base_url+'/public/pagegrid_images/add.png" alt="Add" />';
		Searchbox_tmp = Searchbox_tmp + '</span></div></td></tr>';
		<?php } ?>
		
	    $('#mydata').append(Searchbox_tmp);
	}
	
	function toggleChecked(status) {
		$("#table-example .checkbox").each( function() {
		
			if(status == true)
				status = false;
			else
				status = true;
				
		    $(this).attr("checked",status);
			$('#chkall').attr("checked",status);
		});
	}
	 
	function toggleUnChecked(status,val) {
		
			var d = status;
			var tval = val;
			
			$('#chkall').attr("checked",false);
			
			var tmp_array = new Array();
			var tmp = 1;
			var j = '0';
			
			$("#table-example input:checkbox").each( function(e) {
				
				
				if(e>0 && tval!=this.value)
				{
					
					if(this.checked==false){
						tmp = 0;
					}
				}
			
			})
			if(d==true)
				tmp = 0;
			
			if(tmp == 1){
				$('#chkall').attr("checked",true);
			}
	}
	
	<?php if(isset($this->showdatagrid['columns'])) { ?>
	var grid_colsname = new Array("<?php echo implode('","',array_values($this->showdatagrid['columns']));?>");
	<?php } ?>
</script>

<script type="text/javascript">
    function changeRowRange(obj) {
	if(obj!="")
	{
		var newUrl = "<?php echo $this->url(array('prow'=>'prowval','page'=>'1')); ?>";        
		newUrl = newUrl.replace("prowval",obj)        
		window.location = newUrl;
	}
    }
</script>

	<!-- Content -->
	
	<div id="paging_grid">
				
					<!--<h2 class="grid_12">Tables</h2>
					<div class="clear"></div>-->
					
		  <div class="grid_12">
						<div class="box">
							
						<?php
						if($grid_js_settings['configuration_params']['show_grid_heading'] == true || $grid_js_settings['configuration_params']['show_searchbox'] == true) {
							echo '<div class="header">';
							
					if($grid_js_settings['configuration_params']['show_grid_heading'] == true)
					{
						echo '<h3>'.$grid_js_settings['configuration_params']['grid_heading_message'].'</h3>';
					}
					if($grid_js_settings['configuration_params']['show_searchbox'] == true) {
					    ?>
					    <div class="right">
						    <a href="javascript:;" onclick="javascript:searchbox();"><img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/search_icon.png" /></a>
					    </div>
					    <?php }
					    echo '</div>';
					    } ?>
					
					<div class="content  min_height_10">
					<!-- SearchBox  -->
	<div id="draggable"  class="top" style="display:none;" >
		
		<div class="grid_12">
						<div class="box tabbed">
							<div class="header no-icon">
								<h3><?php echo $this->translate->_('Advance Search');?></h3>
								<div class="right">
									<!--<span class="ui-icon ui-icon-close" title="Close" onclick="searchbox('hide')">-->
									<a title="Close" onclick="searchbox('hide')">
										<img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/close.png" />
									<!--</span>	-->
									</a>
									</div>
							</div>
							<div class="content min_height_10">
								<!--	Comment By Hiren dave on 7th Feb 2012   -->
								<!--<form id="searchForm" name="searchForm" method="post">-->
								<table id="mydata" width="100"  class="table">
								<tbody>
		    <?php
		    /*
		     * Display searched values in form
		     */
		    if(count($this->searchvalues[0]) > 0) {
			$tempGroupon = $this->searchvalues[3];
			
			for($sm=0; $sm<count($this->searchvalues[0]); $sm++)
			{
				$tempFields = $this->searchvalues[0];
				$tempValues = $this->searchvalues[1];
				$tempOpt = $this->searchvalues[2];
			?>
		    <tr class="sf">
			<td class="fields" width="40%" c  >
			    <select name="field[]" class="chzn-done" id="search_field"  >
				<?php
				$tmp = 0;
				foreach($this->showdatagrid['columns'] as $key => $val)
				{
					$selected = ($tempFields[$sm] == $tmp) ? 'selected="selected"' : '';
				    echo '<option value="'.$tmp.'" '.$selected .'>'.ucfirst($val).'</option>';
				    $tmp++;
				}
				?>
			    </select>
			</td>
			<td class="ops">				
				<select id="query_cond" class="default chzn-done" name="op[]">
					<option value="eq" <?php if($tempOpt[$sm]=='eq') echo "selected='selected'"; ?>><?php echo $this->translate->_('Equal');?></option>
					<option value="ne" <?php if($tempOpt[$sm]=='ne') echo "selected='selected'"; ?>><?php echo $this->translate->_('Not Equal');?></option>
					<option value="lt" <?php if($tempOpt[$sm]=='lt') echo "selected='selected'"; ?>><?php echo $this->translate->_('Less');?></option>
					<option value="le" <?php if($tempOpt[$sm]=='le') echo "selected='selected'"; ?>><?php echo $this->translate->_('Less or Equal');?></option>
					<option value="gt" <?php if($tempOpt[$sm]=='gt') echo "selected='selected'"; ?>><?php echo $this->translate->_('Greater');?></option>
					<option value="ge" <?php if($tempOpt[$sm]=='ge') echo "selected='selected'"; ?>><?php echo $this->translate->_('Greater or Equal');?></option>
					<option value="bw" <?php if($tempOpt[$sm]=='bw') echo "selected='selected'"; ?>><?php echo $this->translate->_('Begins With');?></option>
					<option value="bn" <?php if($tempOpt[$sm]=='bn') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not Begin With');?></option>
					<option value="in" <?php if($tempOpt[$sm]=='in') echo "selected='selected'"; ?>><?php echo $this->translate->_('Is In');?></option>
					<option value="ni" <?php if($tempOpt[$sm]=='ni') echo "selected='selected'"; ?>><?php echo $this->translate->_('Is not In');?></option>
					<option value="ew" <?php if($tempOpt[$sm]=='ew') echo "selected='selected'"; ?>><?php echo $this->translate->_('Ends With');?></option>
					<option value="en" <?php if($tempOpt[$sm]=='en') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not End With');?></option>
					<option value="cn" <?php if($tempOpt[$sm]=='cn') echo "selected='selected'"; ?>><?php echo $this->translate->_('Contains');?></option>
					<option value="nc" <?php if($tempOpt[$sm]=='nc') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not Contain');?></option>
				</select>
			</td>
			<td class="data"  ><input type="text" style="" name="seachvalue[]" value="<?php echo $tempValues[$sm]; ?>" class="sea sefield chzn-done" ></td>
			<td width="5%" style="padding-top:10px;" >
				<div class="ui-del ui-state-default ui-corner-all"><span class="ui-icon ui-icon-minus"><img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/remove.png" /></span></div>
			</td>
			<td width="5%" style="padding-top:10px;" >
				<div class="ui-add ui-state-default ui-corner-all"><span class="ui-icon ui-icon-plus" onclick="addMore();"><img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/add.png" /></span></div>
			</td>
		    </tr>	
			<?php
			}
		    } else {
		    ?>
		    <tr >
			<td class="fields margin_t" width="40%" >
			    <select name="field[]" id="search_field" class="default chzn-done" >
				<?php
				$tmp = 0;
				if(isset($this->showdatagrid['columns'])) {
					foreach($this->showdatagrid['columns'] as $key => $val)
					{
					    echo '<option value="'.$tmp.'">'.ucfirst($val).'</option>';
					    $tmp++;
					}
				} 
				?>
			    </select>
			</td>
			<td class="ops ">
				<select id="query_cond" class="default chzn-done" name="op[]" >
					<option value="eq" <?php if($tempOpt[$sm]=='eq') echo "selected='selected'"; ?>><?php echo $this->translate->_('Equal');?></option>
					<option value="ne" <?php if($tempOpt[$sm]=='ne') echo "selected='selected'"; ?>><?php echo $this->translate->_('Not Equal');?></option>
					<option value="lt" <?php if($tempOpt[$sm]=='lt') echo "selected='selected'"; ?>><?php echo $this->translate->_('Less');?></option>
					<option value="le" <?php if($tempOpt[$sm]=='le') echo "selected='selected'"; ?>><?php echo $this->translate->_('Less or Equal');?></option>
					<option value="gt" <?php if($tempOpt[$sm]=='gt') echo "selected='selected'"; ?>><?php echo $this->translate->_('Greater');?></option>
					<option value="ge" <?php if($tempOpt[$sm]=='ge') echo "selected='selected'"; ?>><?php echo $this->translate->_('Greater or Equal');?></option>
					<option value="bw" <?php if($tempOpt[$sm]=='bw') echo "selected='selected'"; ?>><?php echo $this->translate->_('Begins With');?></option>
					<option value="bn" <?php if($tempOpt[$sm]=='bn') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not Begin With');?></option>
					<option value="in" <?php if($tempOpt[$sm]=='in') echo "selected='selected'"; ?>><?php echo $this->translate->_('Is In');?></option>
					<option value="ni" <?php if($tempOpt[$sm]=='ni') echo "selected='selected'"; ?>><?php echo $this->translate->_('Is not In');?></option>
					<option value="ew" <?php if($tempOpt[$sm]=='ew') echo "selected='selected'"; ?>><?php echo $this->translate->_('Ends With');?></option>
					<option value="en" <?php if($tempOpt[$sm]=='en') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not End With');?></option>
					<option value="cn" <?php if($tempOpt[$sm]=='cn') echo "selected='selected'"; ?>><?php echo $this->translate->_('Contains');?></option>
					<option value="nc" <?php if($tempOpt[$sm]=='nc') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not Contain');?></option>
				</select>
			</td>
			<td class="data" width="25%" ><input type="text" style="" name="seachvalue[]" class="default vdata sea sefield chzn-done"></td>
			<td width="5%" style="padding-top:10px;" >
				<div class="ui-del ui-state-default ui-corner-all margin_t2"><span class="ui-icon ui-icon-minus"><img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/remove.png" /></span></div>
			</td>
			<td width="5%" style="padding-top:10px;">
				<div class="ui-add ui-state-default ui-corner-all margin_t2"><span class="ui-icon ui-icon-plus" onclick="addMore();"><img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/add.png" /></span></div>
			</td>
		    </tr>
		    <?php } ?>
		</tbody>
		<tfoot>
			<tr>
			    <td width="33%">
				<div class="_10 margin_top_12" style="display: inline-block; float: left;" >				   
				    <input type="button" name="reset" id="sea_reset"  value="<?php echo $this->translate->_('Reset');?>" onclick="resetSearch();" />
				    <input type="hidden" value="0" name="reset_val" id="reset_val">
				</div>
			    </td>
				 <td width="33%">
				<div class="_100 margin_top_15">				    
					<label class="_20 matchText left margin_left_1 margin_top_12"><?php echo $this->translate->_('Match');?></label>
				    <div class="left _50 margin_top_3" id="">
						<select name="groupOp[]" class="chzn-done"  >
							<option value="AND" <?php if($tempGroupon[0]=='AND') { echo 'selected="selected"'; } ?>><?php echo $this->translate->_('All');?></option>
							<option value="OR" <?php if($tempGroupon[0]=='OR') { echo 'selected="selected"'; } ?>><?php echo $this->translate->_('Any');?></option>
						</select>
					</div>
				    <label class="_20 rulesText left margin_right_1 margin_top_12"> <?php echo $this->translate->_('Rules');?></label>					
				</div>
				</td>
				 <td width="33%">
				
				<div class="_10 margin_top_12">
				    <input type="submit" name="search" value="<?php echo $this->translate->_('Find');?>" id="sea_find" />
				</div>				
			    </td>
			</tr>
			<tr>
				<td>&nbsp;
				</td>
			</tr>
		</tfoot>	
								</table>								
							</div> <!-- End of .content -->
						</div> <!-- End of .box -->
					</div>
	
	    
<!--	Comment By Hiren dave on 7th Feb 2012   -->
	    <!--</form>-->
	</div>
	<!-- End SearchBox -->

	<div class="top shead">
	<?php
	//echo "<pre>";
	//print_r($grid_js_settings);
	//echo "</pre>";
	
	if(isset($Paginator_Paging->show_records_per_page))
		$show_records_per_page = $Paginator_Paging->show_records_per_page;
	else
		$show_records_per_page = $grid_js_settings["configuration_params"]["show_records_per_page"];
		
	?>
	<div id="table-showpages" class="_50 margin_0" >&nbsp;
	<?php
	if( ($grid_js_settings['configuration_params']['show_grid_heading'] == true && $grid_js_settings['total_data'] > $this->paginator->getItemCountPerPage() ) || $grid_js_settings['total_data'] > 10)
	{
	?>

	<label id="ie7_searchlabel" class="_30 label_text_align margin_top_12 ie_margin_0" >
		<?php echo $this->translate->_('Show entries')." ".$this->translate->_('Colan'); ?>
	</label>
	<div class="_50_3 margin_right_1" id="ie7_searchcombo" >
		<select name="show_records_per_page" size="1" id="selMBC" class="pageitem" onchange="this.form.submit();" >
		  <option value="10" <?php if($show_records_per_page==10 ) { ?> selected="selected" <?php } ?> >10</option>
		  <option value="25" <?php if($show_records_per_page==25 ) { ?> selected="selected" <?php } ?> >25</option>
		  <option value="50" <?php if($show_records_per_page==50 ) { ?> selected="selected" <?php } ?> >50</option>
		  <option value="100" <?php if($show_records_per_page==100 ) { ?> selected="selected" <?php } ?> >100</option>
		</select>
	</div>
	<div class="_20">&nbsp;</div>
	<?php		
	}	
	?>
	</div>
	<div id="table-searchall" class="_50">
	<?php
		if($grid_js_settings['configuration_params']['show_searchbox'] == true) {
	?>
	
	  
		<div class="_36">&nbsp;</div>
		  <label class="_25 label_text_align margin_top_12"><?php echo $this->translate->_('Search')." ".$this->translate->_('Colan');?></label>
		  <div class="_40">
			<input type="text" class="sea" name="grid_search_text" id="grid_search_text" value="<?php echo $Paginator_SearchDetails->shortsearch_value; ?>" >
		  </div>	  
	<?php } ?>
	</div>
	  <div class="clear"></div>
	</div>
  <?php
	// Check the data for the data grid display
	if(isset($grid_js_settings['total_data']) && $grid_js_settings['total_data'] > 0)
	{
	?>
							  <table id="table-example" class="table">
									<thead>
										<tr>
											
											<?php
		    /*
		     * Display checkbox if is set to true
		     */
		    if($grid_js_settings['configuration_params']['show_selectbox'] == true) { 
			echo '<th width="13"><input type="checkbox" id="chkall" name="chkall" onclick="toggleChecked(this.checked);" class="checkbox" /></th>';
		    }
		    
		    $colsname_int = 0;
			
			/*
			* Set default sort order images
			*/
			$grid_js_settings['order_imagetype'] = "sorting";
			
			
			
			
			/*
			* Set sorting images
			*/
			if(!is_null($grid_js_settings['order_columns_number']) && trim($grid_js_settings['order_type'])=="asc")
			{
				$grid_js_settings['order_imagetype'] = "sorting_desc";
			}
			else if(!is_null($grid_js_settings['order_columns_number']) && trim($grid_js_settings['order_type'])=="desc")
			{
				$grid_js_settings['order_imagetype'] = "sorting_asc";
			}
		
			$data_display_collection = "";
			
			//print_r($this->showdatagrid['columns']); die();
			
			foreach($this->showdatagrid['columns'] as $key => $val)
			{
				$colnameshow = "";
				if(is_integer($key))
				{
					$colnameshow = $val;
				}
				else
				{
					$colnameshow = $key;
				}
				$colnameshow = $val;
				
				
				/*
				* Prepare data grid columns heading with sorting parameters
				*/
				if(!is_null($grid_js_settings['order_columns_number']) && $grid_js_settings['order_columns_number']==$colsname_int)
				{
					$data_display_collection.= "<th class='".$grid_js_settings['order_imagetype']."'>";
				
				    $data_display_collection.= "<a href='".$this->url(array('order'=> $colsname_int.'_'.$grid_js_settings['order_type']))."'>".ucfirst($colnameshow)." </a>";
				}
				else
				{
					$data_display_collection.= "<th class='sorting'>";
					
				$data_display_collection.= "<a href='".$this->url(array('order'=> $colsname_int.'_asc'))."'>"
						.ucfirst($colnameshow)."</a>";

				}
				$data_display_collection.= "</th>";
				
				
				$colsname_int++;
			}
			echo $data_display_collection;
		    /*
		     * Display editlink if is set to true
		     */
		    if($grid_js_settings['configuration_params']['show_editlink'] == true) { 
			echo '<th >&nbsp;</th>';
		    }
		    
		    /*
		     * Display deletelink if is set to true
		     */
		    if($grid_js_settings['configuration_params']['show_deletelink'] == true) { echo '<th >&nbsp;</th>'; }
			
			
			/*
		     * Display extra link if is set to true
		     */
		    if($grid_js_settings['configuration_params']['show_extralink'] == true) {
				
				for($sel=0; $sel<count($grid_js_settings['configuration_params']['extralink']); $sel++)
					echo '<th >&nbsp;</th>';
			}
		    
			?>
										</tr>
									</thead>
									<tbody>
			<?php
			/*
			 * fill data array in table body
			 */
			
			for($k=0;$k<count($datashowgrid);$k++)
			{
				$classname='class="gradeC"';
				if(($k+1)%2==0)
				{
					$classname='class="gradeA"';
				}
				
				echo "<tr ".$classname." >";
				foreach($datashowgrid[$k] as $key => $val)
				{
					//comment added by Gpatel this is check column aignment for right side or left side
					if(in_array($key,$this->showdatagrid['settings']['configuration_params']['show_columns_right_side']))
					{
					echo "<td class='align_right'>";	
					}else{
					echo "<td>";	
					}
					//comment added by Gpatel end.
					
					
					if($val) {					
						echo $val;					
					}
					else
					{
						echo "&nbsp;";
					}
					echo "</td>";
				}
				echo "</tr>";
			}
			?>
			</tbody>
		</table>
            <div class="actions">
		<?php
		/*
		* Display paging
		*/		
		if($grid_js_settings['total_data'] > $this->paginator->getItemCountPerPage())
		{
		   echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
		
		}
		?>
			</div>
		</div> <!-- End of .content -->
		<?php
	}else{
		echo '<div class="clear_only nodata_message margin_top_50 margin_bottom_10"><b>'.$grid_js_settings['configuration_params']['nodata_message']."</b></div>";
	}
	?>
						</div>
							<div class="clear"></div>
						</div> <!-- End of .box -->
					</div> <!-- End of .grid_12 --><!-- End of .grid_12 -->
					
		  <div class="clean"></div>
					
	</div>