<?php
/**
 *
 * @since      Class available since Pagignation
 * @version    Release: @1.0@
 * @author     M@M
 * @copyright  Elan Technologies
 *
* Short description : This file is used to show pagignation on ajax data grid (especially used when need second ajax grid on same page)
 *
 *
 */

?>

<div class="actions-left">
    <div class="dataTables_info" id="table-example_info">
    <!---Showing 1 to 10 of 57 entries--->
    
    Showing <?php echo (($this->current*$this->itemCountPerPage)-$this->itemCountPerPage+1); ?> - <?php echo (($this->current*$this->itemCountPerPage) < $this->totalItemCount) ? ($this->current*$this->itemCountPerPage) : $this->totalItemCount; ?> of <?php echo $this->totalItemCount; ?>
    </div>
</div>
<div class="actions-right">
            <div class="dataTables_paginate paging_full_numbers" id="table-example_paginate">
                        <!-- First page link -->
                        <?php if (isset($this->previous)): ?>
                              <a href="javascript:void(0);"  class="page_number" id="<?php echo $this->url(array('page' => $this->first)); ?>" class="imgicon">
                              <span class="first paginate_button" id="table-example_first">First</span>
                              </a>
                        <?php else: ?>
                                <span class="first paginate_button paginate_button_disabled" id="table-example_first">First</span>
                        <?php endif; ?>
                        
                        
                        <!-- Previous page link -->    
                        <?php if (isset($this->previous)): ?>
                              <a href="javascript:void(0);" class="page_number" id="<?php echo $this->url(array('page' => $this->previous)); ?>" class="imgicon">
                              <span class="previous paginate_button" id="table-example_previous">Previous</span>
                              </a>
                        <?php else: ?>
                            <span class="previous paginate_button paginate_button_disabled" id="table-example_previous">Previous</span>
                        <?php endif; ?>
        
        
                            
                         <!-- Numbered page links -->
                        <?php foreach ($this->pagesInRange as $page): ?>
                            <?php if ($page != $this->current): ?>
                            <span class="paginate_button">
                                <a href="javascript:void(0);" class="page_number" id="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
                            </span>
                            <?php else: ?>
                                <span class="paginate_active">
                                    <a href="javascript:void(0);" class="page_number" id="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
                                </span> 
                            <?php endif; 
                                if($page != $this->last) {
                                    //echo '<span>...</span>';
                                }
                            ?>
                        <?php endforeach; ?>
                        
                        <!-- Next page link -->
                    <?php if (isset($this->next)): ?>
                          <a href="javascript:void(0);" class="page_number" id="<?php echo $this->url(array('page' => $this->next)); ?>" class="imgicon">
                          <span class="next paginate_button" id="table-example_next">Next</span>
                          </a>
                    <?php else: ?>
                           <span class="next paginate_button paginate_button_disabled" id="table-example_next">Next</span>
                    <?php endif; ?>
                        
                       
                       <!-- Last page link -->
                    <?php if (isset($this->next)): ?>
                          <a href="javascript:void(0);" class="page_number" id="<?php echo $this->url(array('page' => $this->last)); ?>" class="imgicon">
                          <span class="last paginate_button" id="table-example_last">Last</span>
                          </a>
                    <?php else: ?>
                        <span class="last paginate_button paginate_button_disabled" id="table-example_last">Last</span>
                    <?php endif; ?> 
                            
                      
                            
                    </div>
            </div>
           

        
        
<!-- End Pagging -->

