<?php
    $this->Common_NameSpace = new Zend_Session_Namespace('Common');
    echo $this->headLink()->appendStylesheet($this->baseUrl().'/public/css/report-style.css');
?>
     <div>
        <?php if($this->paging->showSearch) { ?>
        <center>
        
        <div class="wrapLine">
            
            <form  method="post" action="" id="searchReportGridForm" name="searchReportGridForm" >
                <input type="text" name="searchText" id="searchText" value="<?php echo $this->Common_NameSpace->pageSearch; ?>" >
                <input type="submit" value="Search" name="search" id="search" style="float:right" />
                
            </form>
            
        </div>
        </center>
        <?php } ?>
        
        <div id="reportContent" >
                 
            <table cellpadding="0" cellspacing="2">
              
                <tr>
                <?php foreach($this->paging->Columns as $_c){ ?>
                    <th><?php echo $_c; ?></th>
                <?php } ?>
                </tr>
                
                <?php
                
                
                if($this->paging->TotalRecords)
                {
                    $columnSum = array();
                    $counter = 0;
                    foreach($this->result as $noticia)
                    {
                        // SET THE ALTERNATE ROW BACKGROUND COLOR
                        $class_row = $counter++%2 ? "altrow" : "";
                        echo "<tr >";
                        $cnt = 0;
                         // LOOP FOR EACH FIELD (COLUMN)
                         foreach($this->paging->Fields as $_f){
                            
                            // GET THE TEXT ALIGNMENT FOR EACH ROW
                            $text_align = 'text_align_'.$this->paging->Align[$cnt];
                            ?>
                                <td class="<?php echo $class_row." ".$text_align; ?> "><?php echo $noticia[$_f]; ?></td>
                            <?php
                            
                            // COUNT FOR TOTAL VALUE IF FIELD IS IN `TotalCols`
                            if(in_array($_f,$this->paging->TotalCols))
                                $columnSum[$cnt] +=  preg_replace("/[^0-9|.]+/", "", $noticia[$_f]);
                            else
                                $columnSum[$cnt] =  "";
                                
                            $cnt++;
                         }
                        echo "</tr>";
                    }
                    ##print_r($columnSum);
                    
                    // TOTAL ROW
                    if(count($this->paging->TotalCols)) {
                    echo '<tr ><td colspan="'.count($this->paging->Fields).'">&nbsp</td></tr>';
                    echo '<tr class="totalRow" >';
                    
                    // IF NEED THE TOTAL FOR FIRST FIELD THEN `Total` KEYWORD WILL NOT BE DISPLAYED
                    if($columnSum[0]>0)
                        echo "<td>number_format($columnSum[0],2)</td>";
                    else
                        echo "<td class='text_align_left' >Total</td>";
                        // DISPLAYING THE EACH COLUMN TOTAL ##print_r($columnSum);
                        
                        for($ti=1; $ti<count($this->paging->Fields); $ti++){
                        ?>
                            <td><?php echo !($columnSum[$ti]==="")?number_format($columnSum[$ti],2):""; ?></td>
                        <?php
                        }
                    echo "</tr>";
                    }
                }
                else {
                 ?>
                    <tr><td colspan="<?php echo count($this->paging->Columns)-1; ?>" class="nodata" >No Report Record(s) Found</td></tr>
                 <?php
                }
            ?>
            </table>    
            
        </div>
        
        
        
        <center>
            <div class="wrapLine"  >
                <?php if($this->paging->TotalRecords) { ?>
                <div id="reportPaging" class="left" style="width:90%;" >
                    
                    <span>
                        <?php if($this->paging->FirstPage!="") { ?>
                            <a href="<?php echo $this->currentpage.'/page/'.$this->paging->FirstPage; ?>"><font face='Verdana' size="2"> << </font></a>
                        <?php } else { ?>
                            <<
                        <?php } ?>
                    </span>
                    <span>|</span>
                    <span>
                        <?php if($this->paging->PreviousPage!="") { ?>
                            <a href="<?php echo $this->currentpage.'/page/'.$this->paging->PreviousPage; ?>"><font face='Verdana' size="2"> < </font></a>
                        <?php } else { ?>
                            <
                        <?php } ?>
                    </span>
                    
                    
                    <?php
                        for($pi=$this->paging->PagingStart; $pi<=$this->paging->PagingEnd; $pi++){
                            
                            echo "<span>|</span> <span>";
                            
                            if($pi==$this->paging->CurrentPage)
                                echo $pi;
                            else
                             echo " <a href='$this->currentpage/page/$pi'><font face='Verdana' size='2'> $pi </font></a>";
                            
                            echo "</span> ";
                        }
                    ?>
                    <span>|</span>
                    <span>
                        <?php if($this->paging->NextPage!="") { ?>
                            <a href="<?php echo $this->currentpage.'/page/'.$this->paging->NextPage; ?>"><font face='Verdana' size="2"> > </font></a>
                        <?php } else { ?>
                            >
                        <?php } ?>
                    </span>
                    <span>|</span>
                    <span>
                        <?php if($this->paging->LastPage!="") { ?>
                            <a href="<?php echo $this->currentpage.'/page/'.$this->paging->LastPage; ?>"><font face='Verdana' size="2"> >> </font></a>
                        <?php } else { ?>
                           >>
                        <?php } ?>
                    </span>
                    
                </div>   
                <?php } ?>
                <div class="left" style="width:8%;padding-top:5px;float:right;">
                        <a onclick="window.print();" href="javascript:void(0);"><img alt="Print"  src="<?php echo $this->baseUrl()?>/public/img/icons/16X16/print_icon.png" width="16" border="0" /></a>
                        <a href="javascript:void(0)"><img alt="Export"  src="<?php echo $this->baseUrl()?>/public/img/icons/16X16/excel_icon.png" width="16" border="0" /></a>
                </div>
            </div>
        <center>
        
    </div>