<?php
/**
* @name       arrangecustomer.phtml
* @since      17 Feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$add_customer_url = $this->url(array("module"=>"account","controller"=>"customerseq","action"=>"addcustomer","week"=>$this->selected_week,"route"=>$this->selected_route), "default", true);
?>
<script type="text/javascript">

function toggleCheckedAll(check_all,class_name) {
	
	var allchc = $("#table-example ."+check_all+':checked').size();
	var chc = $("#table-example ."+check_all).size();
	
	if(allchc==chc)
	{
		$('.'+class_name).attr("checked",true);
	}
}

function toggleChecked(check_all,class_name,status) {
	
	$("#table-example ."+class_name).each( function() {
		
		if(status == true)
			status = false;
		else
			status = true;			
		
		$('.'+check_all).attr("checked",status);
	});
}
function toggleUnChecked(id,class_name,status,val) {

	$('#'+id).attr("checked",false);

	var totalch = $("#table-example input:checkbox."+class_name).size();
	var checkedch = $("#table-example input:checkbox."+class_name+":checked").size();
	
	if(status == true)
		status = false;
	else
		status = true;
	
	if(status)
	{
		if(checkedch>=(totalch-1))
			$('#'+id).attr("checked",true);
		else
			$('#'+id).attr("checked",false);
	}
}
</script>
<style>
th{
	padding: 10px 5px !important;
}
.th_50{
	width:52px !important;
}
.cust_name{
	width:320px !important;
}
#content div.box table th {
	padding :0px !important;
}
.content ._100:first-child {
    margin-top: 5px !important;
}
th{
	padding-bottom: 3px !important;
    padding-left: 5px !important;
    padding-right: 3px !important;
    padding-top: 5px !important;
}
.days
{
   width: 35px !important;
}
.days_check
{
   padding-left:10px !important;
   padding-right:10px !important;
}
th .heading
{
   text-align : center !important;
}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_transaction_arrangecustomer">
<form name="frmoverview" id="frmoverview" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	<h3><?php echo $this->translate->_('Arrange Customer');?></h3>
    </div>
    <div class="_50_3">
	&nbsp;
    </div>
</div>
    <div class="content with-actions" style="">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100">
            <label class="_15 margin_top_10 label_text_align">
                &nbsp;
            </label>
             <label class="_10 margin_top_10 label_text_align">
                <?php echo $this->translate->_('Route')." ".$this->colan;?>
            </label>
            <div class="_25 margin_right_1">
                <select id="ddlroute" name="ddlroute" disabled="disabled" >
		<option value="">--- Select ---</option>
		    <?php
		    for($i=0;$i<count($this->route_info);$i++)
		    {
		?>
			<option value="<?php echo $this->route_info[$i]['id'];?>" <?php echo ($this->route_info[$i]['id'] == $this->selected_route) ? 'selected' : ''; ?> ><?php echo $this->route_info[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
            <label class="_10 margin_top_10 label_text_align">
                <?php echo $this->translate->_('Week')." ".$this->colan;?>
            </label>
            <div class="_25 margin_right_1">
                <select id="ddlweek" name="ddlweek" disabled="disabled" >		
		    <?php
		    for($i=0;$i<count($this->week);$i++)
		    {
		?>
			<option value="<?php echo $this->week[$i]['val'];?>" <?php echo ($this->week[$i]['val'] == $this->selected_week) ? 'selected' : ''; ?> ><?php echo $this->week[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
            <label class="_15 margin_top_10 label_text_align">
                &nbsp;
            </label>
        </div>
        <div class="clear"></div>       
	
	<div class="_100" id="custom_grid">  
	<!-- Content -->
	<div id="content">
	    <div class="box">
	    <div id="paging_grid">
				    
		<div class="grid_12" style="height:350px !important;overflow-y:scroll;">
		    <div class="box">
			<div class="content">
				<table class="table" id="table-example">
					<thead>
					    <tr>
							<th style="padding:10px !important" ><input type="checkbox" name="chkall" id="chkall" class="sel_checkbox" onclick="toggleChecked('sel_checkbox_all','sel_checkbox',this.checked);" /></th>							
							<th class="padding_5" style="padding: 0px 5px ! important;"><?php echo $this->translate->_('Customer Code');?></th>							
							<th class="padding_5" style="padding: 0px 5px ! important;"><?php echo $this->translate->_('Alternate Code');?></th>							
							<th class="padding_5 cust_name" style="padding: 0px 5px ! important;"><?php echo $this->translate->_('Customer Name');?></th>
							<?php
							for($d=0;$d<count($this->day_name);$d++)
							{
								$id_name 	= strtolower($this->day_name[$d].'_all');
								$class_name	= strtolower($this->day_name[$d].'_chk');
								$function 	= 'toggleChecked("'.$class_name.'_all'.'","'.$class_name.'",this.checked)';
								
								
								echo "<th class='days'><div class='heading margin_top_5'>".$this->translate->_($this->day_name[$d])."</div><div class='days_check margin_top_5 back_btn'><input onclick='$function' type='checkbox' name='".$id_name."' id='".$id_name."' class='".$class_name."' value='".$id_name.'[]'."'></div></th>";
							}
							?>
					    </tr>
					</thead>
					<tbody>
						<?php						
							for($i=0;$i<count($this->customer_info);$i++)
							{
								$class 		= ($i%2 == 0) ? 'gradeC' : 'gradeA';
								$cust_code 	= $this->customer_info[$i]['customercode'];							
								
								?>
								<tr class="<?php echo $class;?>">
									<td>
										<input type="checkbox" value="<?php echo $cust_code;?>" class="sel_checkbox_all" name="chk[]" onclick="toggleUnChecked('sel_checkbox_all',this.checked,this.value);" />
									</td>									
									<td><?php echo $cust_code;?></td>									
									<td><?php echo $this->customer_info[$i]['alternatecode']?></td>
									<?php	if($this->css == 'ar_') { ?>										
										<td><?php echo $this->customer_info[$i]['arbcustomername']?></td>
									<?php } else { ?>
										<td><?php echo $this->customer_info[$i]['customername']?></td>
									<?php } ?>
									<td class="days_check"><input <?php if($this->customer_info[$i]['callrestrictiondays1'] == 1) { echo 'checked';}?> type="checkbox" name="<?php echo strtolower($this->day_name[0]."[]"); ?>" value="<?php echo $cust_code;?>" class="<?php echo strtolower($this->day_name[0].'_chk_all');?>" onclick="toggleUnChecked('<?php echo strtolower($this->day_name[0].'_all');?>','<?php echo strtolower($this->day_name[0].'_chk_all');?>',this.checked,this.value);" /></td>
									<td class="days_check"><input <?php if($this->customer_info[$i]['callrestrictiondays2'] == 1) { echo 'checked';}?> type="checkbox" name="<?php echo strtolower($this->day_name[1]."[]"); ?>" value="<?php echo $cust_code;?>" class="<?php echo strtolower($this->day_name[1].'_chk_all');?>"  onclick="toggleUnChecked('<?php echo strtolower($this->day_name[1].'_all');?>','<?php echo strtolower($this->day_name[1].'_chk_all');?>',this.checked,this.value);" /></td>
									<td class="days_check"><input <?php if($this->customer_info[$i]['callrestrictiondays3'] == 1) { echo 'checked';}?> type="checkbox" name="<?php echo strtolower($this->day_name[2]."[]"); ?>" value="<?php echo $cust_code;?>" class="<?php echo strtolower($this->day_name[2].'_chk_all');?>" onclick="toggleUnChecked('<?php echo strtolower($this->day_name[2].'_all');?>','<?php echo strtolower($this->day_name[2].'_chk_all');?>',this.checked,this.value);" /></td>
									<td class="days_check"><input <?php if($this->customer_info[$i]['callrestrictiondays4'] == 1) { echo 'checked';}?> type="checkbox" name="<?php echo strtolower($this->day_name[3]."[]"); ?>" value="<?php echo $cust_code;?>" class="<?php echo strtolower($this->day_name[3].'_chk_all');?>" onclick="toggleUnChecked('<?php echo strtolower($this->day_name[3].'_all');?>','<?php echo strtolower($this->day_name[3].'_chk_all');?>',this.checked,this.value);" /></td>
									<td class="days_check"><input <?php if($this->customer_info[$i]['callrestrictiondays5'] == 1) { echo 'checked';}?> type="checkbox" name="<?php echo strtolower($this->day_name[4]."[]"); ?>" value="<?php echo $cust_code;?>" class="<?php echo strtolower($this->day_name[4].'_chk_all');?>"  onclick="toggleUnChecked('<?php echo strtolower($this->day_name[4].'_all');?>','<?php echo strtolower($this->day_name[4].'_chk_all');?>',this.checked,this.value);" /></td>
									<td class="days_check"><input <?php if($this->customer_info[$i]['callrestrictiondays6'] == 1) { echo 'checked';}?> type="checkbox" name="<?php echo strtolower($this->day_name[5]."[]"); ?>" value="<?php echo $cust_code;?>" class="<?php echo strtolower($this->day_name[5].'_chk_all');?>"  onclick="toggleUnChecked('<?php echo strtolower($this->day_name[5].'_all');?>','<?php echo strtolower($this->day_name[5].'_chk_all');?>',this.checked,this.value);" /></td>
									<td class="days_check"><input <?php if($this->customer_info[$i]['callrestrictiondays7'] == 1) { echo 'checked';}?> type="checkbox" name="<?php echo strtolower($this->day_name[6]."[]"); ?>" value="<?php echo $cust_code;?>" class="<?php echo strtolower($this->day_name[6].'_chk_all');?>"  onclick="toggleUnChecked('<?php echo strtolower($this->day_name[6].'_all');?>','<?php echo strtolower($this->day_name[6].'_chk_all');?>',this.checked,this.value);" /></td>
								</tr>
								<?php
							}
						?>						
					</tbody>
				</table>
			</div>
		    </div> <!-- End of .box -->
		</div>
    
		<div class="clean"></div>
	    
	    </div>
	
	    </div>
	</div>
	</div>	
	
        <div class="clear"></div>
        <div class="_100 margin_top_10 margin_bottom_10">
            <div class="_5">&nbsp;</div>
            <div class="_10">
			<?php if($this->updatepermission==1)
			{ ?>
                <input type="submit" name="save" id="save" value="<?php echo $this->translate->_('SAVE');?>"/>
				<?php
			}
			else
			{
				?>
				 <input type="button" name="nopermission" id="nopermission" value="<?php echo $this->translate->_('SAVE');?>"/>
				<?php
			}
			
				?>
            </div>
			<div class="_5">&nbsp;</div>
            <div class="_10_2" align="center">
               <input type="button" name="addcustomer" id="addcustomer" value="<?php echo $this->translate->_('ADD');?>" onclick="winloc('<?php echo $add_customer_url;?>')"/>
            </div>
			<div class="_5">&nbsp;</div>
            <div class="_10" align="center">
                
					<?php if($this->removepermission==1)
			{ ?>
               <input type="button" name="removecustomer" id="removecustomer" value="<?php echo $this->translate->_('REMOVE');?>"/>
				<?php
			}
			else
			{
				?>
				<input type="button" name="nopermission" id="nopermission" value="<?php echo $this->translate->_('REMOVE');?>"/>
				 
				<?php
			}
			
				?>
            </div>
            <div class="_5">&nbsp;</div>
            <div class="_10" align="center">
                <input type="button" name="print" id="print" value="<?php echo $this->translate->_('PRINT')?>"/>
            </div>
			<div class="_5">&nbsp;</div>
			 <div class="_10" align="center">
                <input type="button" name="export" id="export" value="<?php echo $this->translate->_('EXPORT')?>"/>
            </div>
			<div class="_5">&nbsp;</div>
            <div class="_10">
               <input type="button" name="close" id="close" value="<?php echo $this->translate->_('CLOSE');?>" />
            </div>
            <div class="_15">&nbsp;</div>
        </div>
    </div>
	<input type="hidden" id="hdnremovecustomer" name="hdnremovecustomer" value="">
	<input type="hidden" id="hdnweek" name="hdnweek" value="<?php echo $this->selected_week;?>">
    <input type="hidden" id="hdnroute" name="hdnroute" value="<?php echo $this->selected_route;?>">
    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?'edit':'add'; ?>">
</form>

	<div class="clear"></div>
</div> <!-- End of .box -->
</div>
<script>
    $(window).load(function(){		
        $("#close").click(function() {
            parent.eval('$.prettyPhoto.close()');
        });	
        $("#print").click(function() {
			jConfirm('Are You Sure To Print?', 'Message', function(resp)
	        {
	            if(resp) {
	                $('#hdDelete').val(2);
	                $("form").submit();
	            }
	        })
		});
        $("#export").click(function() {
			jConfirm('Are You Sure To Export?', 'Message', function(resp)
	        {
	            if(resp) {
	                $('#hdDelete').val(3);
	                $("form").submit();
	            }
	        })
        });	
    });
	<?php if(count($this->customer_info) > 0 ) { ?>
	$(document).ready(function()
	{
		toggleCheckedAll("sat_chk_all","sat_chk",this.checked);
		toggleCheckedAll("sun_chk_all","sun_chk",this.checked);
		toggleCheckedAll("mon_chk_all","mon_chk",this.checked);
		toggleCheckedAll("tue_chk_all","tue_chk",this.checked);
		toggleCheckedAll("wed_chk_all","wed_chk",this.checked);
		toggleCheckedAll("thu_chk_all","thu_chk",this.checked);
		toggleCheckedAll("fri_chk_all","fri_chk",this.checked);
		
	})	
	<?php } ?>
	
	$('#nopermission').click(function(){
		alert("You dont have enough permission to this operation.");
	});
	
	$('#removecustomer').click(function(){
		if($('.sel_checkbox_all:checked').size()=='0')
		{
			jAlert('Please Select Customer To Remove.');
			return false;
		}
		else
		{
			jConfirm('Are You Sure To Delete Record(s). ?', 'Message', function(resp)
			{
			    if(resp)
			    {
					$("#hdnremovecustomer").val('1');
					$("form").submit();
			    }
			    else
			    {
					return false;
			    }
			})
		}
	})
</script>
