<?php
/**
* @name       routesequence.phtml
* @since      17 Feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style type="text/css">
#main_content
{
	float:none !important;
}


</style>
<div class="clean"></div>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<div class="grid_12">
<div class="box" id="account_transaction_routesequence">
<form name="frmoverview" id="frmoverview" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	<h3><?php echo $this->translate->_('Route Sequence');?></h3>
    </div>
    <div class="_50_3">
	&nbsp;
    </div>
</div>
    <div class="content with-actions">	
	<div class="_100">
            
             <label class="_10 margin_top_12 label_text_align" style="margin-left: -3%;">
                <?php echo $this->translate->_('Route')." ".$this->colan;?>
            </label>
            <div class="_25 margin_right_1">
                <select id="ddlroute" name="ddlroute" disabled="disabled">
		<option value="">--- Select ---</option>
		    <?php
		    for($i=0;$i<count($this->route_data);$i++)
		    {
		?>
			<option value="<?php echo $this->route_data[$i]['id'];?>" <?php echo ($this->route_data[$i]['id'] == $this->selected_route) ? 'selected' : ''; ?> ><?php echo $this->route_data[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
            <label class="_10 margin_top_12 label_text_align" style="margin-left: -3%;">
                <?php echo $this->translate->_('Day')." ".$this->colan;?>
            </label>
            <div class="_25 margin_right_1">
                <select id="ddlday" name="ddlday" class="required">
		<option value="">--- Select ---</option>
		    <?php for($i=0;$i<count($this->day_name);$i++)
		    {
		?>
			<option value="<?php echo $this->day_name[$i]['id'];?>" <?php echo ($this->day_name[$i]['id'] == $this->selected_dayname) ? 'selected' : ''; ?> ><?php echo $this->day_name[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
            <div class="_10" style=" margin-left:5%; ">
                <input  type="submit" id="loaddata" name="loaddata" value="<?php echo $this->translate->_('LOAD');?>" >
            </div>
			  <div class="_10">
                 <input  type="submit" name="save" id="add" value="<?php echo $this->translate->_('SAVE')?>"/>
            </div> 
			<!--Following check box added by nilesh on 25Feb2016-->
            <div class="_10" style="width:10%; margin-left:1%">				 
				 <?php echo $this->translate->_('Print All Day ')?>  <input type="checkbox" name="printallday">                
            </div>
			<!--End check box added by nilesh on 25Feb2016-->	
			<div class="_10">
                 <input type="button" name="print" id="print" value="<?php echo $this->translate->_('PRINT')?>"/>
            </div>	
		
             
			
           
			
           
        </div>
		
        <div class="space_20">&nbsp;</div>
        <?php if($this->show_button > 0) { ?>
	    <div id="drag_drop">
		<div class="demo">
		    <div class="_100">
			<?php if(!$this->altcode_status) { ?>
			<div class="customer_code margin_left_4"><?php echo $this->translate->_('Code');?></div>
			<?php } elseif($this->altcode_status) { ?>
			<div class="alternate_code"><?php echo $this->translate->_('Alternate Code');?></div>
			<?php } ?>
			<div class="sequence"><?php echo $this->translate->_('Sequence');?></div>
			<div class="_30"><?php echo $this->translate->_('Customer Name');?></div>
			<div class="customer_name_address"><?php echo $this->translate->_('Address');?></div>
		    </div>
		    <div class="clear space_20">&nbsp;</div>
		    <div id="sortable" class="_100">
		    <?php
			$i=0;
			$temp = '';			
			for($m=1; $m<=count($this->customer_info); $m++) {
			    
			    $temp .= ($temp == '') ? $this->customer_info[$i]['customercode'] : ','.$this->customer_info[$i]['customercode'];
			    if($this->altcode_status) {
			    $alt_code 	= ($this->customer_info[$i]['alternatecode'] !='') ? $this->customer_info[$i]['alternatecode'] : '&nbsp;';
				}
			    $dayname	= ($this->customer_info[$i]['dayname'] !='') ? $this->customer_info[$i]['dayname'] : '&nbsp;';
				if($this->css == 'ar_') {
					$cust_name	= ($this->customer_info[$i]['arbcustomername'] != '' ) ? $this->customer_info[$i]['arbcustomername'] : '&nbsp;';
				} else {
					$cust_name	= ($this->customer_info[$i]['customername'] != '' ) ? $this->customer_info[$i]['customername'] : '&nbsp;';
				}
			    
			    $address	= '';			    
			    if(isset($this->customer_info[$i]['customeraddress1'])) {
					$address = $this->customer_info[$i]['customeraddress1'];
			    }
			    if(isset($this->customer_info[$i]['customeraddress2']) && strlen($this->customer_info[$i]['customeraddress2']) > 0) {
					$address .= ','.$this->customer_info[$i]['customeraddress2'];
			    }
			    if(isset($this->customer_info[$i]['customeraddress3']) && strlen($this->customer_info[$i]['customeraddress3']) > 0) {
					$address .= ','.$this->customer_info[$i]['customeraddress3'];
			    }
				if(strlen($address) > 50) {
					$address = substr($address,0,50).'...';
				}
			    ?>
			<div class="item <?php if($i%2==0) { echo "gradeC"; } else { echo "gradeA"; }?>" id="<?php echo $this->customer_info[$i]['customercode']; ?>">
				<?php if(!$this->altcode_status) { ?>
			    <div class="customer_code show_hide" ><?php echo $this->customer_info[$i]['customercode']; ?></div>				
				<?php } elseif($this->altcode_status) { ?>
			    <div class="sort alternate_code"><?php echo $alt_code; ?></div>
				<?php } ?>
			    <div class="sequence sort"><?php echo $dayname; ?></div>
			    <div class="_30"><?php echo $cust_name; ?></div>
			    <div class="customer_name_address"><?php echo $address; ?></div>
			</div>			
			<?php $i++; } ?>
		    </div>	    
		</div>
	    </div>	
	<?php } else { ?>	
		<div class='_100 text_align_center clear_only nodata_message margin_top_50 margin_bottom_10'><b><?php echo $this->translate->_('No Record(s) Found') ?><b></div>
	<?php  } ?>
        <div class="clear space_20"></div>
        <div class="_100 margin_top_10 margin_bottom_10">
             <!--div class="_25">
                &nbsp;
            </div>
            <div class="_15">
                 <input  type="submit" name="save" id="add" value="<?php echo $this->translate->_('SAVE')?>"/>
            </div>
            <div class="_5">
                &nbsp;
            </div>
            <div class="_15">
                 <input type="button" name="cancel" id="cancel" value="<?php echo $this->translate->_('CANCEL')?>"/>
            </div>
            <div class="_5">
                &nbsp;
            </div>
            <div class="_15">
                 <input type="button" name="print" id="print" value="<?php echo $this->translate->_('PRINT')?>"/>
            </div-->
			<!--Following check box added by nilesh on 25Feb2016-->
            <!--div class="_15">				 
				 <?php echo $this->translate->_('Print For All Day ')?>  <input type="checkbox" name="printallday">                
            </div-->
			<!--End check box added by nilesh on 25Feb2016-->
            <div class="_25">
                &nbsp;
            </div>
        </div>
    </div>
    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?'edit':'add'; ?>">    
    <input type="hidden" id="hdnweek" name="hdnweek" value="<?php echo $this->selected_week;?>">
    <input type="hidden" id="hdnroute" name="hdnroute" value="<?php echo $this->selected_route;?>">
    <input type="hidden" id="hdncustomer_code" name="hdncustomer_code" value="<?php echo $temp; ?>">
</form>

	<div class="clear"></div>
</div> <!-- End of .box -->
</div>
<script>
    $(window).load(function() {
		$("#cancel").click(function() {
			parent.eval('$.prettyPhoto.close()');
		});
		
		$('#add').click(function() {
			if($('#hdncustomer_code').val()=='')
			{
				return false;
			}
		})
		
		$('#ddlday_chzn .chzn-drop .chzn-search input[type="text"]').focus();
		$('#ddlday_chzn').addClass('chzn-container-active');
		$("#print").click(function() {
			jConfirm('Are You Sure To Print?', 'Message', function(resp)
	        {
	            if(resp) {
	                $('#hdDelete').val(1);
	                $("form").submit();
	            }
	        })
		});
		
    });
</script>
<script>
    $(function() {		
		$( "#sortable" ).sortable({
			update: function(event, ui)
			{
				saveNow(this);
			},
			stop: function(event, ui) {
				
				$('#sortable div.item:even').removeClass('gradeA').removeClass('gradeC').addClass('gradeC');
				$('#sortable div.item:odd').removeClass('gradeA').removeClass('gradeC').addClass('gradeA');
			}
		});
    });
    
    $(".item .remove").live('click', function() {
	$(this).closest('.item').remove();
	 saveNow("#sortable");
    });
    
    $('.up').click(function(){
	var current = $(this).parent()
	current.prev().before(current);
	saveNow("#sortable");
    });
    
    $('.down').click(function(){
      var current = $(this).parent();
	  current.next().after(current);
	  saveNow("#sortable");
    });
    
   showH();
    
    function saveNow(ele)
    {
		var result = $(ele).sortable('toArray');
		$("#hdncustomer_code").attr('value',result);
		//alert(result);
    }
    var counter = <?php echo $m; ?>;
    function add_sub() {
	var nid = counter++;
	//var contents = '<div class="item" id="'+ nid +'" ><span>*</span>Item '+ nid +' <span class="remove" > | Delete</span><span id="b'+ nid +'" class="up"> | Up  </span><span id="a'+ nid +'" class="down"> | Down </span></div> ';
	var contents = '<div class="item" id="'+ nid +'" ><span class="show_hide" >*</span><span class="sort">Item '+ nid +' </span><span class="remove" > | Delete</span><span class="up"> | Up  </span><span class="down"> | Down </span><div style="border:1px solid green; height:50px;display:none;" id="sub'+ nid +'" ></div></div>'
	$('#sortable').append(contents);
	
	$('#'+nid +' .up').click(function(){
	    var current = $(this).parent()
	    current.prev().before(current);
	    saveNow("#sortable");
	});
	
	$('#'+nid + ' .down').click(function(){
	  var current = $(this).parent();
	      current.next().after(current);
		saveNow("#sortable");
	});
	
	//$('#sortable').sortable("refresh");
	saveNow("#sortable");
	showH();	    
    }
    
    function showH()
    {
	$('.show_hide').click(function(){
	   var pid = $(this).parent().attr('id');
	   $('#sub'+pid).toggle();
	});
    }
</script>