<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({        
   	url:base_url+"/reports/datamonthlyrevenue/datamonthlyrevenuedata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route Code');?>','<?php echo $this->translate->_('Route Name');?>','<?php echo $this->translate->_('January');?>','<?php echo $this->translate->_('February');?>','<?php echo $this->translate->_('March');?>','<?php echo $this->translate->_('April');?>','<?php echo $this->translate->_('May');?>','<?php echo $this->translate->_('June');?>','<?php echo $this->translate->_('July');?>','<?php echo $this->translate->_('August');?>','<?php echo $this->translate->_('September');?>','<?php echo $this->translate->_('October');?>','<?php echo $this->translate->_('November');?>','<?php echo $this->translate->_('December');?>','<?php echo $this->translate->_('Total');?>'],
   	colModel:[
   		{name:'routecode',index:'routecode', width:75, align:"right"},
		{name:'routename',index:'routename', width:200},
        {name:'january',index:'january', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
		{name:'february',index:'february', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
        {name:'march',index:'march', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
		{name:'april',index:'april', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
        {name:'may',index:'may', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
		{name:'june',index:'june', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
        {name:'july',index:'july', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
		{name:'august',index:'august', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
        {name:'september',index:'september', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
		{name:'october',index:'october', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
        {name:'november',index:'november', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
		{name:'december',index:'december', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false},
        {name:'total',index:'total', width:75, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false}
   	],
    <?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
    rowList:eval(RP_ROWLISTSHOW),
    pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
    userDataOnFooter : true,
	altRows : false,
	grouping:false,
    groupingView :
    {
        groupSummary : [true]
    }
});
jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);
jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});
</script>