<?php
/**
* @name       promotionlink.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<script>
  function changeformaction(exportAction)
    {
            var split_path = $("#importcsv").val().split(".").reverse();
            ext_array = new Array('csv', 'xls', 'xlsx');
            
            if($.inArray(split_path[0].toLowerCase(), ext_array) == -1)
            {
                /* Checking file type */
                alert("Invalid file extension");
                return false;
            }
            $('#file_extension').val(split_path[0].toUpperCase());
            var importurl = '<?php echo $this->url(array("module"=>"integration", "controller"=>"import", "action"=>"importcsv"), null, true);?>';
            $('#importexport').attr("action", importurl);
            $('#importexport').submit();
            return true;
    }
</script>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="links_promo_promolink">

<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_links.png">
        <h3><?php echo $this->translate->_('Import From XLS')?></h3>
    </div>
  
</div>
<div class="clear"></div>
<div class="clear"></div>


<div class="content with-actions min_height_50">
    <div class="_100">
        <div class="clear"></div>
    </div>
    <div class="_100">
        <div class="clear"></div>
    </div>
	<?php $this->translate = Zend_Registry::get('Zend_Translate'); ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>

<div class="grid_12">
    <div class="box" id="integration_index">
        
        <div class="clear"></div>
        <?php
        //echo $this->errormessage;
        if($this->errormessage != "")
        {
        ?>
        <div><?php echo $this->errormessage; ?></div>
        <?php
        }
        ?>
        
        <div class="clear"></div>
        
        <form name="" method="post" enctype="multipart/form-data" id="importexport" action="">
            <div class="_30 margin_right_1">
                <select name="tablename" id="tablename">
                    <option value="">------- Select -------</option>
                    <!--<option value="temp_customermaster">Customer Master</option>
                    <option value="temp_itemmaster">Item Master</option>
                    <option value="temp_employee">Salesman</option>
                    <option value="temp_customerinvoice">Customer Invoice</option>--->
                    <option value="temp_routesequence">Journey Plan</option>
					<option value="temp_routegoal">Salesman Target</option>
					<option value="temp_loadrequest">Load Request</option>
					<option value="temp_freecontract">Customer FOC Contract</option>
                </select>
            </div>
            <input type="file" name="importcsv" id="importcsv" class="_20 margin_right_1"/>
            <input type="hidden" name="file_extension" id="file_extension" value="" />
            <input type="submit" name="submit_file" id="submit_file" value="Import" onclick="return changeformaction(0);" class="_20 margin_right_1"/>
        </form>
        
        
        
        
    </div>
</div>
</div>
</div>
</div>