<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Cash Description
*/
    $this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
    $(document).ready(function(){
	
	$("#txtname").focus();
	
	$('#btnsave').click(function() {		
		$('#ddlitem_code').removeClass('required');
		$('#txtprod_code').removeClass('required');
	});
	
	$('#sbtnadd').click(function() {
	   
		$('#ddlitem_code').addClass('required');
		$('#txtprod_code').addClass('required');
		
	   if($("#frmdetsec").valid())
	    {
	        var  url = base_url+'/account/index/addoutletproductcode/';			
	        $.ajax({
				url:url,
				data:$("#frmdetsec").serialize(),
				type:'post',
				beforeSend: function() {
					$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
				},
				success:function(data){
					if(data > 0)
					{
						$("#hdngroupcode").val(data);
						$("#hdnid").val(data);
						loaddata('<?php echo $this->itemgrid; ?>'+'/key/'+data,'item-grid');
					}
					else
					{
						loaddata('<?php echo $this->itemgrid; ?>','item-grid');	
					}
					
					$("#loader").html("");
					$("#txtprod_code").val('');
					$("#ddlitem_code").val("");
					$('select').trigger('liszt:updated');
				}
	        })
	    }
	});
	
	loaddata('<?php echo $this->itemgrid; ?>','item-grid');
	
    })
</script>

<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_index_outletproduct">
<form id="frmdetsec" name="frmdetsec" class="validate" method="post" action="" novalidate="novalidate">
    <div class="header">
	<div class="_50_3 back_btn">
	    <img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	    <h3><?php echo $this->translate->_('Outlet Product Code');?></h3>
	</div>
	<div class="_50_3">
	    <div class="_10 save_btn">
		    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"index","action"=>"outletproduct"),"default", true);?>')">
	    </div>
	    <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
	</div>
    </div>
    <div id="nav_sub" class="ie_nav_sub">
    <div class="container_12">
	<ul id="nav_main">
	    <li class="current">
		<ul style="display: block;">
		    <li>
			<a href="<?php echo $this->url(array("module"=>"account","controller"=>"index","action"=>"outletproduct"),"default", true);?>"><?php echo $this->overview?></a>
		    </li>
		    <li class="last-child">
			<a href="<?php echo $this->url(array("module"=>"account","controller"=>"index","action"=>"addoutletproduct"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		    </li>
		</ul>
	    </li>
	</ul>
    </div>
    </div>
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100">
	     <label class="_20 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Code').''.$this->required;?>
	    </label>
	    <div class="_25 margin_right_1">
		<input name="txtcode" id="txtcode" readonly="readonly" type="text" class="required text_align" value="<?php echo $this->formdata['txtcode']?>"	/>
	    </div>	
	    <label class="_20 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Name').''.$this->required;?>
	    </label>
	    <div class="_25 margin_right_1">
		<input name="txtname" id="txtname"  maxlength="50" type="text" class="text_align required" value="<?php echo $this->formdata['txtname']?>" />
	    </div>
	</div>
	<div class="_100">
	     <label class="_20 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Name ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_25 margin_right_1">
		<input name="txtname_arb" id="txtname_arb"  maxlength="50" class="arb_text_align margin_top_5" type="text" value="<?php echo $this->formdata['txtname_arb']?>" />
	    </div>	
	    <label class="_20 margin_top_12 label_text_align">
	       <?php echo $this->translate->_('Status').''.$this->colan;?>
		</label>
		<div class="_25  margin_right_1">
	       <select id="ddlstatus" name="ddlstatus">
		   <option <?php echo $this->formdata['ddlstatus']== '1' ? 'selected' : ''; ?> value="1"><?php echo $this->translate->_('Active');?></option>
		   <option <?php echo $this->formdata['ddlstatus']== '0' ? 'selected' : ''; ?> value="0"><?php echo $this->translate->_('Inactive');?></option>
	       </select>
	   </div>
       </div>
	<div class="_100 space_20">&nbsp;</div>
    </div>
    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<div class="content with-actions min_height_10">    
	<fieldset>
	    <legend><?php echo $this->translate->_('Outlet Product Code')?></legend>
	    <div class="_100">
		 <label class="_15_1 margin_top_10 label_text_align margin_left_right_1_1">
		    <?php echo $this->translate->_('Item').''.$this->required;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <select id="ddlitem_code" name="ddlitem_code" class="required">
			<option value="">--- Select ---</option>
			<?php
			for($i=0;$i<count($this->item_data);$i++)
			{
			?>
			    <option value="<?php echo $this->item_data[$i]['id'];?>"><?php echo $this->item_data[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>	    
		<label class="_20_2 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Outlet Product Code').''.$this->required;?>
		</label>
		<div class="_25_1">
		    <input name="txtprod_code" id="txtprod_code" class="required" type="text" maxlength="20">
		</div>	    
		<input type="hidden" id="hdngroupcode" name="hdngroupcode" value="" >
		<div class="_15">
		    <input type="button" name="sbtnadd" id="sbtnadd" value="<?php echo $this->translate->_('ADD'); ?>">
		</div>
	    </div>
	</fieldset>    
    <div class="_100">
	<div id="loader"></div>
     <div id="item-grid"> <!--grid load here --> </div>
    </div>
</div>
</form>
</div>
</div> <!-- End of .box -->