<?php
/**
* @name       index.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
	$(document).ready(function(){
		$('#ddlroute').change(function(){
			
			var rid = $('#ddlroute').val();
			if(rid > 0){
				loaddata('<?php echo $this->itemgrid; ?>/rid/'+rid,'item-grid');
			}
			else{
				$("#item-grid").html('');
			}
		})
		
		$('#btnapply').click(function(){
			if($('#frmdetail').valid()) {
				
				
				var rid = $('#ddlroute').val();
				var  url = '<?php echo $this->itemgrid; ?>'+'/apply/true/rid/'+rid ;
				$.ajax({
					url:url,
					data:$("#frmdetail").serialize(),
					type:'post',
					success:function(data) {						
						$("#item-grid").html(data);
						$('#txtamount').val('');
						$('#chkequally').attr('checked',false);
					}					
				})
			}
		})
	})
</script>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>

<div class="clean"></div>
<div class="grid_12">
<div class="box">
<form id="frmdetail" name="frmdetail" class="validate" novalidate action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	<h3><?php echo $this->translate->_('Expiry Management');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"index","action"=>"expirymanagement"),"default", true);?>')"></div>
	<div class="_10 save_btn">&nbsp;</div>
    </div>
</div>
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100 margin_bottom_5">
	    <label class="_20 margin_left_0 margin_top_10 label_text_align">
		<?php echo $this->translate->_('Route').''.$this->required;?>
	    </label>
	    <div class="_36 margin_left_1 margin_right_1">
		<select id="ddlroute" name="ddlroute" class="required">
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->route_info);$i++)
			{
		    ?>
			<option value="<?php echo $this->route_info[$i]['id'];?>"><?php echo $this->route_info[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	    <div class="_15 margin_left_1 margin_right_1">
			<input name="txtamount" id="txtamount" type="text" class="number required">
	    </div>
	    <div class="_10 margin_left_2 margin_top_3">
		<div class="_36">
		    <input type="checkbox" name="chkequally" id="chkequally" value="1">
		</div>
		<div class="_60 margin_top_10">
		    <?php echo $this->translate->_('Equally');?>
		</div>
	    </div>	
	    <div class="_10">
			<input type="button" name="btnapply" id="btnapply" value="<?php echo $this->translate->_('APPLY');?>" >
	    </div>
	</div>
	<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
    </div>
    <div id="loader"></div>    
        <div id="item-grid" class="content"> <!--grid load here --> </div>
	<div class="clear"></div>
</form>
</div> <!-- End of .box -->
</div>