<?php
/**
* @name       customerfreegoodsdetails.phtml
* @since      31-01-2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add customerfreegoodsdetails
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<div class="clean"></div>
<div class="grid_12">
<div class="box">
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<form class="validate" method="post" action="" novalidate="novalidate">
<div class="header ie_header_height">
    <div class="_80 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png">
	<h3><?php echo $this->title;?></h3>
    </div>
    <div class="_20">
	<div class="_50 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel">
	</div>
	<div class="_50 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div class="content with-actions ie_grid min_height_10">
    <div class="_100">
	 <label class="_40 margin_top_17 label_text_align">
	    <?php echo $this->translate->_('Items'); ?>&nbsp;:
	</label>
	<div class="_50 margin_right_1">
	    <select id="ddlitem" name="ddlitem">
		<option value="">--- Select ---</option>
	    </select>
	</div>
    </div>
    <div class="_100">
	 <label class="_40 margin_top_17 label_text_align">
	    <?php echo $this->translate->_('Free Item'); ?>&nbsp;:
	</label>
	<div class="_50">
	    <input name="txtfree_item" id="txtfree_item" type="text" >
	</div>
    </div>
    <div class="_100 margin_bottom_5">
	 <label class="_40 margin_top_17 label_text_align">
	    <?php echo $this->translate->_('Unit Price').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input name="txtunit_price" id="txtunit_price" type="text" >
	</div>
    </div>        
    <div class="_100 margin_bottom_10">
	<label class="_40 margin_top_17 label_text_align">
	   <?php echo $this->translate->_('Item Price').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" name="txitemprice" id="txitemprice" value="">
	</div>
    </div>
</div>
</form>
</div>
</div> <!-- End of .box -->

<script type="text/javascript">
$(window).load(function() {    
    $("#btncancel").click(function() {
	parent.eval('$.prettyPhoto.close()');
    });    
});
</script>