<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({
   	url:base_url+"/reports/itemgroupwisesales/itemgroupwisesalesdata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Transaction Date');?>','<?php echo $this->translate->_('Route');?>','<?php echo $this->translate->_('Item Category');?>','<?php echo $this->translate->_('Item Code');?>','<?php echo $this->translate->_('Description');?>','<?php echo $this->translate->_('UPC');?>','<?php echo $this->translate->_('Sales Qty');?>','<?php echo $this->translate->_('Sales @ Inv. Price');?>','<?php echo $this->translate->_('G. Return Qty');?>','<?php echo $this->translate->_('G.Return @ Inv. Price');?>','<?php echo $this->translate->_('Damaged Return Qty');?>','<?php echo $this->translate->_('Damaged Return @ Inv. Price');?>','<?php echo $this->translate->_('Expired Qty');?>','<?php echo $this->translate->_('Expired @ Inv. Price');?>','<?php echo $this->translate->_('Free Qty');?>','<?php echo $this->translate->_('Free Goods @ Std. Price');?>','<?php echo $this->translate->_('Discounts');?>','<?php echo $this->translate->_('Total Amount');?>'],
   	colModel:[
		{name:'transactiondate',index:'transactiondate', width:120},
        {name:'routecode',index:'routecode', width:120},
      
        {name:'itemgroupcode',index:'itemgroupcode', width:120},
        {name:'itemcode',index:'itemcode', width:90},
        {name:'itemdescription',index:'itemdescription', width:250},
        {name:'unitspercase',index:'unitspercase',summaryType:'sum', width:50, align:"right"},
        {name:'salesqty',index:'salesqty', width:50,summaryType:'sum', align:"right"},
        {name:'sales_invprice',index:'sales_invprice', width:75,summaryType:'sum', formatter: 'number', align:"right",formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
        {name:'returnqty',index:'returnqty', width:60,summaryType:'sum', align:"right"},
        {name:'goodretun_invprice',index:'goodretun_invprice', width:75,summaryType:'sum', formatter: 'number', align:"right",formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
        {name:'damagedqty',index:'damagedqty', width:50,summaryType:'sum', align:"right"},
        {name:'damagereturn_invprice',index:'damagereturn_invprice', width:75,summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"},
		{name:'expiryqty',index:'expiryqty', width:50,summaryType:'sum', align:"right"},
        {name:'expiryreturn_invprice',index:'expiryreturn_invprice', width:75,summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"},
        {name:'freesampleqty',index:'freesampleqty', width:50,summaryType:'sum', align:"right"},
        {name:'freegods_stdprice',index:'freegods_stdprice', width:75,summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"},
        {name:'itempromodiscount',index:'itempromodiscount', width:90,summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"},
        {name:'total',index:'total', width:90,summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }, align:"right"}
   	],
    <?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
    rowList:eval(RP_ROWLISTSHOW),
    pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,        
	groupingView :
        {
            groupField : ['transactiondate','routecode','itemgroupcode'],
            groupColumnShow : [false,false,false],
            groupCollapse : true,
            groupOrder: ['asc','asc','asc'] ,
            groupSummary : [false,false,true]
        }
});
jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
   // document.location.href = exporturl;
    return false;
});
</script>