<!--Source code -->
<!-- Style to put some height on the map -->
<style type="text/css"><style>
#content{background-image:none!important;}
#main_content{width: 100% !important;}
#header,#colors-switcher{display:none;}
aside{display:none;}
footer{display:none;}
#content{background:none!important;}

.nodata_message {
    color: #ff0000;
    font-size: 14px;
    padding: 10px;
    text-align: center;
}
.content {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background: #fff none repeat scroll 0 0;
    border-color: #2b5177 #c8c8c8 #c8c8c8;
    border-image: none;
    border-radius: 0 0 3px 3px;
    border-style: solid;
    border-width: 1px;
    padding: 0;
}


</style>
</style>
<?php
$mapdata = $this->mapdata;
?>
<!-- Load the Google Maps aPI -->
<script src="http://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyA1tLicnmjy5h3qD2IDGOPOocTbVOXIYRo"></script>
<!-- All of the script for multiple requests -->
<script type="text/javascript">

    // Initialise some variables
    var directionsService = new google.maps.DirectionsService();
    var num, map, data;
    var requestArray = [], renderArray = [];
	
    // A JSON Array containing some people/routes and the destinations/stops
    var jsonArray = {
			<?php
	if(count($mapdata) > 0)
	{
		for($i=0;$i<count($mapdata);$i++)
		{
			$comma =",";
			if($i == count($mapdata) )
			{
				$comma="";
			}
			?>
        "<?php echo $mapdata[$i]['routecode'];?>": ["<?php echo $mapdata[$i]['startlatitude'];?>,<?php echo $mapdata[$i]['startlongitude'];?>","<?php echo $mapdata[$i]['midlatitude'];?>,<?php echo $mapdata[$i]['midlongitude'];?>","<?php echo $mapdata[$i]['endlatitude'];?>,<?php echo $mapdata[$i]['endlongitude'];?>"]<?php echo $comma;?>
		<?php  
		}
	}
	?>	
    }
        
    // 16 Standard Colours for navigation polylines
    var colourArray = ['navy', 'grey', 'fuchsia', 'black', 'white', 'lime', 'maroon', 'purple', 'aqua', 'red', 'green', 'silver', 'olive', 'blue', 'yellow', 'teal'];

    // Let's make an array of requests which will become individual polylines on the map.
    function generateRequests(){

        requestArray = [];

        for (var route in jsonArray){
            // This now deals with one of the people / routes

            // Somewhere to store the wayoints
            var waypts = [];
            
            // 'start' and 'finish' will be the routes origin and destination
            var start, finish
            
            // lastpoint is used to ensure that duplicate waypoints are stripped
            var lastpoint

            data = jsonArray[route]

            limit = data.length
            for (var waypoint = 0; waypoint < limit; waypoint++) {
                if (data[waypoint] === lastpoint){
                    // Duplicate of of the last waypoint - don't bother
                    continue;
                }
                
                // Prepare the lastpoint for the next loop
                lastpoint = data[waypoint]

                // Add this to waypoint to the array for making the request
                waypts.push({
                    location: data[waypoint],
                    stopover: true
                });
				
				  var contentString = '<div id="content">'
            '</div>';

        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });
            }

            // Grab the first waypoint for the 'start' location
            start = (waypts.shift()).location;
            // Grab the last waypoint for use as a 'finish' location
            finish = waypts.pop();
            if(finish === undefined){
                // Unless there was no finish location for some reason?
                finish = start;
            } else {
                finish = finish.location;
            }
			
            // Let's create the Google Maps request object
            var request = {
                origin: start,
                destination: finish,
                waypoints: waypts,
                travelMode: google.maps.TravelMode.DRIVING
            };
			
            // and save it in our requestArray
            requestArray.push({"route": route, "request": request});
        }

        processRequests();
    }
	var arrayName = <?php echo json_encode($mapdata); ?>;
    function processRequests(){

        // Counter to track request submission and process one at a time;
        var i = 0;

        // Used to submit the request 'i'
        function submitRequest(){
            directionsService.route(requestArray[i].request, directionResults);
        }

        // Used as callback for the above request for current 'i'
		
        function directionResults(result, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                
                // Create a unique DirectionsRenderer 'i'
				var myHtml = "<table style='width:100%;'><tr><td><b>" + "Route:"+arrayName[i]['routecode'] + "</b></td></tr><tr><td><b>" + "Salesman:"+arrayName[i]['salesmancode'] + "</b></td></tr></table>";
				var infowindow_forRoutedMarker = new google.maps.InfoWindow({				
                content: myHtml				
				});	
				
				
				
                renderArray[i] = new google.maps.DirectionsRenderer();
                renderArray[i].setMap(map);				
                // Some unique options from the colorArray so we can see the routes	
				
               renderArray[i].setOptions({
                    preserveViewport: true,
                    suppressInfoWindows: true,					
					infoWindow: infowindow_forRoutedMarker,					
                    suppressMarkers: false,											
					markerOptions: ({ clickable: true,							
					title:"Route:"+arrayName[i]['routecode'] + " " + "Salesman:"+arrayName[i]['salesmancode']+ " " + "Start Time:"+arrayName[i]['starttime']+ " " + "End Time:"+arrayName[i]['endtime'],						
                    zIndex: 3 }),
					polylineOptions: {
                        strokeWeight: 4,
                        strokeOpacity: 0.8,
                        strokeColor: colourArray[i]
                    }		
				  /*	markerOptions:{
							icon:{
								path: google.maps.SymbolPath.CIRCLE,
								scale: 3,
								strokeColor: colourArray[i]
							}
						}	*/			
				
                });	
				
				
                // Use this new renderer with the result
                renderArray[i].setDirections(result);
                // and start the next request
                nextRequest();

            }

        }
		
        function nextRequest(){
            // Increase the counter
            i++;
            // Make sure we are still waiting for a request
            if(i >= requestArray.length){
                // No more to do
                return;
            }
            // Submit another request
            submitRequest();
			
        }
		

        // This request is just to kick start the whole process
        submitRequest();
    }
    // Called Onload
	var directionsDisplay;
	var directionsService = new google.maps.DirectionsService();

    function init() {

        // Some basic map setup (from the API docs) 
		directionsDisplay = new google.maps.DirectionsRenderer();
        var mapOptions = {
            center: new google.maps.LatLng(<?php echo $mapdata[0]['startlatitude'];?>, <?php echo $mapdata[0]['startlongitude'];?>),
            zoom: 13,
            mapTypeControl: false,
            streetViewControl: false,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
            
        map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

        // Start the request making	
        generateRequests();
    }
	

    // Get the ball rolling and trigger our init() on 'load'
    google.maps.event.addDomListener(window, 'load', init);
</script>

<!-- Somewhere in the DOM for the map to be rendered -->
<?php
if($mapdata!= NULL)
{	
?>
<div id="map-canvas" style="width:100%;height:670px;" ></div>
<?php
}
else{
?>
<div class="content  min_height_10"><div class="clear_only nodata_message margin_top_50 margin_bottom_10"><b>No Record(s) Found.</b></div>					</div>
<?php
}
?>