<?php
/**
* @name       addinvoice.phtml
* @since      03-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
if($this->formdata['voidflag'] == 'VOIDED')
	$invoice_status = '<div style="color:red;"><b>'.$this->formdata['voidflag'].'</b></div>';
else
	$invoice_status = $this->formdata['voidflag'];
	
$total_invo_dis = ($this->formdata['totalpromoamount']-$this->promoamount);
?>
<div class="content with-actions ie_grid min_height_10">
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Document No').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_doc_no" name="txt_doc_no" value="<?php echo $this->formdata['documentnumber']; ?>">
	    </div>
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Invoice No').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_invoice_no" name="txt_invoice_no" value="<?php echo $this->formdata['invoicenumber']; ?>">
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Invoice Date').''.$this->colan;?>
	    </label>
	    <label class="_25_1  margin_top_12 margin_right_1">
		<?php echo date('d-m-Y',strtotime($this->formdata['transactiondate'])); ?>
	    </label>
	    <div class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Invoice Time').''.$this->colan;?>
	    </div>
	    <div class="_25_1  margin_top_12 margin_right_1">
		<?php echo $this->formdata['transactiontime']; ?>
	    </div>	    
	</div>
	<div class="_100 margin_top_10">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Route').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<select id="ddlroute" name="ddlroute" disabled="disabled" >
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->route_info);$i++)
			{
		    ?>
			    <option <?php  echo ($this->formdata['routecode'] == $this->route_info[$i]['id']) ? 'selected' : ''; ?> value="<?php echo $this->route_info[$i]['id'];?>"><?php echo $this->route_info[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Route Start Date').''.$this->colan;?>
	    </label>
	    <div class="_25_1  margin_top_12 margin_right_1">
		<?php echo $this->formdata['routestartdate']; ?>
	    </div>	    
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Salesman').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_salesman" name="txt_salesman" value="<?php echo $this->formdata['salesmanname']; ?>" readonly="readonly" class="margin_top_5">
	    </div>
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Invoice Status').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_12">
			<?php echo $invoice_status; ?>
	    </div>	    
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Customer Code').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_cust_code" name="txt_cust_code" value="<?php echo $this->formdata['customercode']; ?>">
	    </div>	    
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Customer Name').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_doc_status" name="txt_doc_status" value="<?php echo $this->formdata['customername']; ?>">
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Address').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_address" name="txt_address" value="<?php echo $this->formdata['customeraddress1']; ?>">
	    </div>
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Customer Payment Term').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_invo_pay_term" name="txt_invo_pay_term" value="<?php echo $this->formdata['paymentterm']; ?>">
	    </div>
	</div>
	<div class="clear space_20"></div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Total Sales Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_total_sales" name="txt_total_sales" value="<?php echo number_format($this->formdata['totalsalesamount'],$this->decimalplaces); ?>"  class="number amount_text_align">
	    </div>
	    <label class="_25_1 date_color label_text_align margin_top_12">
		<?php echo $this->translate->_('Total Invoice Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_total_invo_amt" name="txt_total_invo_amt" value="<?php echo number_format($this->formdata['totalinvoiceamount'],$this->decimalplaces); ?>"  class="number amount_text_align">
	    </div>
	</div>
	<div class="_100">	    
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Total Returned Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_total_buyback" name="txt_total_buyback" value="<?php echo number_format($this->formdata['totalreturnamount'],$this->decimalplaces); ?>"  class="number amount_text_align">
	    </div>	    
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Total Damaged Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_total_damaged" name="txt_total_damaged" value="<?php echo number_format($this->formdata['totaldamagedamount'],$this->decimalplaces); ?>"  class="number amount_text_align">
	    </div>
	    <label class="_25_1 date_color label_text_align margin_top_12">
		<?php echo $this->translate->_('Amount Paid').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_amount_paid" name="txt_amount_paid" value="<?php echo number_format($this->formdata['amountpaid'],$this->decimalplaces); ?>"  class="number amount_text_align">
	    </div>
	</div>
	<div class="_100">	
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Total Free Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_total_free_goods" name="txt_total_free_goods" value="<?php echo number_format($this->formdata['totalfreesampleamount'],$this->decimalplaces); ?>"  class="number amount_text_align">
	    </div>	    
	</div>
	<div class="_100">	    
	    <!--<label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Total Line Item Tax').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_line_item_tax" name="txt_line_item_tax" value="<?php echo number_format($this->formdata['itemlinetaxamount'],$this->decimalplaces); ?>"  class="number amount_text_align">
	    </div>-->
        <label class="_25_1 label_text_align margin_top_12">
            <?php echo $this->translate->_('Total Line Item Discount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
            <input type="text" id="txt_total_linedis" name="txt_total_linedis" value="<?php echo number_format($this->promoamount,$this->decimalplaces); ?>"  class="number amount_text_align">
	    </div>
	    <label class="_25_1 date_color label_text_align margin_top_12">
            <?php echo $this->translate->_('Invoice Balance').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
            <input type="text" id="txt_invoice_balance" name="txt_invoice_balance" value="<?php echo number_format($this->formdata['invoicebalance'],$this->decimalplaces); ?>" class="number amount_text_align">
	    </div>
	</div>
	
	<div class="_100">	
	    <label class="_25_1 label_text_align margin_top_12">
            <?php echo $this->translate->_('Total Invoice Discount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
            <input type="text" id="txt_total_discount" name="txt_total_discount" value="<?php echo number_format($total_invo_dis,$this->decimalplaces); ?>"  class="number amount_text_align">
	    </div>	    
	</div>
	<div class="_100">	
	    <label class="_25_1 label_text_align margin_top_12">
            <?php echo $this->translate->_('Comments').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_5">
            <textarea id="txtcomment" name="txtcomment"><?php echo $this->formdata['comments']; ?></textarea>
	    </div>
	</div>
	<div class="clear space_20">&nbsp;</div>
</div>