<?php
/**
* @name       addcompanygroup.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Comopany Group
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>

$(document).ready(function() {
    var id ="<?php echo $this->params['id'];?>";
    var routekey = "<?php echo $this->result['routekey']; ?>";
    var routecode = "<?php echo $this->result['routecode']; ?>";
    var loadid = "<?php echo $this->result['loadnumber']; ?>";
    loaddata(base_url+'/hhctransaction/processload/loaditemdetail/routekey/'+routekey+"/routecode/"+routecode+"/loadid/"+loadid,'item-grid');
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="hhctransaction_cloudtran_addprocessload">
<form class="validate" method="post" action="" novalidate="novalidate">      
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
	<h3><?php echo $this->translate->_('Process Load');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"processload","action"=>"processload"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"></div>
    </div>
</div>
 <div class="clear space_20"></div>
    <div class="clear"></div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"processload","action"=>"processload"),"default", true);?>"><?php echo $this->overview?></a>
                </li>		
		<ul style="display: block; margin-left:75px;" class="tabs">
		    <li> 
			<a href="#tab1" id="t1" class="admin_active"><?php echo $this->translate->_('Detail');?></a>
		    </li>
		   
		</ul>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
	<div class="_100">
		<div class="clean"></div>
	</div>
	<div class="_100">
		<label class="_25 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Route').''.$this->required;?>
		</label>
		<div class="_25 margin_right_1  ">
           		<input type="text" id="route_name" name="route_name" value="<?php echo $this->result['route_name']; ?>">                        
        </div>    
		<label class="_20 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Salesman').''.$this->colan;?>
		</label>
		<div class="_25 margin_right_1  ">
            <input type="text" id="salesman_name" name="salesman_name" value="<?php echo $this->result['salesman_name']; ?>">			
		</div>
	</div>
	<div class="_100">
		<label class="_25 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Load Period').''.$this->required;?>
		</label>
		<div class="_25 margin_right_1 ">
            <input type="text" id="loadnumber" name="loadnumber" value="<?php echo $this->result['loadnumber']; ?>">                    
        </div>    
		<label class="_20 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Date').''.$this->colan;?>
		</label>
		<div class="_25 margin_right_1 ">
			 <input type="text" id="transactiondate" name="transactiondate" value="<?php echo date("d-m-Y",strtotime($this->result['transactiondate'])); ?>">
		</div>
	</div>
       <div class="clear space_20"></div>
	<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>">
	  <fieldset class="_95 margin_left_2">
            <legend class="margin_top_5"><?php echo $this->translate->_('Detail');?></legend>
            <div class="margin_top_10">&nbsp;</div>
            <div id="loader"></div>
            <div class="_100" id="item-grid"></div>
         </fieldset>
</div>
</form>
</div>
</div>