<div class="content no-padding with-actions">
	<div class="_100">
		<div class="clean"></div>
	</div>
	<div class="_100">
		<label class="_36 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Route').''.$this->required;?>
		</label>
		<div class="_25 margin_right_1  margin_top_12">
           		<?php echo $this->result['route_name'];?>
	   
        </div>
    </div>
	<div class="_100">
		<label class="_36 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Salesman').''.$this->colan;?>
		</label>
		<div class="_25 margin_right_1  margin_top_12">
			<?php echo $this->result['salesman_name'];?>
		</div>
	</div>
	<div class="_100">
		<label class="_36 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Load Period').''.$this->required;?>
		</label>
		<div class="_25 margin_right_1  margin_top_12">
                    <?php echo $this->result['loadnumber'];?>
        </div>
    </div>
	<div class="_100">
		<label class="_36 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Date').''.$this->colan;?>
		</label>
		<div class="_15 margin_right_1  margin_top_12">
			 <?php echo $this->result['transactiondate'];?>
		</div>
	</div>
       <div class="clear space_20"></div>
	
         
         <fieldset>
            <legend class="margin_top_5"><?php echo $this->translate->_('Detail');?></legend>
                 <div class="margin_top_10">&nbsp;</div>
                <div id="loader"></div>
                <div class="_100" id="item-grid"></div>
        </fieldset>
    <div class="clear space_20">&nbsp;</div>
</div>
