<?php
/**
* @name       index.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of website
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');
?>
<style type="text/css">

.admin_active{
 font-weight:bold;   
}
</style>

<script type="text/javascript">

$(document).ready(function() {
	$(".tab_content").hide();
	$("#tab1").show();
	    $("ul.tabs li").click(function() {
	    $("ul.tabs li a").removeClass("admin_active"); //Remove any "active" class
	    $(this).find("a").addClass("admin_active");
	    $(".tab_content").hide(); //Hide all tab content
	    var activeTab = $(this).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
	    $(activeTab).fadeIn(); //Fade in the active content
	    return false;
	});
		
	
});	
</script>


<div class="clean"></div>
<div class="grid_12" id="admin_cpanel_index">
<div class="box" id="rdbtn">
<form name="frmoverview" id="frmoverview" action="" method="post" class="validate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_administration.png">
	<h3><?php echo $this->title;?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btncancel" id="btncancel"></div>
	<?php if($this->checkaccess("update")) { ?>
        <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    <?php } ?>
    </div>
</div>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;" class="tabs">
		<li> 
		    <a id="general_tab" href="#tab1" class="admin_active"><?php echo $this->translate->_('General');?></a>
		</li>
		<li>
		    <a id="route_tab" href="#tab2"><?php echo $this->translate->_('Route');?></a>
		</li>
		<li>
		    <a id="customer_tab" href="#tab3"><?php echo $this->translate->_('Customer');?></a>
		</li>
		<li class="last-child">
		    <a id="item_tab" href="#tab4"><?php echo $this->translate->_('Items');?></a>
		</li>
		</ul>
	</li>
    </ul>
</div>
</div>
    <div class="content with-actions">
	<div id="tab1" class="tab_content">
	    <?php include('general.phtml');?>
	</div>
	<div id="tab2" class="tab_content">
	    <?php include('route.phtml');?>
	</div>
	<div id="tab3" class="tab_content">
	    <?php include('customer.phtml');?>
	</div>
	<div id="tab4" class="tab_content">
	    <?php include('item.phtml');?>
	</div>
    </div>
</form>
</div> <!-- End of .box -->
</div>

<script type="text/javascript">
    $(window).unload(function(){
	$("#tab2").hide();
	$("#tab3").hide();
	$("#tab4").hide(); 
    });

</script>