<?php
/**
* @name       index.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of website
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');
?>
<div class="clean"></div>

<div class="_100">
	<div class="clean"></div>
</div>
<div class="content with-actions">
	<fieldset>
		<legend><?php echo $this->route;?></legend>
		<div class="_100">
			<div class="_5_2">
				<input type="checkbox" id="chkdisp_comp_region" name="chkcpanel[]" <?php echo $this->cpanel_data["Enable Company and Region"]['status'] == '1' ? 'checked' : '' ;?> value="<?php  echo $this->cpanel_data["Enable Company and Region"]['flagid']; ?>">
			</div>            
			<label class="_55 margin_top_10 text_align">
				<?php echo $this->translate->_('Enable Company And Region');?>
			</label>
			<div class="_5_2">
				<input type="checkbox" id="chkalloradi" name="chkcpanelroute[]" <?php echo $this->cpanel_data['Allowed Radius']['status'] == '1' ? 'checked' : '' ;?> value="<?php echo $this->cpanel_data['Allowed Radius']['flagid'];?>" >
			</div>
			<label class="_40 margin_top_10 text_align">
				<?php echo $this->translate->_('Allowed Radius (For GPS Limits)');?>
			</label>
		</div>
		<div class="_100">
			<div class="_5_2">
				<input type="checkbox" id="chkautho_item_grp" name="chkcpanel[]" <?php echo $this->cpanel_data["Enable Item Must List"]['status'] == '1' ? 'checked' : '' ;?> value="<?php  echo $this->cpanel_data["Enable Item Must List"]['flagid']; ?>">
			</div>
			<label class="_55 margin_top_10 text_align">
				<?php echo $this->translate->_('Enable Item Must List');?>
			</label>
			<div class="_5_2">
				<input type="checkbox" id="chkimportsales" name="chkcpanelroute[]" <?php echo $this->cpanel_data['Import Sync With Salesman Load']['status'] == '1' ? 'checked' : '' ;?> value="<?php echo $this->cpanel_data['Import Sync With Salesman Load']['flagid'];?>" >
			</div>
			<label class="_40 margin_top_10 text_align">
				<?php echo $this->translate->_('Import Sync With Salesman Load');?>
			</label>
		</div>
	</fieldset>
	<fieldset>
	    <legend><?php echo $this->translate->_('Starting Load');?></legend>
		<div class="_100">
			<label class="_40 margin_top_10 text_align">
				<?php echo $this->translate->_('Daily Salesman Load Generation Method').''.$this->colan;?>
			</label>
			<div class="_30 margin_left_right_1_1">
				<select id="ddlsalesmanload" name="ddlsalesmanload" >
					<?php /*<option value="<?php  echo $this->cpanel_data["Import Sync With Salesman Load"]['flagid']; ?>" <?php  echo $this->cpanel_data["Import Sync With Salesman Load"]['status'] == '1' ? 'selected' : '' ;?>><?php echo $this->translate->_('Create New Load');?></option>
					<option value="<?php  echo $this->cpanel_data["Load From ERP"]['flagid']; ?>" <?php  echo $this->cpanel_data["Load From ERP"]['status'] == '1' ? 'selected' : '' ;?>><?php echo $this->translate->_('Load Imported From ERP');?></option>
					<option value="<?php  echo $this->cpanel_data["Convert Load Request to Salesman Load"]['flagid']; ?>" <?php  echo $this->cpanel_data["Convert Load Request to Salesman Load"]['status'] == '1' ? 'selected' : '' ;?>><?php echo $this->translate->_('Convert Load Request to Load');?></option>
					<option value="<?php  echo $this->cpanel_data["Sales Order Load"]['flagid']; ?>" <?php  echo $this->cpanel_data["Sales Order Load"]['status'] == '1' ? 'selected' : '' ;?>><?php echo $this->translate->_('Sales order to load');?></option>
					<option value="<?php  echo $this->cpanel_data["Salesman Load From Previous Day"]['flagid']; ?>" <?php  echo $this->cpanel_data["Salesman Load From Previous Day"]['status'] == '1' ? 'selected' : '' ;?>><?php echo $this->translate->_('Populate Previous day load');?></option>
					<option value="<?php  echo $this->cpanel_data["Suggested Sales"]['flagid']; ?>" <?php  echo $this->cpanel_data["Suggested Sales"]['status'] == '1' ? 'selected' : '' ;?>><?php echo $this->translate->_('Use Suggested Load');?></option> */ ?>					
					<option value="0" <?php  echo $this->cpanel_data["Load From ERP"]['status'] == '0' ? 'selected' : '' ;?>><?php echo $this->translate->_('Create New Load');?></option>
					<option value="1" <?php  echo $this->cpanel_data["Load From ERP"]['status'] == '1' ? 'selected' : '' ;?>><?php echo $this->translate->_('Load Imported From ERP');?></option>
					<option value="2" <?php  echo $this->cpanel_data["Load From ERP"]['status'] == '2' ? 'selected' : '' ;?>><?php echo $this->translate->_('Convert Load Request to Load');?></option>
					<option value="3" <?php  echo $this->cpanel_data["Load From ERP"]['status'] == '3' ? 'selected' : '' ;?>><?php echo $this->translate->_('Sales order to load');?></option>
					<option value="4" <?php  echo $this->cpanel_data["Load From ERP"]['status'] == '4' ? 'selected' : '' ;?>><?php echo $this->translate->_('Populate Previous day load');?></option>
					<option value="5" <?php  echo $this->cpanel_data["Load From ERP"]['status'] == '5' ? 'selected' : '' ;?>><?php echo $this->translate->_('Use Suggested Load');?></option>
				</select>
			</div>			
	    </div>
		<?php  if($this->cpanel_data["Import Sync With Salesman Load"]['status'] == 1) { ?>
			<input type="hidden" id="hdn_starting_load_method" name="hdn_starting_load_method" value="<?php echo $this->cpanel_data["Import Sync With Salesman Load"]['flagid'];?>">
		<?php  } elseif($this->cpanel_data["Load From ERP"]['status'] == 1) { ?>
		<input type="hidden" id="hdn_starting_load_method" name="hdn_starting_load_method" value="<?php echo $this->cpanel_data["Load From ERP"]['flagid'];?>">
		<?php  } elseif($this->cpanel_data["Convert Load Request to Salesman Load"]['status'] == 1) { ?>
		<input type="hidden" id="hdn_starting_load_method" name="hdn_starting_load_method" value="<?php echo $this->cpanel_data["Convert Load Request to Salesman Load"]['flagid'];?>">
		<?php  } elseif($this->cpanel_data["Sales Order Load"]['status'] == 1) { ?>
		<input type="hidden" id="hdn_starting_load_method" name="hdn_starting_load_method" value="<?php echo $this->cpanel_data["Sales Order Load"]['flagid'];?>">
		<?php  } elseif($this->cpanel_data["Salesman Load From Previous Day"]['status'] == 1) { ?>
		<input type="hidden" id="hdn_starting_load_method" name="hdn_starting_load_method" value="<?php echo $this->cpanel_data["Salesman Load From Previous Day"]['flagid'];?>">
		<?php  } elseif($this->cpanel_data["Suggested Sales"]['status'] == 1) { ?>
		<input type="hidden" id="hdn_starting_load_method" name="hdn_starting_load_method" value="<?php echo $this->cpanel_data["Suggested Sales"]['flagid'];?>">
		<?php  }  ?>
	</fieldset>
</div>
