<?php
    $this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({        
   	url:base_url+"/reports/pdc/pdcdata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route');?>','<?php echo $this->translate->_('Salesman');?>','<?php echo $this->translate->_('HOCode');?>','<?php echo $this->translate->_('Transaction Date');?>','<?php echo $this->translate->_('Invoice Number');?>','<?php echo $this->translate->_('Customer Code');?>','<?php echo $this->translate->_('Customer Name');?>','<?php echo $this->translate->_('Credit Days');?>','<?php echo $this->translate->_('PDC Amount');?>','<?php echo $this->translate->_('PDC Date');?>'],
   	colModel:[
        {name:'routecode',index:'routecode', width:120},
        {name:'salesmancode',index:'salesmancode', width:120},
		{name:'hocode',index:'hocode', width:120},
        {name:'transactiondate',index:'transactiondate', width:70},
        {name:'invoicenumber',index:'invoicenumber', width:70},
        {name:'customercode',index:'customercode', width:70},
		{name:'customername',index:'customername', width:250},
        {name:'creditlimitdays',index:'creditlimitdays', width:70},
        {name:'pdcbalance',index:'pdcbalance', width:120, align:"right",summaryType:'sum',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces }},
		{name:'pdcdate',index:'pdcdate', width:120}
	],
    <?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
    pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,
	groupingView :
    {
        groupField : ['routecode','salesmancode','hocode'],
        groupColumnShow : [false,false,false],
        groupCollapse : true,
        groupOrder: ['asc','asc','asc'] ,
        groupSummary : [false,false,true],
        groupDataSorted : true
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,

);


jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
</script>