<?php
/**
* @name       routestartenddays.phtml
* @since      16 feb, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script type="text/javascript">
$(document).ready(function() {
  
    $('#ddlcustomertype').change(function() {
        
        var val = $('#ddlcustomertype').val();
        if(val > 0)
        {
            $('#ddlcustomer').html('');
            var url = base_url+'/reports/pdc/getcustomers/cust_type/'+val;
            
            $.ajax({
                url:url,        
                type:'post',
                success:function(data) {
                    var customer_info = JSON.parse(data);
                    if (customer_info == '') {
                        return false;
                    }
                    if(typeof(customer_info[0]) == 'object') {
                        $('<option/>').val('').html('--- Select ---').appendTo('#ddlcustomer');
                        for (i=0;i<customer_info[0].length;i++) {
                            $('<option/>').val(customer_info[0][i]['id']).html(customer_info[0][i]['val']).appendTo('#ddlcustomer');
                        }
                        $('#ddlcustomer').trigger('liszt:updated');
                    }
                    
                }
            })
        }
        else
        {
            $('#ddlcustomer').html('');
            $('<option/>').val('').html('--- Select ---').appendTo('#ddlcustomer');
            $('#ddlcustomer').trigger('liszt:updated');
        }
    })    
});
</script>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10" id="for_report_only">
<div class="box" id="report_basic_commstatus">
<form id="thisform" name="thisform" onsubmit="return addhidden();"  class="validate" target="_blank" action="<?php echo $this->url(array("module"=>"reports","controller"=>"pdc","action"=>"index"), "default", true);?>" method="post" >
    <div class="header">
        <div class="_50_3 back_btn">
        <img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_reports.png">
            <h3><?php echo $this->translate->_('PDC');?></h3>
        </div>
    </div>
    <div class="content with-actions min_height_10">
        <!--TOP RADIOS-->
        <div class="_100">
            <label class="_40_1 label_text_align margin_top_12">
            <?php echo $this->translate->_('Customer Type').''.$this->colan;?>
            </label>
            <div class="_30 margin_right_1">
            <select id="ddlcustomertype" name="ddlcustomertype" class="required">
                <option value="">--- Select ---</option>
                <option  value="1">Normal</option>
                <option  value="2">Branch</option>
                <option  value="3">Head Office</option>
            </select>
            </div>
        </div>
    
        <div class="_100">
            <label class="_40_1 label_text_align margin_top_12">
            <?php echo $this->translate->_('Customer').''.$this->colan;?>
            </label>
            <div class="_30 margin_right_1">
                <select id="ddlcustomer" name="ddlcustomer" >
                    <option value="">--- Select ---</option>
                </select>
            </div>
        </div>
    
       
        <div class="clear space_20"></div>
        <div class="_100" id="ok_button">
        <div class="_45">&nbsp</div>
        <div class="_10_1">
            <input type="submit" id="sub_ok" name="sub_ok" value="<?php echo $this->translate->_('OK');?>" />
        </div>
        
        </div>
             <div class="clear space_20"></div>
    </div>
</form>
</div> <!-- End of .box -->
</div>