<?php
/**
* @name       unloadvar.phtml
* @since      30-01-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');

?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png" class="margin_top_10">
		<h3><?php echo $this->translate->_('Unload Variance')?></h3>
	    </div>
	    <div class="_50_3">
		<!--<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnexport" id="btnexport"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint"></div>-->		
	    </div>
        </div>
	<div class="_100">
	    <div class="_10">&nbsp;</div>
	    <div class="_10 label_text_align margin_top_12"><label class="advance_search_css"><?php echo $this->translate->_('Route').''.$this->colan;?></label></div>
	    <div class="_30_1  margin_right_1">
			<select id="ddlroute" name="ddlroute" >
				<option value="0">--- ALL ---</option>				
				<?php for($i=0;$i<count($this->route_info);$i++) {?>
				<option value="<?php echo $this->route_info[$i]['id'];?>" <?php if($this->route == $this->route_info[$i]['id']) { echo "selected"; } ?> ><?php echo $this->route_info[$i]['val'];?></option>
				<?php } ?>
			</select>
	    </div>
	    <div class="_20 label_text_align margin_top_12"><label class="advance_search_css"><?php echo $this->translate->_('Select Date').''.$this->colan;?></label></div>
	    <div class="_20 label_text_align margin_right_1"><input type="text" id="txtdate" name="txtdate" value="<?php echo $this->date; ?>"></div>
	    <div class="_10 margin_top_5 ie7marginright"><input type="submit" name="btnload" id="btnload" value="<?php echo $this->translate->_('OK'); ?>" class="margin_zero"></div>
              
	</div>
	
	<div class="clear"></div>
		<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>