<?php
/**
* @name       addsurvaykey.phtml
* @since      30-01-12
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  Elan Technologies
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
    $(document).ready(function(){
	$("#txt_surveydesc").focus();
	var key_id = '<?php echo $this->params["id"]; ?>';
	loaddata('<?php echo $this->itemgrid; ?>/key/'+key_id,'item-grid');
	loaddata('<?php echo $this->itemgrid2; ?>/key/'+key_id,'item-grid-2');
	$("#sbtnadd").click(function(){
	    if($('#frmselection').valid())
	    {
		var values = $('#frmselection').serialize();
		$.ajax({
		    type : "POST",
		    url : base_url+"/merchandize/index/addselectedsurveyplan/key/"+key_id,
		    data :values+'&add=yes',
		    success:function(returndata){
		       
			$('#item-grid').html(returndata);
		    }
		});
	    }
	});
    });
</script>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
    <div class="box" id="merchandize_index_addsurveykey">
	<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post" >
	      
	    <div class="header">
		<div class="_50_3 back_btn">
		    <img src="<?php echo $this->baseUrl()?>/public/images/icon_merchandizing.png" class="margin_top_7">
		    <h3><?php echo $this->translate->_('Survey Key')?></h3>
		</div>
		<div class="_50_3">
		    <div class="_10 save_btn">
			    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"surveykey"),"default", true);?>')">
		    </div>
		    <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
		</div>
	    </div>
	    <div id="nav_sub" class="ie_nav_sub">
	    <div class="container_12">
		<ul id="nav_main">
		    <li class="current">
			<ul style="display: block;">
			    <li>
				<a href="<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"surveykey"),"default", true);?>"><?php echo $this->overview?></a>
			    </li>
			    <li class="last-child">
				<a href="<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"addsurveykey"),"default", true);?>"><b><?php echo $this->details;?></b></a>
			    </li>
			</ul>
		    </li>
		</ul>
	    </div>
	    </div>

    <div class="content with-actions ie_grid min_height_10">		
	<div class="_100 ">
	    <label class="_20_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Code').''.$this->colan;?>
	    </label>
	    <div class="_20_1">
		<input type="text" id="txt_code" name="txt_code" value="<?php echo $this->formdata['surveykey']; ?>" readonly="readonly" >
	    </div>
	    <label class="_20_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Survey Key').''.$this->required;?>
	    </label>
	    <div class="_20_1">	
		<input type="text" id="txt_surveydesc" maxlength="50" name="txt_surveydesc" class="required" value="<?php echo $this->formdata['surveydescription'];?>" >
	    </div>
	</div>
	<div class="_100">
	    <label class="_20_1 margin_top_12 label_text_align"><?php echo $this->translate->_('Status').''.$this->colan;?></label>
	    <div class="_20_1">
		<select id="ddl_status" name="ddl_status">		
		    <option value="1" <?php echo ($this->formdata['activestatus']=='1')?'selected':''; ?> ><?php echo $this->translate->_('Active');?></option>
		    <option value="0" <?php echo ($this->formdata['activestatus']=='0')?'selected':''; ?> ><?php echo $this->translate->_('Inactive');?></option>
		</select>
	    </div>
	    <label class="_20_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Survey Key ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_20_1">	
		<input type="text" id="txt_arbsurveydesc" maxlength="50" name="txt_arbsurveydesc" value="<?php echo $this->formdata['arbsurveydescription'];?>" class="arb_text_align margin_top_5" >
	    </div>	
	</div>
	    </div>
	<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
	<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>" />
	</form>
	
	
	<div class="content with-actions">
    <?php if($this->params["id"] > 0) { ?>
   <form id="frmselection" name="frmselection" class="validate" novalidate action="" method="post">
	<div class="_100 margin_top_25">
	    <fieldset id="ab" name="ab" class="fieldset_effect">		
		<legend class="ttl"><?php echo $this->translate->_('Survey Plan Selection');?></legend>
		<hr id="ie_hr" >
		<div class="_5 clear_only">&nbsp;</div>
		<div class="_100">
		    <div id="loader"></div>
		    <div id="item-grid-2"> <!--grid load here --> </div>
		</div>
		<?php if($this->conter > 0) { ?>
		<div class="_100" style="text-align:center;" >
		    <div class="_40">&nbsp;</div>
		    <div class="_15">
			<input type="button" value="<?php echo $this->translate->_('ADD');?>" id="sbtnadd" name="sbtnadd" class="margin_top_5">
		    </div>
		    <div class="_40">&nbsp;</div>
		</div>
		<?php } ?>
	    </fieldset>
	</div>
   </form>
	<div class="_100 margin_top_25">
	    <form id="frmdetsec" name="frmdetsec" class="validate" novalidate action="" method="post">
	    <fieldset id="ab" name="ab" class="fieldset_effect">		
		<legend class="ttl"><?php echo $this->translate->_('Selected Survey Plan');?></legend>
		<hr id="ie_hr" >
		<div class="_5 clear_only">&nbsp;</div>
		<div class="_100">
		    <div id="loader"></div>
		    <div id="item-grid"> <!--grid load here --> </div>
		</div>		
	    </fieldset>
	    </form>
	</div>    
    <?php } ?>
</div>
	
    </div> <!-- End of .box -->
</div>