<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Cash Description
*/
$this->translate = Zend_Registry::get('Zend_Translate');
$date = $this->date != '' ? $this->date : date('d-m-Y');
?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<script type="text/javascript">

$(document).ready(function(){
	
	$('#ddlroute_chzn .chzn-drop .chzn-search input[type="text"]').focus();
	$('#ddlroute_chzn').addClass('chzn-container-active');
	
	$('#btnsave').click(function() 	{
		if($("#frmdetsec").valid()) {
			if(parseInt($('#txtamount').val()) == 0) {				
				jAlert('Amount Must Be Less Than OR Greate Than The Zero.');
				$('#txtamount').focus();
				$('#txtamount').val('');
				return false;
			}
		}
	})

	$('#ddlroute').change(function(){
		$.blockUI();
		getsalesman($('#ddlroute').val(),'');
		$.unblockUI();
	})
	
	<?php if($this->params["id"] > 0) { ?>
		getsalesman('<?php echo $this->formdata['routecode'];?>','<?php echo $this->formdata['customercode'];?>');
		$('input[type=text]').attr('readonly',true);
		$('select').attr('disabled',true);
		$('#ddlroute').trigger('liszt:updated');
	<?php } ?>	
})

function getsalesman(routeid,customerid)
{
	$('#txtsalesman').val('');
	$('#hdnsalesman').val('');
	$('#ddlcustomer').html('');
	
	var  url = base_url+'/home/index/getopeningsalesmanfromroutecode/routeid/'+routeid;
	$.ajax({
		url:url,
		data:$("#frmdetsec").serialize(),
		type:'post',		
		success:function(data) {
			var salesman_info = JSON.parse(data);
			if (salesman_info == '')
			{
				return false;
			}
			$('#txtsalesman').val(salesman_info[0][0]['salesmanname1']);
			$('#hdnsalesman').val(salesman_info[0][0]['salesmancode']);
			
			if(customerid == '')
			{
				$('#hdnmaxid').val(salesman_info[2][0]['lastid']);			
				var doc_invo = routeid+''+$('#hdnmaxid').val();
				$('#txtdoc_no').val(doc_invo);
				$('#txtinvo_no').val(doc_invo);
			}
			
			if(typeof(salesman_info[1]) == 'object')
			{
				$('<option/>').val('').html('--- Select ---').appendTo('#ddlcustomer');
				for (i=0;i<salesman_info[1].length;i++) {
					if(customerid > 0 && customerid == salesman_info[1][i]['id']) {
						$('<option selected />').val(salesman_info[1][i]['id']).html(salesman_info[1][i]['val']).appendTo('#ddlcustomer');
					}
					else {
						$('<option/>').val(salesman_info[1][i]['id']).html(salesman_info[1][i]['val']).appendTo('#ddlcustomer');
					}
				}
			}
			$('#ddlcustomer').trigger('liszt:updated');
		}
	})
}
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_transaction_openingbal">
<form class="validate" method="post" action="" novalidate="novalidate" name="frmdetsec" id="frmdetsec">
    <div class="header">
	<div class="_50_3 back_btn">
	    <img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	    <h3><?php echo $this->translate->_('Opening Balance');?></h3>
	</div>
	<div class="_50_3">
	    <div class="_10 save_btn">
		    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"transaction","action"=>"openingbal"),"default", true);?>')">
	    </div>
	    <div class="_10 save_btn">
		<?php if($this->params["id"] > 0) { ?>
			<input class="border_none" type="button" value="" alt="<?php echo $this->baseUrl()."/account/transaction/openingbal/delid/".$this->params["id"]?>" name="btndeletetran" id="btndeletetran" >
		<?php } else { ?>
			<input class="border_none" type="submit" value="" name="btnsave" id="btnsave">
		<?php } ?>
		</div>
	</div>
    </div>
    <div class="_100" style="text-align:center">

		<div class="_20 label_text_align margin_top_7">&nbsp;</div>
		<div class="_20 label_text_align margin_top_5"><label class="advance_search_css"><?php echo $this->translate->_('Selected Date').''.$this->colan;?></label></div>
		<div class="_20 label_text_align"><input type="text" id="txtdate" readonly="readonly" name="txtdate" value="<?php echo $date;?>" class="margin_zero"></div>
		<div class="_10 margin_top_3">&nbsp;</div>
		<div class="_30">
		    &nbsp;
		</div>
	</div>
    <div class="clear space_20"></div>
    <div class="clear"></div>
    <div id="nav_sub" class="ie_nav_sub">
    <div class="container_12">
	<ul id="nav_main">
	    <li class="current">
		<ul style="display: block;">
		    <li>
			<a href="<?php echo $this->url(array("module"=>"account","controller"=>"transaction","action"=>"openingbal"),"default", true);?>"><?php echo $this->overview?></a>
		    </li>
		    <li class="last-child">
			<a href="<?php echo $this->url(array("module"=>"basic","controller"=>"transaction","action"=>"addopeningbal"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		    </li>
		</ul>
	    </li>
	</ul>
    </div>
    </div>
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100 ">
		<label class="_20_2 margin_top_12 label_text_align"><?php echo $this->translate->_('Doc Date').''.$this->colan;?></label>
		<div class="_25_1 margin_top_10"><?php echo $date;?></div>
	</div>
	<div class="_100">
	    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Document No').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
			<input name="txtdoc_no" id="txtdoc_no" type="text" readonly="readonly" value="<?php echo $this->formdata['documentnumber'];?>" />
	    </div>
		<label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Invoice Number').''.$this->colan;?>
	    </label>
	    <div class="_25_1 ">
			<input name="txtinvo_no" id="txtinvo_no" type="text" readonly="readonly" value="<?php echo $this->formdata['invoicenumber'];?>">
	    </div>
	</div>
	<div class="_100">
	    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Route').''.$this->required;?>
	    </label>
	    <div class="_25_1">
			<select id="ddlroute" name="ddlroute" class="required">
				<option value="">--- Select ---</option>
				<?php
					for($i=0;$i<count($this->route);$i++)
					{
				?>
					<option value="<?php echo $this->route[$i]['id'];?>" <?php if($this->formdata['routecode'] == $this->route[$i]['id']) { echo 'selected';}?> ><?php echo $this->route[$i]['val'];?></option>
				<?php } ?>
			</select>
	    </div>	
		<div id="loader"></div>	
	    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Salesman').''.$this->colan;?>
	    </label>
	   <div class="_25_1 ">
			<input class="margin_top_5" name="txtsalesman" id="txtsalesman" type="text" value="" readonly="readonly" >
	    </div>
	</div>
	<div class="_100">
	    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Customer').''.$this->required;?>
	    </label>
	    <div class="_25_1">
			<select id="ddlcustomer" name="ddlcustomer" class="required">
				<option value="">--- Select ---</option>
				<?php
					for($i=0;$i<count($this->customer);$i++)
					{
				?>
					<option value="<?php echo $this->customer[$i]['id'];?>" <?php if($this->formdata['customercode'] == $this->customer[$i]['id']) { echo 'selected';}?> ><?php echo $this->customer[$i]['val'];?></option>
				<?php } ?>
			</select>
	    </div>	
	    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Amount').''.$this->required;?>
	    </label>
	    <div class="_25_1 ">
			<input name="txtamount" id="txtamount" class="number margin_top_3 required"  type="text" value="<?php echo number_format($this->formdata['totalinvoiceamount'],$this->decimalplaces);?>">
	    </div>
	</div>
	<div class="_100">
	    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Remark 1').''.$this->colan;?>
	    </label>
	     <div class="_25_1">
			<input name="txtremark1" id="txtremark1" class="margin_top_5" type="text" value="<?php echo $this->formdata['remarks1'];?>" >
	    </div>	
	    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Remark 2').''.$this->colan;?>
	    </label>
	    <div class="_25_1 ">
			<input name="txtremark2" id="txtremark2" class="margin_top_3" type="text" value="<?php echo $this->formdata['remarks2'];?>" >
	    </div>
	</div>
	<div class="_100">
	    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('ERP Reference No.').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
			<input name="txterpno" id="txterpno" class="margin_top_5" maxlength="30" type="text" value="<?php echo $this->formdata['erpreferencenumber'];?>">
	    </div>
	</div>
	<div class="space_200 clear">&nbsp;</div>
    </div>
	<input type="hidden" id="hdnsalesman" name="hdnsalesman" value="">
    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
	<input type="hidden" id="hdnmaxid" name="hdnmaxid" value="<?php echo $this->formdata['hdnmaxid'];?>">
</form>
</div>
</div> <!-- End of .box -->