
<?php
/**
* @name       monthclose.phtml
* @since      17 feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<div class="grid_12">
    <div class="box" id="account_transaction_monthclose">
        <div class="header">
            <div class="_50_3 back_btn">
				<img src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png" class="margin_top_7">
				<h3><?php echo $this->translate->_('Month Close');?></h3>
			</div>
			<div class="_50_3">
				<div class="_10 save_btn">
					<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"transaction","action"=>"monthcloseinfo"), "default", true);?>')" >
				</div>
			</div>				
        </div>
		<div id="nav_sub" class="ie_nav_sub">
		<div class="container_12">
			<ul id="nav_main">
			<li class="current">
				<ul style="display: block;">
				<li>
					<a href="<?php echo $this->url(array("module"=>"account","controller"=>"transaction","action"=>"monthcloseinfo"),"default", true);?>"><?php echo $this->overview?></a>
				</li>
				<li class="last-child">
					<a href="<?php echo $this->url(array("module"=>"account","controller"=>"transaction","action"=>"monthclose"),"default", true);?>"><b><?php echo $this->details;?></b></a>
				</li>
				</ul>
			</li>
			</ul>
		</div>
		</div>
	<div class="clear"></div>
	<div class="clear"></div>
        <form id="frmsearch" name="frmsearch" class="validate" novalidate action="" method="post">
            <div class="content with-actions min_height_10">                
				<div class="_100" style="text-align:center">
					<div class="_10 label_text_align margin_top_7">&nbsp;</div>
					<div class="_10 label_text_align margin_top_12"><?php echo $this->translate->_('Year').''.$this->required;?></div>
					<div class="_20 text_align">
						<select id="ddlyear" name="ddlyear" class="required">
							<option value="">--- Select ---</option>
							<?php
							for($i=0;$i<count($this->years);$i++)
							{
							?>
								<option value="<?php echo $this->years[$i]['id'];?>" <?php echo ($this->years[$i]['id'] == $this->year) ? 'selected' : ''; ?> ><?php echo $this->years[$i]['val'];?></option>
							<?php } ?>
						</select>
					</div>
					<div class="_10 label_text_align margin_top_12"><?php echo $this->translate->_('Month').''.$this->required;?></div>
					<div class="_20 text_align">
						<select id="ddlmonth" name="ddlmonth" class="required">
							<option value="">--- Select ---</option>
							<?php
							for($i=0;$i<count($this->months);$i++)
							{
							?>
								<option value="<?php echo $this->months[$i]['id'];?>" <?php echo ($this->months[$i]['id'] == $this->month) ? 'selected' : ''; ?> ><?php echo $this->months[$i]['val'];?></option>
							<?php } ?>
						</select>
					</div>			
					<div class="_10 label_text_align margin_top_7"><input type="submit" name="btnload" id="btnload" value="<?php echo $this->translate->_('OK'); ?>" class="margin_zero"></div>					
				</div>
				<div class="clear space_200">&nbsp;</div>
            </div>
        </form>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->