<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<form name="frmoverview" id="frmoverview" action="" method="post">
    <input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box" id="account_transaction_monthcloseoverview">
        <div class="header">
            <div class="_50_3 back_btn">
				<img src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png" class="margin_top_7">
				<h3><?php echo $this->translate->_('Month Close');?></h3>
			</div>
			<div class="_50_3">
				<!--<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnexport" id="btnexport"></div>
				<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint"></div>-->
			</div>
		</div>
		<div class="clear"></div>
		<div id="nav_sub" class="ie_nav_sub">
		<div class="container_12">
			<ul id="nav_main">
				<li class="current">
					<ul style="display: block;">
						<li>
							<a href="<?php echo $this->url(array("module"=>"account","controller"=>"transaction","action"=>"monthcloseinfo"),"default", true);?>"><?php echo $this->overview?></a>
						</li>						
						<li> 
							<a href="Javascript:void(0);" class="admin_active"><?php echo $this->translate->_('Detail');?></a>
						</li>
					</ul>
				</li>
			</ul>
		</div>
		</div>
	<div class="clear space_20"></div>
	<div class="clear"></div>
	<div class="_100">
		<?php echo $this->partial('datagrid.phtml', $this); ?>
	</div>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>
