<?php
$this->translate = Zend_Registry::get('Zend_Translate');
$mapdata = $this->mapdata;
?>

<script src="http://maps.googleapis.com/maps/api/js"></script>
<script>
var myCenter = new google.maps.LatLng(<?php echo ($mapdata[0]['fixedlatitude'] && $mapdata[0]['fixedlongitude']) ? $mapdata[0]['fixedlatitude'].",".$mapdata[0]['fixedlongitude'] : '51.508742,-0.120850'; ?>);

function initialize() {
	var mapProp = {
		center: myCenter,
		zoom: 12,
		mapTypeId: google.maps.MapTypeId.ROADMAP
	};
	
	var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
	
	var infowindow = new google.maps.InfoWindow();
	
	<?php
	$tmproutekey = '';
	$color = array('#FF0000','#FF00FF','#0000FF','#00FF00','#FFFF00');
	$j=-1;
	$k=0;
	if(count($mapdata) > 0)
	{
		for($i=0;$i<count($mapdata);$i++)
		{
			?>
			var markerPosition<?php echo $i;?> = new google.maps.LatLng(<?php echo $mapdata[$i]['fixedlatitude'];?>,<?php echo $mapdata[$i]['fixedlongitude'];?>);
			
			var marker<?php echo $i;?> = new google.maps.Marker({
				position:markerPosition<?php echo $i;?>,
			});
			marker<?php echo $i;?>.setMap(map);
			
			google.maps.event.addListener(marker<?php echo $i;?>, 'click', function() {
				infowindow.setContent("<div style='line-height:1.35;overflow:hidden;white-space:nowrap;'>Customername: <?php echo $mapdata[$i]['customername'];?><br>Time In: <?php echo $mapdata[$i]['visitstarttime'];?><br>Time Out: <?php echo $mapdata[$i]['visitendtime'];?><br>Sequence: <?php echo $mapdata[$i]['visitkey'];?></div>");
				infowindow.open(map, marker<?php echo $i;?>);
				//map.setZoom(9);
				//map.setCenter(marker.getPosition());
			});
			<?php
			if($tmproutekey == '' || $tmproutekey != $mapdata[$i]['routekey'])
			{
				$tmproutekey = $mapdata[$i]['routekey'];
				$j++;
				$markerposition[$j] = "markerPosition".$i;
			}
			else
			{
				$markerposition[$j] = $markerposition[$j].",markerPosition".$i;
			}
			
			
			//if($i == 0)
			//{
			//	$markerposition = "markerPosition".$i;
			//}
			//else
			//{
			//	$markerposition = $markerposition.",markerPosition".$i;
			//}
			
			//echo "alert('".$markerposition[$j]."');";
		}
		for($z=0; $z<count($markerposition); $z++)
		{
			?>
			var myTrip = [<?php echo $markerposition[$z];?>];
			var flightPath = new google.maps.Polyline({
				path:myTrip,
				strokeColor:"<?php echo $color[$z];?>",
				strokeOpacity:0.8,
				strokeWeight:2
			});
			flightPath.setMap(map);
			<?php
		}
	}
	?>
	
	//var myTrip = [<?php echo $markerposition;?>];
	//var flightPath = new google.maps.Polyline({
	//	path:myTrip,
	//	strokeColor:"#FF00FF",
	//	strokeOpacity:0.8,
	//	strokeWeight:2
	//});
	//flightPath.setMap(map);
	
	$("ul.tabs li").click(function() {
		var center = map.getCenter();
		google.maps.event.trigger(map, 'resize');
		map.setCenter(center);
	});
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div class="content with-actions ie_grid min_height_10">
	<div id="googleMap" style="width:100%;height:470px;"></div>
</div>