export const reportModules = [
  {
    key: "reports",
    title: "Reports",
    titleKey: "reports",
    icon: "fa fa-chart-column",
    permission: "reports",
    groups: [
      {
        key: "daily-reports",
        title: "Daily Report",
        titleKey: "daily_report",
        icon: "fa fa-calendar-day",
        legacyModule: "reports",
        legacyController: "routesummary",
        legacyAction: "routesummary",
        items: [
          {
            key: "route-summary",
            title: "Route Summary",
            titleKey: "route_summary",
            description: "View route-wise sales, collections, expenses, and settlement totals for the selected day.",
            descriptionKey: "route_summary_report_note",
            icon: "fa fa-route",
            href: "/reports/daily-report/route-summary",
            permission: "route summary",
            legacyModule: "reports",
            legacyController: "routesummary",
            legacyAction: "routesummary",
          },
          {
            key: "route-activity",
            title: "Route Activity",
            titleKey: "route_activity",
            description: "Monitor route visits, transactions, orders, receipts, and non-service activity for each day.",
            descriptionKey: "route_activity_report_note",
            icon: "fa fa-list-check",
            href: "/reports/daily-report/route-activity",
            permission: "route activity",
            legacyModule: "reports",
            legacyController: "routeactivity",
            legacyAction: "routeactivity",
          },
          {
            key: "route-inventory",
            title: "Route Inventory",
            titleKey: "route_inventory",
            description: "Track opening stock, stock movements, sales, returns, and closing inventory for each route.",
            descriptionKey: "route_inventory_report_note",
            icon: "fa fa-boxes-stacked",
            href: "/reports/daily-report/route-inventory",
            permission: "route inventory",
            legacyModule: "reports",
            legacyController: "routeinventory",
            legacyAction: "routeinventory",
          },
          {
            key: "route-trip-analysis",
            title: "Route Trip Analysis",
            titleKey: "route_trip_analysis",
            description: "Review scheduled visits, customer trip activity, and transaction outcomes for each route day.",
            descriptionKey: "route_trip_analysis_report_note",
            icon: "fa fa-map-signs",
            href: "/reports/daily-report/route-trip-analysis",
            permission: "route trip analysis",
            legacyModule: "reports",
            legacyController: "routetripanalysis",
            legacyAction: "routetripanalysis",
          },
          {
            key: "route-deposit-summary",
            title: "Route Deposit Summary",
            titleKey: "route_deposit_summary",
            description: "Review cash and cheque deposits from route invoices, collections, and advance payments.",
            descriptionKey: "route_deposit_summary_report_note",
            icon: "fa fa-money-check-dollar",
            href: "/reports/daily-report/route-deposit-summary",
            permission: "route deposit summary",
            legacyModule: "reports",
            legacyController: "routedepositsummary",
            legacyAction: "routedepositsummary",
          },
          {
            key: "discount-summary",
            title: "Discount Summary",
            titleKey: "discount_summary",
            description: "Review discounted and free-sample invoices for the selected month.",
            descriptionKey: "discount_summary_report_note",
            icon: "fa fa-percent",
            href: "/reports/daily-report/discount-summary",
            permission: "discount summary",
            legacyModule: "reports",
            legacyController: "discountsummary",
            legacyAction: "discountsummary",
          },
          {
            key: "pricing-summary",
            title: "Pricing Summary",
            titleKey: "pricing_summary",
            description: "Review invoices where item selling prices differ from the standard price.",
            descriptionKey: "pricing_summary_report_note",
            icon: "fa fa-tags",
            href: "/reports/daily-report/pricing-summary",
            permission: "pricing summary",
            legacyModule: "reports",
            legacyController: "pricingsummary",
            legacyAction: "pricingsummary",
          },
        ],
      },
      {
        key: "transaction-reports",
        title: "Transaction Report",
        titleKey: "transaction_report",
        icon: "fa fa-receipt",
        legacyModule: "reports",
        legacyController: "transactionreport",
        legacyAction: "index",
        items: [
          {
            key: "sales-summary",
            title: "Sales Summary",
            titleKey: "sales_summary",
            description: "Review summarized sales transactions for the selected report period.",
            descriptionKey: "sales_summary_report_note",
            icon: "fa fa-chart-line",
            href: "/reports/transaction-report/sales-summary",
            permission: "sales summary",
            legacyModule: "reports",
            legacyController: "salessummary",
            legacyAction: "salessummary",
          },
          {
            key: "order-summary",
            title: "Order Summary",
            titleKey: "order_summary",
            description: "Review route-wise order transactions and order net amounts for the selected period.",
            descriptionKey: "order_summary_report_note",
            icon: "fa fa-file-invoice",
            href: "/reports/transaction-report/order-summary",
            permission: "order summary",
            legacyModule: "reports",
            legacyController: "ordersummary",
            legacyAction: "ordersummary",
          },
          {
            key: "bad-return-summary",
            title: "Bad Return Summary",
            titleKey: "bad_return_summary",
            description: "Review item-wise damaged, expired, and other bad return quantities and values for the selected period.",
            descriptionKey: "bad_return_summary_report_note",
            icon: "fa fa-arrow-rotate-left",
            href: "/reports/transaction-report/bad-return-summary",
            permission: "bad return summary",
            legacyModule: "reports",
            legacyController: "returnsummary",
            legacyAction: "returnsummary",
          },
          {
            key: "collection-summary",
            title: "Collection Summary",
            titleKey: "collection_summary",
            description: "Review route-wise receipt collections, cash, cheque, and invoice references for the selected period.",
            descriptionKey: "collection_summary_report_note",
            icon: "fa fa-money-check-dollar",
            href: "/reports/transaction-report/collection-summary",
            permission: "collection summary",
            legacyModule: "reports",
            legacyController: "transactioncollectionsummary",
            legacyAction: "collectionsummary",
          },
          {
            key: "route-visit-summary",
            title: "Route Visit Summary",
            titleKey: "route_visit_summary",
            description: "Review scheduled and unscheduled route visits, visit outcomes, and route kilometers for the selected period.",
            descriptionKey: "route_visit_summary_report_note",
            icon: "fa fa-road-circle-check",
            href: "/reports/transaction-report/route-visit-summary",
            permission: "route visit summary",
            legacyModule: "reports",
            legacyController: "transactionroutereview",
            legacyAction: "routevisit",
          },
          {
            key: "payment-summary",
            title: "Payment Summary",
            titleKey: "payment_summary",
            description: "Review invoice-wise payments, collections, and outstanding balances for the selected period.",
            descriptionKey: "payment_summary_report_note",
            icon: "fa fa-wallet",
            href: "/reports/transaction-report/payment-summary",
            permission: "payment summary",
            legacyModule: "reports",
            legacyController: "transactionpaymentsummary",
            legacyAction: "paymentsummary",
          },
          {
            key: "deposit-summary",
            title: "Deposit Summary",
            titleKey: "deposit_summary",
            description: "Review invoice and receipt deposits by transaction date, route, payment type, and total amount.",
            descriptionKey: "deposit_summary_report_note",
            icon: "fa fa-money-check-dollar",
            href: "/reports/transaction-report/deposit-summary",
            permission: "deposit summary",
            legacyModule: "reports",
            legacyController: "transactiondepositsummary",
            legacyAction: "depositsummary",
          },
          {
            key: "final-deposit",
            title: "Final Deposit",
            titleKey: "final_deposit",
            description: "Review final deposited collection amounts by receipt, customer, invoice reference, and payment method.",
            descriptionKey: "final_deposit_report_note",
            icon: "fa fa-money-bill-transfer",
            href: "/reports/transaction-report/final-deposit",
            permission: "final deposit",
            legacyModule: "reports",
            legacyController: "transactionfinaldeposit",
            legacyAction: "finaldeposit",
          },
          {
            key: "item-history",
            title: "Item History",
            titleKey: "item_history",
            description: "Review route trip inventory movement, returns, and closing stock by item and major category.",
            descriptionKey: "item_history_report_note",
            icon: "fa fa-clock-rotate-left",
            href: "/reports/transaction-report/item-history",
            permission: "item history",
            legacyModule: "reports",
            legacyController: "transactionitemhistory",
            legacyAction: "itemhistory",
          },
        ],
      },
      {
        key: "merchandizing-reports",
        title: "Merchandizing Report",
        titleKey: "merchandizing_report",
        icon: "fa fa-store",
        legacyModule: "reports",
        legacyController: "merchandizingreport",
        legacyAction: "index",
        items: [
          {
            key: "pos-tracking",
            title: "POS Tracking",
            titleKey: "pos_tracking",
            description: "Review POS equipment activity captured during customer visits, including added, removed, and checked POS items.",
            descriptionKey: "pos_tracking_report_note",
            icon: "fa fa-map-location-dot",
            href: "/reports/merchandizing-report/pos-tracking",
            permission: "pos tracking",
            legacyModule: "reports",
            legacyController: "merchandizingpos",
            legacyAction: "posstatus",
          },
          {
            key: "survey-tracking",
            title: "Survey Tracking",
            titleKey: "survey_tracking",
            description: "Review survey questions and captured responses for customer visits across the selected report period.",
            descriptionKey: "survey_tracking_report_note",
            icon: "fa fa-clipboard-question",
            href: "/reports/merchandizing-report/survey-tracking",
            permission: "survey tracking",
            legacyModule: "reports",
            legacyController: "merchandizingsurvey",
            legacyAction: "surveytracking",
          },
          {
            key: "waste-stock",
            title: "Waste Stock",
            titleKey: "waste_stock",
            description: "Review outlet waste stock checks by visit date, customer, item, location quantity, and expiry.",
            descriptionKey: "waste_stock_report_note",
            icon: "fa fa-trash-can",
            href: "/reports/merchandizing-report/waste-stock",
            permission: "waste stock",
            legacyModule: "reports",
            legacyController: "wastagestock",
            legacyAction: "wastagestock",
          },
          {
            key: "assets-availability",
            title: "Assets Availability",
            titleKey: "assets_availability",
            description: "Review customer asset visit records by route, outlet, POS code, serial number, status, and remarks.",
            descriptionKey: "assets_availability_report_note",
            icon: "fa fa-box-archive",
            href: "/reports/merchandizing-report/assets-availability",
            permission: "assets availability",
            legacyModule: "reports",
            legacyController: "customerassets",
            legacyAction: "customerassets",
          },
          {
            key: "merchandized-stock",
            title: "Merchandized Stock",
            titleKey: "merchandized_stock",
            description: "Review outlet shelf and store stock checks by visit, customer, item, cut-off quantity, and expiry.",
            descriptionKey: "merchandized_stock_report_note",
            icon: "fa fa-boxes-stacked",
            href: "/reports/merchandizing-report/merchandized-stock",
            permission: "merchandized stock",
            legacyModule: "reports",
            legacyController: "distributionchecksummary",
            legacyAction: "distributionchecksummary",
          },
        ],
      },
      {
        key: "accounts-reports",
        title: "Accounts Report",
        titleKey: "accounts_report",
        icon: "fa fa-wallet",
        legacyModule: "reports",
        legacyController: "accountreport",
        legacyAction: "index",
        items: [
          {
            key: "route-ageing",
            title: "Route Ageing",
            titleKey: "route_ageing",
            description: "Review open route invoices by ageing bucket, customer credit days, and PDC balance.",
            descriptionKey: "route_ageing_report_note",
            icon: "fa fa-hourglass-half",
            href: "/reports/accounts-report/route-ageing",
            permission: "route ageing",
            legacyModule: "reports",
            legacyController: "accountrouteageing",
            legacyAction: "routeageing",
          },
          {
            key: "customer-ageing",
            title: "Customer Ageing",
            titleKey: "customer_ageing",
            description: "Review open customer invoices by customer type, customer, route, and ageing bucket.",
            descriptionKey: "customer_ageing_report_note",
            icon: "fa fa-users-between-lines",
            href: "/reports/accounts-report/customer-ageing",
            permission: "customer ageing",
            legacyModule: "reports",
            legacyController: "accountcustomerageing",
            legacyAction: "customerageing",
          },
          {
            key: "route-pending-balance",
            title: "Route Pending Balance",
            titleKey: "route_pending_balance",
            description: "Review pending invoice balances by route, salesman, and year.",
            descriptionKey: "route_pending_balance_report_note",
            icon: "fa fa-chart-simple",
            href: "/reports/accounts-report/route-pending-balance",
            permission: "route pending balance",
            legacyModule: "reports",
            legacyController: "routependingbalance",
            legacyAction: "routependingbalance",
          },
          {
            key: "customer-pending-balance",
            title: "Customer Pending Balance",
            titleKey: "customer_pending_balance",
            description: "Review pending invoice balances by head office, customer, invoice, and month.",
            descriptionKey: "customer_pending_balance_report_note",
            icon: "fa fa-file-invoice-dollar",
            href: "/reports/accounts-report/customer-pending-balance",
            permission: "customer pending balance",
            legacyModule: "reports",
            legacyController: "customerbalance",
            legacyAction: "customerpendingbalance",
          },
        ],
      },
      {
        key: "data-analysis",
        title: "Data Analysis",
        titleKey: "data_analysis",
        icon: "fa fa-chart-pie",
        legacyModule: "reports",
        legacyController: "dataanalysis",
        legacyAction: "index",
        items: [
          {
            key: "route-monthly-revenue",
            title: "Route Monthly Revenue",
            titleKey: "route_monthly_revenue",
            description: "Review route revenue by month for the selected year.",
            descriptionKey: "route_monthly_revenue_report_note",
            icon: "fa fa-chart-column",
            href: "/reports/data-analysis/route-monthly-revenue",
            permission: "route monthly revenue",
            legacyModule: "reports",
            legacyController: "routemonthlyrevenue",
            legacyAction: "routemonthlyrevenue",
          },
          {
            key: "sales-free-summary",
            title: "Sales Free Summary",
            titleKey: "sales_free_summary",
            description: "Review sales, free, returns, discounts, and net sales by route, item group, and item.",
            descriptionKey: "sales_free_summary_report_note",
            icon: "fa fa-chart-bar",
            href: "/reports/data-analysis/sales-free-summary",
            permission: "sales free summary",
            legacyModule: "reports",
            legacyController: "datasalesfree",
            legacyAction: "salesfreesummary",
          },
          {
            key: "item-sales-summary",
            title: "Item Sales Summary",
            titleKey: "item_sales_summary",
            description: "Review item-wise sales, returns, expiry, discounts, and free goods across the selected period.",
            descriptionKey: "item_sales_summary_report_note",
            icon: "fa fa-table-cells-large",
            href: "/reports/data-analysis/item-sales-summary",
            permission: "item sales summary",
            legacyModule: "reports",
            legacyController: "itemsalessummary",
            legacyAction: "itemsalessummary",
          },
          {
            key: "item-group-wise-sales",
            title: "Item Group Wise Sales",
            titleKey: "item_group_wise_sales",
            description: "Review route-wise sales, returns, free goods, and discounts by item group for the selected period.",
            descriptionKey: "item_group_wise_sales_report_note",
            icon: "fa fa-layer-group",
            href: "/reports/data-analysis/item-group-wise-sales",
            permission: "item group wise sales",
            legacyModule: "reports",
            legacyController: "itemgroupwisesales",
            legacyAction: "itemgroupwisesales",
          },
        ],
      },
    ],
  },
];
