<?php
/**
 
 * @since      Class available since Pagignation
 * @version    Release: @1.0@
 * @author     HC [harsh@elantechnologies.com]
 * @author     MB [mayur.b@elantechnologies.com]
 * @copyright  Elan technologies
 *
 * Short description : Inserted pagignation with multi search and sort functionalities.
 *
 *
 */

$this->translate = Zend_Registry::get('Zend_Translate');
    
$this->paginator = $this->pagegridshow['paginator'];

$grid_js_settings =  $this->pagegridshow['datagrid']['settings'];

// SOME STATIC FIELD NAMES ARE PUSHED WITH PASSED PARAMETER WHICH IS NOT REQUIRED ON SEARCH FIELD OPTIONS -

if(!isset($grid_js_settings['configuration_params']['no_search_fields']))
$grid_js_settings['configuration_params']['no_search_fields'] = array();

array_push($grid_js_settings['configuration_params']['no_search_fields'],"activeindicator","active","activestate","iscase","startdate","enddate","cdat","mdat","createddate","modifieddate");

// SOME STATIC FIELD NAMES ARE PUSHED WITH PASSED PARAMETER WHICH IS NOT REQUIRED ON SEARCH FIELD OPTIONS -


$grid_js_settings[] = $this->url();

$this->showdatagrid = $this->pagegridshow['datagrid'];

/*
 * Added stylesheet for paging
 */
$this->headLink()->appendStylesheet($this->baseUrl().'/public/css/pagegrid_style.css');


$datashowgrid = $this->showdatagrid['data'];

/*
 * Retrieve search parameters form values
 */
$this->searchvalues = $grid_js_settings['search_values'];

$Paginator_SearchDetails = new Zend_Session_Namespace('Paginator_SearchDetails');
$Paginator_Paging = new Zend_Session_Namespace('Paginator_Paging');
?>
<script type="text/javascript">
	var base_url = '<?php echo$this->baseurl();?>';
	/*
	* Hide show search box
	*/


	$(document).ready(function(){
		
		/**
		 *
		 * Hiren Dave on 1st June.
		 * Fix search issue for chrome and IE because in those browser search functionality was not working.
		 * 
		*/
		$("#grid_search_text").keypress(function(e) { 
			if (e.which == 13)
			{
				$("form").submit();
			}
		});
		
	    $('#frmoverview').submit(function() {			
			if($('#hdDelete').val() != 1)
			{
				str =  document.URL;
				var strrep = str.replace(/page\/\d+/gi, "page\/1");
				this.action = strrep;
			}
	    });
	});
	
	function searchbox(obj) {
		if(obj == 'hide') {
		    $('#draggable').hide();
		    $('#table-searchall').show();
		    $('#table-showpages').show();
		    
		} else {
		    $('#draggable').show();
		    $('#table-searchall').hide();
		    $('#table-showpages').hide();
		}
	}
	
	/*
	* Reset button will redirect to current url
	*/
	function resetSearch() {
		
		$('.sefield').val('');
		$('#reset_val').val(1);
		$('#frmoverview').submit();		
	}
	
	/*
	* Added stylesheet for paging
	*/
	function addMore()
	{
		<?php
		$tmp = 0;
		$tempval = '';
		if(isset($this->showdatagrid['columns'])) {
			foreach($this->showdatagrid['columns'] as $key => $val)
			{
			    $tempval .= '<option value="'.$tmp.'">'.ucfirst($val).'</option>';
			    $tmp++;
			}		
		?>		
		var Searchbox_tmp = '<tr class="sf"><td class="fields" width="40%"><select class="" name="field[]" style="width:178px;">'; 
		Searchbox_tmp = Searchbox_tmp + '<?php echo $tempval; ?>';
		Searchbox_tmp = Searchbox_tmp + '</select></td><td class="ops" width="25%"><select class="default " name="op[]" style="width:148px;"><option value="eq">Equal</option><option value="ne">Not Equal</option><option value="lt">Less</option><option value="le">Less or Equal</option><option value="gt">Greater</option><option value="ge">Greater or Equal</option><option value="bw">Begins With</option><option value="bn">Does Not Begin With</option><option value="in">Is In</option><option value="ni">Is Not In</option><option value="ew">Ends With</option><option value="en">Does Not End With</option><option value="cn">Contains</option><option value="nc">Does Not Contain</option></select></td><td class="data" width="25%" ><input type="text" style="" name="seachvalue[]" class="default vdata sea "></td><td width="5%"  ><div class="ui-del ui-state-default ui-corner-all"><span class="ui-icon ui-icon-minus" onclick="$(this).parent().parent().parent().remove()">';
		Searchbox_tmp = Searchbox_tmp + '<img src="'+base_url+'/public/pagegrid_images/remove.png" alt="remove" />';
		Searchbox_tmp = Searchbox_tmp + '</span></div></td><td width="5%" ><div class="ui-add ui-state-default ui-corner-all"><span class="ui-icon ui-icon-plus" onclick="addMore();">';
		Searchbox_tmp = Searchbox_tmp + '<img src="'+base_url+'/public/pagegrid_images/add.png" alt="Add" />';
		Searchbox_tmp = Searchbox_tmp + '</span></div></td></tr>';
		<?php } ?>
		
	    $('#mydata').append(Searchbox_tmp);
		
		if ($.fn.chosen) {
			$("select").chosen();
		}
	}
 
	function toggleChecked(status) {
		$("#table-example .checkbox").each( function() {
		
			if(status == true)
				status = false;
			else
				status = true;
				
		    $(this).attr("checked",status);
			$('#chkall').attr("checked",status);
		});
	}
	 
	function toggleUnChecked(status,val) {
		
		
		 $('#chkall').attr("checked",false);

		var totalch = $("#table-example input:checkbox.sel_checkbox_all").size();
		var checkedch = $("#table-example input:checkbox.sel_checkbox_all:checked").size();
		
		if(status == true)
			    status = false;
		    else
			    status = true;
		
		if(status)
		{
			    if(checkedch>=(totalch-1))
					$('#chkall').attr("checked",true);
			    else
					$('#chkall').attr("checked",false);
		}
		
	}
	
	<?php if(isset($this->showdatagrid['columns'])) { ?>
	var grid_colsname = new Array("<?php echo implode('","',array_values($this->showdatagrid['columns']));?>");
	<?php } ?>
</script>

<script type="text/javascript">
    function changeRowRange(obj) {
		if(obj!="")
		{
			var newUrl = "<?php echo $this->url(array('prow'=>'prowval','page'=>'1')); ?>";        
			newUrl = newUrl.replace("prowval",obj)        
			window.location = newUrl;
		}
    }
</script>

	<!-- Content -->
	
	<div id="paging_grid">
				
					<!--<h2 class="grid_12">Tables</h2>
					<div class="clear"></div>-->
					
		  <div class="grid_12">
						<div class="box">
							
						<?php
						if($grid_js_settings['configuration_params']['show_grid_heading'] == true || $grid_js_settings['configuration_params']['show_searchbox'] == true) {
							echo '<div class="header">';
							
					if($grid_js_settings['configuration_params']['show_grid_heading'] == true)
					{
						echo '<h3>'.$grid_js_settings['configuration_params']['grid_heading_message'].'</h3>';
					}
					if($grid_js_settings['configuration_params']['show_searchbox'] == true) {
					    ?>
					    <div class="right">
						    <a href="javascript:;" onclick="javascript:searchbox();"><img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/search_icon.png" /></a>
					    </div>
					    <?php }
					    echo '</div>';
					    } ?>
					
					<div class="content  min_height_10">
					<!-- SearchBox  -->
	<div id="draggable"  class="top" style="display:none;" >
		
		<div class="grid_12">
						<div class="box tabbed">
							<div class="header no-icon">
								<h3><?php echo $this->translate->_('Advance Search');?></h3>
								<div class="right">
									<!--<span class="ui-icon ui-icon-close" title="Close" onclick="searchbox('hide')">-->
									<a title="Close" onclick="searchbox('hide')">
										<img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/close.png" />
									<!--</span>	-->
									</a>
									</div>
							</div>
							<div class="content min_height_10">
								<!--	Comment By Hiren dave on 7th Feb 2012   -->
								<!--<form id="searchForm" name="searchForm" method="post">-->
								<table id="mydata" width="100"  class="table">
								<tbody>
		    <?php
		    /*
		     * Display searched values in form
		     */
		    if(count($this->searchvalues[0]) > 0) {
			$tempGroupon = $this->searchvalues[3];
			
			for($sm=0; $sm<count($this->searchvalues[0]); $sm++)
			{
				$tempFields = $this->searchvalues[0];
				$tempValues = $this->searchvalues[1];
				$tempOpt = $this->searchvalues[2];
			?>
		    <tr class="sf">
			<td class="fields" width="40%" c  >
			    <select name="field[]" class="" id="search_field"  >
				<?php
				$tmp = 0;
				foreach($this->showdatagrid['columns'] as $key => $val)
				{
					$asName = explode("as",$grid_js_settings['configuration_params']['fetch_columns_inquery'][$tmp]);
					if(!in_array(trim(end($asName)),$grid_js_settings['configuration_params']['no_search_fields']))
					{
						$selected = ($tempFields[$sm] == $tmp) ? 'selected="selected"' : '';
						echo '<option value="'.$tmp.'" '.$selected .'>'.ucfirst($val).'</option>';
					}
				    $tmp++;
				}
				?>
			    </select>
			</td>
			<td class="ops">				
				<select id="query_cond" class="default " name="op[]">
					<option value="eq" <?php if($tempOpt[$sm]=='eq') echo "selected='selected'"; ?>><?php echo $this->translate->_('Equal');?></option>
					<option value="ne" <?php if($tempOpt[$sm]=='ne') echo "selected='selected'"; ?>><?php echo $this->translate->_('Not Equal');?></option>
					<option value="lt" <?php if($tempOpt[$sm]=='lt') echo "selected='selected'"; ?>><?php echo $this->translate->_('Less');?></option>
					<option value="le" <?php if($tempOpt[$sm]=='le') echo "selected='selected'"; ?>><?php echo $this->translate->_('Less or Equal');?></option>
					<option value="gt" <?php if($tempOpt[$sm]=='gt') echo "selected='selected'"; ?>><?php echo $this->translate->_('Greater');?></option>
					<option value="ge" <?php if($tempOpt[$sm]=='ge') echo "selected='selected'"; ?>><?php echo $this->translate->_('Greater or Equal');?></option>
					<option value="bw" <?php if($tempOpt[$sm]=='bw') echo "selected='selected'"; ?>><?php echo $this->translate->_('Begins With');?></option>
					<option value="bn" <?php if($tempOpt[$sm]=='bn') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not Begin With');?></option>
					<option value="in" <?php if($tempOpt[$sm]=='in') echo "selected='selected'"; ?>><?php echo $this->translate->_('Is In');?></option>
					<option value="ni" <?php if($tempOpt[$sm]=='ni') echo "selected='selected'"; ?>><?php echo $this->translate->_('Is not In');?></option>
					<option value="ew" <?php if($tempOpt[$sm]=='ew') echo "selected='selected'"; ?>><?php echo $this->translate->_('Ends With');?></option>
					<option value="en" <?php if($tempOpt[$sm]=='en') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not End With');?></option>
					<option value="cn" <?php if($tempOpt[$sm]=='cn') echo "selected='selected'"; ?>><?php echo $this->translate->_('Contains');?></option>
					<option value="nc" <?php if($tempOpt[$sm]=='nc') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not Contain');?></option>
				</select>
			</td>
			<td class="data"  ><input type="text" style="" name="seachvalue[]" value="<?php echo $tempValues[$sm]; ?>" class="sea sefield " ></td>
			<td width="5%" style="padding-top:10px;" >
				<div class="ui-del ui-state-default ui-corner-all"><span class="ui-icon ui-icon-minus" onclick="$(this).parent().parent().parent().remove()"><img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/remove.png"/></span></div>
			</td>
			<td width="5%" style="padding-top:10px;" >
				<div class="ui-add ui-state-default ui-corner-all"><span class="ui-icon ui-icon-plus" onclick="addMore();"><img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/add.png" /></span></div>
			</td>
		    </tr>	
			<?php
			}
		    } else {
		    ?>
		    <tr >
			<td class="fields margin_t" width="40%" >
			    <select name="field[]" id="search_field" class="default " >
				<?php
				$tmp = 0;
				if(isset($this->showdatagrid['columns'])) {
					foreach($this->showdatagrid['columns'] as $key => $val)
					{
						$asName = explode("as",$grid_js_settings['configuration_params']['fetch_columns_inquery'][$tmp]);
						if(!in_array(trim(end($asName)),$grid_js_settings['configuration_params']['no_search_fields']))
						   {
							   echo '<option value="'.$tmp.'">'.ucfirst($val).'</option>';
						   }
					    $tmp++;
					}
				} 
				?>
			    </select>
			</td>
			<td class="ops ">
				<select id="query_cond" class="default " name="op[]" >
					<option value="eq" <?php if($tempOpt[$sm]=='eq') echo "selected='selected'"; ?>><?php echo $this->translate->_('Equal');?></option>
					<option value="ne" <?php if($tempOpt[$sm]=='ne') echo "selected='selected'"; ?>><?php echo $this->translate->_('Not Equal');?></option>
					<option value="lt" <?php if($tempOpt[$sm]=='lt') echo "selected='selected'"; ?>><?php echo $this->translate->_('Less');?></option>
					<option value="le" <?php if($tempOpt[$sm]=='le') echo "selected='selected'"; ?>><?php echo $this->translate->_('Less or Equal');?></option>
					<option value="gt" <?php if($tempOpt[$sm]=='gt') echo "selected='selected'"; ?>><?php echo $this->translate->_('Greater');?></option>
					<option value="ge" <?php if($tempOpt[$sm]=='ge') echo "selected='selected'"; ?>><?php echo $this->translate->_('Greater or Equal');?></option>
					<option value="bw" <?php if($tempOpt[$sm]=='bw') echo "selected='selected'"; ?>><?php echo $this->translate->_('Begins With');?></option>
					<option value="bn" <?php if($tempOpt[$sm]=='bn') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not Begin With');?></option>
					<option value="in" <?php if($tempOpt[$sm]=='in') echo "selected='selected'"; ?>><?php echo $this->translate->_('Is In');?></option>
					<option value="ni" <?php if($tempOpt[$sm]=='ni') echo "selected='selected'"; ?>><?php echo $this->translate->_('Is not In');?></option>
					<option value="ew" <?php if($tempOpt[$sm]=='ew') echo "selected='selected'"; ?>><?php echo $this->translate->_('Ends With');?></option>
					<option value="en" <?php if($tempOpt[$sm]=='en') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not End With');?></option>
					<option value="cn" <?php if($tempOpt[$sm]=='cn') echo "selected='selected'"; ?>><?php echo $this->translate->_('Contains');?></option>
					<option value="nc" <?php if($tempOpt[$sm]=='nc') echo "selected='selected'"; ?>><?php echo $this->translate->_('Does not Contain');?></option>
				</select>
			</td>
			<td class="data" width="25%" ><input type="text" style="" name="seachvalue[]" class="default vdata sea sefield "></td>
			<td width="5%" style="padding-top:10px;" >
				<div class="ui-del ui-state-default ui-corner-all margin_t2"><span class="ui-icon ui-icon-minus"><img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/remove.png"/></span></div>
			</td>
			<td width="5%" style="padding-top:10px;">
				<div class="ui-add ui-state-default ui-corner-all margin_t2"><span class="ui-icon ui-icon-plus" onclick="addMore();"><img src="<?php echo $this->baseUrl(); ?>/public/pagegrid_images/add.png" /></span></div>
			</td>
		    </tr>
		    <?php } ?>
		</tbody>
		<tfoot>
			<tr>
			    <td width="33%">
				<div class="_30 margin_top_12" style="display: inline-block; float: left;" >
				    <input type="button" name="reset" id="sea_reset"  value="<?php echo $this->translate->_('Reset');?>" onclick="resetSearch();" />
				    <input type="hidden" value="0" name="reset_val" id="reset_val">
				</div>
			    </td>
				<td width="33%">
				<div class="_100 margin_top_12">				    
					<label class="_20 matchText left margin_left_1 margin_top_7"><?php echo $this->translate->_('Match');?></label>
				    <div class="left _50">
						<select name="groupOp[]" class=""  >
							<option value="AND" <?php if($tempGroupon[0]=='AND') { echo 'selected="selected"'; } ?>><?php echo $this->translate->_('All');?></option>
							<option value="OR" <?php if($tempGroupon[0]=='OR') { echo 'selected="selected"'; } ?>><?php echo $this->translate->_('Any');?></option>
						</select>
					</div>				    
				</div>
				</td>
				<td width="33%">
					<div class="_30">
						<div style="width:10%">&nbsp;</div>
						<input type="submit" name="search" value="<?php echo $this->translate->_('Find');?>" id="sea_find" />
					</div>
			    </td>
			</tr>
			<tr>
				<td>&nbsp;
				</td>
			</tr>
		</tfoot>	
		</table>								
	</div> <!-- End of .content -->
</div> <!-- End of .box -->
</div>
	
	    
<!--	Comment By Hiren dave on 7th Feb 2012   -->
	    <!--</form>-->
	</div>
	<!-- End SearchBox -->

	<div class="top shead">
	<?php
	//echo "<pre>";
	//print_r($grid_js_settings);
	//echo "</pre>";
	
	if(isset($Paginator_Paging->show_records_per_page))
		$show_records_per_page = $Paginator_Paging->show_records_per_page;
	else
		$show_records_per_page = $grid_js_settings["configuration_params"]["show_records_per_page"];
		
	?>
	<div id="table-showpages" class="_50 margin_0" >&nbsp;
	<?php
	if( ($grid_js_settings['configuration_params']['show_grid_heading'] == true && $grid_js_settings['total_data'] > $grid_js_settings['total_row_per_page'] ) || $grid_js_settings['total_data'] > 10)
	{
	?>

	<label id="ie7_searchlabel" class="_30_1 label_text_align margin_top_12 ie_margin_0" >
		<?php echo $this->translate->_('Show Entries')." ".$this->translate->_('Colan'); ?>
	</label>
	<div class="_50_3 margin_right_1" id="ie7_searchcombo" >
		<select name="show_records_per_page" size="1" id="selMBC" class="pageitem" onchange="$('#frmoverview').submit();" >
		  <option value="10" <?php if($show_records_per_page==10 ) { ?> selected="selected" <?php } ?> >10</option>
		  <option value="25" <?php if($show_records_per_page==25 ) { ?> selected="selected" <?php } ?> >25</option>
		  <option value="50" <?php if($show_records_per_page==50 ) { ?> selected="selected" <?php } ?> >50</option>
		  <option value="100" <?php if($show_records_per_page==100 ) { ?> selected="selected" <?php } ?> >100</option>
		</select>
	</div>
	<!--<div class="_20">&nbsp;</div>-->
	<?php		
	}	
	?>
	</div>
	<div id="table-searchall" class="_50">
	<?php
		if($grid_js_settings['configuration_params']['show_searchbox'] == true){
	?>
	
	  
		<div class="_36">&nbsp;</div>
		  <label class="_25 label_text_align margin_top_12"><?php echo $this->translate->_('Search')." ".$this->translate->_('Colan');?></label>
		  <div class="_40">
			<input type="text" class="sea" name="grid_search_text" id="grid_search_text" value="<?php echo $Paginator_SearchDetails->shortsearch_value; ?>" >
		  </div>	  
	<?php } ?>
	</div>
	  <div class="clear"></div>
	</div>
  <?php
	// Check the data for the data grid display
	if(isset($grid_js_settings['total_data']) && $grid_js_settings['total_data'] > 0)
	{
	?>
	<div id="comman_grid_div">
							  <table id="table-example" class="table">
									<thead>
										<tr>
											
											<?php
		    /*
		     * Display checkbox if is set to true
		     */
		    if($grid_js_settings['configuration_params']['show_selectbox'] == true) { 
			echo '<th width="13"><input type="checkbox" id="chkall" name="chkall" onclick="toggleChecked(this.checked);" class="checkbox" /></th>';
		    }
		    
		    $colsname_int = 0;
			
			/*
			* Set default sort order images
			*/
			$grid_js_settings['order_imagetype'] = "sorting";
			
			
			
			
			/*
			* Set sorting images
			*/
			if(!is_null($grid_js_settings['order_columns_number']) && trim($grid_js_settings['order_type'])=="asc")
			{
				$grid_js_settings['order_imagetype'] = "sorting_asc";
			}
			else if(!is_null($grid_js_settings['order_columns_number']) && trim($grid_js_settings['order_type'])=="desc")
			{
				$grid_js_settings['order_imagetype'] = "sorting_desc";
			}
		
			$data_display_collection = "";
			if($this->showdatagrid['columns_top'] == true)
			{
				echo "<tr>";
				foreach($this->showdatagrid['columns_top_value'] as $key => $val)
				{
					echo "<th class='top_header' colspan='".$val[0]."' >".$val[1]."</th>";
				}
				echo "</tr>";
			}
			
			//print_r($this->showdatagrid['columns']); die();
			
			foreach($this->showdatagrid['columns'] as $key => $val)
			{
				$colnameshow = "";
				if(is_integer($key))
				{
					$colnameshow = $val;
				}
				else
				{
					$colnameshow = $key;
				}
				$colnameshow = $val;
				
				
				// set the link of sorting (by Meral)
				$currentSortLink = $grid_js_settings['order_type']=="asc"?"desc":"asc";
				
				/*
				* Prepare data grid columns heading with sorting parameters
				*/
				if(!is_null($grid_js_settings['order_columns_number']) && $grid_js_settings['order_columns_number']==$colsname_int)
				{
					if(in_array($colnameshow,$this->showdatagrid['settings']['configuration_params']['show_header_right_side']))
					{						
						$data_display_collection.= "<th class='align_right ".$grid_js_settings['order_imagetype']."'>";
					}
					else
					{
						$data_display_collection.= "<th class='".$grid_js_settings['order_imagetype']."'>";	
					}				
				    $data_display_collection.= "<a href='".$this->url(array('order'=> $colsname_int.'_'.$currentSortLink))."'>".ucfirst($colnameshow)." </a>";
				}
				else
				{
					if(in_array($colnameshow,$this->showdatagrid['settings']['configuration_params']['show_header_right_side']))
					{
						$data_display_collection.= "<th class='sorting align_right'>";
					}
					else
					{
						$data_display_collection.= "<th class='sorting'>";
					}					
					
				$data_display_collection.= "<a href='".$this->url(array('order'=> $colsname_int.'_asc'))."'>"
						.ucfirst($colnameshow)."</a>";

				}
				$data_display_collection.= "</th>";
				
				
				$colsname_int++;
			}
			echo $data_display_collection;
		    /*
		     * Display editlink if is set to true
		     */
		    if($grid_js_settings['configuration_params']['show_editlink'] == true) { 
			echo '<th >&nbsp;</th>';
		    }
		    
		    /*
		     * Display deletelink if is set to true
		     */
		    if($grid_js_settings['configuration_params']['show_deletelink'] == true) { echo '<th >&nbsp;</th>'; }
			
			
			/*
		     * Display extra link if is set to true
		     */
		    if($grid_js_settings['configuration_params']['show_extralink'] == true) {
				
				for($sel=0; $sel<count($grid_js_settings['configuration_params']['extralink']); $sel++)
					echo '<th >&nbsp;</th>';
			}
		    
			?>
										</tr>
									</thead>
									<tbody>
			<?php
			/*
			 * fill data array in table body
			 */
			
			for($k=0;$k<count($datashowgrid);$k++)
			{
				$classname='class="gradeC"';
				if(($k+1)%2==0)
				{
					$classname='class="gradeA"';
				}
				
				$showtextbox = array('batchno','expirydate','allowcases','allowpieces');
				echo "<tr ".$classname." >";
				foreach($datashowgrid[$k] as $key => $val)
				{
					if($key!="edit_del_primary_id" && $key!="sett_tran_type")
					{
						//comment added by Gpatel & HDave this is check column aignment for right side or left side
						if(in_array($key,$this->showdatagrid['settings']['configuration_params']['show_columns_right_side'])) {
							echo "<td class='align_right'>";
						} else {
							echo "<td>";
						}
						if($val !='' && $grid_js_settings['configuration_params']['inventory_setting'] == 1 && !in_array($key,$showtextbox)) {						
							echo $val;
						} elseif(!in_array($key,$showtextbox) && $val !='') {
							echo $val;
						} else {
							echo "&nbsp;";
						}
						// store invoicebalance value in span for validating with current amount.
						if($grid_js_settings['configuration_params']['inventory_setting'] == 1 && $key=="allowcases") {
							echo '<input style="width: 50% !important;" class="cls_allowcases" type="text" id="txtcases_'.$datashowgrid[$k]["edit_del_primary_id"].'" value="'.$datashowgrid[$k]["allowcases"].'">';
							echo '<span style="display:none" id="span_'.$datashowgrid[$k]["edit_del_primary_id"].'">'.$datashowgrid[$k]["allowcases"].'</span>';
						}
						// store invoicebalance value in span for validating with current amount.
						if($grid_js_settings['configuration_params']['inventory_setting'] == 1 && $key=="allowpieces") {
							echo '<input style="width: 50% !important;" class="cls_allowpieces" type="text" id="txtpcs_'.$datashowgrid[$k]["edit_del_primary_id"].'" value="'.$datashowgrid[$k]["allowpieces"].'">';
							echo '<span style="display:none" id="span1_'.$datashowgrid[$k]["edit_del_primary_id"].'">'.$datashowgrid[$k]["allowpieces"].'</span>';
						}
						// store invoicebalance value in span for validating with current amount.
						if($grid_js_settings['configuration_params']['inventory_setting'] == 1 && $key=="batchno") {
							echo '<input style="width: 50% !important;" class="cls_batchno" type="text" id="txtbatchno_'.$datashowgrid[$k]["edit_del_primary_id"].'" value="">';
						}
						// store invoicebalance value in span for validating with current amount.
						if($grid_js_settings['configuration_params']['inventory_setting'] == 1 && $key=="expirydate") {
							echo '<input style="width: 85% !important;" class="cls_expdate" type="text" id="txtexpdate_'.$datashowgrid[$k]["edit_del_primary_id"].'" value="">';
						}
						echo "</td>";
					}
				}
				echo "</tr>";
			}
			?>
			</tbody>
		</table>
	</div>        
			<div class="actions">
		<?php
		/*
		* Display paging
		*/		
		if($grid_js_settings['total_data'] > $grid_js_settings['total_row_per_page'])
		{
		   echo $this->partial('pagination.phtml', $this);
		}
		?>
			</div>
		
		<?php
	}else{
		echo '<div class="clear_only nodata_message margin_top_50 margin_bottom_10"><b>'.$grid_js_settings['configuration_params']['nodata_message']."</b></div>";
	}
	?>
					</div> <!-- End of .content -->
						</div>
							<div class="clear"></div>
						</div> <!-- End of .box -->
					</div> <!-- End of .grid_12 --><!-- End of .grid_12 -->
					
	<div class="clean"></div>
<?php

$tmpSearchArray = $this->pagegridshow['datagrid']['settings']['search_values'][1];

if(isset($tmpSearchArray) && count($tmpSearchArray) && $tmpSearchArray[0]!="" ){ ?>
<script type=text/javascript>
	searchbox('show');
</script>

<?php } ?>