<?php
/**
 *
 * @since      Class available since Pagignation
 * @version    Release: @1.0@
 * @author     HC
 * @author     MB
 * @copyright  Elan Technologies
 *
 * Short description : This file is used to show pagignation.
 *
 *
 */

    $paginator = $this->pagegridshow_4['paginator'];

    $this->current = $paginator["currenet"];
    $this->itemCountPerPage = $paginator["itemCountPerPage"];
    $this->totalItemCount = $paginator["totalItemCount"];
            
    $this->TotalPages = ceil($this->totalItemCount/$this->itemCountPerPage);
    
    if(!($this->current>=$this->TotalPages)){
          $this->next = $this->current+1;
          $this->last = $this->TotalPages;
    }
    
    if(!($this->current<=1)){
          $this->previous = $this->current-1;
          $this->first = "1";
    }
    
    $this->PagingStart = $this->current-$paginator["pagingLength"];
            $this->PagingEnd  = $this->current+$paginator["pagingLength"];
            
    if($this->PagingStart<1)
        $this->PagingStart = 1;
        
    if($this->PagingEnd>$this->TotalPages)
        $this->PagingEnd = $this->TotalPages;
 
?>
<div class="actions-left">
    <div class="dataTables_info" id="table-example_info_4">
    <!---Showing 1 to 10 of 57 entries--->
    
    Showing <?php echo (($this->current*$this->itemCountPerPage)-$this->itemCountPerPage+1); ?> - <?php echo (($this->current*$this->itemCountPerPage) < $this->totalItemCount) ? ($this->current*$this->itemCountPerPage) : $this->totalItemCount; ?> of <?php echo $this->totalItemCount; ?>
    </div>
    </div>
            <div class="actions-right">
                    <div class="dataTables_paginate paging_full_numbers" id="table-example_paginate_4">
                        <!-- First page link -->
                        <?php if (isset($this->previous)): ?>
                              <a class="imgicon page_number" id="<?php echo $this->url(array('page' => $this->first)); ?>" >
                              <span class="first paginate_button" id="table-example_first_4">First</span>
                              </a>
                        <?php else: ?>
                                <span class="first paginate_button paginate_button_disabled" id="table-example_first_4">First</span>
                        <?php endif; ?>
                        
                        
                        <!-- Previous page link -->    
                        <?php if (isset($this->previous)): ?>
                              <a class="imgicon page_number" id="<?php echo $this->url(array('page' => $this->previous)); ?>" >
                              <span class="previous paginate_button" id="table-example_previous_4">Previous</span>
                              </a>
                        <?php else: ?>
                            <span class="previous paginate_button paginate_button_disabled" id="table-example_previous_4">Previous</span>
                        <?php endif; ?>
        
        
                            <span>
                         <!-- Numbered page links -->
                         <?php for($page=$this->PagingStart; $page<=$this->PagingEnd; $page++) { ?>
                        
                            <?php if ($page != $this->current): ?>
                            <span class="paginate_button">
                                <a class="page_number" id="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
                            </span>
                            <?php else: ?>
                                <span class="paginate_active">
                                    <a class="page_number" id="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
                                </span> 
                            <?php endif; 
                                if($page != $this->last) {
                                    //echo '<span>...</span>';
                                }
                            ?>
                        <?php } ?>
                        
                        <!-- Next page link -->
                    <?php if (isset($this->next)): ?>
                          <a class="imgicon page_number" id="<?php echo $this->url(array('page' => $this->next)); ?>" >
                          <span class="next paginate_button" id="table-example_next_4">Next</span>
                          </a>
                    <?php else: ?>
                           <span class="next paginate_button paginate_button_disabled" id="table-example_next_4">Next</span>
                    <?php endif; ?>
                        
                       
                       <!-- Last page link -->
                    <?php if (isset($this->next)): ?>
                          <a class="imgicon page_number" id="<?php echo $this->url(array('page' => $this->last)); ?>" >
                          <span class="last paginate_button" id="table-example_last_4">Last</span>
                          </a>
                    <?php else: ?>
                        <span class="last paginate_button paginate_button_disabled" id="table-example_last_4">Last</span>
                    <?php endif; ?> 
                            
                      
                            
                    </div>
            </div>


        
        
<!-- End Pagging -->