<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/public/css/report-style.css'); ?>
<center>
            <div class="wrapLine">
            <div id="reportPaging" class="left" style="width:90%;" >


                    <span>
                                                    &lt;&lt;
                                            </span>
                    <span>|</span>
                    <span>
                                                    &lt;
                                            </span>
                    <span>|</span>
                    <span>1</span>
                    <span>|</span>
                    <span>
                                                    &gt;
                                            </span>
                    <span>|</span>
                    <span>
                                                   &gt;&gt;
                                            </span>

            </div>

            <div class="left" style="width:8%;padding-top:5px;float:right;">
                        <a onclick="window.print();" href="javascript:void(0);"><img alt="Print"  src="<?php echo $this->baseUrl()?>/public/img/icons/16X16/print_icon.png" width="16" border="0" /></a>
                        <a href="javascript:void(0)"><img alt="Export"  src="<?php echo $this->baseUrl()?>/public/img/icons/16X16/excel_icon.png" width="16" border="0" /></a>
                        
            </div>

            </div>
        </center>