<?php
/**
* @name       ajaxgrid.phtml
* @since      21-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  Elan Technologies
*
* 
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$Common_NameSpace = new Zend_Session_Namespace('Common');

?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
  <div class="clear"></div>
	<?php echo $this->partial('datagrid_ajax.phtml', $this); ?>
    <div class="clear"></div>
  <?php
  
  $total_price ="0";
	foreach($this->result_arr as $value)
	{
	   
	    $total_price = $total_price + str_replace(",","",$value['total_amount']);
	}
	
  ?>
  
  <input type="hidden" name="customer_total_amount" id="customer_total_amount" value="<?php echo number_format($total_price,$this->decimalplaces);?>" />
  <input type="hidden" name="customer_tc_amount" id="customer_tc_amount" value="<?php echo number_format($this->tc_amount_value,$this->decimalplaces);?>" />
  <input type="hidden" name="totalitem_list" id="totalitem_list" value="<?php echo count($this->result_arr);?>" />
<?php 
//if(isset($this->totalInvoice) && $this->totalInvoice > 0 && isset($this->invoiceData[0]))
//{
//    $result = $this->invoiceData[0];
//    print "<pre>";
//    print_r($result);
//    print "++++++++++++++++++++++++++<br/>";
//    print_r($this->invoiceData2);
?>
<script type="text/javascript">
//    $(document).ready(function() {
//        // Item
//        $('#ddlitem').val('<?php echo $result['actualitemcode']; ?>');
//        $('#ddlitem').trigger('liszt:updated');
//        
//        $('#txt_sale_price').val('<?php echo $result['salescaseprice']; ?>');
//        $('#txt_upc').val('<?php echo $result['unitspercase']; ?>');
//        $('#txt_sales_pcs_price').val('<?php echo $result['salesprice']; ?>');
//        
//        $('#txt_return_pcs_price').val('<?php echo $result['returnprice']; ?>');
//        $('#txt_sales_pcs_price').val('<?php echo $result['salescaseprice']; ?>');
//        
//        $('#txt_return_price').val('<?php echo $result['returncaseprice']; ?>');        
//        $('#txt_return_pcs_price').val('<?php echo $result['FORMAT(id.returnprice,2)']; ?>');        
//        $('#txt_sales_case').val('<?php echo $result['case_sales_qty']; ?>');
//        $('#txt_sales_pieces').val('<?php echo $result['pcs_sales_qty']; ?>');
//        
//        $('#txt_freegood_case').val('<?php echo $result['case_manualfreeqty_qty']; ?>');
//        $('#txt_freegood_pieces').val('<?php echo $result['pcs_manualfreeqty_qty']; ?>');
//        
//        $('#txt_buyback_cases').val('<?php echo $result['salescaseprice']; ?>');
//        $('#txt_buyback_pieces').val('<?php echo $result['salescaseprice']; ?>');
//        
//        $('#txt_damage_cases').val('<?php echo $result['salescaseprice']; ?>');
//        $('#txt_damage_pieces').val('<?php echo $result['salescaseprice']; ?>');
//        
//        $('#txt_expirey_case').val('<?php echo $result['salescaseprice']; ?>');
//        $('#txt_expirey_pieces').val('<?php echo $result['salescaseprice']; ?>');
//        
//        // Drop downs
//        $('#ddfreegoodreason').val('<?php echo $result['actualitemcode']; ?>');
//        $('#ddfreegoodreason').trigger('liszt:updated');
//        
//        //ddfreegoodreason
//        //ddreturnreason
//        //dddamagereason
//        //ddexpiryreason
//    });
 </script>

