<div id="hhctransaction_ordertransaction_salesorderadd_detail1" >
 <form id="frmorderadd" name="frmorderadd" class="validate" novalidate action="" method="post">
   <div class="content with-actions" id="hhctransaction_ordertransaction_salesorderadd">
	  <input type="hidden" name="hdndata" value="salesorderadd" />     
	  <div class="_100">
	    <label class="_17_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Route').''.$this->required;?>
	    </label>
	    <div class="_30 margin_right_2_2">
		<select id="ddlroute" name="ddlroute" class="required" >
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->route);$i++)
			{
		    ?>
			    <option  value="<?php echo $this->route[$i]['id'];?>"><?php echo $this->route[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	    <label class="_25 label_text_align margin_top_12">
		<?php echo $this->translate->_('Date').''.$this->colan;?>
	    </label>
	    <label class="_25  margin_top_12">
			<?php echo date('d-m-Y h:i:s');?>		
	    </label>
    </div>
     <div class="_100">
	    <label class="_17_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Salesman').''.$this->colan;?>
	    </label>
	    <div class="_30 margin_right_2_2">
		<input type="text" class="margin_top_5" id="txt_salesman" name="txt_salesman" value=""  readonly="readonly">
	    </div>
	    <label class="_25 label_text_align margin_top_12">
		<?php echo $this->translate->_('Order No').''.$this->colan;?>
	    </label>
	    <label class="_25">
		<input type="hidden" name="order_id_auto" id="order_id_auto" value="<?php echo $this->order_no; ?>" />
		<input type="text" class="margin_top_5" id="txt_order_no" name="txt_order_no" value="" readonly="readonly" >
	    </label>

    </div>
     <div class="_100">
	    <label class="_17_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Customer').''.$this->required;?>
	    </label>
	    <div class="_30 margin_right_2_2">
		<select id="ddlcustomer" name="ddlcustomer" class="required" >
		    <option value="">--- Select ---</option>
		</select>
		
	    </div>
	    <label class="_25 label_text_align margin_top_12">
		
		<?php echo $this->translate->_('Document No').''.$this->colan;?>
	    </label>
	    <label class="_25">
		<input type="hidden" name="document_id_auto" id="document_id_auto" value="<?php echo $this->document_no; ?>" />
		<input type="text" class="margin_top_5" id="txt_doc_no" name="txt_doc_no" value="" readonly="readonly" >
	    </label>

    </div>
     
      <div class="_100">
	    <label class="_17_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Address').''.$this->colan;?>
	    </label>
	    <div class="_30 margin_right_2_2">
		<input type="text" class="margin_top_5" name="txt_customer_address" id="txt_customer_address" value="" readonly="readonly" />
		
	    </div>
	    <label class="_25 label_text_align margin_top_12">
		
		<?php echo $this->translate->_('Customer Payment Term').''.$this->colan;?>
	    </label>
	    <label class="_25">
	    <input type="text" class="margin_top_5" name="customer_payment_terms_text" id="customer_payment_terms_text" value=""  readonly="readonly"/>
		
	    </label>

    </div>
     <div class="_100">
	    <label class="_17_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Credit Limit').''.$this->colan;?>
	    </label>
	    <div class="_30 margin_right_2_2">
		<input type="text" class="margin_top_5" name="txt_customer_creditlimit" id="txt_customer_creditlimit" value="" readonly="readonly" />
	    </div>
	    <label class="_25 label_text_align margin_top_12">
		
		<?php echo $this->translate->_('Credit Days').''.$this->colan;?>
	    </label>
	    <label class="_25">
	    <input type="text" class="margin_top_5" name="txt_customer_credit_day" id="txt_customer_credit_day" value="" readonly="readonly" />
		
	    </label>

    </div>
      <div class="_100">
	    <label class="_17_1 label_text_align margin_top_12">
			<?php echo $this->translate->_('LPO Number').''.$this->colan;?>
	    </label>
	    <div class="_30 margin_right_2_2">
			<input type="text" class="margin_top_5" name="txt_lpo_number" id="txt_lpo_number" value="" />
	    </div>
	    <label class="_25 label_text_align margin_top_12">
			<?php echo $this->translate->_('Delivery Date').''.$this->required;?>
	    </label>
	    <label class="_25">	    
			<input name="txt_delivery_date1" id="txt_delivery_date1" maxlength="50" type="text" class="margin_top_5 required"  readonly="readonly"  value="">
	    </label>
    </div>
    <div class="_100 margin_top_10">
		<label class="_17_1 label_text_align">
			<?php echo $this->translate->_('Remarks').''.$this->colan;?>	
		</label>
		<div class="_25">&nbsp;</div>
			<label class="_25_3 label_text_align  margin_right_1"><?php echo $this->translate->_('Signature').''.$this->colan;?></label>
		<label class="_20   margin_right_1"> <a href="javascript:;" onclick=clear_sig() >Clear</a></label>
    </div>
    <div class="_100">
		<div class="_17_1">&nbsp;</div>
	    <div class="_30 margin_right_2_2 margin_left_0">
			<textarea cols="45" rows="3" name="txt_order_comment" class="transaction" ></textarea>
	    </div>
		<div class="_25_3 margin_left_right_0">&nbsp;</div>
		<div class="_20 margin_top_7" id="signature_id">
			<div class="sigPad signed">
				<div class="sigWrapper">
				  <canvas class="pad" width="200" height="66"></canvas>
				  <input type="hidden" name="output" class="output">
				</div>
			</div>		
	    </div>
    </div>   
    <div class="clear"></div>
    <div class="_100">
	  
           <div class="float_right" style="margin-right:83px"><input type="button" name="btn_next" value="Next" id="btn_next_add_order"/></div>
    </div>
    <div class="clear space_20"></div>
</div><!-- Main div end -->
</form>
</div>