<style>
.gridclass {
    border-left: 1px solid #CCCCCC;
    border-top: 1px solid #CCCCCC;
    }
.gridclass td { height:22px; padding:3px;}
#table-example td span{ text-align:center}
.align_center{ text-align:center}
    
</style>
<form id="frmpromotion" name="frmpromotion" class="validate" novalidate action="" method="post">
<div class="content with-actions" id="hhctransaction_ordertransaction_promotion">

<div class="_100 margin_bottom_5">
	   <label class="_15_2 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Customer Name').''.$this->colan;;?>
		</label>
		<label class="_36 margin_top_12 margin_left_2 margin_right_2_2">
		    <div id="detail_3_customer"></div>
		</label>
	   
	    <label class="_20 label_text_align margin_top_12">
		<?php echo $this->translate->_('Total Amount').''.$this->colan;?>
	    </label>
	    <div class="_25 margin_right_1">
		<input type="text" name="total_amount_pro" id="total_amount_pro" readonly="readonly" value="" class="amount_text_align" />
	    </div>
	   

    </div>
	   <div class="_100 ">

	    <div  id="promotion-grid" class="gridclass" ></div>

	   </div>	
         <div class="clear"></div>
        <div class="_100">
	  
           <div style="float:right"><input type="button" name="btn_next_promotion" id="btn_next_promotion" value="Next" /></div>
	   <div style="float:right">&nbsp;&nbsp;</div>
	   
	   <div style="float:right"><input type="button" name="btn_previous_promotion" id="btn_previous_promotion" value="Previous" /></div>
	</div>
         <div class="clear space_100"></div>
         
</div>
</form>

<script type="text/javascript">
$(window).load(function() {
    
    $("a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',theme:'light_rounded', allow_resize: false});
});
</script>