<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Cash Description
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.table1{ border:1px solid #EEEEEE}
.table1 th{ color:#164A7E;padding:6px; background:#EEEEEE}
.table1 td{ border:1px solid #EEEEEE; padding:6px}
</style>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="merchandize_index_addlookupindex">
<form id="frmfirstaaaa" name="frmfirstaaaa" class="validate" method="post" action="" novalidate="novalidate" >
	<input type="hidden" id="hdnid1" name="hdnid1" value="<?php echo $this->params["edit"]=="yes"?$this->params["trankey"]:0; ?>">
    <input type="hidden" id="defkey" name="defkey" value="<?php echo $this->defkey; ?>">
    <div class="header">
	<div class="_50_3 back_btn">
	    <img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
	    <h3><?php echo $this->translate->_('Promotion Detail');?></h3>
	</div>
	<!--<div class="_50_3">
	    <div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel">
	    </div>
	    <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
	</div>-->
    </div>    
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100">
	     <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Promotion Name').''.$this->required;?>
	    </label>
	    <div class="_70 margin_right_1" style="margin-left:0px;">
		<input name="txt_promotion_name" id="txt_promotion_name" readonly="readonly"  type="text" value="<?php echo $this->promotion_data[0]['plandescription']?>" 	/>
	    </div>
	</div>
        <div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Start Date').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_start_date" readonly="readonly" name="txt_start_date" value="<?php echo $this->promotion_data[0]['startdate']?>">
	    </div>
	    <label class="_20_2 label_text_align margin_top_12">
		<?php echo $this->translate->_('End Date').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_end_date"  readonly="readonly" name="txt_end_date" value="<?php echo $this->promotion_data[0]['enddate']?>">
	    </div>
	</div>
        <div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Qualification').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_qualification" readonly="readonly" name="txt_qualification" value="<?php echo $this->promotion_data[0]['qualificationgroup']?>">
	    </div>
	    <label class="_20_2 label_text_align margin_top_12">
		<?php echo $this->translate->_('Assignment').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_assignment" readonly="readonly" name="txt_assignment" value="<?php echo $this->promotion_data[0]['assignmentgroup']?>">
	    </div>
	</div>
         <div class="clear space_20"></div>
        <div>
            <table id="table-example" class="table1" width="100%" cellpadding="2">
                    <thead>
                            <tr>
                                    <th>Min</th>
                                    <th>Max</th>
                                    <th>Promo Value</th>
                                   
                            </tr>
                    </thead>
                    <tbody>
			<?php
			if(!empty($this->promotion_data))
			{
				foreach($this->promotion_data as $value)
				{?>
				
				 <tr class="gradeX">
                                    <td align="center"><?php echo $value['rangelow'];?></td>
                                    <td align="center"><?php echo $value['rangehigh'];?></td>
                                    <td align="center"><?php echo number_format($value['promotionamount'],$this->decimalplaces);?></td>
                                    
				</tr>	
				<?php
				}
				
			}
			
			?>
                           
                           
                            
                    </tbody>
            </table>
            
        </div>
        
	<div class="_100 space_20">&nbsp;</div>
    </div>
	
</form>

</div>
</div> <!-- End of .box -->
<script type="text/javascript">
$(window).load(function()
{
	
    parent.eval('$(".pp_close").attr("href","<?php echo $url; ?>")');
	
});
</script>