<?php
/**
* @name       index.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');

?>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/salesorder/order_clear_data.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/salesorder/order_function.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/salesorder/order_detail1.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/salesorder/order_detail2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/salesorder/order_detail3.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/salesorder/order_detail5.js"></script>

<script type="text/javascript">
//message alret
var please_wait_msg ="<h1 class='blockui_css'><?php echo $this->translate->_('Please Wait ...');?></h1>";
var load_price_value ="<h1 class='blockui_css'><?php echo $this->translate->_('Loading Price ...');?></h1>";

//url
var Overview_URL = base_url+"/hhctransaction/cloudtran/salesorder/";
var ajax_page_URL = base_url+"/hhctransaction/orderajaxdata/";
var save_page_URL = base_url+"/hhctransaction/ordertransactionsave/";

var salesorder_item_grid =base_url+"/hhctransaction/ordertransaction/invoicedetail";
var salesorder_promotion_grid =base_url+"/hhctransaction/ordertransaction/promotionplan";


$(document).ready(function() {
	$(".tab_content").hide();
	$("#tab1").show();
	//$("ul.tabs li").click(function() {
	//    var disable = $(this).find("a").attr("disable");
	//    if(disable != 0)
	//    {
	//	$("ul.tabs li a").removeClass("admin_active"); //Remove any "active" class
	//	$(this).find("a").addClass("admin_active");
	//	$(".tab_content").hide(); //Hide all tab content
	//	var activeTab = $(this).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
	//	$(activeTab).fadeIn(); //Fade in the active content
	//	return false;
	//	
	//    }
	//    
	//});
	//$.blockUI({ message: please_wait_msg });
	$(document).ajaxStop($.unblockUI);
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_customer_addcustomer">

<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
	<h3><?php echo $this->translate->_('Sales Order');?></h3>
    </div>
   
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul>
	    	<li>
		    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"cloudtran","action"=>"salesorder"),"default", true);?>"><?php echo $this->translate->_('Overview');?></a>
		</li>
	    </ul>
	    <ul style="display: block; margin-left:75px;" class="tabs">
		<li> 
		    <a href="#tab1" id="t1" class="admin_active tablink"><?php echo $this->translate->_('Detail 1');?></a> |
		</li>
		<li>
		    <a href="#tab2" id="t2" class="tablink"  disable='1'><?php echo $this->translate->_('Detail 2');?></a> |
		</li>
		<li>
		    <a href="#tab3" id="t3" class="tablink"  disable='1'><?php echo $this->translate->_('Detail 3');?></a> |
		</li>
		<li >
		    <a href="#tab4" id="t4" class="tablink"  disable='1'><?php echo $this->translate->_('Detail 4');?></a> |
		</li>
                <li class="last-child">
		    <a href="#tab5" id="t5" class="tablink"  disable='1'><?php echo $this->translate->_('Detail 5');?></a>
		</li>
		
	    </ul>
	</li>
    </ul>
</div>
</div>

    <div class="content with-actions  min_height_10">
	<div id="tab1" class="tab_content">
	    <?php include('detail1.phtml');?>
	</div>
	<div id="tab2" class="tab_content">
	    <?php include('detail2.phtml');?>
	</div>
	<div id="tab3" class="tab_content">
	    <?php include('detail3.phtml');?>
	</div>
	<div id="tab4" class="tab_content">
	    <?php include('detail4.phtml');?>
	</div>
        <div id="tab5" class="tab_content">
	    <?php include('detail5.phtml');?>
	</div>
       
    </div>
    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">

</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
		$( "#txt_date" ).datepicker({
			dateFormat: 'dd-mm-yy'
		});
		$( "#txt_delivery_date1" ).datepicker({	    
			dateFormat: 'dd-mm-yy',
				changeYear:true,
				yearRange: '-10:+15'
		});
    });
     $('.sigPad').signaturePad({drawOnly:true});
   
});
function clear_sig()
{
	$('.sigPad').signaturePad({drawOnly:true}).clearCanvas();
	return false;
}
</script>