<?php
/**
* @name       addpricingplan.phtml
* @since      1 feb, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<script type="text/javascript">
$(document).ready(function(){
    
    $('#ddlcountry_chzn .chzn-drop .chzn-search input[type="text"]').focus();
    $('#ddlcountry_chzn').addClass('chzn-container-active');
    
    loaddata('<?php echo $this->itemgrid; ?>','item-grid');
    
    $("#sbtnadd").click(function(){
	    if($('#frmdetsec').valid())
	    {
		var values = $('#frmdetsec').serialize();
		$.ajax({
		    type : "POST",
		    url : base_url+"/promotions/advancepricing/pricingplanitemgrid/key/<?php echo $this->params["id"]; ?>",
		    data :values+'&add=yes',
		    success:function(returndata){
		       $('#item-grid').html(returndata);
			clearForm();
			
		    }
		});
	    }
	});
})

    var item_data =  <?php echo json_encode($this->item_info); ?>
		
    function getiteminfo(item_id)
    {
	$("#txtuni_per_case").val('');
	$("#txtstd_case_price1").val('');
	$("#txtstd_case_return_price").val('');
	
	if(item_id > 0 ){
	    $("#txtuni_per_case").val(item_data[item_id]['unitspercase']);
	    $("#txtstd_case_price1").val(item_data[item_id]['caseprice']);
	    $("#txtstd_case_return_price").val(item_data[item_id]['returncaseprice']);
	    $("#txtstd_pcs_price").val(item_data[item_id]['defaultsalesprice']);
	    $("#txtstd_pcs_return").val(item_data[item_id]['defaultgoodreturnprice']);
	}
    }
	
    function clearForm()
    {
	$("#ddlitem_code").val("");
	$('#txtuni_per_case').val('');
	$('#txtstd_pcs_price').val('');
	$('#txtstd_pcs_return').val('');
	$('#txtstd_case_price1').val('');
	$('#txtstd_case_return_price').val('');
	$('#txtsales_price').val('');
	$('#txtstd_case_price').val('');
	$('#txtreturn_price').val('');
	$('#txtcase_return_price').val('');
	$('select').trigger('liszt:updated');
    }
    
</script>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="promotion_advance_addpricingplan">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
    <div class="header">
	<div class="_50_3 back_btn">
	    <img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png">
	    <h3><?php echo $this->translate->_('Pricing Plan');?></h3>
	</div>
	<div class="_50_3">
	    <div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"promotions","controller"=>"advancepricing","action"=>"pricingplan"), "default", true);?>')" >
	    </div>
	    <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
	</div>
    </div>
    <div class="clear"></div>
    <div class="clear"></div>
    <div id="nav_sub" class="ie_nav_sub">
    <div class="container_12">
	<ul id="nav_main">
	    <li class="current">
		<ul style="display: block;">
		   <li>
			<a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"advancepricing","action"=>"pricingplan"),"default", true);?>"><?php echo $this->translate->_('Overview'); ?></a>
		    </li>
		    <li class="last-child">
			<a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"advancepricing","action"=>"addpricingplan"),"default", true);?>"><b><?php echo $this->translate->_('Details'); ?></b></a>
		    </li>
		</ul>
	    </li>
	</ul>
    </div>
    </div>
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Plan Key').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" value="<?php echo $this->formdata['txtplan_key'];?>" name="txtplan_key" id="txtplan_key"/>
	    </div>
	    <label class="_25_1 margin_top_12 label_text_align">
		 <?php echo $this->translate->_('Country').''.$this->required;?>
	    </label>
	    <div class="_25_1">
		 <select id="ddlcountry" name="ddlcountry" class="required">
		    <option value="">--- Select ---</option>
		    <?php for($i=0;$i<count($this->country_info);$i++) { ?>
			<option <?php echo $this->country_info[$i]['id'] == $this->formdata['ddlcountry'] ? 'selected' : '';  ?> value="<?php echo $this->country_info[$i]['id']?>"><?php echo $this->country_info[$i]['val']?></option>
		    <?php } ?>
		</select>
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Description')."".$this->required;?>
	    </label>
	    <div class="_25_1">
		<input type="text"  maxlength="50" value="<?php echo $this->formdata['txtdesc'];?>" name="txtdesc" id="txtdesc" class="required">
	    </div>
	    <label class="_25_1 margin_top_12 label_text_align">
		 <?php echo $this->translate->_('Type').''.$this->required;?>
	    </label>
	    <div class="_25_1">
		 <select id="ddltype" name="ddltype" class="required">
		   <?php for($i=0;$i<count($this->filter_data);$i++) { ?>
			<option <?php echo $this->filter_data[$i]['id'] == $this->formdata['ddltype'] ? 'selected' : '';  ?> value="<?php echo $this->filter_data[$i]['id']?>"><?php echo $this->filter_data[$i]['val']?></option>
			<?php } ?>
		</select>
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text"  maxlength="50" value="<?php echo $this->formdata['txtdesc_arb'];?>" name="txtdesc_arb" class="arb_text_align" id="txtdesc_arb"/>
	    </div>
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Status').''.$this->colan;?>
	    </label>
	    <div class="_25_1">		
		<select id="chkstatus" name="chkstatus">
		    <option value="1" <?php echo ($this->formdata['chkstatus']=='1')?'selected':''; ?> ><?php echo $this->translate->_('Active');?></option>
		    <option value="0" <?php echo ($this->formdata['chkstatus']=='0')?'selected':''; ?> ><?php echo $this->translate->_('Inactive');?></option>
		</select>
	    </div>
	</div>
    </div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>" />
</form>
<div class="content with-actions min_height_10">
    <?php if($this->params["id"] > 0) { ?>
    <form id="frmdetsec" name="frmdetsec" class="validate" novalidate action="" method="post">
	<div class="_100 margin_top_25">
	     <fieldset id="a" name="a"  class="fieldset_effect">
		<legend class="ttl"><?php echo $this->translate->_('Details');?></legend>
		<hr id="ie_hr" >
		<div class="_100">
		    <label class="_20_2 margin_top_12 label_text_align">
			 <?php echo $this->translate->_('Item Code').''.$this->required;?>
		    </label>
		    <div class="_20_2">
			<select id="ddlitem_code" name="ddlitem_code" onchange="getiteminfo(this.value)" class="required">
			    <option value="">--- Select ---</option>
			    <?php for($i=0;$i<count($this->item_master_data);$i++) { ?>
			    <option value="<?php echo $this->item_master_data[$i]['id'];?>"><?php echo $this->item_master_data[$i]['val'];?></option>
			    <?php } ?>
			</select>
		    </div>
		    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Units Per Case').''.$this->colan;?>
		    </label>
		    <div class="_10_1 margin_right_1">
			<input type="text" value="" name="txtuni_per_case" readonly="readonly" id="txtuni_per_case">
		    </div>
		    <div class="_15">&nbsp;</div>
		</div>
		<div class="_100">		    
		    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Price Case').''.$this->colan;?>
		    </label>
		    <div class="_20_2">
			<input type="text" value="" class="margin_top_5" readonly="readonly" name="txtstd_case_price1" id="txtstd_case_price1">
		    </div>
		    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Price PCS').''.$this->colan;?>
		    </label>
		    <div class="_20_2">
			<input type="text" value="" readonly="readonly" maxlength="25" class="number amount_text_align" name="txtstd_pcs_price" id="txtstd_pcs_price">
		    </div>		    
			
		</div>
		<div class="_100">
		    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Return Price Case').''.$this->colan;?>
		    </label>
		    <div class="_20_2">
			<input type="text" value="" readonly="readonly" class="number margin_top_5 amount_text_align"  name="txtstd_case_return_price" id="txtstd_case_return_price">
		    </div>
		    <label class="_20_2 margin_top_12 label_text_align">
			 <?php echo $this->translate->_('Return Price PCS').''.$this->colan;?>
		    </label>
		    <div class="_20_2">
			    <input type="text" value=""  maxlength="25" class="number margin_top_5 amount_text_align"   name="txtstd_pcs_return" readonly="readonly" id="txtstd_pcs_return">
		    </div>		    
		</div>
		<div class="_100">
		    <label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('New Price Case').''.$this->colan;?>
		    </label>
		    <div class="_20_2">
			<input type="text" value=""  maxlength="25" class="number amount_text_align margin_top_5"  name="txtstd_case_price" id="txtstd_case_price">
		    </div>
		    <label class="_20_2 margin_top_15 label_text_align">
			<?php echo $this->translate->_('New Price PCS').''.$this->colan;?>
		    </label>
		    <div class="_20_2">
			<input type="text" value=""  name="txtsales_price"  maxlength="25" class="number margin_top_5 amount_text_align" id="txtsales_price">
		    </div>
		</div>
		<div class="_100">
		    <label class="_20_2 margin_top_10 label_text_align">
			<?php echo $this->translate->_('New Return Price Case').''.$this->colan;?>
		    </label>
		    <div class="_20_2">
			<input type="text" value="" maxlength="25" class="number margin_top_5 amount_text_align margin_top_5"  name="txtcase_return_price" id="txtcase_return_price">
		    </div>		    
		    <label class="_20_2 margin_top_15 label_text_align">
			<?php echo $this->translate->_('New Return Price PCS').''.$this->colan;?>
		    </label>
		    <div class="_20_2">
			<input type="text" value=""  name="txtreturn_price"  maxlength="25" class="number margin_top_5 amount_text_align"  id="txtreturn_price">
		    </div>		    
		</div>
		<div class="_100" style="text-align:center;" >
		    <div class="_40">&nbsp;</div>
		    <div class="_15">
			<input type="button" value="<?php echo $this->translate->_('ADD');?>" id="sbtnadd" name="sbtnadd">
		    </div>
		    <div class="_40">&nbsp;</div>
		</div>
		
		<div class="_100 margin_top_25">
		    <div id="loader"></div>
		    <div class="_100" id="item-grid"></div>
		</div>
	    </fieldset>
	</div>
    </form>
    <?php } ?>
</div>
</div> <!-- End of .box -->
</div>