<?php

    $this->translate 	= Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
    <input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png" class="margin_top_7">
		<h3><?php echo $this->translate->_('Pricing Plan');?></h3>
	    </div>
	    <div class="_50_3">
		<!--<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnexport" id="btnexport"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint"></div>-->
		<?php if($this->checkaccess("delete")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" name="btndelete" id="btndelete"></div><?php } ?>
		<?php if($this->checkaccess("update")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnedit" name="btnedit"></div><?php } ?>
		<?php if($this->checkaccess("insert")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnadd" name="btnadd" onclick="winloc('<?php echo $this->url(array("module"=>"promotions","controller"=>"advancepricing","action"=>"addpricingplan"), "default", true);?>')"></div><?php } ?>
	    </div>
        </div>
	<div class="clear"></div>
	<div class="clear"></div>
	<div class="_100">
	    <div class="_100 margin_bottom_10 margin_top_10">
		<div class="_30">&nbsp;</div>
		<label class="_20 label_text_align margin_top_10 advance_search_css"><?php echo $this->translate->_('Filter By').''.$this->colan;?></label>
		<div class="_20 margin_right_1">
		    <select id="ddlfilter" name="ddlfilter">			
			<?php for($i=0;$i<count($this->filter_data);$i++) { ?>
			<option <?php echo $this->filter_data[$i]['id'] == $this->formdata['ddlfilter'] ? 'selected' : '';  ?> value="<?php echo $this->filter_data[$i]['id']?>"><?php echo $this->filter_data[$i]['val']?></option>
			<?php } ?>
		    </select>
		</div>
		<div class="_5">&nbsp;</div>
		<div class="_30"><input type="submit" id="btn_filter" name="btn_filter"  class="margin_top_7" value="<?php echo $this->translate->_('SEARCH');?>" ></div>
	    </div>
	    <div class="_100">
		<?php echo $this->partial('datagrid.phtml', $this); ?>
	    </div>
	</div>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>