<?php
/**
* @name       addsalesmanmsgs.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Salesman Message
*/
    $this->translate = Zend_Registry::get('Zend_Translate');

?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_index_addsalesmanmsgs">
<form class="validate" method="post" action="" novalidate="novalidate">
    <div class="header">
	<div class="_50_3 back_btn">
	    <img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	    <h3><?php echo $this->translate->_('Salesman Message');?></h3>
	</div>
	<div class="_50_3">
	    <div class="_10 save_btn">
		    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"salesman","action"=>"salesmanmsgs"),"default", true);?>')">
	    </div>
	    <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
	</div>
    </div>
    <div id="nav_sub" class="ie_nav_sub">
    <div class="container_12">
	<ul id="nav_main">
	    <li class="current">
		<ul style="display: block;">
		    <li>
			<a href="<?php echo $this->url(array("module"=>"account","controller"=>"salesman","action"=>"salesmanmsgs"),"default", true);?>"><?php echo $this->overview?></a>
		    </li>
		    <li class="last-child">
			<a href="<?php echo $this->url(array("module"=>"account","controller"=>"salesman","action"=>"addsalesmanmsgs"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		    </li>
		</ul>
	    </li>
	</ul>
    </div>
    </div>
    <div class="content with-actions" style="min-height:550px;">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Code').''.$this->required;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtcode" id="txtcode" type="text" class="required " readonly="readonly" value="<?php echo $this->formdata['messagekey'];?>">
	    </div>
	</div>
	<div class="_100">
	    <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Alternate Code').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtaltcode" id="txtaltcode"  maxlength="50" type="text" value="<?php echo $this->formdata['alternatecode']; ?>" class="margin_top_5" >
	    </div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Message Description').''.$this->required;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtmsg_desc" id="txtmsg_desc" maxlength="50"  type="text" class="required margin_top_5" value="<?php echo $this->formdata['messagedescription'];?>">
	    </div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Message Line1').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtmesg1" id="txtmesg1"  maxlength="40"  type="text" value="<?php echo $this->formdata['message1'];?>" class="margin_top_5" >
	    </div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Message Line2').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtmesg2" id="txtmesg2"  maxlength="40"  type="text" value="<?php echo $this->formdata['message2'];?>" class="margin_top_5" >
	    </div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Message Line3').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtmesg3" id="txtmesg3"   maxlength="40" type="text" value="<?php echo $this->formdata['message3'];?>"  class="margin_top_5" >
	    </div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Message Line4').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtmesg4" id="txtmesg4" maxlength="40"   type="text" value="<?php echo $this->formdata['message4'];?>"  class="margin_top_5" >
	    </div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Message Line1 ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtmesg_arb1" id="txtmesg_arb1"  maxlength="40" class="arb_text_align margin_top_5" type="text" value="<?php echo $this->formdata['arbmessageline1'];?>">
	    </div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Message Line2 ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtmesg_arb2" id="txtmesg_arb2" maxlength="40"  class="arb_text_align margin_top_5" type="text" value="<?php echo $this->formdata['arbmessageline2'];?>">
	    </div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Message Line3 ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtmesg_arb3" id="txtmesg_arb3" maxlength="40"  class="arb_text_align margin_top_5" type="text" value="<?php echo $this->formdata['arbmessageline3'];?>">
	    </div>
	</div>
	<div class="_100 ">
	     <label class="_36 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Message Line4 ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtmesg_arb4" maxlength="40"  id="txtmesg_arb4" class="arb_text_align margin_top_5" type="text" value="<?php echo $this->formdata['arbmessageline4'];?>">
	    </div>
	</div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Status').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlstatus" name="ddlstatus">
		    <option <?php if($this->formdata['activestatus'] == '1') {echo 'selected';} ;?> value="1" ><?php echo $this->translate->_('Active');?></option>
		    <option <?php if($this->formdata['activestatus'] == '0') {echo 'selected';} ;?> value="0" ><?php echo $this->translate->_('Inactive');?></option>
		</select>
            </div>
        </div>
	<?php if($this->params["edit"]=="yes") { ?>
	<div class="_100">
            <label class="_36 margin_top_10 label_text_align">
                <?php echo $this->translate->_('Created Date').''.$this->colan;?>
            </label>
            <div class="_50 margin_top_12 margin_right_1 date_color"><?php echo $this->formdata['createddate'];?></div>
        </div>
	<?php } ?>
    </div>
    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
    <input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>">
</form>
</div>
</div> <!-- End of .box -->