<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({
   	url:base_url+"/reports/discountsummary/discountsummarydata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Transaction Date');?>','<?php echo $this->translate->_('Transaction Time');?>','<?php echo $this->translate->_('Invoice Number');?>','<?php echo $this->translate->_( 'Customer Code');?>','<?php echo $this->translate->_('Customer Name');?>','<?php echo $this->translate->_('Sales Amount');?>','<?php echo $this->translate->_('Good Ret. Amount');?>','<?php echo $this->translate->_('Bad Ret.Amount');?>',/*'<?php echo $this->translate->_('Expiry Ret.Amount');?>',*/'<?php echo $this->translate->_('Free Amount');?>','<?php echo $this->translate->_('Invoice Amount');?>','<?php echo $this->translate->_('Discount Amount');?>','<?php echo $this->translate->_('Net Amount');?>'],
   	colModel:[
		{name:'transactiondate',index:'transactiondate', width:100},
        {name:'transactiontime',index:'transactiontime', width:70},
   		{name:'invoicenumber',index:'invoicenumber', width:90,align:'right'},
        {name:'customercode',index:'customercode', width:90,align:'right'},
        {name:'customername',index:'customername', width:250},
		{name:'salesamount',index:'salesamount', width:70,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'},
        {name:'goodreturnamount',index:'goodreturnamount', width:70,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'},
        {name:'totaldamagedamount',index:'totaldamagedamount', width:70,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'},
       /* {name:'totalexpiryamount',index:'totalexpiryamount', width:70,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'},*/
		{name:'freeamount',index:'freeamount', width:70,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'},
        {name:'invoiceamount',index:'invoiceamount', width:70,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'},
		{name:'discountamount',index:'discountamount', width:70,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'},
        {name:'netamount',index:'netamount', width:70,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'}
	],
    <?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
   	pager: '#pagersr',
   	sortname: 'transactiondate',
	viewrecords:true,
	sortorder: "asc",
    footerrow : true,
	userDataOnFooter : true,
   	altRows : false,
    grouping:true,
    groupingView :
    {
        groupField : ['transactiondate'],
        groupColumnShow : [false],
        groupCollapse : true,
        groupOrder: ['asc'],
        groupSummary : [true]
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});

</script>