<?php
/**
* @name       addarea.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Area Description
*/

$this->translate 	= Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="organization_index_area">
<form class="validate" method="post" action="" novalidate="novalidate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_org.png">
	<h3><?php echo $this->translate->_('Area');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"area"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li>
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"area"),"default", true);?>"><?php echo $this->overview;?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"addarea"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Code').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtcode" id="txtcode" type="text" class="margin_top_5 required text_align" readonly="readonly" value="<?php echo $this->formdata['txtcode'];?>" >
            </div>
        </div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Alternate Code').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtaltcode" id="txtaltcode" maxlength="50" class="margin_top_5"  type="text" value="<?php echo $this->formdata['txtaltcode'];?>" >
            </div>
        </div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Name').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtname" id="txtname"  maxlength="30" type="text" class="margin_top_5 text_align required" value="<?php echo $this->formdata['txtname'];?>" >
            </div>
        </div>
	<div class="_100 ">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Name ('.$this->sec_lang.')').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtname_arb" id="txtname_arb"  maxlength="30" class="margin_top_5 arb_text_align" type="text" value="<?php echo $this->formdata['txtname_arb'];?>" >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Branch/Depot').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlbrnch_depot" name="ddlbrnch_depot" class="required">
		<option value="">--- Select ---</option>
		    <?php
		    for($i=0;$i<count($this->branch);$i++)
		    {
		?>
			<option value="<?php echo $this->branch[$i]['id']; ?>" <?php echo $this->branch[$i]['id'] == $this->formdata['ddlbrnch_depot'] ? 'selected' : '';?>><?php echo $this->branch[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Area Manager').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlarea_mngr" name="ddlarea_mngr" class="required">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->area);$i++)
		    {
		?>
			<option value="<?php echo $this->area[$i]['id']; ?>" <?php echo $this->area[$i]['id'] == $this->formdata['ddlarea_mngr'] ? 'selected="selected"' : '';?>><?php echo $this->area[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Status').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlstatus" name="ddlstatus">
		    <option <?php echo $this->formdata['ddlstatus'] == '1' ? 'selected' : ''; ?> value="1"><?php echo $this->translate->_('Active');?></option>
		    <option <?php echo $this->formdata['ddlstatus'] == '0' ? 'selected' : ''; ?> value="0"><?php echo $this->translate->_('Inactive');?></option>
		</select>
            </div>
        </div>
	<?php if($this->params["edit"]=="yes") { ?>
	<div class="_100">
	   <label class="_36 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Created Date').''.$this->colan;?>
	    </label>	   
	    <div class="_50 margin_top_12 date_color margin_right_1"><?php echo $this->formdata['createddate']; ?></div>
	</div>
	<?php } ?>

	<div class="_100">&nbsp;</div>
	<div class="_100">&nbsp;</div>
	<div class="_100">&nbsp;</div>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>">
</form>
</div>
</div> <!-- End of .box -->