<?php
/**
* @name       addbranch.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add branch Details
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="organization_index_branch">
<form class="validate" method="post" action="" novalidate="novalidate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_org.png">
	<h3><?php echo $this->translate->_('Branch/Depot');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"branch"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li>
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"branch"),"default", true);?>"><?php echo $this->overview;?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"addbranch"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
             <label class="_30_1 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Code').''.$this->required;?>
            </label>
           <div class="_50 margin_right_1">
                <input name="txtcode" id="txtcode" type="text" class="required" readonly="readonly" value="<?php echo $this->formdata['txtcode']; ?>">
            </div>
	    <div class="_15">
		<div class="_5">&nbsp;</div>
		<div class="_20 margin_top_7">
		    <input name="chkcentral_wh" id="chkcentral_wh" type="checkbox" value="1" <?php if($this->formdata['chkcentral_wh'] ==1) { echo 'checked';}?> >
		</div>
		<div class="margin_top_17">
		    <?php echo $this->translate->_('Central WH');?>
		</div>
            </div>
        </div>
        <div class="_100">
             <label class="_30_1 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Alternate Code').''.$this->colan;?>
            </label>
           <div class="_50 margin_right_1">
                <input name="txtaltcode"  maxlength="50" class="margin_top_5" id="txtaltcode" type="text" value="<?php echo $this->formdata['txtaltcode']; ?>">
            </div>
        </div>
        <div class="_100">
             <label class="_30_1 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Branch/Depot Prefix').''.$this->colan;?>
            </label>
           <div class="_50 margin_right_1">
                <input name="txtbrnch_prefix"  maxlength="11"  id="txtbrnch_prefix" type="text" class="margin_top_5 number" value="<?php echo $this->formdata['txtbrnch_prefix']; ?>">
            </div>
        </div>
	<div class="_100">
             <label class="_30_1 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Branch/Depot Name').''.$this->required;?>
            </label>
           <div class="_50 margin_right_1">
                <input name="txtbrnch_name"  maxlength="50" id="txtbrnch_name" type="text" class="margin_top_5 required" value="<?php echo $this->formdata['txtbrnch_name']; ?>">
            </div>
        </div>
	<div class="_100 ">
             <label class="_30_1 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Branch/Depot Name ('.$this->sec_lang.')').''.$this->colan;?>
            </label>
           <div class="_50 margin_right_1">
                <input name="txtarbbrnch_name"  maxlength="50" id="txtarbbrnch_name" type="text" class="margin_top_5 arb_text_align" value="<?php echo $this->formdata['txtarbbrnch_name']; ?>">
            </div>
        </div>
	<div class="_100">
             <label class="_30_1 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Branch/Depot Manager').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlbrnch_mng" name="ddlbrnch_mng" class="required">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->branch_mng);$i++)
		    {
		?>
			<option <?php if($this->branch_mng[$i]['id'] == $this->formdata['ddlbrnch_mng']) {echo 'selected';}?> value="<?php echo $this->branch_mng[$i]['id'];?>"><?php echo $this->branch_mng[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
        </div>
	<div class="_100">
             <label class="_30_1 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Company').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlcompany" name="ddlcompany" class="required">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->company_data);$i++)
		    {
		?>
			<option <?php if($this->company_data[$i]['id'] == $this->formdata['ddlcompany']) {echo 'selected';}?> value="<?php echo $this->company_data[$i]['id'];?>"><?php echo $this->company_data[$i]['val'];?></option>
		<?php } ?>
		</select>
	    </div>
        </div>
	<div class="_100">
             <label class="_30_1 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Region').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlregion" name="ddlregion" class="required">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->region_data);$i++)
		    {
		?>
			<option <?php if($this->region_data[$i]['id'] == $this->formdata['ddlregion']) {echo 'selected';}?> value="<?php echo $this->region_data[$i]['id'];?>"><?php echo $this->region_data[$i]['val'];?></option>
		<?php } ?>
		</select>
	    </div>
	</div>
	<div class="_100">
             <label class="_30_1 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Price Key').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlprice_key" name="ddlprice_key">
		    <option value="">--- Select ---</option>
		    <?php
		    for($i=0;$i<count($this->pricekey_data);$i++)
		    {
		?>
			<option <?php if($this->pricekey_data[$i]['id'] == $this->formdata['ddlprice_key']) {echo 'selected';}?> value="<?php echo $this->pricekey_data[$i]['id'];?>"><?php echo $this->pricekey_data[$i]['val'];?></option>
		<?php } ?>
		</select>
	    </div>
	</div>
	<div class="_100">
             <label class="_30_1 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Status').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlstatus" name="ddlstatus">
		    <option <?php echo $this->formdata['ddlstatus'] == '1' ? 'selected' : ''; ?> value="1"><?php echo $this->translate->_('Active');?></option>
		    <option <?php echo $this->formdata['ddlstatus'] == '0' ? 'selected' : ''; ?> value="0"><?php echo $this->translate->_('Inactive');?></option>
		</select>
	    </div>
	</div>
	<?php if($this->params["edit"]=="yes") { ?>
	<div class="_100">
	   <label class="_30_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Created Date').''.$this->colan;?>
	    </label>	   
	    <div class="_50 margin_top_12 date_color margin_right_1"><?php echo $this->formdata['createddate']; ?></div>
	</div>
	<?php } ?>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>">
</form>
</div>
</div> <!-- End of .box -->