<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Country Details
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="organization_index_country">
<form class="validate" method="post" action="" novalidate="novalidate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_org.png">
	<h3><?php echo $this->translate->_('Country');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"country"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
    <div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li>
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"country"),"default", true);?>"><?php echo $this->overview;?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"addcountry"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Country  Code').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtcode" id="txtcode" type="text" class="required" readonly="readonly"  value="<?php echo $this->formdata['txtcode'];?>" >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Alternate Code').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtaltcode" id="txtaltcode" class="margin_top_5" maxlength="50" type="text" value="<?php echo $this->formdata['txtaltcode'];?>" >
            </div>
        </div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Country  Name').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtcntname" id="txtcntname" type="text" class="margin_top_5 required" value="<?php echo $this->formdata['txtcntname'];?>" >
            </div>
        </div>
        <div class="_100 ">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Country Name ('.$this->sec_lang.')').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtarbcntname" id="txtarbcntname"  maxlength="50" type="text" class="margin_top_5 arb_text_align" value="<?php echo $this->formdata['txtarbcntname'];?>" >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Currency Name').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlcurrency" name="ddlcurrency" class="required">
		<option value="">--- Select ---</option>
		    <?php
		    for($i=0;$i<count($this->currency_data);$i++)
		    {
		?>
			<option <?php echo ($this->formdata['ddlcurrency'] ==  $this->currency_data[$i]['id']) ? 'selected' : ''; ?> value="<?php echo $this->currency_data[$i]['id'];?>"><?php echo $this->currency_data[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Company').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlcompany" name="ddlcompany" class="required">
		<option value="">--- Select ---</option>
		    <?php
		    for($i=0;$i<count($this->company_data);$i++)
		    {
		?>
			<option <?php echo ($this->formdata['ddlcompany'] ==  $this->company_data[$i]['id']) ? 'selected' : ''; ?> value="<?php echo $this->company_data[$i]['id'];?>"><?php echo $this->company_data[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('National Sales Manager').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlsales_mng" name="ddlsales_mng" class="required">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->sales_mng_data);$i++)
		    {
		?>
			<option <?php echo ($this->formdata['ddlsales_mng'] ==  $this->sales_mng_data[$i]['id']) ? 'selected' : ''; ?> value="<?php echo $this->sales_mng_data[$i]['id'];?>"><?php echo $this->sales_mng_data[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Price Change Variance').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input type="text" class="margin_top_5 number amount_text_align"  maxlength="18" id="txtprice_chng" name="txtprice_chng" value="<?php echo $this->formdata['txtprice_chng'];?>"  >
            </div>
        </div>
	<?php if($this->params["edit"]=="yes") { ?>
	<div class="_100">
	    <label class="_36 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Created Date').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_top_10 date_color margin_right_1"><?php echo $this->formdata['createddate']; ?></div>
	</div>
	<?php } ?>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>">
</form>
</div>
</div> <!-- End of .box -->