<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Country Details
*/

$this->translate = Zend_Registry::get('Zend_Translate');

?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="organization_index_region" >
<form class="validate" method="post" action="" novalidate="novalidate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_org.png">
	<h3><?php echo $this->translate->_('Region');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"region"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li>
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"region"),"default", true);?>"><?php echo $this->overview;?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"addregion"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
    <div class="_100">
	<div class="clean"></div>
    </div>
    <div class="_100">
	 <label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Region Code').''.$this->required;?>
	</label>
	<div class="_50 margin_right_1">
	    <input name="txtcode" id="txtcode" type="text" class="required" readonly="readonly" value="<?php echo $this->formdata['txtcode']; ?>">
	</div>
    </div>
    <div class="_100">
	 <label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Alternate Code').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input name="txtaltcode" id="txtaltcode" type="text" class="margin_top_5"  maxlength="50" value="<?php echo $this->formdata['txtaltcode']; ?>">
	</div>
    </div>
    <div class="_100">
	 <label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Region  Name').''.$this->required;?>
	</label>
	<div class="_50 margin_right_1">
	    <input name="txtregname" id="txtregname" maxlength="50" type="text" class="margin_top_5 required" value="<?php echo $this->formdata['txtregname']; ?>">
	</div>
    </div>
    <div class="_100 ">
	 <label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Region Name ('.$this->sec_lang.')').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input name="txtarbregname" id="txtarbregname" maxlength="50" type="text" class="margin_top_5 arb_text_align" value="<?php echo $this->formdata['txtarbregname']; ?>">
	</div>
    </div>
    <div class="_100">
	 <label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Country').''.$this->required;?>
	</label>
	<div class="_50 margin_right_1">
	    <select id="ddlcountry" name="ddlcountry" class="required">
	    <option value="">--- Select ---</option>
		<?php
		for($i=0;$i<count($this->country_data);$i++)
		{
	    ?>
		    <option value="<?php echo $this->country_data[$i]['id'];?>" <?php if($this->country_data[$i]['id'] == $this->formdata['ddlcountry']) { echo 'selected'; } ?> ><?php echo $this->country_data[$i]['val'];?></option>
	    <?php } ?>
	    </select>
	</div>
    </div>
    <div class="_100">
	 <label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Region Manager').''.$this->required;?>
	</label>
	<div class="_50 margin_right_1">
	    <select id="ddlreg_mng" name="ddlreg_mng" class="required">
	    <option value="">--- Select ---</option>
	    <?php
		for($i=0;$i<count($this->region_mng);$i++)
		{
	    ?>
		    <option value="<?php echo $this->region_mng[$i]['id'];?>" <?php if($this->region_mng[$i]['id'] == $this->formdata['ddlreg_mng']) { echo 'selected'; } ?> ><?php echo $this->region_mng[$i]['val'];?></option>
	    <?php } ?>
	    </select>
	</div>
    </div>
    <?php if($this->params["edit"]=="yes") { ?>
    <div class="_100">
	<label class="_36 margin_top_10 label_text_align">
		<?php echo $this->translate->_('Created Date').''.$this->colan;?>
	</label>
	<div class="_50 margin_top_10 date_color margin_right_1"><?php echo $this->formdata['createddate']; ?></div>
    </div>
    <?php } ?>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>">
</form>
</div>
</div> <!-- End of .box -->