<?php
/**
* @name       addsubarea.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Sub area.
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="organization_index_subarea">
<form class="validate" method="post" action="" novalidate="novalidate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_org.png">
	<h3><?php echo $this->translate->_('Sub Area');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"subarea"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li>
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"subarea"),"default", true);?>"><?php echo $this->overview;?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"addsubarea"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Code').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtcode" id="txtcode" type="text" class="required" readonly="readonly" value="<?php echo $this->formdata['txtcode'];?>" >
            </div>
        </div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Alternate Code').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtaltcode" id="txtaltcode" class="margin_top_5" maxlength="50"  type="text" value="<?php echo $this->formdata['txtaltcode'];?>" >
            </div>
        </div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Name').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtname" id="txtname" maxlength="50"  type="text" class="margin_top_5 required" value="<?php echo $this->formdata['txtname'];?>" >
            </div>
        </div>
	<div class="_100 ">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Name ('.$this->sec_lang.')').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtname_arb" id="txtname_arb" maxlength="50"  class="margin_top_5 arb_text_align" type="text" value="<?php echo $this->formdata['txtname_arb'];?>" >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Area').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlarea" name="ddlarea" class="required">
		<option value="">--- Select ---</option>
		    <?php
		    for($i=0;$i<count($this->area);$i++)
		    {
		?>
			<option <?php echo $this->area[$i]['id'] == $this->formdata['ddlarea'] ? 'selected' : ''; ?>  value="<?php echo $this->area[$i]['id'];?>"><?php echo $this->area[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Supervisor').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlsupervisor" name="ddlsupervisor" class="required">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->super);$i++)
		    {
		?>
			<option <?php echo $this->super[$i]['id'] == $this->formdata['ddlsupervisor'] ? 'selected' : ''; ?> value="<?php echo $this->super[$i]['id'];?>"><?php echo $this->super[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Status').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlstatus" name="ddlstatus">
		    <option <?php echo '1' == $this->formdata['ddlstatus'] ? 'selected' : ''; ?> value="1"><?php echo $this->translate->_('Active');?></option>
		    <option <?php echo '0' == $this->formdata['ddlstatus'] ? 'selected' : ''; ?> value="0"><?php echo $this->translate->_('Inactive');?></option>
		</select>
            </div>
        </div>
	<?php if($this->params["edit"]=="yes") { ?>
	<div class="_100">
	    <label class="_36 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Created Date').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_top_10 date_color margin_right_1"><?php echo $this->formdata['createddate']; ?></div>
	</div>
	<?php } ?>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</form>
</div>
</div> <!-- End of .box -->