<?php
/**
* @name       addvan.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add van Details
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="organization_index_van">
<form class="validate" method="post" action="" novalidate="novalidate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_org.png">
	<h3><?php echo $this->translate->_('Van');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"van"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li>
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"van"),"default", true);?>"><?php echo $this->overview;?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"index","action"=>"addvan"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Van Code').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtcode" id="txtcode" type="text" class="required" readonly="readonly" value="<?php echo $this->formdata['txtcode'];?>" >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Alternate Code').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtaltcode" id="txtaltcode"  class="margin_top_5" maxlength="50" type="text" value="<?php echo $this->formdata['txtaltcode'];?>" >
            </div>
        </div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Van Reg. No').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtvanregno" id="txtvanregno"  maxlength="50" type="text" class="margin_top_5 required" value="<?php echo $this->formdata['txtvanregno'];?>" >
            </div>
        </div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Van Brand/Model').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtvanmodel" id="txtvanmodel"  maxlength="50" type="text" class="margin_top_5 text_align" value="<?php echo $this->formdata['txtvanmodel'];?>" >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Van Type').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtvantype" id="txtvantype" type="text"   maxlength="50" value="<?php echo $this->formdata['txtvantype'];?>" >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Van Description').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtvandesc" id="txtvandesc" type="text"  maxlength="50" class="required"  value="<?php echo $this->formdata['txtvandesc'];?>" >
            </div>
        </div>
	<div class="_100 ">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Van Description ('.$this->sec_lang.')').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtarbvandesc" id="txtarbvandesc" type="text"  maxlength="50" class="arb_text_align" value="<?php echo $this->formdata['txtarbvandesc'];?>" >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Status').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlstatus" name="ddlstatus">
		    <option <?php echo $this->formdata['ddlstatus'] == '1' ? 'selected' : ''; ?> value="1"><?php echo $this->translate->_('Active');?></option>
		    <option <?php echo $this->formdata['ddlstatus'] == '0' ? 'selected' : ''; ?> value="0"><?php echo $this->translate->_('Inactive');?></option>
		</select>
            </div>
        </div>
	<?php if($this->params["edit"]=="yes") { ?>
	<div class="_100">
	   <label class="_36 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Created Date').''.$this->colan;?>
	    </label>	   
	    <div class="_50 margin_top_12 date_color margin_right_1"><?php echo $this->formdata['createddate']; ?></div>
	</div>
	<?php } ?>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>">
</form>
</div>
</div> <!-- End of .box -->