<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Expenses
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="basic_reason_expensesreason">
<form method="post" action="" class="validate">
<div class="header">
    <div class="_50_3 back_btn">
       <img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_basics.png">
        <h3><?php echo $this->translate->_('Expenses'); ?></h3>
    </div>
    <div class="_50_3">
        <div class="_10 save_btn">
            <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"basic","controller"=>"reasons","action"=>"expensereason"), "default", true);?>')" >
        </div>
        <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
<ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"basic","controller"=>"reasons","action"=>"expensereason"), "default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"basic","controller"=>"reasons","action"=>"addexpensereason"), "default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
    <div class="content no-padding with-actions">
        <div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
            <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Code').''.$this->required;?>
            </label>
             <div class="_50 margin_right_1">
                <input name="txtcode" id="txtcode" type="text" class="required " value="<?php echo $this->formdata['txtcode']; ?>" >
            </div>
        </div>
		<div class="_100">
            <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Alternate Code').''.$this->colan;?>
            </label>
             <div class="_50 margin_right_1">
                <input name="txtaltcode" id="txtaltcode"  maxlength="50"  type="text" value="<?php echo $this->formdata['txtaltcode'];?>" >
            </div>
        </div>
        <div class="_100">
            <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Description').''.$this->required;?>
            </label>
             <div class="_50 margin_right_1">
                <input name="txtdesc" id="txtdesc" type="text"  maxlength="20"  class="required " value="<?php echo $this->formdata['txtdesc']; ?>">
            </div>
        </div>
        <div class="_100">
            <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtdesc_arb" id="txtdesc_arb" type="text"  maxlength="20"  class="required arb_text_align" value="<?php echo $this->formdata['txtdesc_arb']; ?>"/>
            </div>
        </div>
		<?php if($this->params["edit"]=="yes") { ?>
		<div class="_100">
			<label class="_36 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Created Date').''.$this->colan;?>
			</label>
			<div class="_50 margin_top_12 date_color margin_right_1"><?php echo $this->formdata['createddate']; ?></div>
		</div>
		<?php } ?>
    </div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</form>
</div> <!-- End of .box -->
</div>