<?php
/**
* @name       activenonactive.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<script>
$(document).ready(function() {
    
    
    
    <?php if(count($this->nonactiveitems) > 0) { ?>
	$('#ddlnonactiveitem').dblclick(function() {
	    
	    var val = this.value;	
	    $("#ddlnonactiveitem option[value='"+val+"']").remove();	
	    $("#ddlactiveitem option[value='"+val+"']").show();	
	});
    <?php } ?>
    
    $("#ddlactiveitem").dblclick(function() {	
		$("#lblddlnonactiveitem").hide();
    });
    
    $("#btnsave").click(function() {
	
		if($("#frmdet").valid())
		{	    
			var i 	= 0;
			var str 	= '';
			$("#ddlnonactiveitem option").each(function()
			{
			str += $(this).val()+',';
			i++;
			});
			
			$("#hdnselecteditem").val(str);
			$("#hdncount_items").val(i);
		}
    });
	 $('#btnloaddata').click(function()
	{
	    if($("#frmdet").valid())
        {
			var itemgrp	= $('#ddlitemgrp').val();
            $('#ddlactiveitem').html('');
            $('#ddlnonactiveitem').html('');
            
            var  url = base_url+"/links/route/getitemfromitemgrp/itemgrp/"+itemgrp;
            var result;
            $.ajax({
                url:url,
                data:$("#frmdet").serialize(),
                type:'post',
                success:function(data) {
                    
                    var item_list = JSON.parse(data);
					
                    if (item_list == '')
                    {
                        return false;
                    }
                    
                    // Below foe loop for the selected customer are stored in array for checking with all route customer.
                    if(typeof(item_list[2]) == 'object') {
                        var arr = new Array();
                        for (i=0;i<item_list[2].length;i++) {
                            arr[i] = item_list[2][i]['actualitemcode'];
                        }
                    }
                    
                    // For Select customer
                    var select_item = item_list[0];
                    
                    for (i=0;i<select_item.length;i++) {
                    
                        if(typeof(item_list[2]) == 'object'){
                            if($.inArray(select_item[i]['id'],arr) != '-1')
                            {
                                $('<option class="movedElement1" selected="selected" style="display: none;"/>').val(select_item[i]['id']).html(select_item[i]['val']).appendTo('#ddlactiveitem');
                            }
                            else
                            {
                                $('<option/>').val(select_item[i]['id']).html(select_item[i]['val']).appendTo('#ddlactiveitem');
                            }
                        }
                        else
                        {
                            $('<option />').val(select_item[i]['id']).html(select_item[i]['val']).appendTo('#ddlactiveitem');			    
                        }
                    }
                    
                    // For Selected customer		    
                    if(typeof(item_list[1]) == 'object')
                    {
                        var selected_item = item_list[1];		    
                        for (i=0;i<selected_item.length;i++) {
                           $('<option class="movedElement1" selected="selected" />').val(selected_item[i]['id']).html(selected_item[i]['val']).appendTo('#ddlnonactiveitem');
                        }
                    }
                    
                    $('#ddlactiveitem').transfer({
						to:'#ddlnonactiveitem',//selector of second multiple select box
						dblClick:true,//true or false, activates double click transfer
						addId:'#btn_move_item',//add buttong id
						addAllId:'#btn_move_item_all', // add all button id
						removeId:'#btn_remove_item', // remove button id
						removeAllId:'#btn_remove_item_all',// remove all button id
						tClass:'movedElement1'//class to be added when option tranfered to another select.
					});
                }
            })
        }
    })
})
</script>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="links_route_activenonactive">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_links.png">
        <h3><?php echo $this->translate->_('Active/ In Active Items')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"links","controller"=>"route","action"=>"activenonactive"), "default", true);?>')" >
	</div>
    <?php if($this->checkaccess("update")) { ?>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    <?php } ?>
    </div>
</div>
<div class="clear"></div>
<div class="clear"></div>


<div class="content with-actions min_height_10">
	<div class="_100">
		<div class="_45 left">
			<div class="_100">
				<label class="_30 margin_top_12 label_text_align">
					<?php echo $this->translate->_('Item Group').''.$this->required;?>
				</label>
				<div class="_50_1 margin_right_4">
					<select id="ddlitemgrp" name="ddlitemgrp" class="required">
					<option value="">--- Select ---</option>
					<option value="0">--- ALL ---</option>
					<?php
						for($i=0;$i<count($this->itemgroup_info);$i++)
						{
					?>
						<option value="<?php echo $this->itemgroup_info[$i]['id'];?>"><?php echo $this->itemgroup_info[$i]['val'];?></option>
					<?php } ?>
					</select>
				</div>
			</div>
		</div>
		<div class="_8">&nbsp;</div>
		<div class="_45 left">
			<input type="button" id="btnloaddata" name="btnloaddata" value="<?php echo $this->translate->_('LOAD DATA');?>" class="right" >
		</div>
	</div>	
    <div class="space_20 clear">&nbsp;</div>
    <div class="_100">	 
	<div class="_45 left">
	    <div style="width:85px;clear:both">
		<?php echo $this->translate->_('Active Item').''.$this->colan;?>
	    </div>
	    <div class="simple_dropdown margin_top_10">
		<select id="ddlactiveitem" name="ddlactiveitem" multiple="multiple" size="15" style="height:200px">		    
		</select>
	    </div>
	</div>
	<div class="left">&nbsp;&nbsp;</div>
	<div class="left navigation_button">
	   <input type="button" name="btn_move_item" id="btn_move_item" value="<?php echo $this->translate->_('moveone'); ?>"  class="margin_top_50" >
                <input type="button" name="btn_move_item_all" id="btn_move_item_all" value="<?php echo $this->translate->_('moveall'); ?>" class="navigation_button margin_top_15" >
                <input type="button" name="btn_remove_item" id="btn_remove_item" value="<?php echo $this->translate->_('removeone'); ?>" class="navigation_button margin_top_15" >
                <input type="button" name="btn_remove_item_all" id="btn_remove_item_all" value="<?php echo $this->translate->_('removeall'); ?>" class="navigation_button margin_top_15" >
	</div>
	<div class="_45 left">
	    <div style="width:115px;clear:both">
		<?php echo $this->translate->_('Non Active Item').''.$this->colan;?>
	    </div>		
	    <div class="simple_dropdown  margin_top_10">
		<select id="ddlnonactiveitem" name="ddlnonactiveitem[]" multiple="multiple" size="15" style="height:200px">		    
		</select>		    
	    </div>
	</div>
    </div>
    <div class="space_300">&nbsp;</div>
</div>
<input type="hidden" id="hdncount_items" name="hdncount_items" value="" />
<input type="hidden" id="hdnselecteditem" name="hdnselecteditem" value="" />
</form>
</div> <!-- End of .box -->
</div>