<?php
/**
* @name       routeitemlink.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<script>
$(document).ready(function() {

    $('#ddlrouteitem_chzn .chzn-drop .chzn-search input[type="text"]').focus();
    $('#ddlrouteitem_chzn').addClass('chzn-container-active');
       
    $('#ddlfillby').change(function() {
        var width1 = $('#ddlfillby_chzn').css('width');
        var width2 = $('#ddlfillby_chzn .chzn-drop').css('width');
        var width3 = $('#ddlfillby_chzn [type=text]').css('width');
        var fillby = $('#ddlfillby').val();
        if(fillby == 1)
        {
            $('#divdepot').hide();
            $('#divarea').hide();
            $('#divregion').show();
            $('#ddlregion_chzn').css('width',width1);
            $('#ddlregion_chzn .chzn-drop').css('width',width2);
            $('#ddlregion_chzn [type=text]').css('width',width3);
        }
        else if(fillby == 2)
        {
            $('#divregion').hide();
            $('#divarea').hide();
            $('#divdepot').show();
            $('#ddldepot_chzn').css('width',width1);
            $('#ddldepot_chzn .chzn-drop').css('width',width2);
            $('#ddldepot_chzn [type=text]').css('width',width3);
        }
        else if(fillby == 3)
        {
            $('#divregion').hide();
            $('#divdepot').hide();
            $('#divarea').show();
            $('#ddlarea_chzn').css('width',width1);
            $('#ddlarea_chzn .chzn-drop').css('width',width2);
            $('#ddlarea_chzn [type=text]').css('width',width3);
        }	
        $('#ddldepot').val('');
        $('#ddlregion').val('');
        $('#ddlarea').val('');	
        $('select').trigger('liszt:updated');
    });
    
    $('#ddlselectedroute').dblclick(function() {
	
        var val = this.value;	
        $("#ddlselectedroute option[value='"+val+"']").remove();	
        $("#ddlroute option[value='"+val+"']").show();	
    });
    
    
    $("#btnsave").click(function() {
	
        if($("#frmdet").valid())
        {
            var fillby 	    = $('#ddlfillby').val();
            
            if(fillby == '1' && $('#ddlregion').val() =='')
            {
                jAlert('Please Select Region.');
                return false;
            }
            else if(fillby == '2' && $('#ddldepot').val() =='')
            {
                jAlert('Please Select Depot.');
                return false;
            }
            else if(fillby == '3' && $('#ddlarea').val() =='')
            {
                jAlert('Please Select Area.');
                return false;
            }
            
            var i 	= 0;
            var str 	= '';
            $("#ddlselectedroute option").each(function()
            {
            str += $(this).val()+',';
            i++;
            });
            
            $("#hdnselectedroute").val(str);
            $("#hdncount_route").val(i);
        }
    });
    
    $('#btnloaddata').click(function() {
	
        var routeitmgrp	= $('#ddlrouteitem').val();	
        var fillby 	    = $('#ddlfillby').val();
        var fillby_val	= '';
        
        if(fillby == '1')
            fillby_val	= $('#ddlregion').val();
        else if(fillby == '2')
            fillby_val 	= $('#ddldepot').val();
        else if(fillby == '3')
            fillby_val 	= $('#ddlarea').val();	
	
        if($("#frmdet").valid())
        {
            $('#hdnfillbyval').val(fillby_val);
            $('#ddlroute').html('');
            $('#ddlselectedroute').html('');
            
            var  url = base_url+"/links/route/getroutefromcriteria/routeitmgrp/"+routeitmgrp+"/fillby/"+fillby+"/val/"+fillby_val;
            var result;
            $.ajax({
                url:url,
                data:$("#frmdet").serialize(),
                type:'post',		
                success:function(data) {
                    
                    var route_list = JSON.parse(data);
                    if (route_list == '')
                    {
                        return false;
                    }
                    
                    // Below foe loop for the selected customer are stored in array for checking with all route customer.
                    if(typeof(route_list[2]) == 'object') {
                        var arr = new Array();
                        for (i=0;i<route_list[2].length;i++) {
                            arr[i] = route_list[2][i]['routecode'];
                        }
                    }
                    
                    // For Select customer
                    var select_route = route_list[0];
                    
                    for (i=0;i<select_route.length;i++) {
                    
                        if(typeof(route_list[2]) == 'object'){
                            if($.inArray(select_route[i]['id'],arr) != '-1')
                            {
                                $('<option class="movedElement1" selected="selected" style="display: none;"/>').val(select_route[i]['id']).html(select_route[i]['val']).appendTo('#ddlroute');
                            }
                            else
                            {
                                $('<option/>').val(select_route[i]['id']).html(select_route[i]['val']).appendTo('#ddlroute');
                            }
                        }
                        else
                        {
                            $('<option />').val(select_route[i]['id']).html(select_route[i]['val']).appendTo('#ddlroute');			    
                        }
                    }
                    
                    // For Selected customer		    
                    if(typeof(route_list[1]) == 'object')
                    {
                        var selected_route = route_list[1];		    
                        for (i=0;i<selected_route.length;i++) {
                           $('<option class="movedElement1" selected="selected" />').val(selected_route[i]['id']).html(selected_route[i]['val']).appendTo('#ddlselectedroute');
                        }
                    }
                    
                    $('#ddlroute').transfer({
                        to:'#ddlselectedroute',		//selector of second multiple select box
                        dblClick:true,				//true or false, activates double click transfer
                        addId:'#btn_move_cust',			//add buttong id
                        addAllId:'#btn_move_cust_all', 		// add all button id
                        removeId:'#btn_remove_cust', 		// remove button id
                        removeAllId:'#btn_remove_cust_all',	// remove all button id
                        tClass:'movedElement1'			//class to be added when option tranfered to another select.
                    });
                }
            })
        }
    })
})
</script>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="links_route_routeitemlink">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_links.png">
        <h3><?php echo $this->translate->_('Route Item Group')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"links","controller"=>"route","action"=>"routeitemlink"), "default", true);?>')" >
	</div>
    <?php if($this->checkaccess("update")) { ?>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    <?php } ?>
    </div>
</div>
<div class="clear"></div>
<div class="clear"></div>


<div class="content with-actions min_height_10">
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<label class="_20 margin_left_right_0 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Route Item Group').''.$this->required;?>
	</label>
	<div class="_25 margin_right_1">
	    <select id="ddlrouteitem" name="ddlrouteitem" class="required">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->routeitem_info);$i++)
		    {
		?>
			<option value="<?php echo $this->routeitem_info[$i]['id'];?>"><?php echo $this->routeitem_info[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
	<label class="_20_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Fill By').''.$this->colan;?>
	</label>
	<div class="_25 margin_right_1">
	    <select id="ddlfillby" name="ddlfillby">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->fill_by);$i++)
		    {
		?>
			<option <?php if($this->fill_by[$i]['id'] == '3' ) { echo 'selected';}?> value="<?php echo $this->fill_by[$i]['id'];?>"><?php echo $this->fill_by[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>

    </div>
    <div class="_100" id="divregion" style="display:none">
        <div class="_45">&nbsp;</div>
        <div class="_10">&nbsp;</div>
        <label class="_5_2 margin_left_right_0 margin_top_12 label_text_align">
            <?php echo $this->translate->_('Region').''.$this->colan;?>
        </label>
        <div class="_25 margin_right_1">
            <select id="ddlregion" name="ddlregion" class="">
                <option value="">--- Select ---</option>
                <option value="0">--- ALL ---</option>
                <?php
                    for($i=0;$i<count($this->region_info);$i++)
                    {
                ?>
                    <option value="<?php echo $this->region_info[$i]['id'];?>"><?php echo $this->region_info[$i]['val'];?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="_100" id="divdepot"  style="display:none">
        <div class="_45">&nbsp;</div>
        <div class="_10">&nbsp;</div>
        <label class="_5_2 margin_left_right_0 margin_top_12 label_text_align">
            <?php echo $this->translate->_('Depot').''.$this->colan;?>
        </label>
        <div class="_25 margin_right_1">
            <select id="ddldepot" name="ddldepot" class="">
                <option value="">--- Select ---</option>
                <option value="0">--- ALL ---</option>
                <?php
                    for($i=0;$i<count($this->depot_info);$i++)
                    {
                ?>
                    <option value="<?php echo $this->depot_info[$i]['id'];?>"><?php echo $this->depot_info[$i]['val'];?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="_100" id="divarea">
        <div class="_45">&nbsp;</div>
        <div class="_10">&nbsp;</div>
        <label class="_5_2 margin_left_right_0 margin_top_12 label_text_align">
            <?php echo $this->translate->_('Area').''.$this->colan;?>
        </label>
        <div class="_25 margin_right_1">
            <select id="ddlarea" name="ddlarea" class="">
            <option value="">--- Select ---</option>
            <option value="0">--- ALL ---</option>
            <?php
                for($i=0;$i<count($this->area_info);$i++)
                {
            ?>
                <option value="<?php echo $this->area_info[$i]['id'];?>"><?php echo $this->area_info[$i]['val'];?></option>
            <?php } ?>
            </select>
        </div>
    </div>    
    <div class="space_20 clear">&nbsp;</div>
	<div class="_100">
		<div class="_30_1">&nbsp;</div>
		<div class="_70">
			<input type="button" id="btnloaddata" name="btnloaddata" value="<?php echo $this->translate->_('LOAD DATA');?>" class="right" >
		</div>		
    </div>
    <div class="space_20 clear">&nbsp;</div>
    <div class="_100">	 
	    <div class="_45 left">
		<div style="width:55px;clear:both">
		    <?php echo $this->translate->_('Route').''.$this->colan;?>
		</div>
		<div class="simple_dropdown margin_top_10">
		    <select id="ddlroute" name="ddlroute" multiple="multiple" size="15" style="height:200px">
		    </select>
		</div>
	    </div>
	    <div class="left">&nbsp;&nbsp;</div>
	    <div class="left navigation_button">
	       <input type="button" name="btn_move_cust" id="btn_move_cust" value="<?php echo $this->translate->_('moveone'); ?>" class="margin_top_50" >
	       <input type="button" name="btn_move_cust_all" id="btn_move_cust_all" value="<?php echo $this->translate->_('moveall'); ?>" class="navigation_button margin_top_15" >
	       <input type="button" name="btn_remove_cust" id="btn_remove_cust" value="<?php echo $this->translate->_('removeone'); ?>" class="navigation_button margin_top_15" >
	       <input type="button" name="btn_remove_cust_all" id="btn_remove_cust_all" value="<?php echo $this->translate->_('removeall'); ?>" class="navigation_button margin_top_15" >
	    </div>
	    <div class="_45 left">		
		<div style="width:115px;clear:both;">
		    <?php echo $this->translate->_('Selected Route').''.$this->colan;?>
		</div>
		<div class="simple_dropdown  margin_top_10">
		    <select id="ddlselectedroute" name="ddlselectedroute[]" multiple="multiple" size="15" style="height:200px">
		    </select>		    
		</div>
	    </div>
    </div>
    <div class="space_300">&nbsp;</div>

</div>
<input type="hidden" id="hdncount_route" name="hdncount_route" value="" />
<input type="hidden" id="hdnselectedroute" name="hdnselectedroute" value="" />
<input type="hidden" id="hdnfillbyval" name="hdnfillbyval" value="" />
</form>
</div> <!-- End of .box -->
</div>