<?php
/**
* @name       addcompanygroup.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Comopany Group
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
	$('#ddlroute').change(function(){
	
		var routeid = $('#ddlroute').val();
		$('#enddate').html('');
		if(routeid > 0){			
			
			var  url = base_url+'/hhctransaction/routestartday/getrouteenddate/routeid/'+routeid;
			$.ajax({
				url:url,
				data:$("#frmdet").serialize(),
				type:'post',		
				success:function(data) {
					$('#enddate').html(data);
					$('#div_enddate').show();
				}
			});
		}
	})
});
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="inventory_index_addcompanygroup">
<form class="validate" method="post" action="" novalidate="novalidate">      
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
	<h3><?php echo $this->translate->_('Route Start Of Day');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"routestartday","action"=>"routestartday"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li>
		    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"routestartday","action"=>"routestartday"),"default", true);?>"><?php echo $this->overview;?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"routestartday","action"=>"addroute"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
            <div class="_100">
                <div class="clean"></div>
            </div>
            <div class="_100">
                <label class="_36 margin_top_12 label_text_align">
                    <?php echo $this->translate->_('Route').''.$this->required;?>
                </label>
                <div class="_50 margin_right_1">
                    <select id="ddlroute" name="ddlroute" class="required" >
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->route);$i++)
			{
		    ?>
			    <option  value="<?php echo $this->route[$i]['id'];?>"><?php echo $this->route[$i]['val'];?></option>
		    <?php } ?>
		</select>
                </div>
            </div>
	    <div class="_100">
                <label class="_36 margin_top_12 label_text_align">
                    <?php echo $this->translate->_('Salesman').''.$this->colan;?>
                </label>
                <div class="_50 margin_right_1">
                    <input name="txt_salesman" id="txt_salesman" maxlength="50" type="text" value="" class="margin_top_5" >
                </div>
            </div>
            <div class="_100">
                <label class="_36 margin_top_12 label_text_align">
                    <?php echo $this->translate->_('Route Start Date').''.$this->required;?>
                </label>
                <div class="_50 margin_right_1">
                    <input name="txtdate" id="txtdate" maxlength="50" type="text" class="required margin_top_5"  readonly="readonly"  value="<?php echo date('d-m-Y');?>">
                </div>
            </div>
			<div class="_100">
                <label class="_36 margin_top_12 label_text_align">
                    <?php echo $this->translate->_('Route Start Time').''.$this->colan;;?>
                </label>
                <div class="_50 margin_right_1 margin_top_12">
					<?php echo date('h:i:s');?>                   
                </div>
            </div>
			<div class="_100" id="div_enddate" style="display:none">
                <label class="_36 margin_top_12 label_text_align">
                    <?php echo $this->translate->_('Previous Route End Date').''.$this->colan;;?>
                </label>
                <div class="_50 margin_right_1 margin_top_12" id="enddate">
                </div>
            </div>
            
	    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
	    <input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>">
        </form>      
      </div>
</div>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({	    
		dateFormat: 'dd-mm-yy',
            changeYear:true,
            yearRange: '-10:+15'
	});
    });
    $("#ddlroute").change(function() {
         var str = $(this).find("option:selected").text();
	var substr = str.split(' -- ');
	$("#txt_salesman").attr("value",substr[1]);
        
    });
});

</script>