<?php
/**
* @name       index.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add items detail
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style type="text/css">

.admin_active{
 font-weight:bold;   
}
</style>

<script type="text/javascript">

$(document).ready(function() {
	$(".tab_content").hide();
	$("#tab1").show();
	    $("ul.tabs li").click(function() {
	    $("ul.tabs li a").removeClass("admin_active"); //Remove any "active" class
	    $(this).find("a").addClass("admin_active");
	    $(".tab_content").hide(); //Hide all tab content
	    var activeTab = $(this).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
	    $(activeTab).fadeIn(); //Fade in the active content
	    return false;
	});
		
	$('.tablink').click(function()
	{
		if(this.id == 't1')
		{
			$("#txtaltcode").focus();
		}
		else if(this.id == 't2')
		{
			$("#txtprnt_seq_cust").focus();				
		}		
	});
	$("#txtaltcode").focus();
	
	// calculation for  Sales Cost PCS Price and Sales Cost Price.
	var cost_price 		= '<?php echo $this->enable_cost_price; ?>';
	var parcent 		= '<?php echo $this->cost_price_percent; ?>';
	var decimal_places 	= '<?php echo $this->decimalplaces; ?>';
	
	$('#txtsalespcprice').change(function(){		
		
		var salespcprice = $('#txtsalespcprice').val();
			salespcprice = salespcprice.replace(/\,/g,'');
		
		
		if(parcent > 0) {			
			var val1 = salespcprice - ((salespcprice * parcent)/100);
			
			$('#txtsalescostpcsprice').val('');
			$('#txtsalescostpcsprice').val(addCommas(val1,decimal_places));
			$('#hdntxtsalescostpcsprice').val(val1);
			$('#txtsalescostpcsprice').attr('readonly',true);
		}
	})
	$('#txtsalescaseprice').change(function() {
		
		var salescaseprice = $('#txtsalescaseprice').val();
			salescaseprice = salescaseprice.replace(/\,/g,'');
		
		if(parcent > 0)
		{
			var val1 = salescaseprice - ((salescaseprice * parcent)/100);
			
			$('#txtsalespcsprice').val('');
			$('#hdntxtsalespcsprice').val(val1);
			$('#txtsalespcsprice').val(addCommas(val1,decimal_places));
			$('#txtsalespcsprice').attr('readonly',true);
		}
	})
	
	$('#btnsave').click(function(){
		if(parcent == 0) {			
			$('#hdntxtsalescostpcsprice').val($('#txtsalescostpcsprice').val());
			$('#hdntxtsalespcsprice').val($('#txtsalespcsprice').val());
		}
		var flag = 0;
		$( ".gtab" ).each(function() {
			if(this.value != '') {
				flag = 1;
			}
		});
		if(!$("#frmdetail").valid()) {
			
		}
	});
	
	if(parcent > 0) {
		$('#txtsalespcsprice').attr('readonly',false);
		$('#txtsalescostpcsprice').attr('readonly',false);
	} else {
		$('#txtsalespcsprice').attr('readonly',true);
		$('#txtsalescostpcsprice').attr('readonly',true);
	}
});

</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="chk_margin_0">
<form id="frmdetail" name="frmdetail" class="validate" novalidate action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_inventory_mag.png">
	<h3><?php echo $this->translate->_('Items');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"inventory","controller"=>"index","action"=>"items"),"default", true);?>')"></div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
	<ul id="nav_main">	 
	<li class="current">
		<ul>
			<li>
				<a href="<?php echo $this->url(array("module"=>"inventory","controller"=>"index","action"=>"items"),"default", true);?>"><?php echo $this->overview;?></a>
			</li>
		 </ul>
	     <ul style="display: block;  margin-left:75px;" class="tabs">
			<li> 
				<a href="#tab1" id="general_tab" class="admin_active tablink"><?php echo $this->translate->_('General');?></a>
			</li>
			<li>
				<a href="#tab2" id="setting1_tab" class="tablink"><?php echo $this->translate->_('Setting 1');?></a>
			</li>
			<li>
				<a href="#tab3" d="barcode_tab" class="tablink"><?php echo $this->translate->_('BarCode');?></a>
			</li>
		</ul>
	</li>
    </ul>
    
</div>
</div>

    <div class="content with-actions">
		<div id="tab1" class="tab_content">
			<?php include('general.phtml');?>
		</div>
		<div id="tab2" class="tab_content">
			<?php include('itemset1.phtml');?>
		</div>
		<div id="tab3" class="tab_content">
			<?php include('additionalitembarcode.phtml');?>
		</div>		
    </div>

<input type="hidden" id="hdntxtsalescostpcsprice" name="hdntxtsalescostpcsprice" value="<?php echo $this->formdata['txtsalescostpcsprice']; ?>">
<input type="hidden" id="hdntxtsalespcsprice" name="hdntxtsalespcsprice" value="<?php echo $this->formdata['txtsalespcsprice']; ?>">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes" ? $this->params["id"] : 0; ?>">
</form>
</div> <!-- End of .box -->
</div>