<?php
/**
* @name       index.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add items detail
*/
$this->translate = Zend_Registry::get('Zend_Translate');
$Settings_NameSpace = new Zend_Session_Namespace('Settings');
?>

<div id="inventory_index_additems">
    <div class="content with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<fieldset>
	    <legend><?php echo $this->general?></legend>
	    <div class="_100 ">
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Code').''.$this->required;?>
		</label>
		<div class="_25">
		    <input type="text" class="required" id="txtcode" name="txtcode" value="<?php echo $this->formdata['txtcode']; ?>" readonly= "true"/>
		</div>
		<label class="_25_1 margin_top_12 label_text_align">
		   <?php echo $this->translate->_('Alternate Code').''.$this->required;?>
		</label>
		<div class="_25">
		    <input type="text" id="txtaltcode" name="txtaltcode" value="<?php echo $this->formdata['txtaltcode']; ?>" class="required gtab">
		</div>
	    </div>
	    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Item Group').''.$this->required;?>
		</label>
		<div class="_25 margin_right_1">
		   <select id="ddlitemgrp" name="ddlitemgrp" class="required gtab">
			<option value="">--- Select ---</option>
			<?php
			for($i=0;$i<count($this->itemgroup);$i++)
			{
			?>
			    <option value="<?php echo $this->itemgroup[$i]['id'];?>" <?php echo ($this->itemgroup[$i]['id'] ==  $this->formdata['ddlitemgrp'] )? 'selected': ''; ?>><?php echo $this->itemgroup[$i]['val'];?></option>
			<?php } ?>
		   </select>
		</div>
		<label class="_25_1 margin_top_12 label_text_align">
		   <?php echo $this->translate->_('Warehouse Stock').''.$this->colan;?>
		</label>
		<div class="_25">
		    <input maxlength="18"  type="text" id="txtwarehouse" name="txtwarehouse" value="<?php echo $this->formdata['txtwarehouse']; ?>" class="margin_top_5 number"
		</div>
	    </div>
	    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
		   <?php echo $this->translate->_('Item Name').''.$this->required;?>
		</label>
		<div class="_25">
		    <input maxlength="50"  type="text" id="txtitemname" name="txtitemname" value="<?php echo $this->formdata['txtitemname']; ?>" class="required gtab margin_top_5">
		</div>
		<label class="_25_1 margin_top_12 label_text_align">
		   <?php echo $this->translate->_('Units Per Case').''.$this->required;?>
		</label>
		<div class="_25">
		    <input maxlength="11" type="text" id="txtupc" name="txtupc" value="<?php echo $this->formdata['txtupc']; ?>" class="number margin_top_3 required gtab">
		</div>
	    </div>
	    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
		   <?php echo $this->translate->_('Description').''.$this->required;?>
		</label>
		<div class="_25">
		    <input maxlength="50" type="text" id="txtdescription" name="txtdescription" value="<?php echo $this->formdata['txtdescription']; ?>" class="margin_top_5 required gtab"/>
		</div>
		<label class="_25_1 margin_top_12 label_text_align">
		   <?php echo $this->translate->_('Case Qty').''.$this->colan;?>
		</label>
		<div class="_25">
		    <input maxlength="11" type="text" id="txtcaseqty" name="txtcaseqty" value="<?php echo $this->formdata['txtcaseqty']; ?>" class="margin_top_3 number">
		</div>		
	    </div>	    
	    <div class="_100">		
		<label class="_25_1 margin_top_12 label_text_align">
		   <?php echo $this->translate->_('Litre/Kg Per Pcs').''.$this->colan;?>
		</label>
		<div class="_25">
		    <input maxlength="11" type="text" id="txtltrprunit" name="txtltrprunit" value="<?php echo $this->formdata['txtltrprunit']; ?>" class="margin_top_5 number">
		</div>
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Litre/Kg Per Case').''.$this->colan;?>
		</label>
		<div class="_25">
		    <input maxlength="11" type="text" id="txtltrprcase" name="txtltrprcase" value="<?php echo $this->formdata['txtltrprcase']; ?>" class="margin_top_3 number">
		</div>		
	    </div>
	    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Std Sales Pcs Price').''.$this->colan;?>
		</label>
		<div class="_25">
		    <input maxlength="25" type="text" id="txtsalespcprice" name="txtsalespcprice" value="<?php echo $this->formdata['txtsalespcprice']; ?>" class="number margin_top_5 amount_text_align">
		</div>
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Std Sales Case Price').''.$this->colan;?>
		</label>
		<div class="_25">
		    <input maxlength="25" type="text" id="txtsalescaseprice" name="txtsalescaseprice" value="<?php echo  $this->formdata['txtsalescaseprice']; ?>" class="number margin_top_3 amount_text_align">
		</div>		
	    </div>
	    <div class="_100">		
		<label class="_25_1 margin_top_12 label_text_align">
		   <?php echo $this->translate->_('Std Good Return Pcs Price').''.$this->colan;?>
		</label>
		<div class="_25">
		    <input maxlength="25" type="text" id="txtstdgdretpcprice" name="txtstdgdretpcprice" value="<?php echo $this->formdata['txtstdgdretpcprice']; ?>" class="number margin_top_5 amount_text_align">
		</div>
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Std Good Return Pcs Price').''.$this->colan;?>
		</label>
		<div class="_25">
		    <input maxlength="25" type="text" id="txtstdgdretcaseprice" name="txtstdgdretcaseprice" value="<?php echo $this->formdata['txtstdgdretcaseprice']; ?>" class="number margin_top_3 amount_text_align" >
		</div>		
	    </div>
	    <div class="_100 ">
			<label class="_25_1 margin_top_12 label_text_align">
			   <?php echo $this->translate->_('Std Damage/Expiry Pcs Price').''.$this->colan;?>
			</label>
			<div class="_25">
				<input maxlength="25" type="text" id="txtstddmgpcprice" name="txtstddmgpcprice" value="<?php echo $this->formdata['txtstddmgpcprice']; ?>" class="number margin_top_5 amount_text_align">
			</div>
			<label class="_25_1 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Std Damage/Expiry Case Price').''.$this->colan;?>
			</label>
			<div class="_25">
				<input maxlength="25" type="text" id="txtstddmgcaseprice" name="txtstddmgcaseprice" value="<?php echo $this->formdata['txtstddmgcaseprice']; ?>" class="number margin_top_3 amount_text_align" >
			</div>
	    </div>
		<?php if($Settings_NameSpace->cpanel['Enable Cost Price']['status'] == 1) { ?>
		<div class="_100 ">
			<label class="_25_1 margin_top_12 label_text_align">
			   <?php echo $this->translate->_('Sales Cost PCS Price').''.$this->colan;?>
			</label>
			<div class="_25">
				<input maxlength="25" type="text" id="txtsalescostpcsprice" name="txtsalescostpcsprice" value="<?php echo $this->formdata['txtsalescostpcsprice']; ?>" class="number margin_top_5 amount_text_align">
			</div>
			<label class="_25_1 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Sales Cost Price').''.$this->colan;?>
			</label>
			<div class="_25">
				<input maxlength="25" type="text" id="txtsalespcsprice" name="txtsalespcsprice" value="<?php echo $this->formdata['txtsalespcsprice']; ?>" class="number margin_top_3 amount_text_align" >
			</div>
	    </div>
		<?php } ?>
	    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Status').''.$this->colan;?>
		</label>
		<div class="_25  margin_right_1">
		    <select id="ddlstatus" name="ddlstatus">
			<option value="1" <?php echo ($this->formdata['ddlstatus'] == '1') ? 'selected' : ''; ?> ><?php echo $this->translate->_('Active');?></option>
			<option value="0" <?php echo ($this->formdata['ddlstatus'] == '0') ? 'selected' : ''; ?> ><?php echo $this->translate->_('Inactive');?></option>
		    </select>
		</div>
		<div id="chk" class="_25_1 margin_top_10">
		    <input type="checkbox" name="chkshelfstock" id="chkshelfstock" value="1" <?php echo ($this->formdata['chkshelfstock'] == 1) ? 'checked' : 0; ?> >
		</div>
		<label class="_25 margin_top_17 margin_right_2_2">
		   <?php echo $this->translate->_('Capture Shelf Stock');?>
		</label>
	    </div>
	    <div class="_100">		
		<div id="chk" class="_25_1">
		    <input type="checkbox" name="chktcallowed" id="chktcallowed" value="1" <?php echo ($this->formdata['chktcallowed'] == 1) ? 'checked' : 0; ?> >
		</div>
		<label class="_25 margin_top_10 margin_right_2_2">
		    <?php echo $this->translate->_('TCAllowed');?>
		</label>
		<div id="chk" class="_25_1">
		    <input type="checkbox" name="chkinvopricechng" id="chkinvopricechng" value="1" <?php echo ($this->formdata['chkinvopricechng'] == 1) ? 'checked' : 0; ?> >
		</div>
		<label class="_25 margin_top_10 margin_right_2_2">
		    <?php echo $this->translate->_('Allow Invoice Price Change');?>
		</label>
	    </div>	    
	</fieldset>
	<fieldset>
	    <legend><?php echo $this->translate->_('2nd Language Settings').$this->colan;?></legend>
	    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Name ('.$this->sec_lang.')').''.$this->colan;?>
		</label>
		<div class="_25">
		    <input maxlength="50" type="text" id="txtnamearb" name="txtnamearb" class="arb_text_align" value="<?php echo $this->formdata['txtnamearb']; ?>" />
		</div>
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Short Name ('.$this->sec_lang.')').''.$this->colan;?>
		</label>
		<div class="_25">
		    <input maxlength="50" type="text" id="txtshortnamearb" name="txtshortnamearb" class="arb_text_align" value="<?php echo $this->formdata['txtshortnamearb']; ?>"/>
		</div>
	    </div>
	</fieldset>
    </div>
</div>

<?php
/* 
<label class="_25_1 margin_top_17 label_text_align">
    <?php echo $this->translate->_('Alphanumeric Code').''.$this->colan;?>
</label>
<div class="_25">
    <input type="text"  id="txtalphanum" name="txtalphanum" value="<?php echo $this->formdata['txtalphanum']; ?>">
</div>
*/
?>