<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({        
   	url:base_url+"/reports/returnsummary/returnsummarydata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Transaction Date');?>','<?php echo $this->translate->_('Route Code');?>','<?php echo $this->translate->_('Item Group');?>','<?php echo $this->translate->_( 'Item Code');?>','<?php echo $this->translate->_('Item Description');?>','<?php echo $this->translate->_('UPC');?>','<?php echo $this->translate->_('Damaged Qty.');?>','<?php echo $this->translate->_('Damaged Value');?>','<?php echo $this->translate->_('Expired Qty.');?>','<?php echo $this->translate->_('Expired Value');?>','<?php echo $this->translate->_('Other Damaged Qty.');?>','<?php echo $this->translate->_('Other Damaged Value');?>','<?php echo $this->translate->_('Total Damaged Qty.');?>','<?php echo $this->translate->_('Total Damaged Value');?>'],//,'<?php echo $this->translate->_('Return Price (Pcs)');?>','<?php echo $this->translate->_('Qty in PCS');?>','<?php echo $this->translate->_('Value');?>'],
   	colModel:[
		{name:'transactiondate',index:'transactiondate', width:120},
		{name:'routecode',index:'routecode', width:120},
        {name:'majorcategorycode',index:'majorcategorycode', width:100},		
        {name:'itemcode',index:'itemcode', width:100},
        {name:'itemdescription',index:'itemdescription', width:300},
		
		{name:'upc',index:'upc', width:40,align:'right', summaryType:'sum'},
		
		{name:'damagedqty',index:'damagedqty', width:80,align:'right', summaryType:'sum'},
        {name:'damagevalue',index:'damagevalue', width:80,align:'right', formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'},
		
		{name:'expiredqty',index:'expiredqty', width:70,align:'right', summaryType:'sum'},
        {name:'expvalue',index:'expvalue', width:80,align:'right', formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'},
		
		{name:'otherdamagedqty',index:'otherdamagedqty', width:90,align:'right', summaryType:'sum'},
        {name:'otherdamagevalue',index:'otherdamagevalue', width:120,align:'right', formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'},
		
		{name:'totaldamage',index:'totaldamage', width:90,align:'right', summaryType:'sum'},
        {name:'totaldamagevalue',index:'totaldamagevalue', width:120,align:'right', formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'}
		/*{name:'quantity',index:'quantity', width:90,align:'right', summaryType:'sum'},
        {name:'value',index:'value', width:120,align:'right', formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'}*/
	],
	<?php if($this->css == 'ar_') { ?>
		direction :"rtl",
	<?php } ?>	
    height: 'auto',
    width: 'auto',
    rowNum:eval(RP_NOOFRECORDSHOW),
    rowList:eval(RP_ROWLISTSHOW),
    pager: '#pagersr',
    sortname: 'routecode',
    viewrecords:true,
    sortorder: "asc",
    altRows : false,
    grouping:true,
    footerrow : true,
    userDataOnFooter : true,
	groupingView :
    {
        groupField : ['transactiondate','routecode','majorcategorycode'],
        groupColumnShow : [false,false,false],
        groupCollapse : true,
        groupOrder: ['asc','asc','asc'],
        groupSummary : [false,false,false]
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});
</script>