<?php $this->translate = Zend_Registry::get('Zend_Translate'); ?>
<table>
    <thead>
        <tr>
            <th width="60%"><a href="javascript:void(0)"><?php echo $this->translate->_('Image Description')?></a></th>
            <th width="30%"><a href="javascript:void(0)"><?php echo $this->translate->_('Image')?></a></th>
            <th width="10%">&nbsp;</th>
        </tr>
    </thead>
    <tbody>    
        <?php
        for($i=0;$i<count($this->formdata['txtimage']);$i++)
        {
            $css = $i%2 == 0 ? 'gradeC' : 'gradeA';
            ?>
            <tr class="<?php echo $css?>">
                <td><?php echo ($this->formdata['txtdesc'][$i]) ? $this->formdata['txtdesc'][$i] : ''; ?></td>
                <td><img src="<?php echo $this->formdata['txtimage'][$i]; ?>" alt="your image" width="120" height="80" /></td>
                <td><a id="<?php echo $this->formdata['txtid'][$i];?>" onclick="deleteadvertiseimg(this.id)">delete</a></td>
            </tr>
            <?php
        }
        ?>
    </tbody>
</table>