<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Cash Description
*/
$this->translate = Zend_Registry::get('Zend_Translate');
if($this->defkey > 0)
    $url	= $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"addsurvey","edit"=>"yes","id"=>$this->defkey,"addlookupindex"=>true,"oi"=>$this->oi,"sp"=>$this->sp,"st"=>$this->st,"lt"=>$this->lt,"li"=>$this->li,"spa"=>$this->spa,"status"=>$this->status), "default", true);
else
    $url	= $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"addsurvey","addlookupindex"=>true,"oi"=>$this->oi,"sp"=>$this->sp,"st"=>$this->st,"lt"=>$this->lt,"li"=>$this->li,"spa"=>$this->spa,"status"=>$this->status), "default", true);
    

if($this->params["trankey"] > 0)
    $action	= $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"addlookupindex","defkey"=>$this->defkey,"edit"=>"yes","trankey"=>$this->params["trankey"]), "default", true);
else
    $action	= $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"addlookupindex","defkey"=>$this->defkey,), "default", true);
?>
<script>
    $(document).ready(function() {
	
	$("#txtlk_desc").focus();
	
		$('#sbtnadd').click(function() {
		   
		   if($("#frmdetsec").valid())
			{
				var  url = base_url+'/merchandize/index/addlookupindexgrid/';
				$.ajax({
				url:url,
				data:$("#frmdetsec").serialize(),
				type:'post',
				beforeSend: function() {
					$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");
				},
				success:function(data){
					loaddata('<?php echo $this->itemgrid; ?>','item-grid');
					$("#loader").html("");
					
					$("#txtarbdesc").val("");
					$("#txtdesc").val("");
				}
				})
			}
		});
		
		loaddata('<?php echo $this->itemgrid; ?>','item-grid');
		
		$("#btncancel").click(function() {
			parent.eval('$.prettyPhoto.close()');
			parent.eval('winloc("<?php echo $url; ?>")');
			//parent.window.reload();
		});
    });    
</script>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="merchandize_index_addlookupindex">
<form id="frmfirstaaaa" name="frmfirstaaaa" class="validate" method="post" action="" novalidate="novalidate" >
	<input type="hidden" id="hdnid1" name="hdnid1" value="<?php echo $this->params["edit"]=="yes"?$this->params["trankey"]:0; ?>">
    <input type="hidden" id="defkey" name="defkey" value="<?php echo $this->defkey; ?>">
    <div class="header">
	<div class="_50_3 back_btn">
	    <img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_merchandizing.png">
	    <h3><?php echo $this->translate->_('Survey Lookup');?></h3>
	</div>
	<div class="_50_3">
	    <div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel">
	    </div>
	    <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
	</div>
    </div>    
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Lookup Index').''.$this->required;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtcode" id="txtcode"  readonly="readonly" type="text" class="required" value="<?php echo $this->formdata['transactionkey']?>"	/>
	    </div>
	</div>
	<div class="_100">
	     <label class="_36 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Lookup Description').''.$this->required;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtlk_desc" id="txtlk_desc" maxlength="50" type="text" class="required" value="<?php echo $this->formdata['description']?>" />
	    </div>
	</div>
	<div class="_100 margin_bottom_5">
	     <label class="_36 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Lookup Description ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_50 margin_right_1">
		<input name="txtarblk_desc" id="txtarblk_desc" maxlength="50" class="arb_text_align" type="text" value="<?php echo $this->formdata['arbdescription']?>" />
	    </div>
	</div>	
	<div class="_100 space_50">&nbsp;</div>
    </div>
	<div id="hdnids">
		<input type="hidden" id="hdnoi" name="hdnoi" value="<?php echo $this->oi; ?>">
		<input type="hidden" id="hdnsp" name="hdnsp" value="<?php echo $this->sp; ?>">
		<input type="hidden" id="hdnst" name="hdnst" value="<?php echo $this->st; ?>">
		<input type="hidden" id="hdnlt" name="hdnlt" value="<?php echo $this->lt; ?>">
		<input type="hidden" id="hdnli" name="hdnli" value="<?php echo $this->li; ?>">
		<input type="hidden" id="hdnspa" name="hdnspa" value="<?php echo $this->spa; ?>">
		<input type="hidden" id="hdnstatus" name="hdnstatus" value="<?php echo $this->status; ?>">
	</div>	
</form>
<?php if($this->params["edit"]=="yes") { ?>
<div class="content with-actions min_height_10">
    <form id="frmdetsec" name="frmdetsec" class="validate" novalidate action="" method="post">
	<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["trankey"]:0; ?>">
	<fieldset>
	    <legend><?php echo $this->translate->_('Lookup Index Detail')?></legend>
	    <div class="_100">
		 <label class="_36 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Description').''.$this->required;?>
		</label>
		<div class="_50 margin_right_1">
		    <input name="txtdesc" id="txtdesc" type="text" maxlength="50"  value="" class="required">
		</div>
	    </div>
	    <div class="_100 margin_bottom_5">
		<label class="_36 margin_top_15 label_text_align">
		    <?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
		</label>
		<div class="_50 margin_right_1">
		    <input name="txtarbdesc" id="txtarbdesc" type="text"  maxlength="50" value="" class="arb_text_align">
		</div>
	    </div>
	    <div class="_100 margin_bottom_5" align="center">		
		<div class="_5_button">
		    <input type="button" name="sbtnadd" id="sbtnadd" value="<?php echo $this->translate->_('ADD'); ?>">
		</div>
	    </div>
	</fieldset>		
    </form>
    <div class="_100">
	<div id="loader"></div>
     <div id="item-grid"> <!--grid load here --> </div>
    </div>
</div>
<?php } ?>
</div>
</div> <!-- End of .box -->
<script type="text/javascript">
$(window).load(function()
{
	
    parent.eval('$(".pp_close").attr("href","<?php echo $url; ?>")');
	//$(".pp_close").click(function() {
	//	parent.eval('$.prettyPhoto.close()');
	//	parent.eval('winloc("<?php echo $url; ?>")');
	//	//parent.window.reload();
	//});
});
</script>