<?php
/**
* @name       addcustcat.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Customer Category
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<script type="text/javascript">
        function readURL(input,id) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#'+id).attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_customer_custcat">
<form class="validate" method="post" action="" enctype="multipart/form-data" novalidate="novalidate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	<h3><?php echo $this->translate->_('Planogram');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"visuals"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"visuals"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"addvisual"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Code').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtcode" id="txtcode" readonly="readonly" type="text" class="required text_align" value="<?php echo $this->formdata['txtcode'];?>"  >
            </div>
        </div>
		
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Planogram Description').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtname" id="txtname" type="text"  maxlength="50" class="margin_top_5 required" value="<?php echo $this->formdata['txtname'];?>"  >
            </div>
        </div>
	<div class="_100 ">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Planogram Description ('.$this->sec_lang.')').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtname_arb" id="txtname_arb"  maxlength="50" class="arb_text_align margin_top_5" type="text" value="<?php echo $this->formdata['txtname_arb'];?>"  >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Remarks');?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtremark" id="txtremark" type="text"  class="margin_top_5" value="<?php echo $this->formdata['txtremark'];?>"  >
            </div>
        </div>
	<div class="_100" style="padding-bottom:10px;"></div>
	<div class="_100" style="padding-bottom:10px;">
             
            <div class="_30_2 margin_right_1">
                 <div class="_70 margin_right_1">
                <input name="txtdesc1" id="txtdesc1" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc1'];?>"  >
            </div>
		<input type="hidden" name="oldfile1" value="<?php echo $this->formdata['txtid1'];?>" />
		
		<?php
		if($this->formdata['txtimage1'] !='')
		{
		    $image1 = $this->formdata['txtimage1'];
		}
		else
		$image1 = $this->baseUrl('public/images/thumbnail-default.jpg');
		?>
		<img id="image1" src="<?php echo $image1; ?>" alt="your image" width="150" height="100" style="float: left;" />
		<input type='file' name="imagefile1" value="<?php echo $this->formdata['txtimage1'];?>" onchange="readURL(this,'image1');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;" />
		
		
           
	    
            </div>
	    <div class="_30_2 margin_right_1">
               <div class="_70 margin_right_1">
                <input name="txtdesc2" id="txtdesc2" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc2'];?>"  >
            </div>
		<input type="hidden" name="oldfile2" value="<?php echo $this->formdata['txtid2'];?>" />
		<?php
		if($this->formdata['txtimage2'] !='')
		{
		    $image2 = $this->formdata['txtimage2'];
		}
		else
		$image2 = $this->baseUrl('public/images/thumbnail-default.jpg');
		?>
		<img id="image2" src="<?php echo $image2; ?>" alt="your image" width="150" height="100" style="float: left;" />
		 <input type='file' name="imagefile2" value="<?php echo $this->formdata['txtimage2'];?>" onchange="readURL(this,'image2');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;"/>
		 
		
            
		 
            </div>
	    <div class="_30_2 margin_right_1">
              <div class="_70 margin_right_1">
                <input name="txtdesc3" id="txtdesc3" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc3'];?>"  >
            </div>
		<input type="hidden" name="oldfile3" value="<?php echo $this->formdata['txtid3'];?>" />
		<?php
		if($this->formdata['txtimage3'] !='')
		{
		    $image3= $this->formdata['txtimage3'];
		}
		else
		$image3 = $this->baseUrl('public/images/thumbnail-default.jpg');
		?>
		<img id="image3" src="<?php echo $image3; ?>" alt="your image" width="150" height="100" style="float: left;" />
		  <input type='file' name="imagefile3" value="<?php echo $this->formdata['txtimage3'];?>" onchange="readURL(this,'image3');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;" />
		  
		  
            
            </div>
        </div>
	
	<div class="_100"  style="padding-bottom:10px;">
             
            
	    <div class="_30_2 margin_right_1">
                
		<div class="_70 margin_right_1">
                <input name="txtdesc4" id="txtdesc4" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc4'];?>"  >
            </div>
		<?php
		if($this->formdata['txtimage4'] !='')
		{
		    $image4 = $this->formdata['txtimage4'];
		}
		else
		$image4 = $this->baseUrl('public/images/thumbnail-default.jpg');
		?>
		<img id="image4" src="<?php echo $image4; ?>" alt="your image" width="150" height="100" style="float: left;" />
		<input type="hidden" name="oldfile4" value="<?php echo $this->formdata['txtid4'];?>" />
		<input type='file' name="imagefile4" value="<?php echo $this->formdata['txtimage4'];?>" onchange="readURL(this,'image4');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;" />
		
		
            
            </div>
	    
	    <div class="_30_2 margin_right_1">
               
		<div class="_70 margin_right_1">
                <input name="txtdesc5" id="txtdesc5" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc5'];?>"  >
            </div>
		<?php
		if($this->formdata['txtimage5'] !='')
		{
		    $image5 = $this->formdata['txtimage5'];
		}
		else
		$image5 = $this->baseUrl('public/images/thumbnail-default.jpg');
		?>
		
		<img id="image5" src="<?php echo $image5; ?>" alt="your image" width="150" height="100" style="float: left;" />
		<input type="hidden" name="oldfile5" value="<?php echo $this->formdata['txtid5'];?>" />
		 <input type='file' name="imagefile5" value="<?php echo $this->formdata['txtimage5'];?>" onchange="readURL(this,'image5');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;" />
		 
		 
            
            </div>
        </div>
	
	
	<?php //if($this->params["edit"]=="yes") {?>
	<!--<div class="_100">
             <label class="_36 margin_top_10 label_text_align">
                <?php //echo $this->translate->_('Created Date').''.$this->colan;?>
            </label>
            <div class="_50  margin_top_10 date_color margin_right_1"><?php //echo $this->formdata['createddate'];?>
            </div>
    </div>-->
	<?php //} ?>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</form>
</div>
</div> <!-- End of .box -->