<?php
/**
* @name       addcustcat.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Customer Category
*/
$this->translate = Zend_Registry::get('Zend_Translate');

$img_count = count($this->formdata['txtimage']);
$add_visual_img_grid = $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"addvisualimggrid"),"default", true);
?>

<script type="text/javascript">
    $(document).ready(function(){
	$("a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast', theme:'light_rounded', allow_resize: true, slideshow:5000, autoplay_slideshow:false, opacity:0.70});
    });
</script>

<script>
$(document).ready(function() {
    $("#txtaltcode").focus();
});
</script>
<script type="text/javascript">
    function readURL(input,id) {
	if (input.files && input.files[0]) {
	    var reader = new FileReader();

	    reader.onload = function (e) {
		$('#'+id).attr('src', e.target.result);
	    }

	    reader.readAsDataURL(input.files[0]);
	}
    }
</script>

<script type="text/javascript">
    $(document).ready(function() {
	
	var glob_i = <?php echo (isset($img_count) && $img_count > 2) ? ($img_count+1): '2';?>;
	$('#plus_img').live('click',function(){
	    
	    //$('.image_caption_area:last').after('<div class="_100 image_caption_area"><label class="_36 margin_top_12 label_text_align"></label><div class="_30_2 margin_right_1"><div class="_70 margin_right_1"><input name="txtdesc'+glob_i+'" id="txtdesc'+glob_i+'" type="text"  class="margin_bottom_5" value="" ></div><input type="hidden" name="oldfile'+glob_i+'" value="" /><?php $image1 = $this->baseUrl('public/images/thumbnail-default.jpg');?><img id="image'+glob_i+'" src="<?php echo $image1; ?>" alt="your image" width="150" height="100" style="float: left;" /><input type="file" name="imagefile'+glob_i+'" value="" onchange="readURL(this,\'image'+glob_i+'\');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;" /></div><div class="_330_2"><a class="minus_img" title="Remove Image" style="display:inline-block; margin-top:10px;">Remove</a></div></div>');
	    $('.image_caption_area:last').after('<div class="_100 image_caption_area"><label class="_36 margin_top_12 label_text_align"></label><div class="_50 margin_right_1"><div class="_50 margin_right_1"><input name="txtdesc['+glob_i+']" id="txtdesc['+glob_i+']" type="text"  class="margin_bottom_5" value="" ></div><input type="hidden" name="oldfile['+glob_i+']" value="" /><?php $image1 = $this->baseUrl('public/images/thumbnail-default.jpg');?><img id="image'+glob_i+'" src="<?php echo $image1; ?>" alt="your image" width="120" height="80" style="float: right; margin-top: 10px;" /><input type="file" name="imagefile'+glob_i+'" value="" onchange="readURL(this,\'image'+glob_i+'\');" class="_50 margin_top_5" /><a class="minus_img" title="Remove Image" style="display:inline-block; float:right; margin-top:10px; clear:both;">Remove</a></div></div>');
	    glob_i = glob_i + 1; // increment the value for KIDS DOB
	});
	
	$('.minus_img').live('click',function(){
	    $(this).parents('._100').remove();
	});
	
    });
    
    function changeplanogramacl()
    {
	var code_id = $('#txtcode').val();
	var tempcode = $('#tempcode').val();
	var url = '<?php echo $add_visual_img_grid; ?>';
	var data = "id="+code_id+"&tempcode="+tempcode;
	
	$.blockUI();
	$.ajax({
	    url:url,
	    data: data,
	    type:'post',
	    success:function(data) {
		$.unblockUI();
		$("#table-example").html(data);
	    }
	});
    }
    
    function deleteplanoimg(txtid)
    {
	var id = $('#txtcode').val();
	var tempcode = $('#tempcode').val();
	var url = '<?php echo $this->baseUrl(); ?>/merchandize/index/deletevisualimg';
	var data = "id="+id+"&txtid="+txtid+"&tempcode="+tempcode;
	
	$.blockUI();
	$.ajax({
	    url:url,
	    data: data,
	    type:'post',
	    success:function(data) {
		$.unblockUI();
		changeplanogramacl();
	    }
	});
    }
    
    $(document).ready(function() {
	$('#sbtnadd').click(function() {
	    
	    if($("#addimgform").valid())
	    {
		$("#addimgform").submit(); //Submit  the FORM
	    }
	    
	});
	
	$("#addimgform").submit(function(e)
	{
	    var formURL = $(this).attr("action");
	    var txtcode = $('#txtcode').val();
	    var tempcode = $('#tempcode').val();
	    
	    var data = new FormData(this);
	    data.append('txtcode',txtcode);
	    data.append('tempcode',tempcode);
	    
	    $.blockUI();
	    $.ajax(
	    {
		url : formURL,
		type: "POST",
		data : data,
		cache: false,
		contentType: false,
		processData: false,
		success:function(data, textStatus, jqXHR)
		{
		    $.unblockUI();
		    changeplanogramacl();
		    $('#txtdesc').val('');
		    $('#imagefile').val('');
		    //data: return data from server
		},
		error: function(jqXHR, textStatus, errorThrown)
		{
		    //if fails     
		}
	    });
	    e.preventDefault(); //STOP default action
	    //e.unbind(); //unbind. to stop multiple form submit.
	});
	
	$('#btncancel').click(function() {
	    
	    var tempcode = $('#tempcode').val();
	    
	    if(tempcode)
	    {
		var url = '<?php echo $this->baseUrl(); ?>/merchandize/index/deletevisualimg';
		var data = "tempcode="+tempcode;
		
		$.ajax({
		    url:url,
		    data: data,
		    type:'post',
		    success:function(data) {
			winloc('<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"visuals"),"default", true);?>');
		    }
		});
		
	    }
	    else
	    {
		winloc('<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"visuals"),"default", true);?>');
	    }
	});
    });
</script>

<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_customer_custcat">
<form class="validate" method="post" action="" enctype="multipart/form-data" novalidate="novalidate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	<h3><?php echo $this->translate->_('Planogram');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"visuals"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"addvisual"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions min_height_10">
	<div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Code').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtcode" id="txtcode" readonly="readonly" type="text" class="required text_align" value="<?php echo $this->formdata['txtcode'];?>"  >
            </div>
        </div>
		
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Planogram Description').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtname" id="txtname" type="text"  maxlength="50" class="margin_top_5 required" value="<?php echo $this->formdata['txtname'];?>"  >
            </div>
        </div>
	<div class="_100 ">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Planogram Description ('.$this->sec_lang.')').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtname_arb" id="txtname_arb"  maxlength="50" class="arb_text_align margin_top_5" type="text" value="<?php echo $this->formdata['txtname_arb'];?>"  >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Remarks');?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtremark" id="txtremark" type="text"  class="margin_top_5" value="<?php echo $this->formdata['txtremark'];?>"  >
            </div>
        </div>
	
	<?php
	/*if(isset($img_count) && $img_count > 0)
	{
	    for($l=0; $l<$img_count; $l++)
	    {
		?>
		<div class="_100 image_caption_area">
		    <label class="_36 margin_top_12 label_text_align">
			<?php if($l == 0){ echo $this->translate->_('Images').''.$this->colan;}?>
		    </label>
		    <div class="_50 margin_right_1">
			<div class="_50 margin_right_1">
			    <input name="txtdesc[<?php echo $l+1;?>]" id="txtdesc[<?php echo $l+1;?>]" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc'][$l];?>"  >
			</div>
			<input type="hidden" name="oldfile[<?php echo $l+1;?>]" value="<?php echo $this->formdata['txtid'][$l];?>" />
			
			<?php
			if($this->formdata['txtimage'][$l] !='')
			{
			    $image1 = $this->formdata['txtimage'][$l];
			}
			else
			$image1 = $this->baseUrl('public/images/thumbnail-default.jpg');
			?>
			<input type="hidden" name="oldimg[<?php echo $l+1;?>]" value="<?php echo $this->formdata['txtoldimage'][$l];?>" />
			<img id="image<?php echo $l+1;?>" src="<?php echo $image1; ?>" alt="your image" width="120" height="80" style="float: right; margin-top: 10px;" />
			<input type='file' name="imagefile<?php echo $l+1;?>" value="<?php echo $this->formdata['txtimage'][$l];?>" onchange="readURL(this,'image<?php echo $l+1;?>');" class="_50 margin_top_5" />
			<?php
			if($l == 0)
			{
			    ?>
			    <a id="plus_img" title="Add New Image" style="display:inline-block; float:right; margin-top:10px; clear:both;">Add New</a>
			    <?php
			}
			else
			{
			    ?>
			    <!--<a class="minus_img" style="display:inline-block; float:right; margin-top:10px; clear:both;" title="Remove Image">Remove</a>-->
			    <?php
			}
			?>
		    </div>
		</div>
		<?php
	    }
	}
	else
	{
	    ?>
	    <div class="_100 image_caption_area">
		 <label class="_36 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Images').''.$this->colan;?>
		</label>
		<div class="_50 margin_right_1">
		    <div class="_50 margin_right_1">
			<input name="txtdesc[1]" id="txtdesc[1]" type="text"  class="margin_bottom_5" value=""  >
		    </div>
		    <input type="hidden" name="oldfile[1]" value="" />
		    
		    <?php $image1 = $this->baseUrl('public/images/thumbnail-default.jpg');?>
		    <img id="image1" src="<?php echo $image1; ?>" alt="your image" width="120" height="80" style="float: right; margin-top: 10px;" />
		    <input type='file' name="imagefile1" value="" onchange="readURL(this,'image1');" class="_50 margin_top_5" />
		    <a id="plus_img" title="Add New Image" style="display:inline-block; float:right; margin-top:10px; clear:both;">Add New</a>
		</div>
	    </div>
	    <?php
	}*/
	?>
	
	
	
	<div class="_100" style="padding-bottom:10px;"></div>
	
	<!--<div class="_100" style="padding-bottom:10px;">
             
            <div class="_30_2 margin_right_1">
                 <div class="_70 margin_right_1">
                <input name="txtdesc1" id="txtdesc1" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc1'];?>"  >
            </div>
		<input type="hidden" name="oldfile1" value="<?php echo $this->formdata['txtid1'];?>" />
		
		<?php
		if($this->formdata['txtimage1'] !='')
		{
		    $image1 = $this->formdata['txtimage1'];
		}
		else
		$image1 = $this->baseUrl('public/images/thumbnail-default.jpg');
		?>
		<img id="image1" src="<?php echo $image1; ?>" alt="your image" width="150" height="100" style="float: left;" />
		<input type='file' name="imagefile1" value="<?php echo $this->formdata['txtimage1'];?>" onchange="readURL(this,'image1');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;" />
            </div>
	    <div class="_30_2 margin_right_1">
               <div class="_70 margin_right_1">
                <input name="txtdesc2" id="txtdesc2" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc2'];?>"  >
            </div>
		<input type="hidden" name="oldfile2" value="<?php echo $this->formdata['txtid2'];?>" />
		<?php
		if($this->formdata['txtimage2'] !='')
		{
		    $image2 = $this->formdata['txtimage2'];
		}
		else
		$image2 = $this->baseUrl('public/images/thumbnail-default.jpg');
		?>
		<img id="image2" src="<?php echo $image2; ?>" alt="your image" width="150" height="100" style="float: left;" />
		<input type='file' name="imagefile2" value="<?php echo $this->formdata['txtimage2'];?>" onchange="readURL(this,'image2');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;"/>
            </div>
	    <div class="_30_2 margin_right_1">
              <div class="_70 margin_right_1">
                <input name="txtdesc3" id="txtdesc3" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc3'];?>"  >
            </div>
		<input type="hidden" name="oldfile3" value="<?php echo $this->formdata['txtid3'];?>" />
		<?php
		if($this->formdata['txtimage3'] !='')
		{
		    $image3= $this->formdata['txtimage3'];
		}
		else
		$image3 = $this->baseUrl('public/images/thumbnail-default.jpg');
		?>
		<img id="image3" src="<?php echo $image3; ?>" alt="your image" width="150" height="100" style="float: left;" />
		<input type='file' name="imagefile3" value="<?php echo $this->formdata['txtimage3'];?>" onchange="readURL(this,'image3');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;" />
            </div>
        </div>
	
	<div class="_100"  style="padding-bottom:10px;">
             
            
	    <div class="_30_2 margin_right_1">
                
		<div class="_70 margin_right_1">
                <input name="txtdesc4" id="txtdesc4" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc4'];?>"  >
            </div>
		<?php
		if($this->formdata['txtimage4'] !='')
		{
		    $image4 = $this->formdata['txtimage4'];
		}
		else
		$image4 = $this->baseUrl('public/images/thumbnail-default.jpg');
		?>
		<img id="image4" src="<?php echo $image4; ?>" alt="your image" width="150" height="100" style="float: left;" />
		<input type="hidden" name="oldfile4" value="<?php echo $this->formdata['txtid4'];?>" />
		<input type='file' name="imagefile4" value="<?php echo $this->formdata['txtimage4'];?>" onchange="readURL(this,'image4');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;" />
            </div>
	    
	    <div class="_30_2 margin_right_1">
               
		<div class="_70 margin_right_1">
                <input name="txtdesc5" id="txtdesc5" type="text"  class="margin_bottom_5" value="<?php echo $this->formdata['txtdesc5'];?>"  >
            </div>
		<?php
		if($this->formdata['txtimage5'] !='')
		{
		    $image5 = $this->formdata['txtimage5'];
		}
		else
		$image5 = $this->baseUrl('public/images/thumbnail-default.jpg');
		?>
		
		<img id="image5" src="<?php echo $image5; ?>" alt="your image" width="150" height="100" style="float: left;" />
		<input type="hidden" name="oldfile5" value="<?php echo $this->formdata['txtid5'];?>" />
		<input type='file' name="imagefile5" value="<?php echo $this->formdata['txtimage5'];?>" onchange="readURL(this,'image5');" class="margin_top_5" style="width: 37%;margin-left: 34px;border: none;" />
            </div>
        </div>-->
	
	
	<?php //if($this->params["edit"]=="yes") {?>
	<!--<div class="_100">
             <label class="_36 margin_top_10 label_text_align">
                <?php //echo $this->translate->_('Created Date').''.$this->colan;?>
            </label>
            <div class="_50  margin_top_10 date_color margin_right_1"><?php //echo $this->formdata['createddate'];?>
            </div>
    </div>-->
	<?php //} ?>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input name="tempcode" id="tempcode" type="hidden" value="<?php echo $this->formdata['tempcode'];?>"  >
</form>

<div class="content with-actions min_height_10">
    <form id="addimgform" class="validate" method="post" action="<?php echo $this->baseUrl(); ?>/merchandize/index/addvisualimg" enctype="multipart/form-data" novalidate="novalidate">
	<div class="_100">
	    <fieldset>
		<legend><?php echo $this->translate->_('Add Item');?>:</legend>
		<div class="_100 image_caption_area">
		    <label class="_20 margin_top_12 label_text_align">
			    <?php echo $this->translate->_('Images').''.$this->colan;?>
		    </label>
		    <div class="_20 margin_right_1">
			    <input name="txtdesc" id="txtdesc" type="text"  class="margin_bottom_5" value=""  >
		    </div>
		    
		    <label class="_10 margin_top_12 label_text_align"></label>
		    <div class="_30 margin_right_1">
			    <input type='file' id="imagefile" class="required" name="imagefile" value="" />
		    </div>
		    
		    <div class="_5">
		    <input id="sbtnadd" class="sbtnadd" type="button" name="sbtnadd" value="ADD">
		    </div>
	       </div>
	    </fieldset>
	</div>
    </form>
    
    <div class="_100" id="custom_grid">  
	<!-- Content -->
	<div id="content">
	    <div class="box">
		<div id="paging_grid" class="padding_zero">
		    <div class="grid_12">
			<div class="box">
			    <div class="content min_height_10">
				    <table class="table" id="table-example" width="100%">
					    <thead>
						<tr>
							    <th width="60%"><a href="javascript:void(0)"><?php echo $this->translate->_('Image Description')?></a></th>
							    <th width="30%"><a href="javascript:void(0)"><?php echo $this->translate->_('Image')?></a></th>
							    <th width="10%">&nbsp;</th>
						</tr>
					    </thead>
					    <tbody>
						    <?php
						    for($i=0;$i<count($this->formdata['txtimage']);$i++)
						    {
							$css = $i%2 == 0 ? 'gradeC' : 'gradeA';
							?>
							<tr class="<?php echo $css?>">
							    <td><?php echo ($this->formdata['txtdesc'][$i]) ? $this->formdata['txtdesc'][$i] : ''; ?></td>
							    <td><a href="<?php echo $this->formdata['txtimage'][$i]; ?>" rel="prettyPhoto[gallery]" id="pretty_link" title="<?php echo $this->formdata['txtdesc'][$i]; ?>" class="btn btn2"><img src="<?php echo $this->formdata['txtimage'][$i]; ?>" alt="<?php echo $this->formdata['txtdesc'][$i]; ?>" width="120" height="80" /></a></td>
							    
							    <td><a id="<?php echo $this->formdata['txtid'][$i];?>" onclick="deleteplanoimg(this.id)">delete</a></td>
							</tr>
							<?php
						    }
						    ?>
					    </tbody>
				    </table>
			    </div>
			    
			</div> <!-- End of .box -->
		    </div>    
		    <div class="clean"></div>
		</div>
	    </div>
	</div>
    </div>
</div>

</div>
</div> <!-- End of .box -->