<?php
/**
* @name       invoice.phtml
* @since      06-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$date = $this->date != '' ? $this->date : date('d-m-Y');
?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_merchandizing.png" class="margin_top_10">
		<h3><?php echo $this->translate->_('Customer Images')?></h3>
	    </div>
	    <div class="_50_3">&nbsp;</div>
        </div>
	<div class="_100" >
	    <div class="_20 label_text_align margin_top_10"><label class="advance_search_css"><?php echo $this->translate->_('Rotue Name').''.$this->colan;?></label></div>
		<div class="_25 margin_right_1">
			<select id="ddlroutecode" name="ddlroutecode" class="margin_zero">
				<option value="">--- Select ---</option>
				<?php for($i=0;$i<count($this->routeinfo);$i++) { ?>
				<option <?php echo ($this->route == $this->routeinfo[$i]['id']) ? 'selected' : ''; ?> value="<?php echo $this->routeinfo[$i]['id']; ?>"><?php echo $this->routeinfo[$i]['val']; ?></option>
				<?php } ?>
			</select>
		</div>
		
		<div class="_20 label_text_align margin_top_10"><label class="advance_search_css"><?php echo $this->translate->_('Transaction Date').''.$this->colan;?></label></div>
		<div class="_20 label_text_align margin_right_1"><input type="text" id="txtdate" readonly="readonly" name="txtdate" value="<?php echo $date;?>" class="margin_zero"></div>
		
		<div class="_5 margin_right_2_2"><input type="submit" name="btnload" id="btnload" value="<?php echo $this->translate->_('OK'); ?>" class="margin_zero"></div>
		<div class="_10"><input type="submit" name="btnreset" id="btnreset" value="<?php echo $this->translate->_('RESET'); ?>" class="margin_zero"></div>
		
            <div class="_15">
                &nbsp;
            </div>
	</div>
	<div class="clear space_20"></div>
	<div class="clear"></div>
	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
		$( "#txtdate" ).datepicker({
			dateFormat: 'dd-mm-yy'
		});
    });
	
	$("#table-example tr").each(function() {
		$(this).find('td').eq(2).find('a').html('View');
	})
});

</script>