<?php
/**
* @name       surveydefination.phtml
* @since      31-01-12
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  Elan Technologies
*
* 
*/

$this->translate = Zend_Registry::get('Zend_Translate');

?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="merchandize_index_surveydefination">
<form id="frmdet" name="frmdet" class="validate" action="" method="post">
    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
<div class="header">    
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_merchandizing.png">
        <h3><?php echo $this->translate->_('Survey Definition')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="history.back(-1);" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave" ></div>
    </div>
</div>
<div class="clear"></div>
<div class="clear"></div>
<div id="ie_spacer" ></div>
<div class="content with-actions" >
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<label class="_36 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Message Type').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtmessage_type" name="txtmessage_type" value="1" >
	</div>
    </div>
    <div class="_100">
	<label class="_36 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Line Index').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtline_index" name="txtline_index" value="1" >
	</div>
    </div>
    <div class="_100">
	<label class="_36 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Survey Promt').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtsurvey_promt" name="txtsurvey_promt" value="Rourte Survey Testing " >
	</div>
    </div>
    <div class="_100">
	<label class="_36 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Survey Promt ('.$this->sec_lang.')').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtsurvey_promt_arabic" name="txtsurvey_promt_arabic" value="Rourte Survey" >
	</div>
    </div>
    <div class="_100 margin_top_7">
	<label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Record Type').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <select id="ddlrecord_type" name="ddlrecord_type" >
		<option value="">--- Select ---</option>
		<?php for($i=0;$i<count($this->record_type);$i++) { ?>
		    <option value="<?php echo $this->record_type[$i]['id'];?>" selected="selected" ><?php echo $this->record_type[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
    </div>
    <div class="_100">
	<label class="_36 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Response Length').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtresponse_length" name="txtresponse_length" value="20" >
	</div>
    </div>
    <div class="_100 margin_top_7">
	<label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Response Decimal Pos').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <select id="ddlresponse_decimal_pos" name="ddlresponse_decimal_pos" >
		<option value="">--- Select ---</option>
		<?php		    
		    for($i=0;$i<count($this->response_decimal_pos);$i++)
		    {
		?>
			<option value="<?php echo $this->response_decimal_pos[$i]['id'];?>" selected="selected"><?php echo $this->response_decimal_pos[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
    </div>
    <div class="_100 margin_top_7">
	<label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Lookup Type').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <select id="ddllookup_type" name="ddllookup_type" disabled="disabled" >
		<option value="">--- Select ---</option>
		<?php		    
		    for($i=0;$i<count($this->lookup_type);$i++)
		    {
		?>
			<option value="<?php echo $this->lookup_type[$i]['id'];?>"><?php echo $this->lookup_type[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
	
	<div class="_5_3 formbutton">
	    <input type="button" name="btnAdd" id="btnAdd" value="<?php echo $this->translate->_('ADD'); ?>" class="margin_top_5" onclick="winloc('<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"surveylookup"), "default", true);?>')" >
	</div>
	
	<div class="_5_3 formbutton">
	    <input type="button" name="btnCancel" id="btnCancel" value="<?php echo $this->translate->_('Edit'); ?>" class="margin_top_5" onclick="javascript:void(0);" >
	</div>
	
    </div>
    <div class="_100 margin_top_7">
	<label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Lookup Index').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <select id="ddllookup_index" name="ddllookup_index" disabled="disabled" >
		<option value="">--- Select ---</option>
		<?php		    
		    for($i=0;$i<count($this->lookup_index);$i++)
		    {
		?>
			<option value="<?php echo $this->lookup_index[$i]['id'];?>"><?php echo $this->lookup_index[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
    </div>
    
    <div class="clear space_100"></div>
</form>
</div> <!-- End of .box -->
</div>
