<div class="grid_12">
    <div class="box" id="account_customer_customerimages">
		<div class="header">
			<div class="_50_3 back_btn">
				<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
				<h3><?php echo $this->title;?></h3>
			</div>
			<div class="_50_3">
				<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"customerimages"), "default", true);?>')" ></div>				
			</div>
		</div>		
		<?php
		$i=0;
			if(count($this->images) > 0) {
			?>
			<div class="content with-actions padding_zero clear_only" id="customerimages">
				<table border="1" cellpadding="10px" >
					<tr> 
					<?php
						$i=0;						
							foreach($this->images as $curimg) {
								if(file_exists($this->path.$curimg['imagename']) && $curimg['imagename'] != '.' && $curimg['imagename'] != '..') { ?>		
									<td align="center" class="padding_top_10"><?php echo '<img height="200" width="200" src="' . $this->path1.$curimg['imagename'] . '" /><br>'.$curimg['imagename'].'&nbsp;'; ?></td>
								<?php } ?>
								<?php if(++$i%4 == 0) echo '</tr><tr>'; ?>
						<?php } ?>
					</tr>
				</table>
			</div>
			<?php } else { ?>				
				<div class="content with-actions min_height_10 margin_top_10">
					<div class="clear_only nodata_message margin_top_50 margin_bottom_10"><b><?php echo $this->message;?></b></div>
				</div>
			<?php
			}
		?>	
	</div>
</div>