<?php
/**
* @name       addcustomer.phtml
* @since      17 Feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
        $(document).ready(function(){
            loaddata_popup('<?php echo $this->itemgrid; ?>','item-grid');
        })
    </script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_settlement_addcashreceipt">
<form name="frmoverview" id="frmoverview" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	<h3><?php echo $this->translate->_('Inventory Check');?></h3>
    </div>
    <div class="_50_3">
	&nbsp;
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub" >
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"merchandize","controller"=>"index","action"=>"inventorycheck"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="javascript:;" class="admin_active"><?php echo $this->details;?></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
   <div class="content with-actions ie_grid min_height_10" style="padding-bottom: 20px;">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="clear space_20">&nbsp;</div>
	<div id="loader"></div>
	<div class="_100">
		<div id="item-grid" style="overflow-x:auto;">&nbsp;</div>
	</div>
	<div class="clear space_20">&nbsp;</div>
</div>
    <div class="clear"></div>
    <div class="clear"></div>    
</form>
 </div><!-- End of .box -->
</div>