<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({        
   	url:base_url+"/reports/transactioncollectionsummary/collectionsum/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route');?>','<?php echo $this->translate->_('Receipt Number');?>','<?php echo $this->translate->_('Transaction Date');?>','<?php echo $this->translate->_('Customer');?>','<?php echo $this->translate->_( 'Amount Paid in CASH');?>','<?php echo $this->translate->_( 'Amount Paid in CHEQUE');?>','<?php echo $this->translate->_('Total Amount');?>','<?php echo $this->translate->_('Against Invoice');?>','<?php echo $this->translate->_('Invoiced By');?>','<?php echo $this->translate->_('Invoiced Date');?>','<?php echo $this->translate->_('Paid Amount');?>'],
   	colModel:[
   		{name:'routecode',index:'routecode', width:100},
        {name:'documentnumber',index:'documentnumber', width:100},
        {name:'transactiondate',index:'transactiondate', width:90},
        {name:'customercode',index:'customercode', width:250},
		{name:'arcash',index:'arcash', width:70, align:"right",summaryType:'sum',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces }},
		{name:'archeck',index:'archeck', width:70, align:"right",summaryType:'sum',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces }},
        {name:'totalinvoiceamount',index:'totalinvoiceamount', width:70, align:"right",summaryType:'sum',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces }},
		{name:'alternateinvoicenumber',index:'alternateinvoicenumber', width:70},
		{name:'invoicedby',index:'invoicedby', width:70},
		{name:'invoicedate',index:'invoicedate', width:70},
   		{name:'amountpaid',index:'amountpaid', width:70, align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces }}
   	],
	<?php if($this->css == 'ar_') { ?>
		direction :"rtl",
	<?php } ?>	
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
   	pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,
	groupingView :
    {
        groupField : ['routecode','documentnumber'],
        groupColumnShow : [false,true],
        groupCollapse : true,
        groupOrder: ['asc','asc'] ,
        groupSummary : [false,true],
        groupDataSorted : true,
        showSummaryOnHide: false
       
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});
</script>