<?php

declare(strict_types=1);

if ($argc < 3 || $argc > 4) {
    fwrite(STDERR, "Usage:\n");
    fwrite(STDERR, "  php database/tools/convert_mysql_dump_to_pgsql.php <input.sql> <output.sql>\n");
    fwrite(STDERR, "  php database/tools/convert_mysql_dump_to_pgsql.php <input.sql> <schema.sql> <data.sql>\n");
    exit(1);
}

$inputPath = $argv[1];
$schemaOutputPath = $argv[2];
$dataOutputPath = $argc === 4 ? $argv[3] : null;

if (!is_file($inputPath)) {
    fwrite(STDERR, "Input file not found: {$inputPath}\n");
    exit(1);
}

$inputHandle = fopen($inputPath, 'rb');
if ($inputHandle === false) {
    fwrite(STDERR, "Failed to open input file: {$inputPath}\n");
    exit(1);
}

$schemaHandle = openOutputHandle($schemaOutputPath);
$dataHandle = $dataOutputPath !== null ? openOutputHandle($dataOutputPath) : $schemaHandle;

fwrite($schemaHandle, buildHeader($inputPath, 'schema'));
if ($dataOutputPath !== null) {
    fwrite($dataHandle, buildHeader($inputPath, 'data'));
}

$warnings = [];
$stats = [
    'schema_statements' => 0,
    'data_statements' => 0,
    'skipped_statements' => 0,
];
$deferredForeignKeys = [];
$usedSchemaObjectNames = [];

foreach (readSqlStatements($inputHandle) as $statement) {
    $trimmed = trim($statement);

    if ($trimmed === '' || isIgnorableStatement($trimmed)) {
        $stats['skipped_statements']++;
        continue;
    }

    if (preg_match('/^DROP TABLE IF EXISTS\s+`([^`]+)`$/i', rtrim($trimmed, ';'), $matches)) {
        fwrite($schemaHandle, sprintf("DROP TABLE IF EXISTS %s CASCADE;\n\n", quoteIdent($matches[1])));
        $stats['schema_statements']++;
        continue;
    }

    if (preg_match('/^CREATE TABLE\s+`([^`]+)`\s*\((.*)\)\s*(.*)$/is', rtrim($trimmed, ';'), $matches)) {
        [$createTableSql, $indexSql, $foreignKeySql, $createWarnings] = convertCreateTable($matches[1], $matches[2], $matches[3]);
        array_push($warnings, ...$createWarnings);
        array_push($deferredForeignKeys, ...$foreignKeySql);

        fwrite($schemaHandle, $createTableSql . "\n\n");
        foreach ($indexSql as $indexStatement) {
            fwrite($schemaHandle, $indexStatement . "\n\n");
        }

        $stats['schema_statements'] += 1 + count($indexSql);
        continue;
    }

    if (preg_match('/^INSERT\s+INTO\b/i', $trimmed)) {
        $convertedInsert = convertInsertStatement($trimmed, $warnings);
        fwrite($dataHandle, ensureSemicolon($convertedInsert) . "\n\n");
        $stats['data_statements']++;
        continue;
    }

    if (shouldSkipStatement($trimmed)) {
        $stats['skipped_statements']++;
        continue;
    }

    $generic = convertGenericStatement($trimmed);
    if ($generic !== '') {
        fwrite($schemaHandle, ensureSemicolon($generic) . "\n\n");
        $stats['schema_statements']++;
        continue;
    }

    $stats['skipped_statements']++;
}

if ($deferredForeignKeys !== []) {
    fwrite($schemaHandle, "-- Deferred foreign keys\n\n");

    foreach ($deferredForeignKeys as $foreignKeyStatement) {
        fwrite($schemaHandle, $foreignKeyStatement . "\n\n");
        $stats['schema_statements']++;
    }
}

if ($warnings !== []) {
    fwrite($schemaHandle, "-- Conversion warnings\n");
    foreach (array_values(array_unique($warnings)) as $warning) {
        fwrite($schemaHandle, "-- {$warning}\n");
    }
}

fclose($inputHandle);
fclose($schemaHandle);
if ($dataOutputPath !== null && $dataHandle !== $schemaHandle) {
    fclose($dataHandle);
}

fwrite(STDOUT, "Schema SQL written to {$schemaOutputPath}\n");
if ($dataOutputPath !== null) {
    fwrite(STDOUT, "Data SQL written to {$dataOutputPath}\n");
}
fwrite(STDOUT, sprintf(
    "Processed statements: schema=%d, data=%d, skipped=%d\n",
    $stats['schema_statements'],
    $stats['data_statements'],
    $stats['skipped_statements']
));
if ($warnings !== []) {
    fwrite(STDOUT, 'Warnings: ' . count(array_unique($warnings)) . "\n");
}

function openOutputHandle(string $outputPath)
{
    $dir = dirname($outputPath);
    if (!is_dir($dir) && !mkdir($dir, 0777, true) && !is_dir($dir)) {
        fwrite(STDERR, "Failed to create output directory: {$dir}\n");
        exit(1);
    }

    $handle = fopen($outputPath, 'wb');
    if ($handle === false) {
        fwrite(STDERR, "Failed to open output file: {$outputPath}\n");
        exit(1);
    }

    return $handle;
}

function buildHeader(string $inputPath, string $kind): string
{
    $lines = [
        "-- Converted from MySQL to PostgreSQL ({$kind})",
        "-- Source: {$inputPath}",
        "-- Notes:",
        "-- 1. MySQL table options, collations, and charset clauses were removed.",
        "-- 2. AUTO_INCREMENT columns were converted to GENERATED BY DEFAULT AS IDENTITY.",
        "-- 3. ON UPDATE CURRENT_TIMESTAMP clauses were removed; add triggers if you need that behavior.",
        "-- 4. MySQL ENUM columns were converted to varchar + CHECK constraints.",
    ];

    if ($kind === 'data') {
        $lines[] = "-- 5. MySQL string escaping in INSERT values was normalized for PostgreSQL.";
        $lines[] = "-- 6. Invalid zero dates in INSERT values were converted to NULL.";
    } else {
        $lines[] = "-- 5. Invalid MySQL zero-date defaults were removed because PostgreSQL does not allow them.";
    }

    return implode(PHP_EOL, $lines) . PHP_EOL . PHP_EOL;
}

function readSqlStatements($handle): Generator
{
    $buffer = '';
    $quote = null;
    $inLineComment = false;
    $inBlockComment = false;

    while (($line = fgets($handle)) !== false) {
        $length = strlen($line);

        for ($i = 0; $i < $length; $i++) {
            $char = $line[$i];
            $next = $i + 1 < $length ? $line[$i + 1] : '';

            if ($inLineComment) {
                $buffer .= $char;
                if ($char === "\n") {
                    $inLineComment = false;
                }
                continue;
            }

            if ($inBlockComment) {
                $buffer .= $char;
                if ($char === '*' && $next === '/') {
                    $buffer .= $next;
                    $i++;
                    $inBlockComment = false;
                }
                continue;
            }

            if ($quote !== null) {
                $buffer .= $char;
                if ($char === '\\' && $i + 1 < $length) {
                    $buffer .= $line[$i + 1];
                    $i++;
                    continue;
                }

                if ($char === $quote) {
                    $quote = null;
                }
                continue;
            }

            if ($char === "'" || $char === '"') {
                $quote = $char;
                $buffer .= $char;
                continue;
            }

            if ($char === '-' && $next === '-') {
                $inLineComment = true;
                $buffer .= $char . $next;
                $i++;
                continue;
            }

            if ($char === '/' && $next === '*') {
                $inBlockComment = true;
                $buffer .= $char . $next;
                $i++;
                continue;
            }

            if ($char === ';') {
                yield $buffer;
                $buffer = '';
                continue;
            }

            $buffer .= $char;
        }
    }

    if (trim($buffer) !== '') {
        yield $buffer;
    }
}

function isIgnorableStatement(string $statement): bool
{
    $trimmed = ltrim($statement);

    return $trimmed === ''
        || str_starts_with($trimmed, '--')
        || str_starts_with($trimmed, '/*')
        || preg_match('/^\/\*![\s\S]*\*\/$/', $trimmed) === 1;
}

function shouldSkipStatement(string $statement): bool
{
    return preg_match('/^(LOCK TABLES|UNLOCK TABLES|ALTER TABLE .* (DISABLE|ENABLE) KEYS|SET\s+)/i', $statement) === 1;
}

function convertCreateTable(string $tableName, string $body, string $tail): array
{
    $warnings = [];
    $items = splitTopLevelCommaList($body);
    $columns = [];
    $constraints = [];
    $indexes = [];
    $foreignKeys = [];

    foreach ($items as $item) {
        $line = trim($item);
        if ($line === '') {
            continue;
        }

        if (preg_match('/^PRIMARY KEY\s*\((.+)\)$/is', $line)) {
            $constraints[] = transformIdentifiers($line);
            continue;
        }

        if (preg_match('/^UNIQUE KEY\s+`([^`]+)`\s*\((.+)\)$/is', $line, $matches)) {
            $constraintName = reserveSchemaObjectName($matches[1], $tableName);
            $constraints[] = sprintf(
                'CONSTRAINT %s UNIQUE (%s)',
                quoteIdent($constraintName),
                transformIndexColumnList($matches[2])
            );
            continue;
        }

        if (preg_match('/^(?:FULLTEXT|SPATIAL)\s+KEY\s+`([^`]+)`\s*\((.+)\)$/is', $line, $matches)) {
            $warnings[] = sprintf('Skipped unsupported %s index %s on table %s.', strtok($line, ' '), $matches[1], $tableName);
            continue;
        }

        if (preg_match('/^KEY\s+`([^`]+)`\s*\((.+)\)$/is', $line, $matches)) {
            $indexName = reserveSchemaObjectName($matches[1], $tableName);
            $indexes[] = sprintf(
                'CREATE INDEX %s ON %s (%s);',
                quoteIdent($indexName),
                quoteIdent($tableName),
                transformIndexColumnList($matches[2])
            );
            continue;
        }

        if (preg_match('/^CONSTRAINT\s+`([^`]+)`\s+FOREIGN KEY\s*\((.+)\)\s+REFERENCES\s+`([^`]+)`\s*\((.+)\)(.*)$/is', $line, $matches)) {
            $suffix = trim(transformConstraintSuffix($matches[5]));
            $constraintName = reserveSchemaObjectName($matches[1], $tableName);
            $foreignKeys[] = sprintf(
                'ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)%s;',
                quoteIdent($tableName),
                quoteIdent($constraintName),
                transformIndexColumnList($matches[2]),
                quoteIdent($matches[3]),
                transformIndexColumnList($matches[4]),
                $suffix === '' ? '' : ' ' . $suffix
            );
            continue;
        }

        $columns[] = convertColumnDefinition($line, $warnings, $tableName);
    }

    $definition = array_merge($columns, $constraints);
    $createTable = sprintf(
        "CREATE TABLE %s (\n    %s\n);",
        quoteIdent($tableName),
        implode(",\n    ", $definition)
    );

    if (stripos($tail, 'AUTO_INCREMENT=') !== false) {
        $warnings[] = sprintf('Removed table AUTO_INCREMENT seed from %s.', $tableName);
    }

    return [$createTable, $indexes, $foreignKeys, $warnings];
}

function convertColumnDefinition(string $line, array &$warnings, string $tableName): string
{
    if (!preg_match('/^`([^`]+)`\s+(.*)$/is', $line, $matches)) {
        $warnings[] = sprintf('Unparsed table item left as-is in %s: %s', $tableName, $line);
        return transformIdentifiers($line);
    }

    $columnName = $matches[1];
    $definition = trim($matches[2]);
    $checkConstraints = [];

    $definition = preg_replace('/\s+COMMENT\s+\'(?:\\\\\'|[^\'])*\'/i', '', $definition) ?? $definition;
    $definition = preg_replace('/\s+CHARACTER SET\s+\w+/i', '', $definition) ?? $definition;
    $definition = preg_replace('/\s+COLLATE\s+[\w\d_]+/i', '', $definition) ?? $definition;
    $definition = preg_replace('/\s+ON UPDATE CURRENT_TIMESTAMP(?:\(\))?/i', '', $definition) ?? $definition;
    $definition = preg_replace('/\bUNSIGNED\b/i', '', $definition) ?? $definition;
    $definition = preg_replace('/\bZEROFILL\b/i', '', $definition) ?? $definition;
    $definition = preg_replace("/\\s+DEFAULT\\s+'0000-00-00(?: 00:00:00)?'/i", '', $definition) ?? $definition;

    if (preg_match('/^enum\s*\((.+)\)(.*)$/is', $definition, $enumMatches)) {
        $values = array_map('trim', splitTopLevelCommaList($enumMatches[1]));
        $maxLength = 1;
        $normalizedValues = [];

        foreach ($values as $value) {
            $trimmed = trim($value);
            $normalizedValues[] = $trimmed;
            $raw = trim($trimmed, "'");
            $maxLength = max($maxLength, strlen(str_replace("\\'", "'", $raw)));
        }

        $definition = sprintf('varchar(%d)%s', $maxLength, $enumMatches[2]);
        $checkConstraints[] = sprintf('CHECK (%s IN (%s))', quoteIdent($columnName), implode(', ', $normalizedValues));
    }

    if (preg_match('/^(bigint|int|integer|smallint|tinyint)\b(.*)\bAUTO_INCREMENT\b(.*)$/is', $definition, $autoMatches)) {
        $mappedType = match (strtolower($autoMatches[1])) {
            'tinyint', 'smallint' => 'smallint',
            'bigint' => 'bigint',
            default => 'integer',
        };
        $remainder = trim(($autoMatches[2] ?? '') . ' ' . ($autoMatches[3] ?? ''));
        $definition = trim($mappedType . ' GENERATED BY DEFAULT AS IDENTITY ' . $remainder);
    }

    $definition = preg_replace('/\bdatetime\b/i', 'timestamp without time zone', $definition) ?? $definition;
    $definition = preg_replace('/\bblob\b/i', 'bytea', $definition) ?? $definition;
    $definition = preg_replace('/\blongtext\b/i', 'text', $definition) ?? $definition;
    $definition = preg_replace('/\bmediumtext\b/i', 'text', $definition) ?? $definition;
    $definition = preg_replace('/\btinytext\b/i', 'text', $definition) ?? $definition;
    $definition = preg_replace('/\bdouble\s*\(\s*\d+\s*,\s*\d+\s*\)/i', '__PG_DOUBLE_PRECISION__', $definition) ?? $definition;
    $definition = preg_replace('/\bdouble\b(?!\s+precision\b)/i', '__PG_DOUBLE_PRECISION__', $definition) ?? $definition;
    $definition = preg_replace('/\bfloat\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/i', 'numeric($1,$2)', $definition) ?? $definition;
    $definition = preg_replace('/\bfloat\b(?!\s*\()/i', 'double precision', $definition) ?? $definition;
    $definition = preg_replace('/\btinyint\b/i', 'smallint', $definition) ?? $definition;
    $definition = str_replace('__PG_DOUBLE_PRECISION__', 'double precision', $definition);

    $definition = preg_replace("/DEFAULT\\s+'([^']*)'/i", "DEFAULT '$1'", $definition) ?? $definition;
    $definition = preg_replace('/\s+/', ' ', trim($definition)) ?? trim($definition);

    if ($checkConstraints !== []) {
        $definition .= ' ' . implode(' ', $checkConstraints);
    }

    return sprintf('%s %s', quoteIdent($columnName), transformIdentifiers($definition));
}

function convertInsertStatement(string $statement, array &$warnings): string
{
    $normalized = transformIdentifiers($statement);
    $result = '';
    $length = strlen($normalized);

    for ($i = 0; $i < $length; $i++) {
        $char = $normalized[$i];

        if ($char !== "'") {
            $result .= $char;
            continue;
        }

        [$literal, $nextOffset] = readMysqlStringLiteral($normalized, $i + 1, $warnings);
        $result .= normalizeInsertLiteral($literal);
        $i = $nextOffset;
    }

    return $result;
}

function readMysqlStringLiteral(string $sql, int $offset, array &$warnings): array
{
    $decoded = '';
    $length = strlen($sql);

    for ($i = $offset; $i < $length; $i++) {
        $char = $sql[$i];

        if ($char === '\\' && $i + 1 < $length) {
            $escaped = $sql[$i + 1];
            $decoded .= match ($escaped) {
                '0' => '',
                'b' => "\x08",
                'n' => "\n",
                'r' => "\r",
                't' => "\t",
                'Z' => '',
                '\\' => '\\',
                "'" => "'",
                '"' => '"',
                default => $escaped,
            };

            if ($escaped === '0' || $escaped === 'Z') {
                $warnings[] = 'Dropped MySQL-only control escape from INSERT string literal.';
            }

            $i++;
            continue;
        }

        if ($char === "'") {
            if ($i + 1 < $length && $sql[$i + 1] === "'") {
                $decoded .= "'";
                $i++;
                continue;
            }

            return [$decoded, $i];
        }

        $decoded .= $char;
    }

    return [$decoded, $length - 1];
}

function normalizeInsertLiteral(string $literal): string
{
    if (preg_match('/^0{4}-0{2}-0{2}(?: 0{2}:0{2}:0{2})?$/', $literal) === 1) {
        return 'NULL';
    }

    return "'" . str_replace("'", "''", $literal) . "'";
}

function convertGenericStatement(string $statement): string
{
    $statement = preg_replace('/^\/\*![\s\S]*\*\/$/', '', trim($statement)) ?? trim($statement);
    $statement = preg_replace('/\bENGINE=\w+\b/i', '', $statement) ?? $statement;
    $statement = preg_replace('/\bAUTO_INCREMENT=\d+\b/i', '', $statement) ?? $statement;
    $statement = preg_replace('/\bDEFAULT CHARSET=\w+\b/i', '', $statement) ?? $statement;
    $statement = preg_replace('/\bCOLLATE=\w+\b/i', '', $statement) ?? $statement;

    return transformIdentifiers(trim($statement));
}

function transformConstraintSuffix(string $suffix): string
{
    return transformIdentifiers(trim($suffix));
}

function transformIndexColumnList(string $columnList): string
{
    $parts = splitTopLevelCommaList($columnList);
    $normalized = [];

    foreach ($parts as $part) {
        $trimmed = trim($part);
        $trimmed = preg_replace('/`([^`]+)`\s*\(\s*\d+\s*\)/', '"$1"', $trimmed) ?? $trimmed;
        $normalized[] = transformIdentifiers($trimmed);
    }

    return implode(', ', $normalized);
}

function transformIdentifiers(string $sql): string
{
    return preg_replace('/`([^`]+)`/', '"$1"', $sql) ?? $sql;
}

function splitTopLevelCommaList(string $input): array
{
    $items = [];
    $buffer = '';
    $depth = 0;
    $length = strlen($input);
    $quote = null;

    for ($i = 0; $i < $length; $i++) {
        $char = $input[$i];

        if ($quote !== null) {
            $buffer .= $char;
            if ($char === '\\' && $i + 1 < $length) {
                $buffer .= $input[$i + 1];
                $i++;
                continue;
            }

            if ($char === $quote) {
                $quote = null;
            }
            continue;
        }

        if ($char === "'" || $char === '"') {
            $quote = $char;
            $buffer .= $char;
            continue;
        }

        if ($char === '(') {
            $depth++;
            $buffer .= $char;
            continue;
        }

        if ($char === ')') {
            $depth--;
            $buffer .= $char;
            continue;
        }

        if ($char === ',' && $depth === 0) {
            $items[] = $buffer;
            $buffer = '';
            continue;
        }

        $buffer .= $char;
    }

    if (trim($buffer) !== '') {
        $items[] = $buffer;
    }

    return $items;
}

function quoteIdent(string $identifier): string
{
    return '"' . str_replace('"', '""', $identifier) . '"';
}

function ensureSemicolon(string $statement): string
{
    $trimmed = rtrim($statement);
    return str_ends_with($trimmed, ';') ? $trimmed : $trimmed . ';';
}

function reserveSchemaObjectName(string $name, string $tableName): string
{
    global $usedSchemaObjectNames;

    $candidate = truncatePgIdentifier($name);
    $normalized = strtolower($candidate);

    if (!isset($usedSchemaObjectNames[$normalized])) {
        $usedSchemaObjectNames[$normalized] = true;
        return $candidate;
    }

    $suffixBase = '_' . preg_replace('/[^a-zA-Z0-9_]+/', '_', $tableName);
    $suffixBase = trim($suffixBase, '_');
    $suffixBase = $suffixBase === '' ? 'dup' : $suffixBase;

    $counter = 0;

    do {
        $suffix = '_' . $suffixBase . ($counter === 0 ? '' : '_' . $counter);
        $candidate = truncatePgIdentifier($name, $suffix) . $suffix;
        $normalized = strtolower($candidate);
        $counter++;
    } while (isset($usedSchemaObjectNames[$normalized]));

    $usedSchemaObjectNames[$normalized] = true;

    return $candidate;
}

function truncatePgIdentifier(string $name, string $suffix = ''): string
{
    $maxLength = 63;
    $allowedLength = $maxLength - strlen($suffix);

    if ($allowedLength < 1) {
        $suffix = substr($suffix, -($maxLength - 1));
        $allowedLength = 1;
    }

    return substr($name, 0, $allowedLength);
}
