<?php
/**
Added by nilesh gotre on 7-Aug-2016
* Add Tax
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
#myform .chzn-search input{width:94%!important;}
#myform .chzn-drop{width:99.6%!important;}

</style>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_index_addsalesman">
<?php if(SFA_Message::isErrorMsg()) {  ?>
<div class="alert error">
    <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
</div>
<?php } ?>
<form class="validate" method="post" action="" id="myform" novalidate="novalidate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	<h3><?php echo $this->translate->_('Tax');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"tax","action"=>"index"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"account","controller"=>"tax","action"=>"index"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"account","controller"=>"tax","action"=>"addtax"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Code').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtcode" id="txtcode" type="text" readonly="readonly" class="required text_align digits" value="<?php echo $this->formdata['txtcode'];?>" <?php if($this->formdata['txtaltcode']!="") { ?> readonly= "true" <?php } ?> />
            </div>
        </div>       
        <div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Description').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtdesc" id="txtdesc" maxlength="50"  type="text" class="margin_top_5 required" value="<?php echo $this->formdata['txtdesc'];?>" >
            </div>
        </div>
	<div class="_100 ">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="txtdesc_arb" id="txtdesc_arb"  maxlength="50" class="margin_top_5 arb_text_align" type="text" value="<?php echo $this->formdata['txtdesc_arb'];?>" >
            </div>
        </div>
	<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Tax Type').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddltax_type" name="ddltax_type" class="required">
		<option value="">--- <?php echo $this->translate->_('Select');?> ---</option>
		    <?php
		    for($i=0;$i<count($this->tax_type);$i++)
		    {
		?>
			<option <?php echo $this->formdata['ddltax_type'] == $this->tax_type[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->tax_type[$i]['id'];?>"><?php echo $this->tax_type[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
        </div>
	<div class="_100 ">	
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Tax %').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <input name="taxpercentage" id="taxpercentage" class="margin_top_5 number required" type="text" value="<?php echo number_format($this->formdata['taxpercentage'],$this->decimalplaces);?>" >
            </div>
    </div>	
		<div class="_100">
             <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Tax Base').''.$this->required;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddltax_base" name="ddltax_base" class="required">
		<option value="">--- <?php echo $this->translate->_('Select');?> ---</option>
		    <?php
		    for($i=0;$i<count($this->tax_base);$i++)
		    {
		?>
			<option <?php echo $this->formdata['ddltax_base'] == $this->tax_base[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->tax_base[$i]['id'];?>"><?php echo $this->tax_base[$i]['val'];?></option>
		<?php } ?>
		</select>
            </div>
        </div>
	<?php if($this->params["edit"]=="yes") {?>
	<div class="_100">
             <label class="_36 margin_top_10 label_text_align">
                <?php echo $this->translate->_('Created Date').''.$this->colan;?>
            </label>
            <div class="_50  margin_top_10 date_color margin_right_1"><?php echo $this->formdata['createddate'];?>
            </div>
    </div>
	<?php } ?>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</form>
</div>
</div> <!-- End of .box -->
<script>
    $(window).load(function(){	
	$("#txtdesc").focus();
	
	})
</script>