<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">

jQuery("#search").jqGrid({        
   	url:base_url+"/reports/tabletrouteactivity/routeact/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route');?>','<?php echo $this->translate->_('Document#');?>','<?php echo $this->translate->_('Time In');?>','<?php echo $this->translate->_('Time Out');?>','<?php echo $this->translate->_('Customer Code');?>','<?php echo $this->translate->_('Customer Name');?>','<?php echo $this->translate->_('Type');?>','<?php echo $this->translate->_('Amount');?>'],
   	colModel:[
   		{name:'routecode',index:'routecode', width:100},
		{name:'documentnumber',index:'documentnumber', width:90},
		{name:'timeinhour',index:'timeinhour', width:70},
		{name:'timeouthour',index:'timeouthour', width:70},
		{name:'customercode',index:'customercode', width:90},
		{name:'customername',index:'customername', width:250},
		{name:'trantype',index:'trantype', width:90},
		{name:'tranamount',index:'tranamount', width:90, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }}		
   	],
	<?php if($this->css == 'ar_') { ?>
		direction :"rtl",
	<?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
    rowList:eval(RP_ROWLISTSHOW),
  //  loadonce:true,
    pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,        
	groupingView :
        {
            groupField : ['routecode'],
            groupColumnShow : [false],
            groupCollapse : true,
            groupOrder: ['asc'] ,
            groupSummary : [true],
            groupDataSorted : true,
            showSummaryOnHide: false
        }
});
jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});
</script>