<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
var column = <?php echo json_encode($this->column); ?>;
var column_config = <?php echo json_encode($this->column_config); ?>;
var display_column_config = [];

for(var i=0; i < column_config.length; i++)
{
    if(column_config[i] != "routecode" && column_config[i] != "salesmancode") {
        display_column_config.push({name:column_config[i],index:column_config[i], width:120, summaryType:'sum', align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false});
    } else if(column_config[i] == "salesmancode") {
        display_column_config.push({name:column_config[i],index:column_config[i], width:250});
    } else {
        display_column_config.push({name:column_config[i],index:column_config[i], width:120});
    }
}

jQuery("#search").jqGrid({
   	url:base_url+"/reports/routependingbalance/routependingbal/",
	datatype: "json",
   	colNames:column,
   	colModel:display_column_config,
    <?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
   	pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:false,
	sortorder: "desc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,
	groupingView :
    {
        groupField : ['routecode'],
        groupColumnShow : [false],
        groupCollapse : true,
        groupOrder: ['asc'] ,
        groupSummary : [true]
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);



jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});

</script>