<!-- Start of footer-->
<footer>
    <!--div class="container_12">Copyright &copy; <?php echo date('Y');?> Mirnah Technology Systems, all rights reserved.</div-->
    <!--<div class="container_12 footer"><a href="#nogo">Terms of Service</a> | <a href="#nogo">Privacy Policy</a> | Copyright &copy; <?php echo date('Y');?> Mirnah Technology Systems. All Rights Reserved.</div>-->
    <div class="container_12 footer"><a href="Javascript:void(0)">RoutePro SFA Cloud</a> | <a href="Javascript:void(0)">Version 1.0</a> | Copyright &copy; <?php echo date('Y');?> Mirnah Technology Systems. All Rights Reserved.</div>        
</footer><!-- End of footer-->
<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to
support IE 6.
chromium.org/developers/how-tos/chrome-frame-getting-started -->
<!--[if lt IE 7 ]>
<script defersrc="<?php echo $this->baseUrl(); ?>/public/js/CFInstall.min.js"></script>
<script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
<![endif]-->

<script type="text/javascript">
    var ua = $.browser;
    if(ua.msie && ua.version.slice(0,3) == '7.0') {
        $('form input[type=submit]').attr('style', 'text-align: center !important');
        $('form input[type=button]').attr('style', 'text-align: center !important');
    }
    $('#for_report_only #txt_route_start_date').val('<?php echo date('d-m-Y');?>');
    $('#for_report_only #txt_route_end_date').val('<?php echo date('d-m-Y');?>');
</script>
