<?php echo $this->doctype(); ?>
<?php
$this->translate = Zend_Registry::get('Zend_Translate');
$css = $this->translate->_('CSS');
$base_public = $this->baseUrl().'/public/';
$dir = "";
if($_COOKIE['lang'] !='' && isset($_COOKIE['lang'])) {
    $language = explode('_',$_COOKIE['lang']);
    $lang = $language[0];
    if($lang == "ar") {
        $dir = 'dir="RTL"';
    }
}
else
{
    $lang = 'en';
}
?>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="<?php echo $lang;?>" <?php echo $dir; ?>> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="<?php echo $lang;?>" <?php echo $dir; ?>> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="<?php echo $lang;?>" <?php echo $dir; ?>> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="<?php echo $lang;?>" <?php echo $dir; ?>><!--<![endif]-->
<head>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl().'/public/images/favicon.ico'; ?>" />
    <title>Mirnah SFA Cloud: RoutePro Middleware</title>
	<meta charset="utf-8">
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headStyle(); ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
	<script type="text/javascript">
	    var base_url = '<?php echo $this->baseUrl(); ?>';
	    var css	 = '<?php echo $css; ?>';	    
	</script>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/public/css/'.$css.'report.css'); ?>
	<!--[if IE]><script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl().'/public/js/excanvas.min.js';?>"></script><![endif]-->    
	<!--[if IE 7]><link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-7.css" /><![endif]-->
	<!--[if IE 8]><link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-8.css" /><![endif]-->
	<!--[if IE 9]><link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-9.css" /><![endif]-->    
	<!--[if lt IE 9]><![endif]-->
	
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/public/jqreport/themes/redmond/jquery-ui-custom.css'); ?>
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/public/jqreport/themes/ui.jqgrid.css'); ?>
	
	<script src="<?php echo $this->baseUrl().'/public/jqreport/js/jquery.js';?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl().'/public/jqreport/js/i18n/grid.locale-'.$lang.'.js';?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl().'/public/jqreport/js/jquery.jqGrid.min.js';?>" type="text/javascript"></script>
    
	<!--<script src="<?php //echo $this->baseUrl().'/public/jqreport/js/ui.multiselect.js';?>" type="text/javascript"></script>-->
	
	<!-- START -->
<script type="text/javascript">
    var message="";
    function clickIE() {if (document.all) {(message);return false;}}
    function clickNS(e) {
	if(document.layers||(document.getElementById&&!document.all)) {
	    if (e.which==2||e.which==3) {(message);return false;}}
	}
	if (document.layers){
	    document.captureEvents(Event.MOUSEDOWN);document.onmousedown=clickNS;
	}
    else {
	document.onmouseup=clickNS;document.oncontextmenu=clickIE;
    }
    document.oncontextmenu=new Function("return false")
</script>
<script type="text/javascript">
    function disableSelection(target){
	if (typeof target.onselectstart!="undefined")
	    target.onselectstart=function(){return false}
	else if (typeof target.style.MozUserSelect!="undefined")
	    target.style.MozUserSelect="none"
	else
	    target.onmousedown=function(){return false}
	    
	target.style.cursor = "default"
    }
</script>
	<script type="text/javascript">
	    var RP_NOOFRECORDSHOW = <?php echo $this->RP_NOOFRECORDSHOW; ?>;
	    var RP_ROWLISTSHOW = '<?php echo $this->RP_ROWLISTSHOW; ?>';
	    
	    var winheight = $(window).height();
	    var winwidth = $(window).width();
	    var reportwidth = winwidth + 120 ;

	</script>
	
	
	
</head>
<body>
    
    <div id="content" class="_100">
	<div id="content-wrapper" class="container_12" role="main" >
	   
	    <!--- Code Added by GPatel  ------------->
	    
	    <div class="clean"></div>
	    <div class="grid_12 margin_bottom_10" id="for_report_only">
	    <div class="box" id="report_basicreport_dailysalesreport">
	    <div class="_100">
            <div class="_50_3">
                <label class="_20 margin_0 text_align_left"><?php echo $this->translate->_($this->pageHeaderTitle).''.$this->translate->_('Colan'); ?></label>
                <div class="_30 report_margin_left_1"><?php echo $this->translate->_($this->pageHeadervalue); ?></div>
            </div>
	    </div>
	    <div class="_100">
            <div class="_40_3">
                <label class="_10 margin_0 text_align_left">&nbsp;</label>
                <div class="_100 report_margin_left_1 text_align_left"><h3><?php echo $this->translate->_($this->ReportTitle); ?></h3></div>
            </div>
	    </div>
        <?php if(isset($this->searchParams) && !empty($this->searchParams)) { ?>
            <div class="_100 report_margin_left_1">
                <?php foreach($this->searchParams as $key => $row) {
                    if($row["value"] != "")
                    { ?>
                        <label class="_15 margin_0 text_align_left"><?php echo $this->translate->_($row["title"]).''.$this->translate->_('Colan');?> </label>
                        <div class="_3 text_align_center"> &nbsp;</div>
                        <div class="_70 text_align_left"><?php echo $row["value"]; ?></div>
                        <div style="clear:both;"> </div>
                <?php }
                } ?>
            </div>
        <?php } ?>
        <div class="_100">&nbsp;</div>
	    <div class="_100  report_margin_left_1">
            <div>
                <?php
                //HC
                // Condtion to check the export link to avalible or not
                if(isset($this->xlsexport_link) && $this->xlsexport_link!= "" ||
                   isset($this->cvsexport_link) && $this->cvsexport_link!= "" )
                {
                ?>
                <label class="_15 margin_0 text_align_left"><?php echo $this->translate->_('Export As').''.$this->translate->_('Colan'); ?></label>
                <div class="_3 text_align_center"> &nbsp;</div>
                <div class="_70 text_align_left">
                <?php
                    if(isset($this->xlsexport_link) && $this->xlsexport_link!= "" )
                    {
                    echo '<a href="'.$this->xlsexport_link.'" id="xlsexport">XLS</a>&nbsp;';
                    }
                    
                    if(isset($this->cvsexport_link) && $this->cvsexport_link!= "" )
                    {
                    echo '<a href="'.$this->cvsexport_link.'" id="csvexport">CSV</a>';
                    }
                    ?>
                </div>
                <?php }
                ?>
                
            </div>
		</div>
	    
	    <div class="_100 margin_top_25">
		<div id="custom-grid">
		     <?php echo $this ->layout()-> content; ?>
		</div>
	    </div>
	    <div class=_100>
	    
	    </div>
	    </div> <!-- End of .box -->
	    </div>
	    
	    
	    <!------- Code End By Gpatel -------------->
	    
	    
	    
	    
	    
	    
	</div>
     </div>    
    <!--[if lt IE 7 ]>
    <script defer
    src="<?php echo $this->baseUrl().'/public/js/CFInstall.min.js';?>"></script>
    <script
    defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
    <![endif]-->
    
    <!-- For disable selection and right click -->
	<!-- START -->
	    <script type="text/javascript">
		disableSelection(document.body);
	    </script>
	<!-- END -->
    
    
    </body>
</html>
