<?php

$this->translate = Zend_Registry::get('Zend_Translate');
$css = $this->translate->_('CSS');

if($_COOKIE['lang'] !='' && isset($_COOKIE['lang'])) {
    $language = explode('_',$_COOKIE['lang']);
    $lang = $language[0];
}
else
{
    $lang = 'en';

}

?>
<!-- Added by hiren dave @ elan-->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta charset="utf-8">
<!-- Use the .htaccess and remove these lines to avoid edge case issues.
More info: h5bp.com/b/378 -->
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl().'/public/images/favicon.ico'; ?>" />
<title>Mirnah SFA Cloud: RoutePro Middleware</title>
<meta name="description" content="">
<meta name="author" content="Simon Stamm & Markus Siemens">
<!-- Mobile viewport optimized: j.mp/bplateviewport -->
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/reset.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/style.css" media="screen" />
<?php if($_COOKIE['css_color'] != '') { ?>
<link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/colors/<?php echo $lang.'_'.$_COOKIE['css_color'];?>" />
<?php } else {?>
<link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/colors/<?php echo $lang;?>_blue.css" />
<?php } ?>
<!-- Place favicon.ico and apple-touch-icon.png in the root directory:
mathiasbynens.be/notes/touch-icons -->

<title>Mirnah Technologies</title>

<script type="text/javascript">
    var base_url = '<?php echo $this->baseUrl(); ?>';
    var css	 = '<?php echo $css; ?>';
</script>

<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/public/css/960gs/'.$css.'fluid.css')
			    ->appendStylesheet($this->baseUrl().'/public/css/h5bp/'.$css.'normalize.css')
			    ->appendStylesheet($this->baseUrl().'/public/css/h5bp/'.$css.'non-semantic.helper.classes.css')
			    ->appendStylesheet($this->baseUrl().'/public/css/h5bp/'.$css.'print.styles.css')
			    ->appendStylesheet($this->baseUrl().'/public/css/'.$css.'special-page.css')
			    ->appendStylesheet($this->baseUrl().'/public/css/'.$css.'sprites.css')
			    ->appendStylesheet($this->baseUrl().'/public/css/'.$css.'typographics.css')
			    ->appendStylesheet($this->baseUrl().'/public/css/'.$css.'content.css')
			    ->appendStylesheet($this->baseUrl().'/public/css/'.$css.'sprite.forms.css')
                            ->appendStylesheet($this->baseUrl().'/public/css/'.$css.'langmenu.css');?>



    <!--[if IE 7]>
	    <link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-7.css" />
	    <link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-7-adminlogin.css" />
    <![endif]-->
    <!--[if IE 8]>    <link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-8.css" /> <![endif]-->
    <!--[if IE 9]>    <link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-9.css" /> <![endif]-->
    
<!-- For disable right click and selection of text by hiren dave on 06th march 2012 -->
<!-- START -->
<script type="text/javascript">
    var message="";
    function clickIE() {if (document.all) {(message);return false;}}
    function clickNS(e) {
	if(document.layers||(document.getElementById&&!document.all)) {
	    if (e.which==2||e.which==3) {(message);return false;}}
	}
	if (document.layers){
	    document.captureEvents(Event.MOUSEDOWN);document.onmousedown=clickNS;
	}
    else {
	document.onmouseup=clickNS;document.oncontextmenu=clickIE;
    }
    document.oncontextmenu=new Function("return false");
</script>
<script type="text/javascript">
    function disableSelection(target){
	if (typeof target.onselectstart!="undefined")
	    target.onselectstart=function(){return false}
	else if (typeof target.style.MozUserSelect!="undefined")
	    target.style.MozUserSelect="none"
	else
	    target.onmousedown=function(){return false}
	    
	target.style.cursor = "default"
    }
</script>
<!-- END -->
</head>
    
    <body class="special_page"  id="adminlogin">
	<div>
	    <img src="<?php echo $this->baseUrl();?>/public/images/bg.png" alt="" id="bgimg" >
	</div>
	<div class="top">
	    <!--<div class="gradient"></div>
	    <div class="white"></div>
	    <div class="shadow"></div>-->
	    
             <!--<div class="container_12 margin_top_20 logo">-->
	     <div class="container_12 logo">
		<div class="_50 text_align" style="height:65px; padding-bottom: 8px; position:absolute; z-index:425; top:10px;">
		    <a target="_blank" href="http://www.mirnah.com/">
			<img src="<?php echo $this->baseUrl();?>/public/images/original-Logo.png" alt="mirnah" title="Mirnah Technology Systems">
		    </a>
		</div>
	    </div>
            <div class="langname" >
                <div class="toolbar_large">
		        <div class="toolbutton">
                    <div class="toolmenu">
                        <div id="lang_switch" class="toolcaption padding_zero">
                            <?php if($lang == 'en'){?>
                            <div class="toolicon"><img class="margin_top_5" src="<?php echo $this->baseUrl()?>/public/images/en.png"></div><span>&nbsp;English&nbsp;</span>
                            <?php }else{?>
                            <div class="toolicon"><img class="margin_top_5" src="<?php echo $this->baseUrl()?>/public/images/ar.png"></div><span>&nbsp;Arabic&nbsp;</span>
                             <?php } ?>
                            </div>                          
                            <div class="dropdown padding_zero">
				<div id="switch_language">
                                <ul>
                                    <?php if($lang == 'en'){?>
                                    <li style="width:80px;">
                                        <div class="toolicon">
                                            <img class="margin_top_5" src="<?php echo $this->baseUrl()?>/public/images/ar.png">
                                        </div>&nbsp;<a href="<?php echo $this->url(array("controller"=>"index","action"=>"changelang",'lang'=>'ar_AR'), "default", true);?>" title="Arabic" alt="Arabic">Arabic</a>
                                    </li>
                                     <?php }else{?>
                                    <li style="width:80px;">
                                        <div class="toolicon">
                                            <img class="margin_top_5" src="<?php echo $this->baseUrl()?>/public/images/en.png">
                                        </div>&nbsp;<a href="<?php echo $this->url(array("controller"=>"index","action"=>"changelang",'lang'=>'en_US'), "default", true);?>" title="English" alt="English">English</a>
                                    </li>
                                    <?php } ?>
                                </ul>
                            </div>
			    </div>
                    </div>
                </div>
            
                </div>
            </div>
	</div>
	<div class="content c_align noSelect">	    
	    <!--<h1>RoutePro</h1>-->
	    <div class="_50 text_align">		
		<h1><img src="<?php echo $this->baseUrl()?>/public/images/route_logo.png"  alt="RoutePro" ></h1>	
	    </div>	    
	    <div class="background"></div>
	    <div class="wrapper">
		<?php if(SFA_Message::isSetMsg()) {  ?>
		<div class="alert error">
		    <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
		</div>
	    <?php } ?>
		<div class="box">
		    <div class="header grey">
			<img src="<?php echo $this->baseUrl(); ?>/public/img/icons/16X16/lock.png" width="16" height="16">
			<h3><?php echo $this->Login;?></h3>
		    </div>
		    <form method="post" action="" id="loginForm" >
			<div id="border_left_right" class="content no-padding min_height_10">
			    <div class="section _100">
				<label>
				    <?php echo $this->Username;?>
				</label>
				<div>
				    <input name="txtusername" value="<?php echo $this->username;?>" type="text" class="required text_align margin_bottom_10">
				</div>
			    </div>
			    <div class="section _100">
				<label>
				    <?php echo $this->Password;?>
				</label>
				<div>
				    <input name="txtpassword" value="<?php echo $this->password;?>" type="password" class="required text_align margin_bottom_10">
				</div>
			    </div>
			</div>
			
			
			<div class="login" id="chklogin">
			    <div class="login-left _80">
				<div for="newsletter">
				    <div class="_10">
					<input name="chkautologin" type="checkbox" <?php echo $this->autologin;?> value="1"/>
				    </div>
				    <div class="_80 font_size_12 margin_top_7" id="pwd_txt">
					<?php echo $this->Password_Remember;?>
				    </div>
				</div>
			    </div>
			    <div class="login-right" style="margin-top:11px;">
				<input type="submit" id="btnlogin" name="btnlogin" value="<?php echo $this->Login;?>" />
			    </div>
			</div>
			
			
		    </form>
		</div>		
	    </div>
	</div>


	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl(); ?>/public/js/libs/jquery-1.6.4.js"><\/script>')</script>
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
	<script>window.jQuery.ui || document.write('<script src="<?php echo $this->baseUrl(); ?>/public/js/libs/jquery-ui-1.8.16.min.js"><\/script>')</script>
	<!-- scripts concatenated and minified via build script -->
	<script defer src="<?php echo $this->baseUrl(); ?>/public/js/plugins.js"></script> <!-- REQUIRED: Different own jQuery plugnis -->
	<script defer src="<?php echo $this->baseUrl(); ?>/public/js/mylibs/<?php echo $css;?>jquery.validate.js"></script>
	<script defer src="<?php echo $this->baseUrl(); ?>/public/js/mylibs/jquery.jgrowl.js"></script>
	<script defer src="<?php echo $this->baseUrl(); ?>/public/js/mylibs/jquery.checkbox.js"></script>
	<script defer src="<?php echo $this->baseUrl(); ?>/public/js/script.js"></script> <!-- REQUIRED: Generic scripts -->
	<!-- end scripts -->	
	<script type="text/javascript">
	$(window).load(function(){
	    
	    
	    var ua = $.browser;
	    if(ua.msie && ( ua.version.slice(0,3) == '7.0' || ua.version.slice(0,3) == '8.0') && css == 'ar_') {
		$('#switch_language').css('width','78px');
	    }
	    else if(ua.msie && ua.version.slice(0,3) == '9.0' && css == 'ar_') {
		$('#switch_language').css('width','73px');
	    }
	    else if(ua.msie && ua.version.slice(0,3) == '8.0' && css == 'en_') {
		$('#switch_language').css('width','77px');
	    }
	    else if(ua.msie && ua.version.slice(0,3) == '9.0' && css == 'en_') {		
		$('#switch_language').css('width','80px');
	    }
	    /*
	     * Validate the form when it is submitted
	     */
	    <?php if($css == 'en_') { ?>
		var validatelogin = $("form").validate({
			invalidHandler: function(form, validator) {
				var errors = validator.numberOfInvalids();
				if (errors) {
					var message = errors == 1
					  ? "<?php echo  $this->translate->_('Missed One Field');?>"
					  : "<?php echo  $this->translate->_('You Missed');?> " + errors + ' "<?php echo  $this->translate->_('Fields. They have been highlighted.');?>"';
					$('.box .content').removeAlertBoxes();
					$('.box .content').alertBox(message, {type: 'warning', icon: true, noMargin: false});
					$('.box .content .alert').css({
						width: '',
						margin: '0',
						borderLeft: 'none',
						borderRight: 'none',
						borderRadius: 0
					});
				} else {
					$('.box .content').removeAlertBoxes();
				}
			},
			showErrors : function(errorMap, errorList) {
					this.defaultShowErrors();
					var self = this;
					$.each(errorList, function() {
						var $input = $(this.element);
						var $label = $input.parent().find('label.error').hide();
						$label.addClass('red');
						$label.css('width', '');
						$input.trigger('labeled');
						$label.fadeIn();
					});
			}			
		});

	    <?php } else  { ?>

		var validatelogin = $("form").validate({
			invalidHandler: function(form, validator) {
				var errors = validator.numberOfInvalids();
				if (errors) {
					var message = errors == 1
					  ? "<?php echo  $this->translate->_('Missed One Field');?>"
					  : "<?php echo  $this->translate->_('You Missed');?> " + errors + ' "<?php echo  $this->translate->_('Fields. They have been highlighted.');?>"';
					$('.box .content').removeAlertBoxes();
					$('.box .content').alertBox(message, {type: 'warning', icon: true, noMargin: false});
					$('.box .content .alert').css({
						width: '',
						margin: '0',
						textAlign: 'right'
					});
				} else {
					$('.box .content').removeAlertBoxes();
				}
			},
			showErrors : function(errorMap, errorList) {
			    this.defaultShowErrors();
			    var self = this;
			    $.each(errorList, function() {
				var $input = $(this.element);
				var $label = $input.parent().find('label.error').hide();
				$label.addClass('red');
				$label.css('width', '');
				$input.trigger('labeled');
				$label.fadeIn();
			    });
			}			
		});
	    <?php } ?>
	});
	</script>
	<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6. chromium.org/developers/how-tos/chrome-frame-getting-started -->
	<!--[if lt IE 7 ]>
	<script defersrc="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
	<script	defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
	<![endif]-->
	<style type="text/css">
	#adminlogin .content ._100:first-child{
	    margin-top: 0px !important;
	}
	</style>
	
	<script type="text/javascript">
	    disableSelection(document.body);
	    $(document).ready(function() {
		$("#lang_switch").click(function(){
		    $("#lang_switch").css('width','85px');		    
		    $(".dropdown").css('width','85px');		    
		})
	    });
	</script>
    </body>
</html>