<?php echo $this->doctype(); ?>
<?php
$this->translate = Zend_Registry::get('Zend_Translate');
$css = $this->translate->_('CSS');
$base_public = $this->baseUrl().'/public/';

if($_COOKIE['lang'] !='' && isset($_COOKIE['lang'])) {
    $language = explode('_',$_COOKIE['lang']);
    $lang = $language[0];
}
else
{
    $lang = 'en';
 
}
?>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
	<!--<![endif]-->
<head>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl().'/public/images/favicon.ico'; ?>" />
	<title>Mirnah SFA Cloud: RoutePro Middleware</title>
	<meta charset="utf-8">
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headStyle(); ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
	<script type="text/javascript">
	    var base_url = '<?php echo $this->baseUrl(); ?>';
	    var css	 = '<?php echo $css; ?>';	    
	</script>
	<style>
	#content { background-image:none !important}
	body
	{
		height: auto !important;
		background: #d1d1d1 !important;
	}
	</style>

	<!-- DNS prefetch -->
	<link rel=dns-prefetch href="//fonts.googleapis.com">
	<!-- Use the .htaccess and remove these lines to avoid edge case issues.
	More info: h5bp.com/b/378 -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- Mobile viewport optimized: j.mp/bplateviewport -->
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<!-- Place favicon.ico and apple-touch-icon.png in the root directory:mathiasbynens.be/notes/touch-icons -->
	
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/reset.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/style.css" media="screen" />
	<?php if($_COOKIE['css_color'] != '') { ?>
	    <link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/colors/<?php echo $lang.'_'.$_COOKIE['css_color'];?>" />
	<?php } else {?>
	    <link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/colors/<?php echo $lang;?>_blue.css" />
	<?php } ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/public/css/960gs/'.$css.'fluid.css')
			->appendStylesheet($this->baseUrl().'/public/css/h5bp/'.$css.'normalize.css')
			->appendStylesheet($this->baseUrl().'/public/css/h5bp/'.$css.'non-semantic.helper.classes.css')
			->appendStylesheet($this->baseUrl().'/public/css/h5bp/'.$css.'print.styles.css')			    
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'sprites.css')
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'header.css')
			->appendStylesheet($this->baseUrl().'/public/css/navigation.css')
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'content.css')
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'footer.css')
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'typographics.css')
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'ie.fixes.css')
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'sprite.forms.css')
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'sprite.tables.css')
			->appendStylesheet($this->baseUrl().'/public/css/pagegrid_style.css')
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'sidebar.css')
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'sprite.lists.css')			
			->appendStylesheet($this->baseUrl().'/public/css/external/'.$css.'jquery-ui-1.8.16.custom.css')
			->appendStylesheet($this->baseUrl().'/public/css/'.$css.'nav.css')
			->appendStylesheet($this->baseUrl().'/public/css/jquery.alerts.css');
	?>
	
    <script src="<?php echo $this->baseUrl().'/public/js/'.$css.'jquery-1.4.2.min.js';?>" type="text/javascript"></script>    
    <script src="<?php echo $this->baseUrl().'/public/js/'.$css.'smooth.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl().'/public/js/'.$css.'smooth.menu.js'?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl().'/public/js/common.js'?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl().'/public/js/jquery.alerts.js';?>" type="text/javascript"></script>
    <!--[if IE]><script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl().'/public/js/excanvas.min.js';?>"></script><![endif]-->
    <!--[if IE 7]>    <link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-7.css" /> <![endif]-->
    <!--[if IE 8]>    <link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-8.css" /> <![endif]-->
    <!--[if IE 9]>    <link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-9.css" /> <![endif]-->

    <!--[if lt IE 9]>
	<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<!-- For disable right click and selection of text by hiren dave on 06th march 2012 -->
<!-- START -->
<!--<script type="text/javascript">
    var message="";
    function clickIE() {if (document.all) {(message);return false;}}
    function clickNS(e) {
	if(document.layers||(document.getElementById&&!document.all)) {
	    if (e.which==2||e.which==3) {(message);return false;}}
	}
	if (document.layers){
	    document.captureEvents(Event.MOUSEDOWN);document.onmousedown=clickNS;
	}
    else {
	document.onmouseup=clickNS;document.oncontextmenu=clickIE;
    }
    document.oncontextmenu=new Function("return false")
</script>
<script type="text/javascript">
    function disableSelection(target){
	if (typeof target.onselectstart!="undefined")
	    target.onselectstart=function(){return false}
	else if (typeof target.style.MozUserSelect!="undefined")
	    target.style.MozUserSelect="none"
	else
	    target.onmousedown=function(){return false}
	    
	target.style.cursor = "default"
    }
</script>-->
<!-- END -->
</head>
<body class="body_bg">
	<div id="content_popup">
		<div id="content-wrapper" class="container_12" role="main">	
			<div id="main_content" style="width:100%;padding:0px 10px 20px 0px;">
				<?php echo $this ->layout()-> content; ?>
			</div>
		</div>
    </div>    
	
	<script src="<?php echo $this->baseUrl().'/public/js/jquery.min.js';?>" type="text/javascript"></script>
    <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl(); ?>/public/js/libs/jquery-1.6.4.js"><\/script>')</script>    
    <script src="<?php echo $this->baseUrl().'/public/js/jquery-ui.min.js';?>" type="text/javascript"></script>
    <script>window.jQuery.ui || document.write('<script src="<?php echo $this->baseUrl(); ?>/public/js/libs/jquery-ui-1.8.16.min.js"><\/script>')</script>
    <script src="<?php echo $this->baseUrl().'/public/js/plugins.js';?>" type="text/javascript"></script>    
    <script src="<?php echo $this->baseUrl().'/public/js/mylibs/jquery.ba-resize.js';?>" type="text/javascript"></script>    
    <script src="<?php echo $this->baseUrl().'/public/js/mylibs/jquery.easing.1.3.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl().'/public/js/mylibs/jquery.checkbox.js';?>"></script>
    <script src="<?php echo $this->baseUrl().'/public/js/mylibs/jquery.chosen.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl().'/public/js/mylibs/jquery.ui.touch-punch.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl().'/public/js/mylibs/jquery.dataTables.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl().'/public/js/mylibs/'.$css.'jquery.validate.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl().'/public/js/script.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl().'/public/js/jquery.prettyPhoto.js';?>" type="text/javascript"></script>
	
	<script type="text/javascript">
	    $(window).load(function() {
		    
		// Title on button
		// Start
		$('#btnexport').attr('title','Export');
		$('#btnprint').attr('title','Print');
		$('#btndelete').attr('title','Delete');
		$('#btnedit').attr('title','Edit');
		$('#btnadd').attr('title','Add');
		$('#btnsave').attr('title','Save');
		$('#btncancel').attr('title','Cancel');
		$('#btnsync').attr('title','Sync');
		$('#btndwnsync').attr('title','Sync');
		// End
		$(function() {
			
			$( "#txtstartdate" ).datepicker({
			    dateFormat: 'dd/mm/yy'
			});
			
			$( "#txtenddate" ).datepicker({
			    dateFormat: 'dd/mm/yy'
			});
			
			$("#txtstartdate").change(function() {
			    var startDate = $('#txtstartdate').val();
			    $("#txtenddate").datepicker( "option", "minDate",startDate);
			});
			
			$("#txtenddate").change(function() {
			    var endDate = $('#txtenddate').val();
			    $("#txtstartdate").datepicker( "option", "maxDate",endDate);
			});
			
		});
	    });
    </script>
	<!--[if lt IE 7 ]>
	<script defer
	src="<?php echo $this->baseUrl().'/public/js/CFInstall.min.js';?>"></script>
	<script
	defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
	<![endif]-->
	<!-- For disable selection and right click -->
	<!-- START -->
	    <script type="text/javascript">
		//disableSelection(document.body);
	    </script>
	<!-- END -->
</body>
</html>