<?php echo $this->doctype(); ?>
<?php
$this->translate = Zend_Registry::get('Zend_Translate');
$css = $this->translate->_('CSS');
$base_public = $this->baseUrl().'/public/';

if($_COOKIE['lang'] !='' && isset($_COOKIE['lang'])) {
    $language = explode('_',$_COOKIE['lang']);
    $lang = $language[0];
}
else
{
    $lang = 'en';
 
}
?>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
	<!--<![endif]-->
<head>
	<title>Mirnah Technology Systems</title>
	<meta charset="utf-8">
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headStyle(); ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
	<script type="text/javascript">
	    var base_url = '<?php echo $this->baseUrl(); ?>';
	    var css	 = '<?php echo $css; ?>';	    
	</script>
	
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/public/css/'.$css.'report.css'); ?>
	
	
	<!--[if IE]><script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl().'/public/js/excanvas.min.js';?>"></script><![endif]-->    
	<!--[if IE 7]><link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-7.css" /><![endif]-->
	<!--[if IE 8]><link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-8.css" /><![endif]-->
	<!--[if IE 9]><link id="color" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/browser/ie-9.css" /><![endif]-->    
	<!--[if lt IE 9]>
	    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
<!-- For disable right click and selection of text by hiren dave on 06th march 2012 -->
<!-- START -->
<script type="text/javascript">
    var message="";
    function clickIE() {if (document.all) {(message);return false;}}
    function clickNS(e) {
	if(document.layers||(document.getElementById&&!document.all)) {
	    if (e.which==2||e.which==3) {(message);return false;}}
	}
	if (document.layers){
	    document.captureEvents(Event.MOUSEDOWN);document.onmousedown=clickNS;
	}
    else {
	document.onmouseup=clickNS;document.oncontextmenu=clickIE;
    }
    document.oncontextmenu=new Function("return false")
</script>
<script type="text/javascript">
    function disableSelection(target){
	if (typeof target.onselectstart!="undefined")
	    target.onselectstart=function(){return false}
	else if (typeof target.style.MozUserSelect!="undefined")
	    target.style.MozUserSelect="none"
	else
	    target.onmousedown=function(){return false}
	    
	target.style.cursor = "default"
    }
</script>
<!-- END -->
</head>
<body>
    <div id="content" class="_100">
	<div id="content-wrapper" class="container_12" role="main">
	    <?php echo $this ->layout()-> content; ?>
	</div>
     </div>    
    <!--[if lt IE 7 ]>
    <script defer
    src="<?php echo $this->baseUrl().'/public/js/CFInstall.min.js';?>"></script>
    <script
    defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
    <![endif]-->
    
    <!-- For disable selection and right click -->
	<!-- START -->
	    <script type="text/javascript">
		disableSelection(document.body);
	    </script>
	<!-- END -->
</body>
</html>