<?php

    $modulename 	= Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
    $controllername 	= Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
    $actionname 	= Zend_Controller_Front::getInstance()->getRequest()->getActionName();

?>
<aside>
    <div id="sidebar_content">	    
	<div id="content" style="background:none;">
	    <div id="left">
		<div id="menu">			
			<h6 <?php if($modulename == 'admin') { echo 'class="selected"'; }?> id="h-menu-pages"><a href="#pages"><span class="icon"><div class="sidebar_img"><img src="<?php echo $this->baseUrl()?>/public/images/icon_administration.png" alt="Administration" /></div><div class="sidebar_menu_text">Administration</div></span></a></h6>
			<ul <?php if($modulename == 'admin') { echo 'class="opened"'; } else { echo 'class="closed"'; } ?> id="menu-pages">
			    <li <?php if($modulename == 'admin' && $controllername == 'index' && $actionname == 'index' ) { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"index","action"=>"index"), "default", true);?>">Basic Setup</a></li>
				<li <?php if($modulename == 'admin' && $controllername == 'cpanel') { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cpanel","action"=>"index"),"default",true);?>">Control Panel</a></li>
			    <li class="collapsible last">
				<a <?php if($controllername == 'security' && $modulename == "admin") { echo 'class="collapsible minus"'; } else { echo 'class="collapsible plus"'; } ?>  href="javascript:void(0)">System Security</a>
				<ul <?php if($controllername == 'security' && $modulename == "admin") { echo 'class="expanded"'; } else { echo 'class="collapsed"'; } ?>>
				    <li <?php if($modulename == 'admin' && $controllername == 'security' && ($actionname == 'usertype' || $actionname == 'addusertype')) { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"usertype"), "default", true);?>" >User Type</a></li>
				    <li <?php if($modulename == 'admin' && $controllername == 'security' && ($actionname == 'user' || $actionname == 'adduser')) { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"user"), "default", true);?>">User Master</a></li>
				    <li <?php if($modulename == 'admin' && $controllername == 'security' && $actionname == 'userpermission') { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"userpermission"), "default", true);?>">User Permission</a></li>
				    <!-- <li <?php if($modulename == 'admin' && $controllername == 'security' && $actionname == 'pwdgenerate' ) { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"pwdgenerate"), "default", true);?>">Password Generator</a></li> -->
					<li <?php if($modulename == 'admin' && $controllername == 'security' && $actionname == 'deviceregistration' ) { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"deviceregistration"), "default", true);?>">Device Registration</a></li>
				    <!--<li><a href="javascript:void(0)"  class="cursor_default">Generate Import Files</a></li>-->
				</ul>
			    </li>
			</ul>					
			<h6 <?php if($modulename == 'datamanagement') { echo 'class="selected"'; }?> id="h-menu-settings"><a href="#settings"><span class="icon"><div class="sidebar_img"><img src="<?php echo $this->baseUrl()?>/public/images/icon_datamanagement.png" alt="Data Management" /></div><div class="sidebar_menu_text">Data Management</div></span></a></h6>
			<ul <?php if($modulename == 'datamanagement') { echo 'class="opened"'; } else { echo 'class="closed"'; } ?> id="menu-settings">				
			    <li <?php if($modulename == 'datamanagement' && $actionname == 'deletedata')  { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"datamanagement","controller"=>"index","action"=>"deletedata"), "default", true);?>">Delete Data</a></li>
			    <li <?php if($modulename == 'datamanagement' && $actionname == 'deletetrxndata')  { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"datamanagement","controller"=>"index","action"=>"deletetrxndata"), "default", true);?>">Delete Transactions By Route</a></li>
			    <li <?php if($modulename == 'datamanagement' && $actionname == 'viewlogdata')  { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"datamanagement","controller"=>"index","action"=>"viewlogdata"), "default", true);?>">View Activity Log</a></li>
				<!-- <li <?php if($modulename == 'datamanagement' && $actionname == 'upsync')  { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"datamanagement","controller"=>"index","action"=>"upsync"), "default", true);?>">Export  </a></li>
			    <li <?php if($modulename == 'datamanagement' && $actionname == 'downsync')  { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"datamanagement","controller"=>"index","action"=>"downsync"), "default", true);?>">Import  </a></li>-->
			    
			</ul>
				<h6 <?php if($modulename == 'integration') { echo 'class="selected"'; }?> id="h-menu-sap"><a href="#sap"><span class="icon"><div class="sidebar_img"><img src="<?php echo $this->baseUrl()?>/public/images/Sync.png" alt="Management" /></div><div class="sidebar_menu_text">Integration</div></span></a></h6>
			<ul <?php if($modulename == 'integration') { echo 'class="opened"'; } else { echo 'class="closed"'; } ?> id="menu-sap">				
			    
				 
			    <li <?php if($modulename == 'integration' && $actionname == 'routeprosync')  { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"integration","controller"=>"index","action"=>"routeprosync"), "default", true);?>">Import  </a></li>
				<li <?php if($modulename == 'integration' && $actionname == 'oracleupdate')  { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"integration","controller"=>"index","action"=>"oracleupdate"), "default", true);?>">Export  </a></li>
				<li <?php if($modulename == 'integration' && $actionname == 'importcsv')  { echo 'class="selected"'; } ?>><a href="<?php echo $this->url(array("module"=>"integration","controller"=>"import","action"=>"importcsv"), "default", true);?>">Import CSV/XLS</a></li>
			    
			</ul>
			
		</div>
	    </div>
    </div>
<!-- end content / left -->
    </div>
</aside>