<?php
/**
* @name       routetmpl.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of Route Template
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');
$url = $this->url(array("module"=>"organization","controller"=>"route","action"=>"routetmpl","edit"=>"yes"),"default", true);
$new = $this->url(array("module"=>"organization","controller"=>"route","action"=>"routetmpl"),"default", true);
?>
<script>
$(document).ready(function() {
    
    $(".tab_content").hide();
    $("#tab1").show();
    $("ul.tabs li").click(function() {
	$("ul.tabs li a").removeClass("admin_active"); //Remove any "active" class
	$(this).find("a").addClass("admin_active");
	$(".tab_content").hide(); //Hide all tab content
	var activeTab = $(this).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
	$(activeTab).fadeIn(); //Fade in the active content
	return false;
    });
    
    $("#btnload").click(function(){
	window.location = '<?php echo $new;?>';
    });
    
    $('#ddlroutetmpl').change(function(){	
	if(this.value > 0) {
	    window.location = '<?php echo $url;?>/id/'+this.value;
	}
    });
    
    $('.tab_link').click(function(){
	
	if(this.id == 't1')
	{
	    $('#ddlroutetmpl_chzn .chzn-drop .chzn-search input[type="text"]').focus();
	    $('#ddlroutetmpl_chzn').addClass('chzn-container-active');	    
	}
	else if(this.id == 't2')
	{
	    $('#ddlprmpt_odometer_chzn .chzn-drop .chzn-search input[type="text"]').focus();
	    $('#ddlprmpt_odometer_chzn').addClass('chzn-container-active');
	}
	else if(this.id == 't3')
	{
	    $('#ddleod_nosale_chzn .chzn-drop .chzn-search input[type="text"]').focus();
	    $('#ddleod_nosale_chzn').addClass('chzn-container-active');	    
	}	
    });
    $('#ddlroutetmpl_chzn .chzn-drop .chzn-search input[type="text"]').focus();
    $('#ddlroutetmpl_chzn').addClass('chzn-container-active');
    
    
    

});
</script>
<div class="clean"></div>
<div class="grid_12" id="organization_route_routetmpl" >
<?php if(SFA_Message::isErrorMsg()) {  ?>
<div class="alert error">
    <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
</div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="box" id="chk_margin_0">
<form id="frmdetail" name="frmdetail" class="validate" novalidate action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_org.png">
	<h3><?php echo $this->translate->_('Route Template');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"organization","controller"=>"route","action"=>"routetmpl"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">	    
	    <ul style="display: block;" class="tabs">
		<li> 
		    <a href="#tab1" id="t1" class="admin_active tab_link"><?php echo $this->general;?></a>
		</li>
		<li>
		    <a href="#tab2" id="t2" class="tab_link"><?php echo $this->setting1;?></a>
		</li>		
		<li class="last-child">
		    <a href="#tab3" id="t3" class="tab_link"><?php echo $this->setting2;?></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
   <div class="content no-padding with-actions">
	<div id="tab1" class="tab_content">
	    <?php include('routetmplgeneral.phtml');?>
	</div>
	<div id="tab2" class="tab_content">
	    <?php include('tmplsetting1.phtml');?>
	</div>
	<div id="tab3" class="tab_content">
	    <?php include('tmplsetting2.phtml');?>
	</div>	
    </div>
   <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</form>
</div> <!-- End of .box -->
</div>
<script>
$(window).unload(function(){
    $("#tab2").hide();
    $("#tab3").hide();
});
</script>