<?php
/**
* @name       index.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script type="text/javascript">
	$(document).ready(function() {
		$(".tab_content").hide();
		$("#tab1").show();
		$("ul.tabs li").click(function() {
			$("ul.tabs li a").removeClass("admin_active"); //Remove any "active" class
			$(this).find("a").addClass("admin_active");
			$(".tab_content").hide(); //Hide all tab content
			var activeTab = $(this).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
			$(activeTab).fadeIn(); //Fade in the active content
			return false;
		});		
	});
</script>
<div class="clean"></div>
<div class="grid_12" id="organization_route_addroute" >
<div class="box" id="chk_margin_0">
<form id="frmdetail" name="frmdetail" class="validate" novalidate action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_org.png">
	<h3><?php echo $this->translate->_('Route');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"organization","controller"=>"route","action"=>"route"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul>
		<li>
		    <a href="<?php echo $this->url(array("module"=>"organization","controller"=>"route","action"=>"route"),"default", true);?>"><?php echo $this->overview?></a>
		</li>
	    </ul>
	    <ul style="display: block;  margin-left:75px;" class="tabs">

		<li> 
		    <a id="xtab1" href="#tab1" class="admin_active"><?php echo $this->general;?></a>
		</li>
		<li>
		    <a id="xtab2" href="#tab2"><?php echo $this->setting1;?></a>
		</li>
		<li>
		    <a id="xtab3" href="#tab3"><?php echo $this->setting2;?></a>
		</li>
		<li class="last-child">
		    <a id="xtab4" href="#tab4"><?php echo $this->reports;?></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>

    <div class="content no-padding with-actions">
	<div id="tab1" class="tab_content">
	    <?php include('general.phtml');?>
	</div>
	<div id="tab2" class="tab_content">
	    <?php include('setting1.phtml');?>
	</div>
	<div id="tab3" class="tab_content">
	    <?php include('setting2.phtml');?>
	</div>
	<div id="tab4" class="tab_content">
	    <?php include('reports.phtml');?>
	</div>
    </div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</form>
</div> <!-- End of .box -->
</div>
<script>    
    $(window).unload(function() {
		$("#tab2").hide();
		$("#tab3").hide();
		$("#tab4").hide(); 
    });
</script>