<?php
/**
* @name       index.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/
$this->translate = Zend_Registry::get('Zend_Translate');
$url = $this->url(array("module"=>"organization","controller"=>"route","action"=>"addroute"),"default", true);
?>
<script type="text/javascript">
	$(document).ready(function() {
		$('#modified_60 input:text').attr('maxlength','1');
		$('#ddlcompany_chzn .chzn-drop .chzn-search input[type="text"]').focus();
		$('#ddlcompany_chzn').addClass('chzn-container-active');
		
		$('#btnload').click(function(){
			
			var val = $("#ddltempl").val();
			if(val > 0) {
				window.location = '<?php echo $url;?>/id/'+val+'/tmpl/1';								  
			}
		});
		<?php if(!isset($this->params["id"])) { ?>
			$('#sec_assign [type=text]').val('0');
		<?php } ?>
		
		$('#div_ddlcustomercode').hide();
		<?php if($this->formdata_setting2['enableautopostingaccount'] == 1) { ?>
			$('#div_ddlcustomercode').show();
			$('#ddlcustomercode').addClass('required');
		<?php } ?>
		
		$('#chkenableautopostingaccount').click(function(){
			
			var dx = $('#chkenableautopostingaccount').is(':checked');
			
			if(!dx) {
				$('#div_ddlcustomercode').show();
				$('#ddlcustomercode').addClass('required');
			} else {
				$('#div_ddlcustomercode').hide();
				$('#ddlcustomercode').removeClass('required');
			}
		})
		
		$('#btnsave').click(function(){
			if($('#ddlcustomercode').val() == '' && $('#chkenableautopostingaccount').attr("checked") == 'checked'){
				$('#xtab1').removeClass('admin_active');
				$('#xtab3').addClass('admin_active');
				$('#ddlcustomercode_chzn .chzn-drop .chzn-search input[type="text"]').focus();
				$('#ddlcustomercode_chzn').addClass('chzn-container-active');
				$('#tab1').hide();
				$('#tab2').hide();
				$('#tab3').show();
				$('#tab4').hide();
			}
		})
	});
	function chack_val(val)
	{
		if(val.value > 5)
		{
			jAlert("Value Must Be Between 0 to 5.");
			val.value = '0';
			return false;
		}
	}
</script>
    <div class="content with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<fieldset>
	    <legend><?php echo $this->general?></legend>
		<?php if($this->params["edit"]=="") { ?>
	    <div class="_100 ">
		<label class="_36 margin_left_0 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Template ID').''.$this->colan;?>
		</label>
		<div class="_36 margin_left_1 margin_right_1">
		    <select id="ddltempl" name="ddltempl">
			<option value="">--- Select ---</option>
			<?php
			for($i=0;$i<count($this->routetemplate);$i++)
			{
			?>
			    <option <?php echo ($this->route_tmplval == $this->routetemplate[$i]['id']) ? 'selected' : '';?> value="<?php echo $this->routetemplate[$i]['id'];?>"><?php echo $this->routetemplate[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
		<div class="_10 margin_left_2">
		    <input type="button" name="btnload" class="margin_top_7" id="btnload" value="<?php echo $this->translate->_('LOAD');?>" >
		</div>		
	    </div>
		<?php } ?>
	    <div class="_100">
			<label class="_25_1 margin_top_12 label_text_align margin_left_2_1">
				<?php echo $this->translate->_('Code').''.$this->required;?>
			</label>
			<div class="_25_1  margin_right_1">
				<input type="text" class="required" id="txtcode" name="txtcode" value="<?php echo $this->formdata['txtcode']; ?>" <?php if($this->formdata['txtaltcode']!="") { ?> readonly= "true" <?php } ?>>
			</div>
			<label class="_20_2 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Company').''.$this->required;?>
			</label>
			<div class="_25_1 ">
				<select id="ddlcompany" name="ddlcompany" class="required">
				<option value="">--- Select ---</option>
				<?php
				for($i=0;$i<count($this->com_data);$i++)
				{
				?>
					<option value="<?php echo $this->com_data[$i]['id'];?>" <?php echo $this->com_data[$i]['id'] == $this->formdata['company_code'] ? 'selected' : '';?>><?php echo $this->com_data[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div> 
	    </div>
	    <div class="_100"> 
			<label class="_25_1 margin_top_10 label_text_align margin_left_2_1">
				<?php echo $this->translate->_('Alternate Code').''.$this->required;?>
			</label>
			<div class="_25_1 margin_right_1">
				<input type="text" class="required margin_top_5" maxlength="50"  id="txtaltcode"  name="txtaltcode" value="<?php echo $this->formdata['txtaltcode'];?>">
			</div>
			<label class="_20_2 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Region').''.$this->required;?>
			</label>
			<div class="_25_1">				
				<select id="ddlregion" name="ddlregion" class="required">
				<option value="">--- Select ---</option>
				<?php
				for($i=0;$i<count($this->region_data);$i++)
				{
				?>
					<option value="<?php echo $this->region_data[$i]['id'];?>" <?php echo $this->region_data[$i]['id'] == $this->formdata['region_code'] ? 'selected' : '';?>><?php echo $this->region_data[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div>
	    </div>
	    <div class="_100">
			<label class="_25_1 margin_top_10 label_text_align margin_left_2_1">
				<?php echo $this->translate->_('Route Name').''.$this->required;?>
			</label>
			<div class="_25_1  margin_right_1">
				<input type="text" id="txtroute_name" name="txtroute_name"  maxlength="50" value="<?php echo $this->formdata['txtroute_name'];?>" class="text_align margin_top_4 required" >
			</div>
			<label class="_20_2 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Sub Area').''.$this->required;?>
			</label>
			<div class="_25_1 margin_right_2">
				<select id="ddlsubarea" class="margin_top_5 required" name="ddlsubarea">
				<option value="">--- Select ---</option>
				<?php
				for($i=0;$i<count($this->subarea_data);$i++)
				{
				?>
					<option value="<?php echo $this->subarea_data[$i]['id'];?>" <?php echo $this->subarea_data[$i]['id'] == $this->formdata['subarea'] ? 'selected' : '';?>><?php echo $this->subarea_data[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div>
	    </div>
	    <div class="_100">
			<label class="_25_1 margin_top_10 label_text_align margin_left_2_1">
				<?php echo $this->translate->_('Name ('.$this->sec_lang.')').$this->colan;?>
			</label>
			<div class="_25_1 margin_right_1">
				<input type="text" id="txtsecond_lang"  maxlength="50"  name="txtsecond_lang" class="margin_top_4" value="<?php echo $this->formdata['txtsecond_lang'];?>">
			</div>
			<label class="_20_2 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Salesman').''.$this->required;?>
			</label>
			<div class="_25_1 margin_right_2">
				<select id="ddlsalesman" name="ddlsalesman" class="required">
				<option value="">--- Select ---</option>
				<?php
				for($i=0;$i<count($this->salesman_data);$i++)
				{
				?>
					<option value="<?php echo $this->salesman_data[$i]['id'];?>" <?php echo $this->salesman_data[$i]['id'] == $this->formdata['salesman'] ? 'selected' : '';?>><?php echo $this->salesman_data[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div>		
	    </div>		
		<div class="_100">
			<label class="_25_1 margin_top_12 label_text_align margin_left_2_1">
				<?php echo $this->translate->_('Van').''.$this->colan;?>
			</label>
			<div class="_25_1 margin_right_1">
				<select id="ddlvan" name="ddlvan" class="">
				<option value="">--- Select ---</option>
				<?php
				for($i=0;$i<count($this->van_data);$i++)
				{
				?>
					<option value="<?php echo $this->van_data[$i]['id'];?>" <?php echo $this->van_data[$i]['id'] == $this->formdata['van'] ? 'selected' : '';?>><?php echo $this->van_data[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div>
			<label class="_20_2 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Route Category').''.$this->colan;?>
			</label>
			<div class="_25_1 margin_right_2">
				<select id="ddlbusi_type" name="ddlbusi_type">
				<option value="0">--- Select ---</option>
				<?php
				for($i=0;$i<count($this->route_data);$i++)
				{
				?>
					<option value="<?php echo $this->route_data[$i]['id'];?>" <?php echo ($this->route_data[$i]['id'] == $this->formdata['ddlbusi_type']) ? 'selected' : '';?>><?php echo $this->route_data[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div>
	    </div>
	    <div class="_100">
			<label class="_25_1 margin_top_12 label_text_align margin_left_2_1">
				<?php echo $this->translate->_('Route Type').''.$this->colan;?>
			</label>
			<div class="_25_1 margin_right_1">
				<select id="ddlroutetype" name="ddlroutetype">
				<?php 
				for($i=0;$i<count($this->route_type);$i++)
				{
				?>
					<option value="<?php echo $this->route_type[$i]['id'];?>" <?php if($this->route_type[$i]['id'] == $this->formdata['ddlroutetype']){ echo 'selected'; }?>><?php echo $this->route_type[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div>
			<label class="_20_2 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Status').''.$this->colan;?>
			</label>
			<div class="_25_1 margin_right_2">
				 <select id="ddlstatus" name="ddlstatus">
				<option value="1" <?php if($this->formdata['active_status'] == '1'){ echo 'selected';}?>><?php echo $this->translate->_('Active');?></option>
				<option value="0" <?php if($this->formdata['active_status'] == '0'){ echo 'selected';}?>><?php echo $this->translate->_('Inactive');?></option>
				</select>
			</div>
		</div>
		
		 
		
		<!---->
	    <div class="_100">
			<label class="_25_1 margin_top_12 label_text_align margin_left_2_1">
				<?php echo $this->translate->_('Device Assigned').''.$this->colan;?>
			</label>
			<div class="_25_1 margin_right_1">
				<select id="device_assigned" name="device_assigned" class="">
				<option value="">--- Select ---</option>
				<?php
				
				for($i=0;$i<count($this->deviceinfo);$i++)
				{
				?>
					<option value="<?php echo $this->deviceinfo[$i]['device_id'];?>" <?php echo $this->deviceinfo[$i]['device_id'] == $this->formdata['device_assigned_id'] ? 'selected' : '';?>><?php echo $this->deviceinfo[$i]['device_id'];?></option>
				<?php } ?>
				</select>
			</div>
			
			<label class="_20_2 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Route Item Group').''.$this->colan;?>
			</label>
			<div class="_25_1 margin_right_2">
			<select id="ddlrouteitemgrpcode" name="ddlrouteitemgrpcode">		    
				<?php
				for($i=0;$i<count($this->itemgroupcode);$i++)
				{
				?>
					<option value="<?php echo $this->itemgroupcode[$i]['id'];?>" <?php if($this->itemgroupcode[$i]['id'] == $this->formdata_setting1['routeitemgrpcode']){ echo 'selected'; }?>><?php echo $this->itemgroupcode[$i]['val'];?></option>
				<?php } ?>
			</select>
			</div>
			
			
			
	    </div>
		
		<div class="_100">
			<?php if($this->status[3]['status'] == 1) { ?>
			<label class="_25_1 margin_top_12 label_text_align margin_left_2_1">
				<?php echo $this->translate->_('Item Must List').''.$this->colan;?>
			</label>			
			<div class="_25_1 margin_right_1">
				<select id="ddlitemmustkey" name="ddlitemmustkey">
				<option value="">--- Select ---</option>
				<?php
				for($i=0;$i<count($this->itemmust_key_data);$i++)
				{
				?>
					<option <?php echo $this->itemmust_key_data[$i]['id'] == $this->formdata['ddlitemmustkey'] ? 'selected' : '';?> value="<?php echo $this->itemmust_key_data[$i]['id'];?>"><?php echo $this->itemmust_key_data[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div>
			<?php } ?>
			
			<div id="chk" class="_20_2">		    
				<input type="checkbox" id="chkallow_chng" name="chkallow_chng" <?php if($this->formdata['pre_sales_order'] == '1'){ echo 'checked=true';}?> value="1">
			</div>
			<label class="_25_1 margin_top_10">
				<?php echo $this->translate->_('Allow Change Salesman');?>
			</label>
			
		</div>
		<!---->
			<div class="_100">
			
			<div id="chk" class="_20_2" style="margin-left:5%;">		    
				<input type="checkbox" id="chkdepot_route" name="chkdepot_route" <?php if($this->formdata['depotroute'] == '1'){ echo 'checked';}?> value="1">
			</div>
			<label class="_25_1 margin_top_10">
				<?php echo $this->translate->_('Depot Route');?>
			</label>
			
			
		
	    </div>
		<!---->
		<div class="_100">			
			<?php if($this->params["edit"]=="yes") { ?>
			<label class="_25_1 margin_top_12 label_text_align margin_left_2_1">
				<?php echo $this->translate->_('Created Date').''.$this->colan;?>
			</label>
			<div class="_25_1 margin_top_12 date_color margin_right_1"><?php echo  $this->formdata['createddate'];?></div>
			<?php } else { ?>
			<div class="_50_3">&nbsp;</div>
			<?php } ?>
		</div>
	</fieldset>
	<fieldset class="_30 margin_left_0 margin_right_0" id="input_textarea_94">
	    <legend><?php echo $this->translate->_('Security Password');?></legend>
	    <div class="_100 margin_top_10">
		<label class="_50 label_text_align margin_top_12">
		    <?php echo $this->translate->_('Password').' 1'.''.$this->colan;?>
		</label>
		<div class="_36">
		    <input type="text" id="txtpwd1" name="txtpwd1" maxlength="6" class="number" value="<?php echo $this->formdata['txtpwd1'];?>">
		</div>
	    </div>
	    	    <div class="_100">
		<label class="_50 label_text_align margin_top_12">
		    <?php echo $this->translate->_('Password').' 2'.''.$this->colan;?>
		</label>
		<div class="_36">
		    <input type="text" id="txtpwd2" name="txtpwd2" maxlength="6" class="number"  value="<?php echo $this->formdata['txtpwd2'];?>">
		</div>
	    </div>
	    <div class="_100">
		<label class="_50 label_text_align margin_top_12">
		    <?php echo $this->translate->_('Password').' 3'.''.$this->colan;?>
		</label>
		<div class="_36">
		    <input type="text" id="txtpwd3" name="txtpwd3" maxlength="6" class="number"   value="<?php echo $this->formdata['txtpwd3'];?>">
		</div>
	    </div>
	    <div class="_100">
		<label class="_50 label_text_align margin_top_12">
		    <?php echo $this->translate->_('Password').' 4'.''.$this->colan;?>
		</label>
		<div class="_36">
		    <input type="text" id="txtpwd4" name="txtpwd4" maxlength="6" class="number"   value="<?php echo $this->formdata['txtpwd4'];?>">
		</div>
	    </div>
	    <div class="_100">
		<label class="_50 label_text_align margin_top_12">
		    <?php echo $this->translate->_('Password').' 5'.''.$this->colan;?>
		</label>
		<div class="_36">
		    <input type="text" id="txtpwd5" name="txtpwd5" maxlength="6" class="number"  value="<?php echo $this->formdata['txtpwd5'];?>">
		</div>
	    </div>
	</fieldset>
	<div id="modified_60">
	    <fieldset class="_70" id="sec_assign">
		<legend><?php echo $this->translate->_('Security Assignment');?></legend>
		<div class="_100 margin_top_10">
		   <!-- <label class="_20 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Route Setup').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtrt_setup"  maxlength="1"   name="txtrt_setup"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtrt_setup'];?>">
		    </div> -->
		      		
		    <!--<label class="_30 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Telecom Setup').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txttel_setup"  maxlength="1" name="txttel_setup"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txttel_setup'];?>">
		    </div>-->
		</div>
		<div class="_100">
		    <label class="_20 margin_top_12 label_text_align">
				<?php echo $this->translate->_('View Van Stock').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtnewreq"  maxlength="1"   name="txtnewreq"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtnewreq'];?>">
		    </div>		
		   <!-- <label class="_23 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Application Exit').''.$this->colan;?>
		    </label>
		    <div class="_10">
				<input type="text" id="txtapp_exit"  maxlength="1"   name="txtapp_exit"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtapp_exit'];?>">
		    </div> -->
		    <label class="_23 margin_top_12 label_text_align">		
				<?php echo $this->translate->_('Un Load').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtunload" maxlength="1"  name="txtunload"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtunload'];?>">
		    </div>    
		</div>
		<div class="_100">
		    <label class="_20 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Start Of Day').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtst_day"  maxlength="1"   name="txtst_day"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtst_day'];?>">
		    </div>
		    <label class="_23 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Price Change').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtpr_chng"  maxlength="1"   name="txtpr_chng" class="number"  onblur="return chack_val(this);" value="<?php echo $this->formdata['txtpr_chng'];?>">
		    </div>	
			<label class="_30 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Load Request').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtload_req"  maxlength="1" name="txtload_req"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtload_req'];?>">
		    </div>  	
		   <!-- <label class="_30 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Date/Time Change').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtdt_time"  maxlength="1"   name="txtdt_time"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtdt_time'];?>">
		    </div>-->
		</div>
		<div class="_100">
		    <label class="_20 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Promo Override').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtpromo_ovr"  maxlength="1"   name="txtpromo_ovr"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtpromo_ovr'];?>">
		    </div>		
		    <label class="_23 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Load In').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtload_out"  maxlength="1"  name="txtload_out"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtload_out'];?>">
		    </div>
		    <label class="_30 margin_top_12 label_text_align">		
				<?php echo $this->translate->_('Settlement').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtsettl"  maxlength="1"  name="txtsettl"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtsettl'];?>">
		    </div>
		</div>
		<div class="_100">
		    <label class="_20 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Load Adjust').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtload_adj" maxlength="1"   name="txtload_adj"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtload_adj'];?>">
		    </div>
		    <label class="_23 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Print Doc At EOD').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text"  id="txtprnt_doc" maxlength="1"  name="txtprnt_doc"  class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtprnt_doc'];?>">
		    </div>    		
		    <label class="_30 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Load Transfer').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
				<input type="text" id="txtload_trans" maxlength="1"  name="txtload_trans" class="number" onblur="return chack_val(this);" value="<?php echo $this->formdata['txtload_trans'];?>">
		    </div>
		    <!--<label class="_23 margin_top_15 label_text_align">		
			<?php //echo $this->translate->_('Load Security Guard').''.$this->colan;?>
		    </label>
		    <div class="_10 margin_right_1">
			<input type="text" id="txtload_sec" name="txtload_sec" value="<?php //echo $this->formdata['txtload_sec'];?>">
		    </div>-->
		</div>
	    </fieldset>	
	</div>
	</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">