<?php
/**
* @name       setting2.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add route setting
*/
$this->translate = Zend_Registry::get('Zend_Translate');
$Menu_NameSpace = new Zend_Session_Namespace('Menu');
$menu_array     = $Menu_NameSpace->header_menu;
?>
<script>
$(document).ready(function() {
    $('#ddlenablenosale_chzn .chzn-drop .chzn-search input[type="text"]').focus();
    $('#ddlenablenosale_chzn').addClass('chzn-container-active');
    $('._50').css('width','47%');
});
</script>
<div id="organization_route_setting2">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_50">
	    <div class="_100">
		<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Enable No Sale').''.$this->colan;?>
		</label>
		<div class="_60_1">
		    <select id="ddlenablenosale" name="ddlenablenosale">
			<?php
			for($i=0;$i<count($this->ena_no_sale);$i++)
			{
			?>
			    <option value="<?php echo $this->ena_no_sale[$i]['id'];?>" <?php if($this->ena_no_sale[$i]['id'] == $this->formdata_setting2['enablenosale']){ echo 'selected'; }?>><?php echo $this->ena_no_sale[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
	    </div>
	    <div class="_100">
		<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Cash Balance').''.$this->colan;?>
		</label>
		<div class="_60_1">
		    <select id="ddlcashbalance" name="ddlcashbalance">
			<?php
			for($i=0;$i<count($this->cash_bal);$i++)
			{
			?>
			    <option value="<?php echo $this->cash_bal[$i]['id'];?>" <?php if($this->cash_bal[$i]['id'] == $this->formdata_setting2['cashbalance']){ echo 'selected'; }?>><?php echo $this->cash_bal[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
	    </div>
	    <div class="_100">
		<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Inventory Variance').''.$this->colan;?>
		</label>
		<div class="_60_1">
		    <select id="ddlinventoryvariance" name="ddlinventoryvariance">
			<?php
			for($i=0;$i<count($this->inv_vari);$i++)
			{
			?>
			    <option value="<?php echo $this->inv_vari[$i]['id'];?>" <?php if($this->inv_vari[$i]['id'] == $this->formdata_setting2['inventoryvariance']){ echo 'selected'; }?>><?php echo $this->inv_vari[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
	    </div>
	    <div class="_100">
		<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Inventory Over Sell').''.$this->colan;?>
		</label>
		<div class="_60_1">
		   <select id="ddlinvenoversell" name="ddlinvenoversell">
			<?php
			for($i=0;$i<count($this->inv_over_sell);$i++)
			{
			?>
			    <option value="<?php echo $this->inv_over_sell[$i]['id'];?>" <?php if($this->inv_over_sell[$i]['id'] == $this->formdata_setting2['invenoversell']){ echo 'selected'; }?>><?php echo $this->inv_over_sell[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
	    </div>
	    <div class="_100">
		<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Enable Damage Trxn').''.$this->colan;?>
		</label>
		<div class="_60_1">
		    <select id="ddlenabledamagedtrxn" name="ddlenabledamagedtrxn">
			<?php
			for($i=0;$i<count($this->ena_dmg_trxn);$i++)
			{
			?>
			    <option value="<?php echo $this->ena_dmg_trxn[$i]['id'];?>" <?php if($this->ena_dmg_trxn[$i]['id'] == $this->formdata_setting2['enabledamagedtrxn']){ echo 'selected'; }?>><?php echo $this->ena_dmg_trxn[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
	    </div>
<!--	    <div class="_100">
		<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Load Access After Unload').''.$this->colan;?>
		</label>
		<div class="_60_1">
		    <select id="ddlload_access_aftr_unload" name="ddlload_access_aftr_unload">
			<option value="<?php echo $this->translate->_('Disable');?>"><?php echo $this->translate->_('Disable');?></option>
			<option value="<?php echo $this->translate->_('Enable');?>"><?php echo $this->translate->_('Enable');?></option>
		    </select>
		</div>
	    </div>-->
	    <div class="_100">
		<!--<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Display Inv Summary').''.$this->colan;?>
		</label>
		<div class="_60_1">
		    <select id="ddldisplayinvsummary" name="ddldisplayinvsummary">disp_inv_summ
			<?php
			for($i=0;$i<count($this->disp_inv_summ);$i++)
			{
			?>
			    <option value="<?php echo $this->disp_inv_summ[$i]['id'];?>" <?php if($this->disp_inv_summ[$i]['id'] == $this->formdata_setting2['displayinvsummary']){ echo 'selected'; }?>><?php echo $this->disp_inv_summ[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div> -->
	    </div>
	    <div class="_100">
		<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Enable Load Request').''.$this->colan;?>
		</label>
		<div class="_60_1">
		    <select id="ddlincludeloadrequest" name="ddlincludeloadrequest">
			<?php
			for($i=0;$i<count($this->inc_load_req);$i++)
			{
			?>
			    <option value="<?php echo $this->inc_load_req[$i]['id'];?>" <?php if($this->inc_load_req[$i]['id'] == $this->formdata_setting2['includeloadrequest']){ echo 'selected'; }?>><?php echo $this->inc_load_req[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
	    </div>
	    <div class="_100">
		<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Load Req Roll Up').''.$this->colan;?>
		</label>
		<div class="_60_1">
		    <select id="ddlloadreqrolluporders" name="ddlloadreqrolluporders">
			<?php
			for($i=0;$i<count($this->load_req_roll_up);$i++)
			{
			?>
			    <option value="<?php echo $this->load_req_roll_up[$i]['id'];?>" <?php if($this->load_req_roll_up[$i]['id'] == $this->formdata_setting2['loadreqrolluporders']){ echo 'selected'; }?>><?php echo $this->load_req_roll_up[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
	    </div>
	    <!--<div class="_100">
		<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Depot Printer').''.$this->colan;?>
		</label>
		<div class="_60_1">
		    <select id="ddldepotprinter" name="ddldepotprinter">
			<?php
			for($i=0;$i<count($this->depot_print);$i++)
			{
			?>
			    <option value="<?php echo $this->depot_print[$i]['id'];?>" <?php if($this->depot_print[$i]['id'] == $this->formdata_setting2['depotprinter']){ echo 'selected'; }?>><?php echo $this->depot_print[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
	    </div>	    -->
	    <div class="_100">
		<label class="_40_3 margin_top_12 label_text_align"><?php echo $this->translate->_('Load Request Method').''.$this->colan;?></label>
		<div class="_60_1">
		    <select id="ddlloadreqmethod" name="ddlloadreqmethod">
			<?php
			for($i=0;$i<count($this->load_req_method);$i++)
			{
			?>
			    <option value="<?php echo $this->load_req_method[$i]['id'];?>" <?php if($this->load_req_method[$i]['id'] == $this->formdata_setting2['loadreqmethod']){ echo 'selected'; }?>><?php echo $this->load_req_method[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
	    </div>
	    <div class="_100">
		<label class="_40_3 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Route Printer').''.$this->colan;?>
		</label>
		<div class="_60_1">
		    <select id="ddlrouteprinter" name="ddlrouteprinter">				
			<?php
			for($i=0;$i<count($this->route_print);$i++)
			{
			?>
			    <option value="<?php echo $this->route_print[$i]['id'];?>" <?php if($this->route_print[$i]['id'] == $this->formdata_setting2['routeprinter']){ echo 'selected'; }?>><?php echo $this->route_print[$i]['val'];?></option>
			<?php } ?>
		    </select>
		</div>
	    </div>
		<!--div class="_100">
			<label class="_40 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Allowed Radius (For GPS)').''.$this->colan;?>
			</label>
			<div class="_60_1 margin_top_3">
				<input type="text" maxlength="15" class="number" id="txtallowradius" name="txtallowradius" value="<?php echo number_format($this->formdata_setting2['allowedradius'],5);?>">
			</div>
	    </div-->
		<!--div class="_100">
			<label class="_40 margin_top_12 label_text_align">
				<?php //echo $this->translate->_('PDC Threshold').''.$this->colan;?></label>
			<div class="_60_1 margin_top_3">
				<input type="text" id="txpdc_threshold" name="txpdc_threshold" value="<?php //echo $this->formdata_setting2['pdcthreshold']; ?>" class="number">
			</div>
	    </div-->
		<div class="_100">
			<label class="_40 margin_top_12 label_text_align">
			<?php echo $this->translate->_('PDC Threshold').''.$this->colan;?></label>
				
			<div class="_60_1 margin_top_3">
			<input type="text" id="txpdc_threshold" name="txpdc_threshold" value="<?php echo $this->formdata_setting2['pdcthreshold']; ?>" class="number">
				
			</div>
	    </div>
		<?php /* ?>
		<div class="_100">
			<label class="_40 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Week Setting').''.$this->colan;?></label>
			<div class="_60_1 margin_top_3">
				<input type="text" id="defaultweeksetting" name="defaultweeksetting" value="<?php echo $this->formdata_setting2['defaultweeksetting']; ?>" class="number">
			</div>
	    </div> <?php */ ?>
	</div>
	<div class="_50 margin_left_3_1">
	    <div class="_100">
		<div class="_5_1 margin_top_5"  >
		    <input type="checkbox" id="chkenablemiddaytelecom" name="chkenablemiddaytelecom" <?php if($this->formdata_setting2['enablemiddaytelecom'] == '1'){echo 'checked=true';}?> value="1">
		</div>
		<label class="_75 margin_top_10 text_align chkboxcontainer"  >
		    <?php echo $this->translate->_('Allow Voiding Of Collections');?>
		</label>
	    </div>	    
	    <!--<div class="_100">
		<div class="_5_1 margin_top_5"  >
		    <input type="checkbox" id="chkallowgctocash" name="chkallowgctocash" <?php if($this->formdata_setting2['allowgctocash'] == '1'){echo 'checked';}?> value="1">
		</div>
		<label class="_75 margin_top_10 text_align chkboxcontainer"  >
		    <?php echo $this->translate->_('Allow Cash Invoice On GC Customer ');?>
		</label>
	    </div>
	    <div class="_100">
		<div class="_5_1 margin_top_5"  >
		    <input type="checkbox" id="chkenablerouteweekday" name="chkenablerouteweekday" <?php if($this->formdata_setting2['enablerouteweekday'] == '1'){echo 'checked=true';}?> value="1">
		</div>		
		<label class="_75 margin_top_10 text_align chkboxcontainer"   >
		    <?php echo $this->translate->_('Change Route Week Day In Start Day');?>
		</label>
	    </div>-->
		<div class="_100">
			<div class="_5_1 margin_top_5"  >
				<input type="checkbox" id="chkenableautopostingaccount" name="chkenableautopostingaccount" <?php if($this->formdata_setting2['enableautopostingaccount'] == '1'){echo 'checked=true';}?> value="1">
			</div>		
			<label class="_50_1 margin_top_10 text_align chkboxcontainer"   >
				<?php echo $this->translate->_('Post Variance Against Salesman');?>
			</label>	    		
			<div class="_40 margin_left_right_1 margin_top_5" id="div_ddlcustomercode">
				<select id="ddlcustomercode" name="ddlcustomercode">
					<option value="">--Select--</option>
					<?php for($i=0;$i<count($this->customerinfo);$i++){ ?>
						<option value="<?php echo $this->customerinfo[$i]['id']?>" <?php echo ($this->formdata_setting2['variancecustomercode'] == $this->customerinfo[$i]['id']) ? 'selected' : ''; ?> > <?php echo $this->customerinfo[$i]['id']?></option>
					<?php } ?>
				</select>
			</div>
	    </div>
		<?php if($menu_array['Allow Cloud Transaction Entry']['status'] == 1 ) { ?>
		<div class="_100">
			<div class="_5_1 margin_top_5"  >
				<input type="checkbox" id="chkallow_route_startday" name="chkallow_route_startday" <?php if($this->formdata['chkallow_route_startday'] == '1'){ echo 'checked=true';}?> value="1">
			</div>
			<label class="_75 margin_top_10 text_align chkboxcontainer"   >
				<?php echo $this->translate->_('Allow Route Start Day in Cloud');?>
			</label>
		</div>
		<?php } ?>
	    <div class="clear space_20" >&nbsp;</div>
	    <div class="_100">
			<label class="_50 margin_top_12 label_text_align"><?php echo $this->translate->_('CDC Validity Days').''.$this->colan;?></label>
			<div class="_50 margin_right_1">
				<input type="text" class="number" id="cdcvaliditydays" name="cdcvaliditydays" value="<?php echo $this->formdata_setting2['cdcvaliditydays']; ?>" >
			</div>			
	    </div>
	    <div class="_100">
		<label class="_50 margin_top_12 label_text_align"><?php echo $this->translate->_('New Customer Seq').''.$this->colan;?></label>
		<div class="_50 margin_right_1">
		    <input type="text" class="number" id="customerseqnumber" maxlength="18" name="customerseqnumber" value="<?php echo $this->new_seq_number; ?>">
			<input type="hidden" class="number" id="newcustomerseqnumber" maxlength="18" name="newcustomerseqnumber" value="<?php echo $this->new_seq_number; ?>">
		</div>
	    </div>
	    <!--div class="_100">
		<label class="_50 margin_top_12 label_text_align"><?php echo $this->translate->_('Credit Limit').''.$this->colan;?></label>
		<div class="_50 margin_right_1">
		    <input type="text" class="number amount_text_align" maxlength="8" id="creditlimit" name="creditlimit" value="<?php echo $this->formdata_setting2['creditlimit']; ?>">
		</div>
	    </div-->
	    <!--div class="_100">
		<label class="_50 margin_top_12 label_text_align"><?php echo $this->translate->_('Route Balance').''.$this->colan;?></label>
		<div class="_50 margin_right_1">
		    <input type="text" readonly="readonly" id="routebalance" name="routebalance" class="number" value="<?php echo number_format($this->formdata_setting2['routebalance'],$this->decimalplaces); ?>">
		</div>
	    </div-->
<!--	    <div class="_100">
		<label class="_50 margin_top_12 label_text_align"><?php //echo $this->translate->_('Vehicle No.').''.$this->colan;?></label>
		<div class="_50 margin_right_1">
		    <input type="text" id="txtveh_no" name="txtveh_no" value="0">
		</div>
	    </div>
-->	    <div class="_100">
		<label class="_50 margin_top_12 label_text_align"><?php echo $this->translate->_('Vehicle Odometer').''.$this->colan;?></label>
		<div class="_50 margin_right_1">
		    <input type="text" class="number" readonly="readonly" maxlength="18" id="vehicleodometer" name="vehicleodometer" value="<?php echo $this->formdata_setting2['vehicleodometer']; ?>">
		</div>
	    </div>
	    <div class="_100">
			<label class="_50 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Default Delivery Days').''.$this->colan;?></label>
			<div class="_50 margin_right_1">
				<input type="text" class="number" maxlength="4" id="defaultdeliverydays" name="defaultdeliverydays" value="<?php echo $this->formdata_setting2['defaultdeliverydays']; ?>">
			</div>
	    </div>
		<div class="_100">
			<label class="_50 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Load Request (Avg. Days)').''.$this->colan;?></label>
			<div class="_50 margin_right_1">
				<input type="text" class="number" maxlength="4" id="defaultrequestdays" name="defaultrequestdays" value="<?php echo $this->formdata_setting2['defaultrequestdays']; ?>">
			</div>
	    </div>
		
		<div class="_100">
			<label class="_50 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Force Settlement Days').''.$this->colan;?></label>
			<div class="_50 margin_right_1">
				<input type="text" id="tx_forcesettlementdays" name="tx_forcesettlementdays" value="<?php echo $this->formdata_setting2['forcesettlementdays']; ?>" class="number" maxlength="2">
			</div>
	    </div>
		
	</div>
	<!---->	
<div class="clear space_5">&nbsp;</div>	
	<div class="content with-actions ie_grid min_height_10">
	    <fieldset class="">
		<legend><?php echo $this->translate->_('Route Credit');?></legend>		
	
		    <div class="_100">
			<div id="chk" class="_25_1" style="width: 21%;">
				<input type="checkbox" id="chk_routecredit" name="chk_routecredit" <?php if($this->formdata_setting2['routecreditcheck'] == "1"){ echo 'checked=true';}?> value="1">
			</div>
			<label class="_25_1 margin_top_10 margin_right_1">
				<?php echo $this->translate->_('Enable Route Credit');?>
			</label>
			
			</div>
			
			<div class="_50" style="width: 47%;">
			<div class="_100" style="margin-top: 0% ! important;">
			 
			<label class="_40_3 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Credit Limit').''.$this->colan;?>
			</label>
			<div class="_60_1">
		    <input type="text" class="number " maxlength="10" id="creditlimit" name="creditlimit" value="<?php echo $this->formdata_setting2['creditlimit']; ?>">
			</div>
			</div>
			</div>
			<div class="_50_3 margin_left_3_1">
			<label class="_50 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Credit Limit Days').''.$this->colan;?>
			</label>
			<div class="_50 margin_right_1">
				 <input type="text" class="number " maxlength="8" id="routecreditlimitdays" name="routecreditlimitdays" value="<?php echo $this->formdata_setting2['routecreditlimitdays']; ?>">
			</div>
			</div>
			
			<div class="_50" style="width: 47%;">
			<div class="_100" style="margin-top: 0% ! important;">
			 
			<label class="_40_3 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Route Balance').''.$this->colan;?>
			</label>
			<div class="_60_1">
		    <input type="text" readonly="readonly" id="routebalance" name="routebalance" class="number" value="<?php echo number_format($this->formdata_setting2['routebalance'],$this->decimalplaces); ?>">
			</div>
			</div>
			</div>
			
			
	    </fieldset>
	</div> 
	<!---->
	
	<div class="content with-actions ie_grid min_height_10">
	    <fieldset class="">
		<legend><?php echo $this->translate->_('Memo');?></legend>
		<div class="_50"> 
		    <div class="_100">
			<label class="_40_3 margin_top_12 label_text_align"><?php echo $this->translate->_('Memo1').''.$this->colan;?></label>
			<div class="_60_1">
			    <input type="text" id="memo1" name="memo1"  maxlength="50" value="<?php echo $this->formdata_setting2['memo1']; ?>">
			</div>
		    </div>
		</div>
		<div class="_50_3 margin_left_3_1"> 
		    <div class="_100">			
			    <label class="_50 margin_top_12 label_text_align">
					<?php echo $this->translate->_('Memo2').''.$this->colan;?>
				</label>
				<div class="_50 margin_right_1">
					<input type="text" id="memo2" name="memo2"  maxlength="50" value="<?php echo $this->formdata_setting2['memo2']; ?>">
				</div>
		    </div>
		</div>     
	    </fieldset>
	</div>    
</div>
<div class="space_100 clear">&nbsp;</div>