<?php
/**
* @name       tmplsetting2.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of Route template
*/

$this->translate = Zend_Registry::get('Zend_Translate');

?>

<div class="_100">
    <div class="clean"></div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Req. EOD No Sale Rpt.').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddleod_nosale" name="ddleod_nosale">
	    <?php
	    for($i=0;$i<count($this->print_option);$i++)
	    {
	    ?>
		<option  <?php if($this->print_option[$i]['id'] == $this->formdata['reqeodnosalereport']) { echo 'selected';} ?> value="<?php echo $this->print_option[$i]['id'];?>"><?php echo $this->print_option[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
    <div class="_5 margin_top_7">
	<input type="checkbox" id="chkhhc_seq" name="chkhhc_seq" value="1" <?php echo ($this->formdata['generatehhcseqfromboflag'] =='1') ? 'checked' : ''; ?> >
    </div>
    <label class="_30_30 margin_top_15 text_align">
	<?php echo $this->translate->_('Generate HHC Seq From Back Office');?>
    </label>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Enable No Sale').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlena_nosale" name="ddlena_nosale">
	    <?php
	    for($i=0;$i<count($this->ena_no_sale);$i++)
	    {
	    ?>
		<option  <?php if($this->ena_no_sale[$i]['id'] == $this->formdata['enablenosale']) { echo 'selected';} ?> value="<?php echo $this->ena_no_sale[$i]['id'];?>"><?php echo $this->ena_no_sale[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
    <div class="_5 margin_top_7">
	<input type="checkbox" id="chkroute_weekday" name="chkroute_weekday" value="1"  <?php echo ($this->formdata['enablestartdayrtewkdayedit'] =='1') ? 'checked' : ''; ?> >
    </div>
    <label class="_30_30 margin_top_15 text_align">
	<?php echo $this->translate->_('Edit Route Week Day');?>
    </label>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Req. Non Dell Rpt.').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
       <select id="ddlnon_dellrpt" name="ddlnon_dellrpt">
	    <?php
	    for($i=0;$i<count($this->print_option);$i++)
	    {
	    ?>
		<option  <?php if($this->print_option[$i]['id'] == $this->formdata['reqeodnondelreport']) { echo 'selected';} ?> value="<?php echo $this->print_option[$i]['id'];?>"><?php echo $this->print_option[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
    <div class="_5 margin_top_7">
	<input type="checkbox" id="chkpopulated_load" name="chkpopulated_load" value="1" <?php echo ($this->formdata['allowpopulateload'] =='1') ? 'checked' : ''; ?>>
    </div>
    <label class="_30_30 margin_top_15 text_align">
	<?php echo $this->translate->_('Allow Populate Load');?>
    </label>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Cash Balance').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlcash_bal" name="ddlcash_bal">
	    <?php
	    for($i=0;$i<count($this->cash_bal);$i++)
	    {
	    ?>
		<option  <?php if($this->cash_bal[$i]['id'] == $this->formdata['cashbalance']) { echo 'selected';} ?> value="<?php echo $this->cash_bal[$i]['id'];?>"><?php echo $this->cash_bal[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
    <div class="_5 margin_top_7">
	<input type="checkbox" id="chkgc_customer" name="chkgc_customer" value="1" <?php echo ($this->formdata['allowgctocash'] =='1') ? 'checked' : ''; ?>>
    </div>
    <label class="_30_30 margin_top_15 text_align">
	<?php echo $this->translate->_('Allow Cash Invoice On GC Customer');?>
    </label>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Req. EOD Exception Rpt.').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddleod_execption" name="ddleod_execption">
	    <?php
	    for($i=0;$i<count($this->print_option);$i++)
	    {
	    ?>
		<option  <?php if($this->print_option[$i]['id'] == $this->formdata['reqeodexceptionrpt']) { echo 'selected';} ?> value="<?php echo $this->print_option[$i]['id'];?>"><?php echo $this->print_option[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
    <div class="_5 margin_top_7">
	<input type="checkbox" id="chkstart_dayinfo" name="chkstart_dayinfo" value="1" <?php echo ($this->formdata['allowroutestartdayflag'] =='1') ? 'checked' : ''; ?> >
    </div>
    <label class="_30_30 margin_top_15 text_align">
	<?php echo $this->translate->_('Allow Route Start Day In Back Office');?>
    </label>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Inventory Variance').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlinv_var" name="ddlinv_var">
	    <?php
	    for($i=0;$i<count($this->inv_variance);$i++)
	    {
	    ?>
		<option  <?php if($this->inv_variance[$i]['id'] == $this->formdata['inventoryvariance']) { echo 'selected';} ?> value="<?php echo $this->inv_variance[$i]['id'];?>"><?php echo $this->inv_variance[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Req. EOD Price Change Rpt.').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddleod_pricechange" name="ddleod_pricechange">
	    <?php
	    for($i=0;$i<count($this->print_option);$i++)
	    {
	    ?>
		<option  <?php if($this->print_option[$i]['id'] == $this->formdata['reqeodprcchgreport']) { echo 'selected';} ?> value="<?php echo $this->print_option[$i]['id'];?>"><?php echo $this->print_option[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Inventory Over Sell').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlinv_oversell" name="ddlinv_oversell">
	    <?php
	    for($i=0;$i<count($this->inv_over_sell);$i++)
	    {
	    ?>
		<option  <?php if($this->inv_over_sell[$i]['id'] == $this->formdata['invenoversell']) { echo 'selected';} ?> value="<?php echo $this->inv_over_sell[$i]['id'];?>"><?php echo $this->inv_over_sell[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Req. EOD Promotions Rpt.').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddleod_promotion" name="ddleod_promotion">
	    <?php
	    for($i=0;$i<count($this->print_option);$i++)
	    {
	    ?>
		<option  <?php if($this->print_option[$i]['id'] == $this->formdata['reqeodpromosreport']) { echo 'selected';} ?> value="<?php echo $this->print_option[$i]['id'];?>"><?php echo $this->print_option[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Enable Damage Trxn').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddldamage_trxn" name="ddldamage_trxn">
	    <?php
	    for($i=0;$i<count($this->ena_dmg_trxn);$i++)
	    {
	    ?>
		<option  <?php if($this->ena_dmg_trxn[$i]['id'] == $this->formdata['enabledamagedtrxn']) { echo 'selected';} ?> value="<?php echo $this->ena_dmg_trxn[$i]['id'];?>"><?php echo $this->ena_dmg_trxn[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Req. EOD Non Scanned Rpt.').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlnon_scanned" name="ddlnon_scanned">
	    <?php
	    for($i=0;$i<count($this->print_option);$i++)
	    {
	    ?>
		<option  <?php if($this->print_option[$i]['id'] == $this->formdata['reqeodnonscannedreport']) { echo 'selected';} ?> value="<?php echo $this->print_option[$i]['id'];?>"><?php echo $this->print_option[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Load Access After Unload').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlaccess_afterunload" name="ddlaccess_afterunload">
	    <option  <?php if('1' == $this->formdata['loadaccessafterunload']) { echo 'selected';} ?> value="1"><?php echo $this->translate->_('Enable');?></option>
	    <option  <?php if('0' == $this->formdata['loadaccessafterunload']) { echo 'selected';} ?> value="0"><?php echo $this->translate->_('Disable');?></option>
	</select>
    </div>
</div>
<div class="_100 ">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Req. EOD OdomLog Rpt.').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="eod_odomload" name="eod_odomload">
	<?php
	    for($i=0;$i<count($this->print_option);$i++)
	    {
	    ?>
		<option  <?php if($this->print_option[$i]['id'] == $this->formdata['reqeododomlogreport']) { echo 'selected';} ?> value="<?php echo $this->print_option[$i]['id'];?>"><?php echo $this->print_option[$i]['val'];?></option>
	<?php } ?>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Use Sales Date Flag').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlsales_date_flag" name="ddlsales_date_flag">
	    <option  <?php if("0" == $this->formdata['usesalesdateflag']) { echo 'selected';} ?> value="0"><?php echo $this->translate->_('Disable');?></option>
	    <option  <?php if("1" == $this->formdata['usesalesdateflag']) { echo 'selected';} ?> value="1"><?php echo $this->translate->_('Enable');?></option>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Display Inv Summary').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlinv_summary" name="ddlinv_summary">
	     <?php
	    for($i=0;$i<count($this->disp_inv_summ);$i++)
	    {
	    ?>
		<option  <?php if($this->disp_inv_summ[$i]['id'] == $this->formdata['displayinvsummary']) { echo 'selected';} ?> value="<?php echo $this->disp_inv_summ[$i]['id'];?>"><?php echo $this->disp_inv_summ[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Include Load Request').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlinc_load_req" name="ddlinc_load_req">
	    <option  <?php if('0' == $this->formdata['includeloadrequest']) { echo 'selected';} ?> value="0"><?php echo $this->translate->_('Disable');?></option>
	    <option  <?php if('1' == $this->formdata['includeloadrequest']) { echo 'selected';} ?> value="1"><?php echo $this->translate->_('Enable (Include Load Request)');?></option>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Credit Limit').''.$this->colan;?>
    </label>
    <div class="_30_1 _26 margin_left_3 margin_right_1"> 
	<input type="text" id="txtcredit_limit" class="margin_top_5 number amount_text_align" maxlength="4" name="txtcredit_limit" value="<?php echo $this->formdata['creditlimit'];?>">
    </div>
</div>
<div class="_100 ">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Default Delivery Days').''.$this->colan;?>
    </label>
    <div class="_30_1 _26 margin_left_3 margin_right_1">
	<input type="text" id="txtdef_del_day" 	name="txtdef_del_day" value="<?php echo $this->formdata['defaultdeliverydays'];?>" class="number" maxlength="3">
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Load Req Roll Up Orders').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlload_rollup" name="ddlload_rollup">
	    <?php
	    for($i=0;$i<count($this->load_req_roll_up);$i++)
	    {
	    ?>
		<option  <?php if($this->load_req_roll_up[$i]['id'] == $this->formdata['loadreqrolluporders']) { echo 'selected';} ?> value="<?php echo $this->load_req_roll_up[$i]['id'];?>"><?php echo $this->load_req_roll_up[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>
<!--<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Depot Printer').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddldepot_print" name="ddldepot_print">
	    <?php
	    for($i=0;$i<count($this->depot_print);$i++)
	    {
	    ?>
		<option  <?php if($this->depot_print[$i]['id'] == $this->formdata['depotprinter']) { echo 'selected';} ?> value="<?php echo $this->depot_print[$i]['id'];?>"><?php echo $this->depot_print[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>-->
<?php /*<div class="_100">
    <label class="_30 padding_0 margin_top_10 label_text_align">
	<?php echo $this->translate->_('Enable TCOM Lock').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddltcom_lock" name="ddltcom_lock">
	    <option value="<?php echo $this->translate->_('Enable');?>"><?php echo $this->translate->_('Enable');?></option>
	    <option value="<?php echo $this->translate->_('Disable');?>"><?php echo $this->translate->_('Disable');?></option>
	</select>
    </div>
</div> */ ?>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Lock Status').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddllock_status" name="ddllock_status">
	    <option  <?php if('1' == $this->formdata['tlockstatus']) { echo 'selected';} ?> value="1"><?php echo $this->translate->_('Locked');?></option>
	    <option  <?php if('0' == $this->formdata['tlockstatus']) { echo 'selected';} ?> value="0"><?php echo $this->translate->_('Unlocked');?></option>
	</select>
    </div>
</div>
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Load Req. Method').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlload_req_method" name="ddlload_req_method">
	    <?php
	    for($i=0;$i<count($this->load_req_method);$i++)
	    {
	    ?>
		<option  <?php if($this->load_req_method[$i]['id'] == $this->formdata['loadreqmethod']) { echo 'selected';} ?> value="<?php echo $this->load_req_method[$i]['id'];?>"><?php echo $this->load_req_method[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>
<!--<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Route Printer').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlroute_print" name="ddlroute_print">
	    <?php
	    for($i=0;$i<count($this->depot_print);$i++)
	    {
	    ?>
		<option  <?php if($this->depot_print[$i]['id'] == $this->formdata['routeprinter']) { echo 'selected';} ?> value="<?php echo $this->depot_print[$i]['id'];?>"><?php echo $this->depot_print[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>-->
<div class="_100">
    <label class="_30 padding_0 margin_top_12 label_text_align">
	<?php echo $this->translate->_('Route Type').''.$this->colan;?>
    </label>
    <div class="_30_1 margin_left_3 margin_right_1">
	<select id="ddlroute_type" name="ddlroute_type">
	    <?php
	    for($i=0;$i<count($this->route_type);$i++)
	    {
	    ?>
		<option  <?php if($this->route_type[$i]['id'] == $this->formdata['routetype']) { echo 'selected';} ?> value="<?php echo $this->route_type[$i]['id'];?>"><?php echo $this->route_type[$i]['val'];?></option>
	    <?php } ?>
	</select>
    </div>
</div>
</div>    