<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;

var column = <?php echo json_encode($this->column); ?>;

var column_config = <?php echo json_encode($this->column_config); ?>;
    
var display_column_config = [];
for(var i=0; i < column_config.length; i++)
{
    if(column_config[i] != "salesmancode" && column_config[i] != "salesmanname1") {
        display_column_config.push({name:column_config[i],index:column_config[i], width:120, summaryType:'sum', align:"right",formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },sortable: false});
    } else if(column_config[i] == "salesmancode") {
        display_column_config.push({name:column_config[i],index:column_config[i], width:120});
    } else {
        display_column_config.push({name:column_config[i],index:column_config[i], width:250});
    }
}

jQuery("#search").jqGrid({        
   	url:base_url+"/reports/salesmanproductivity/salesmanproductivitydata/",
	datatype: "json",
   	colNames:column,
   	colModel:display_column_config,
    <?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
    pager: '#pagersr',
   	sortname: 'salesmancode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:false,
	groupingView :
    {
        groupField : ['hocode'],
        groupColumnShow : [false],
        groupCollapse : false,
        groupOrder: ['asc'] ,
        groupSummary : [false],
        groupDataSorted : true,
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,

);


jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
</script>