<?php
/**
* @name       addcashreceipt.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
$(document).ready(function(){
	
	<?php if($this->params["id"] > 0) { ?>	
		var rid = '<?php echo $this->result["routecode"] ?>';
		var sid = '<?php echo $this->result["salesmancode"] ?>';
		var dt 	= '<?php echo $this->result["transactiondate"] ?>';
		getdata(rid,sid,dt,1);
		$("#formcontrol").find('input,select').attr('disabled','disabled');
		$('select').trigger('liszt:updated');
		$("a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',theme:'light_rounded', allow_resize: false});
	<?php } ?>
	
	$('#btnsave').click(function() {
		
		$("#txtslipno").addClass('required');
		$("#ddlbank").addClass('required');
		if(!$("#frmdetsec").valid()) {			
			return false;
		}
		if(parseFloat($('#txtchqamt').val()) > 0.00){
			jAlert('No Data To Generate Cashier Receipt.');
			return false;
		}
		
	});
	
	$('#btnpopulate').click(function() {
	
		$("#txtslipno").removeClass('required');
		$("#ddlbank").removeClass('required');
		
		if($("#frmdetsec").valid())
		{
			var rid 		= $('#ddlroute').val();
			var sid 		= $('#hdnsalesmancode').val();
			var dt 			= $('#txtdate').val();
			var route_st 	= 0;
			var url_st 		= base_url+'/account/settlement/getrotuestatus/routeid/'+rid+'/routedate/'+dt;
			$.ajax({
				url:url_st,
				type:'post',
				success:function(data) {
					if(data > 0) {
						route_st = data;						
						jAlert("Route Is Live, Can't Generate Cashier Receipt.");
						return false;
					}
					else {
						getdata(rid,sid,dt,0);
					}
				}
			})
			$("a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',theme:'light_rounded', allow_resize: false});
		}
	})
	
	$('#ddlroute').change(function(){
		$.blockUI();		
		getsalesman($('#ddlroute').val());
		$.unblockUI();
	})
	$("a[class^='ico edit']").prettyPhoto({animation_speed:'fast',theme:'light_rounded', allowresize: false});
})
function getdata(rid,sid,dt,view)
{
	//alert(dt.replace('/:-/g', "-"));
	var  url = '<?php echo $this->itemgrid; ?>/key/'+rid+'/key1/'+sid+'/key2/'+dt+'/view/'+view;
	
	var values = $('#frmdetsec').serialize();
	$.ajax({
		url:url,
		data :values,
		type:'post',
		beforeSend: function() {
			$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");
		},
		success:function(returndata) {
			$('#item-grid').html(returndata);
			fnload();
			$("#loader").html("");			
			$("a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',theme:'light_rounded', allow_resize: false});
		}
	})
}
function fnload()
{
	$("#item-grid #paging_grid #table-example tr").each(function() {
		if($(this).find('td').eq(2).html() != 'Receipt') {
			$(this).find('td').eq(9).html('--');
		}
	})
}
function clearcontrol()
{
	$("#ddlroute").val("");
	$("#hdnsalesmancode").val("");
	$("#txtsalesman").val("");
	$("#txtdate").val("");	
	$("#txtslipno").val("");
	$("#ddlbank").val("");	
	$("select").trigger("liszt:updated");	
}
    
function getsalesman(routeid)
{
	if(routeid == '')
	{
		$('#txtsalesman').val('');
		$('#hdnsalesmancode').val('');
		return false;
	}
	var  url = base_url+'/home/index/getsalesmanfromroutecode/routeid/'+routeid;
	$.ajax({
		url:url,
		data:$("#frmdetsec").serialize(),
		type:'post',		
		success:function(data) {
			var salesman_info = JSON.parse(data);
			if (salesman_info == '')
			{
				return false;
			}
			$('#txtsalesman').val(salesman_info[0][0]['salesmanname1']);
			$('#hdnsalesmancode').val(salesman_info[0][0]['salesmancode']);
		}
	})
}
</script>

<style>
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<form id="frmdetsec" name="frmdetsec" class="validate" novalidate action="" method="post">
<div class="box" id="account_settlement_addcashreceipt">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
        <h3><?php echo $this->translate->_('Cashier Receipt')?></h3>
    </div>
    <div class="_50_3">
		<div class="_10 save_btn">
			<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"settlement","action"=>"cashreceipt"), "default", true);?>')" >
		</div>
		<div class="_10 save_btn">
			<?php if($this->params['view'] != 'yes') { ?>
				<input class="border_none" type="submit" value="" name="btnsave" id="btnsave">
			<?php } else { ?>
				<?php if($this->checkaccess("delete")) { ?><input class="border_none" type="button" value="" alt="<?php echo $this->baseUrl()."/account/settlement/cashreceipt/delid/".$this->params["id"]?>" id="btndeletetran" name="btndeletetran" ><?php } ?>
			<?php } ?>
		</div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"account","controller"=>"settlement","action"=>"cashreceipt"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"account","controller"=>"settlement","action"=>"addcashreceipt"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content with-actions min_height_10" id="formcontrol">
    <div class="_100">
		<div class="clear"></div>
    </div>
    <div class="_100">
		<div class="clear"></div>
    </div>
    <div class="_100">
		<label class="_10 label_text_align margin_top_12">
		   <?php echo $this->translate->_('Route').''.$this->required;?>
		</label>
		<div class="_20 margin_right_1">
			<select id="ddlroute" name="ddlroute" class="required">
				<option value="">--- Select ---</option>
				<?php
					for($i=0;$i<count($this->routeinfo);$i++)
					{
				?>
					<option <?php if($this->result["routecode"] == $this->routeinfo[$i]['id']) { echo 'selected="selected"'; } ?> value="<?php echo $this->routeinfo[$i]['id'];?>"><?php echo $this->routeinfo[$i]['val'];?></option>
				<?php } ?>
			</select>
		</div>
		<label class="_10 label_text_align margin_top_12">
			<?php echo $this->translate->_('Salesman').''.$this->colan;?>
		</label>
		<div class="_15 margin_right_2_2">
			<input type="text" id="txtsalesman" name="txtsalesman" value="<?php echo $this->result["salesmancode"]; ?>" readonly="readonly">
		</div>
		<label class="_15 label_text_align margin_top_12">
		   <?php echo $this->translate->_('Route End Date').''.$this->required;?>
		</label>
		<div class="_15 margin_right_2_2">
			<input type="text" id="txtdate" name="txtdate" value="<?php echo $this->date;?>" readonly="readonly" class="required">
		</div>	
		<div class="_3">&nbsp;</div>
		<?php if(!$this->params['view']) { ?>
			<div class="_10_1"><input type="button" id="btnpopulate" name="btnpopulate" value="<?php echo $this->translate->_('POPULATE');?>" /></div>
		<?php } ?>
	</div>
     <div class="clear space_50"></div>
    <div class="_100">
	<div id="loader"></div>
		<div class="_100 margin_top_10" style="height:300px;overflow-y:auto">
			<div id="item-grid"> <!--grid load here --> </div>
		</div>
    </div>	
    <fieldset>
	<?php if(!$this->params['view']) { ?>
		<div class="_100">
			<label class="_15_3 margin_left_01 label_text_align margin_top_12">
				<?php echo $this->translate->_('Cash Amount').''.$this->colan;?>
			</label>
			<div class="_15 margin_right_1">
				<input type="text" id="txtcashamt" name="txtcashamt" value="" readonly="readonly">
			</div>
			<label class="_15 label_text_align margin_top_12">
				<?php echo $this->translate->_('Receipt Amount').''.$this->colan;?>
			</label>
			<div class="_15 margin_right_2_2">
				<input type="text" id="txtrcpamt" name="txtrcpamt" value="" readonly="readonly">
			</div>    
			<label class="_15 margin_left_01 margin_right_0 label_text_align margin_top_12">
				<?php echo $this->translate->_('Cheque Amount').''.$this->colan;?>
			</label>
			<div class="_15 margin_right_1">
				<input type="text" id="txtchqamt" name="txtchqamt" value="" readonly="readonly">
			</div>
		</div>
		<div class="_100">
			<label class="_15_3 label_text_align margin_top_12">
				<?php echo $this->translate->_('Total').''.$this->colan;?>
			</label>
			<div class="_15 margin_right_2_2">
				<input type="text" id="txttotal" name="txttotal" value="" readonly="readonly">
			</div>
			<label class="_15 label_text_align margin_top_12">
			   <?php echo $this->translate->_('Bank').''.$this->required;?>
			</label>
			<div class="_15_3 margin_right_1">
				<select id="ddlbank" name="ddlbank" class="required">
					<option value="">--- Select ---</option>
					<?php
						for($i=0;$i<count($this->bankinfo);$i++)
						{
					?>
						<option <?php ($this->result["bankcode"] == $this->bankinfo[$i]['id']) ? 'selected' : '' ?> value="<?php echo $this->bankinfo[$i]['id'];?>"><?php echo $this->bankinfo[$i]['val'];?></option>
					<?php } ?>
				</select>
			</div>
			<label class="_15_2 margin_left_01 label_text_align margin_top_12">
				<?php echo $this->translate->_('Slip No.').''.$this->required;?>
			</label>
			<div class="_15 margin_right_1">
				<input type="text" id="txtslipno" name="txtslipno" value="" class="required">
			</div>
		</div>
	<?php } else { ?>
		<div class="_100">			
			<label class="_15 label_text_align margin_top_12">
			   <?php echo $this->translate->_('Bank').''.$this->colan;?>
			</label>
			<div class="_15_3 margin_right_1">
				<select id="ddlbank_view" name="ddlbank_view">
					<option value="">--- Select ---</option>
					<?php
						for($i=0;$i<count($this->bankinfo);$i++)
						{ 
					?>
						<option <?php echo ($this->result["tobankcode"] == $this->bankinfo[$i]['id']) ? 'selected' : '' ?> value="<?php echo $this->bankinfo[$i]['id'];?>"><?php echo $this->bankinfo[$i]['val'];?></option>
					<?php } ?>
				</select>
			</div>
			<label class="_15_2 margin_left_01 label_text_align margin_top_12">
				<?php echo $this->translate->_('Slip No.').''.$this->colan;?>
			</label>
			<div class="_15 margin_right_1">
				<input type="text" id="txtslipno" name="txtslipno" value="<?php echo $this->result["slipno"]; ?>" readonly="readonly" >
			</div>
		</div>		
		<?php }  ?>
		<div class="_100 space_20">&nbsp;</div>	
    </fieldset>
    
</div>
<input type="hidden" id="hdnsalesmancode" name="hdnsalesmancode" value="">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</div> <!-- End of .box -->
</form>
</div>