<style>
.margin_zero {margin-top:0px !important;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png" class="margin_top_7">
		<h3><?php echo $this->title?></h3>
	    </div>
	    <div class="_50_3">&nbsp;</div>
        </div>
	<div class="_100" style="overflow-x:auto;height:350px;">
		<?php echo $this->partial('datagrid.phtml', $this); ?>
	</div>	
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>