<?php
/**
* @name       invoice.phtml
* @since      06-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$date = $this->date != '' ? $this->date : date('d-m-Y');
?>
<script type="text/javascript">
$(document).ready(function(){
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
	$('#btnendroute').click(function(){
		var str = '';
        $('#table-example input[type="checkbox"]:checked').each(function() {
			if(parseInt($(this).val()) > 0) {
				str  += $(this).val()+'_';
			}
        });
        
        if(!str){
            jAlert('Please Select Record To End Route.');
			return false;
        } else {
			window.location= base_url+'/hhctransaction/routeendday/editroute/ids/'+str;			
		}
	});
})
</script>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png" class="margin_top_10">
		<h3><?php echo $this->translate->_('Route End Of Day')?></h3>
	    </div>
	     <div class="_50_3">
		<!--<div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnadd" name="btnadd" onclick="winloc('<?php //echo $this->url(array("module"=>"hhctransaction","controller"=>"routeendday","action"=>"editroute"), "default", true);?>')"></div>-->	
	    </div>
        </div>
	<div class="_100" >
	    <div class="_20 label_text_align margin_top_7">&nbsp;</div>
		<div class="_20 label_text_align margin_top_10"><label class="advance_search_css"><?php  echo $this->translate->_('Date').''.$this->colan;?></label></div>
		<div class="_20 label_text_align margin_right_1"><input type="text" id="txtdate" readonly="readonly" name="txtdate" value="<?php echo $date;?>" class="margin_zero"></div>		
		<div class="_5 margin_top_5" style="margin-right:-4px !important"> <input type="checkbox" name="chkoptions" value="1"  <?php if($this->chkoptions != "") { ?> checked="checked" <?php } ?> /></div>
		<div class="_15  margin_top_12"  style="margin-left:0px !important">
			<?php echo $this->translate->_('Show All Days');?> &nbsp;&nbsp;
        </div>		
		<div class="_5"><input type="submit" name="btnload" id="btnload" value="<?php  echo $this->translate->_('OK'); ?>" class="margin_zero"></div>
		<div class="_10"><input type="submit" name="btnreset" id="btnreset" value="<?php echo $this->translate->_('RESET'); ?>" class="margin_zero"></div>
            <div class="_15">
                &nbsp;
            </div>
	</div>
	<div class="clear space_20"></div>
	<?php if($this->total_record > 0) { ?>
		<div class="_20 margin_0"><input type="button" name="btnendroute" id="btnendroute" value="<?php  echo $this->translate->_('END ROUTE(S)'); ?>"></div>
	<?php } ?>
	<div class="clear"></div>
	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>