<?php
/**
* @name       addbrancharcollection.phtml
* @since      07-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');

?>
<script>
        $(document).ready(function(){
            loaddata('<?php echo $this->itemgrid; ?>','item-grid');
            loaddata('<?php echo $this->itemgrid2; ?>','item-grid-2');
        })
</script>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/public/css/pagegrid_2_style.css"  />
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="hhctransaction_index_addbrancharcollection">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_10"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
       <h3><?php echo $this->translate->_('HHC Branch AR Collection')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"brancharcollection"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>

<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"brancharcollection"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"addbrancharcollection"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content with-actions ie_grid min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>

	<div class="_100">
	    <div class="_25_1">&nbsp;</div>
	    <div class="_25_1 margin_right_1">&nbsp;</div>
	    <label class="_25_1 label_text_align margin_top_20">
		<?php echo $this->translate->_('Doc Date').''.$this->colan;?>
	    </label>
	    <label class="_25_1 margin_right_1 margin_top_20">
		<?php echo date('d-m-Y h:i:s');?>
	    </label>

	</div>
	<div class="_100">
	    <div class="_25_1">&nbsp;</div>
	    <div class="_25_1 margin_right_1">&nbsp;</div>
	    <label class="_25_1 label_text_align margin_top_20">
		<?php echo $this->translate->_('Route Start of Day').''.$this->colan;?>
	    </label>
	    <label class="_25_1  margin_right_1 margin_top_20">
		<?php echo date('d-m-Y');?>
	    </label>

	</div>

	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_17">
		<?php echo $this->translate->_('Document No').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_doc_no" name="txt_doc_no" value="2501000020">
	    </div>
	    <div class="_25_1">
		&nbsp;
	    </div>
	    <div class="_25_1 margin_right_1">
		&nbsp;
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_20">
		<?php echo $this->translate->_('Route').''.$this->required;?>
	    </label>
	    <div class="_25_1 margin_top_7 margin_right_1">
		<select id="ddlroute" name="ddlroute" class="required" >
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->route);$i++)
			{
		    ?>
			    <option selected="selected" value="<?php echo $this->route[$i]['id'];?>"><?php echo $this->route[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	    <label class="_25_1 label_text_align margin_top_17">
		<?php echo $this->translate->_('AR No').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_ar_no" name="txt_ar_no" value="2501600001" >
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_20">
		<?php echo $this->translate->_('Salesman').''.$this->required;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_salesman" name="txt_salesman" value="2001 TB Akram Al Kasirie" class="required" >
	    </div>
	    <label class="_25_1 label_text_align margin_top_17">
		<?php echo $this->translate->_('Document Status').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_doc_status" name="txt_doc_status" value="Valid">
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_20">
		<?php echo $this->translate->_('Customer').''.$this->required;?>
	    </label>
	    <div class="_25_1 margin_top_7 margin_right_1">
		<select id="ddlcustomer" name="ddlcustomer" class="required" >
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->customer);$i++)
			{
		    ?>
			    <option selected="selected" value="<?php echo $this->customer[$i]['id'];?>"><?php echo $this->customer[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	    <label class="_25_1 label_text_align margin_top_17">
		<?php echo $this->translate->_('Acc Period').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txtacc_period" name="txtacc_period" value="Opened">
	    </div>
	</div>

	<div class="_100 margin_top_10">
	    <label class="_25_1 label_text_align">
		&nbsp;
	    </label>
	    <div class="_25_1 margin_right_1">
		&nbsp;
	    </div><div class="_20" >&nbsp;</div>
	    <div class="_5" >
		<input type="checkbox" id="chk_fifo" name="chk_fifo" value="1" checked="checked" >
	    </div>
	    <div class="_25_1 margin_top_10 margin_right_1">
		<?php echo $this->translate->_('First In First Out');?>
	    </div>
	</div>

	<div class="_100">
	    <div class="clear_only space_50"></div>
	</div>
	<div class="_100">
	    <div id="loader"></div>
	    <div id="item-grid"> <!--grid load here --> </div>
	</div>



	<!--<div class="_100">-->
	<!---->
	<!--    <label class="_15 label_text_align margin_top_17">-->
	<!--	<?php echo $this->translate->_('Invoice Amount').''.$this->colan;?>-->
	<!--    </label>-->
	<!--    <div class="_15">-->
	<!--	<input type="text" id="txt_invoice_amount" name="txt_total_amount_paid" value="50">-->
	<!--    </div>-->
	<!--    <label class="_15 label_text_align margin_top_17">-->
	<!--	<?php echo $this->translate->_('Balance Amount').''.$this->colan;?>-->
	<!--    </label>-->
	<!--    <div class="_15">-->
	<!--	<input type="text" id="txt_balance_amount" name="txt_balance_amount" value="50">-->
	<!--    </div>-->
	<!--    <label class="_15 label_text_align margin_top_17">-->
	<!--	<?php echo $this->translate->_('Amount Paid').''.$this->colan;?>-->
	<!--    </label>-->
	<!--    <label class="_15" left ">-->
	<!--	<input type="text" id="txt_amount_paid" name="txt_total_amount_paid" value="100">-->
	<!--    </label>-->
	<!---->
	<!--</div>-->

	<div class="clear_only space_20"></div>
	<fieldset>

	    <div class="_100 margin_top_20">
		<label class="_25_1 margin_top_20 label_text_align">
		    <?php echo $this->translate->_('Paymente Mode').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_top_7 margin_right_1">
		    <select id="ddlpaymentmode" name="ddlpaymentmode" >
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->paymentmode);$i++)
			{
		    ?>
			    <option selected="selected" value="<?php echo $this->paymentmode[$i]['id'];?>"><?php echo $this->paymentmode[$i]['val'];?></option>
		    <?php } ?>
		</select>
		</div>

		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Amount').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_amount" name="txt_amount" value="450">
		</div>
	    </div>

	    <div class="_100">
		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Cheque Number').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_cheque_number" name="txt_cheque_number" value="8765478">
		</div>

		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Cheque Date').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_check_date" name="txt_check_date" value="08/02/2012">
		</div>

	    </div>

	    <div class="_100">
		<div class="_25_1">&nbsp;</div>
		<div class="_25_1">&nbsp;</div>
		<div class="_25_1">&nbsp;</div>
		<div class="_25_1">
		   <input type="submit" id="btn_add" name="btn_add" value="Add">
		</div>
	    </div>

	</fieldset>
	<div id="loader2" style="margin-top:50%"></div>
	<div class="clear"></div>
	<div class="_100" id="item-grid-2">
		<?php //echo $this->partial('datagrid_2.phtml', $this); ?>
	</div>
</div>
</form>
</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>