<?php
/**
* @name       addcustomersalesorder.phtml
* @since      03-02-2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');

//$this->headLink()->appendStylesheet($this->baseUrl().'/public/css/datetimepicker/jquery-ui-1.8.16.custom.css');


?>
<script>
        $(document).ready(function(){
            loaddata('<?php echo $this->itemgrid; ?>','item-grid');
        })
</script>
<!--<script type="text/javascript" src="<?php echo $this->baseUrl().'/public/js/jquery-1.6.4.min.js';?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/public/js/jquery-ui-1.8.16.custom.min.js';?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/public/js/jquery-ui-timepicker-addon.js';?>"></script>-->

<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;}
</style>

<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/public/css/pagegrid_2_style.css"  />
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="hhctransaction_index_addarcollection">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_10"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
       <h3><?php echo $this->translate->_('Sales Order')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"customersalesorder"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>

<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"customersalesorder"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"addcustomersalesorder"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content with-actions ie_grid min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_17">
		<?php echo $this->translate->_('Order No').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_ord_no" name="txt_ord_no" value="2501000020">
	    </div>
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Order Type').''.$this->colan;?>
	     </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_ord_type" name="txt_ord_type" value="cash" >
	    </div>
	</div>
	<div class="_100">
            <label class="_25_1 label_text_align margin_top_17">
		<?php echo $this->translate->_('Status').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_ord_status" name="txt_ord_status" value="Active" >
	    </div>
            <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Order Date').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_5">
		<input type="text" id="txtstartdate" name="txtstartdate" value="22/02/2012" class="margin_top_5">
	    </div>
	</div>


	<div class="_100">
            <label class="_25_1 label_text_align margin_top_17">
		<?php echo $this->translate->_('Order Time').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_ord_time" name="txt_ord_time" value="07:08 AM">
	    </div>

	    <label class="_25_1 label_text_align margin_top_17">
		<?php echo $this->translate->_('Delivery Date').''.$this->required;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_5">
		<input type="text" id="txtenddate" name="txtenddate" value="23/02/2012" class="required margin_top_5" >
	    </div>
	</div>
	<div class="_100">
             <label class="_25_1 label_text_align margin_top_20">
		<?php echo $this->translate->_('Route').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_top_7 margin_right_1">
		<select id="ddlroute" name="ddlroute">

		    <?php
			for($i=0;$i<count($this->route);$i++)
			{
		    ?>
			    <option value="<?php echo $this->route[$i]['id'];?>"><?php echo $this->route[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	    <label class="_25_1 label_text_align margin_top_20">
		<?php echo $this->translate->_('Customer').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_top_7 margin_right_1 margin_top_5">
		<select id="ddlcustomer" name="ddlcustomer">

		    <?php
			for($i=0;$i<count($this->customer);$i++)
			{
		    ?>
			    <option value="<?php echo $this->customer[$i]['id'];?>"  ><?php echo $this->customer[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>

	</div>

	<div class="_100">
	     <label class="_25_1 label_text_align margin_top_20">
		<?php echo $this->translate->_('Delivery Route').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_5">
		<select id="ddldelroute" name="ddldelroute" >

		    <?php
			for($i=0;$i<count($this->route);$i++)
			{
		    ?>
			    <option  value="<?php echo $this->route[$i]['id'];?>"><?php echo $this->route[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	     <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('PO Number').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_po_no" name="txt_po_no" value="" class="margin_top_5">
	    </div>
	</div>

        <div class="_100">
	    <div class="clear_only space_50"></div>
	</div>

        <fieldset>
            <legend> <?php echo $this->translate->_('Item Details');?></legend>
	    <div class="_100 margin_top_20">
		<label class="_25_1 margin_top_20 label_text_align">
		    <?php echo $this->translate->_('Item').''.$this->required;?>
		</label>
		<div class="_25_1 margin_top_7 margin_right_1">
		    <select id="ddlitem" name="ddlitem" class="required">
		    <option value="" >--select--</option>
		    <?php
			for($i=0;$i<count($this->item);$i++)
			{
		    ?>
			    <option  value="<?php echo $this->item[$i]['id'];?>" <?php if($this->item[$i]['id']==11) { echo "selected"; }  ?> ><?php echo $this->item[$i]['val'];?></option>
		    <?php } ?>
		</select>
		</div>

		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('UPC').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_upc" name="txt_upc" value="9">
		</div>
	    </div>

	    <div class="_100">
		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Sales Price').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_sales_price" name="txt_sales_price" value="100">
		</div>

		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Return').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_return" name="txt_return" value="23">
		</div>

	    </div>

            <div class="_100">
		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Sales Case').''.$this->required;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_sales_cases" name="txt_sales_cases" value="10" class="required"/>
		</div>

		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Sales Pcs').''.$this->required;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_sales_pcs" name="txt_sales_pcs" value="23" class="required">
		</div>

	    </div>

             <div class="_100">
		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Return(Expiry) Case').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_ret_exp_cases" name="txt_ret_exp_cases" value="100">
		</div>

		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Return(Expiry) Pcs').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_ret_exp_pcs" name="txt_ret_exp_pcs" value="23">
		</div>

	    </div>

            <div class="_100">
		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Free Cases').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_free_goods_cases" name="txt_free_goods_cases" value="100">
		</div>

		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Free Pcs').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_free_goods_pcs" name="txt_free_goods_pcs" value="23">
		</div>

	    </div>

             <div class="_100">
		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Allocated Sales Cases').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_alloc_sales_cases" name="txt_alloc_sales_cases" value="100">
		</div>

		<label class="_25_1 margin_top_17 label_text_align">
		    <?php echo $this->translate->_('Allocated Sales Pcs').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_alloc_sales_pcs" name="txt_alloc_sales_pcs" value="23">
		</div>

	    </div>
	    <div class="_100">
		<div class="_25_1">&nbsp;</div>

		<div class="_25_1">&nbsp;</div>
		<div class="_25_1">&nbsp;</div>
		<div class="_25_1">
		   <input type="submit" id="btn_add" name="btn_add" value="Add">
		</div>
	    </div>
	</fieldset>


	<div class="_100">
	    <div class="clear_only space_50"></div>
	</div>

	<div class="_100">
	    <div id="loader"></div>
	    <div id="item-grid"> <!--grid load here --> </div>
	</div>

	<div class="_100">
	    <div class="clear_only space_50"></div>
	</div>

</div>
</form>
</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
            //Time Picker
//            $('#txt_ord_time').timepicker({
//                ampm: true,
//                hourMin: 8,
//                hourMax: 16
//            });

         /*$('#txt_ord_time').timepicker({
                  showPeriod: true,
                  showLeadingZero: true,
                  onSelect:function(){
                  }
         });*/
    });
});
</script>