<?php
/**
* @name       addreason.phtml
* @since      06-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* 
*/

$this->translate = Zend_Registry::get('Zend_Translate');

?> 
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<script>
    $(document).ready(function(){
	loaddata('<?php echo $this->itemgrid; ?>','item-grid');
    })
</script>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
<div class="header">    
    <div class="_50_3 back_btn">
	<img class="margin_top_10"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
        <h3><?php echo $this->translate->_('Add Reason')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"invoice"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>    


<div id="ie_spacer" ></div>

<div class="content with-actions ie_grid min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
	
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_20">
		<?php echo $this->translate->_('Item Code').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txt_item_code" name="txt_item_code" value="349">
	    </div>
	    <label class="_25_1 label_text_align margin_top_20">
		<?php echo $this->translate->_('UPC').''.$this->colan;?>
	    </label>
	    <label class="_25_1 margin_right_1">
		<input type="text" id="txt_upc" name="txt_upc" value="12">
	    </label>
	    
	</div>
	
	
	<div class="space_50"></div>
	<fieldset>
	    
	    
	    <div class="_100 margin_top_20">
		<label class="_25_1 margin_top_15 label_text_align">
		    <?php echo $this->translate->_('Reason').$this->required;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <select id="ddlreason" name="ddlreason" class="required" >
		    <option value="">--- Select ---</option>
		    <?php		    
			for($i=0;$i<count($this->reason);$i++)
			{
		    ?>
			    <option selected="selected" value="<?php echo $this->reason[$i]['id'];?>"><?php echo $this->reason[$i]['val'];?></option>
		    <?php } ?>
		</select>
		</div>
		
		<label class="_25_1 margin_top_15 label_text_align">
		    <?php echo $this->translate->_('Case').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_cases" name="txt_cases" value="2">
		</div>
	    </div>
	    
	    <div class="_100 ">
		<label class="_25_1 margin_top_15 label_text_align">
		    <?php echo $this->translate->_('Pcs').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_cases" name="txt_cases" value="2">
		</div>
		<div class="_25_1" >&nbsp;</div>
		<div class="_25_1 margin_right_1" >&nbsp;</div>
	    </div>
	    
	</fieldset>
	
	<div class="clear"></div>
	<div id="loader"></div>
	<div class="_100" id="item-grid" >
		<?php //echo $this->partial('datagrid.phtml', $this); ?>
	</div>
	
	<div class="clear space_50"></div>
</div>
</form>
</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>