<?php
/**
* @name       addtransferout.phtml
* @since      03-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');


/* $this->headScript()->appendFile($this->baseUrl().'/public/js/jquery.prettyPhoto.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/public/css/prettyPhoto.css'); */
?>
<script>
        $(document).ready(function(){
            loaddata('<?php echo $this->itemgrid; ?>','item-grid');
        })
</script>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="hhctransaction_index_addtransferout">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_10"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
        <h3><?php echo $this->translate->_('Transfer Out')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"transferout"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"transferout"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"addtransferout"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content with-actions ie_grid min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>

	<div class="_100">
	    <div class="_5">&nbsp;</div>
	    <label class="_15 label_text_align"><?php echo $this->translate->_('Transaction Date').''.$this->colan;?></label>
	    <div class="_15"><?php echo date('d-m-Y');?></div>
	    <label class="_15 label_text_align"><?php echo $this->translate->_('Transaction Time').''.$this->colan;?></label>
	    <div class="_15"><?php echo date('h:m');?></div>
	    <label class="_15 label_text_align"><?php echo $this->translate->_('Route Start Date').''.$this->colan;?></label>
	    <div class="_15"><?php echo date('d-m-Y');?></div>
	    <div class="_5">&nbsp;</div>
	</div>
	<div class="_100 margin_top_10 ">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Document No.').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtpromo_key" name="txtpromo_key" value="25101000060">
	    </div>
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Document Status').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtdoc_status" name="txtdoc_status" value="Closed">
	    </div>
	</div>
	<div class="_100 ">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Route').''.$this->required;?>
	    </label>
	    <div class="_25_1">
		<select id="ddlroute" name="ddlroute" class="required">
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->route);$i++)
			{
		    ?>
			    <option selected="selected" value="<?php echo $this->route[$i]['id'];?>"><?php echo $this->route[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Acc Period').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtacc_period" name="txtacc_period" value="Done">
	    </div>
	</div>
	<div class="_100 margin_bottom_10">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Salesman').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="salesman" name="salesman" value="2001 TB Akram Al Kasirie"  class="">
	    </div>
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Transfer Route').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<select id="ddltrans_route" name="ddltrans_route">
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->trans_route);$i++)
			{
		    ?>
			    <option selected="selected" value="<?php echo $this->trans_route[$i]['id'];?>"><?php echo $this->trans_route[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	</div>

	<div class="clear space_20"></div>
	<fieldset class="fieldset_effect">
	    <legend class="ttl" ><?php echo $this->translate->_('Transfer Out');?></legend>
	    <hr id="ie_hr" >
	    <div id="loader"></div>
	    <div class="_100" id="item-grid">
		<?php //echo $this->partial('datagrid.phtml', $this); ?>
	    </div>
	</fieldset>
</div>
</form>
</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>