<?php
/**
* @name       addunloadvariance.phtml
* @since      28/02/12
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
        $(document).ready(function(){
            loaddata('<?php echo $this->itemgrid; ?>','item-grid');
        })
</script>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="hhctransaction_index_addclosingstock">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_10"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
        <h3><?php echo $this->translate->_('Unload Variance')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"unloadvariance"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"unloadvariance"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"addunloadvariance"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content with-actions ie_grid min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>

	<div class="_100">
	    <div class="_5">&nbsp;</div>
	    <label class="_15 label_text_align"><?php echo $this->translate->_('Transaction Date').''.$this->colan;?></label>
	    <div class="_15"><?php echo date('d-m-Y');?></div>
	    <label class="_15 label_text_align"><?php echo $this->translate->_('Transaction Time').''.$this->colan;?></label>
	    <div class="_15"><?php echo date('h:m');?></div>
	    <label class="_15 label_text_align"><?php echo $this->translate->_('Route Start Date').''.$this->colan;?></label>
	    <div class="_15"><?php echo date('d-m-Y');?></div>
	    <div class="_5">&nbsp;</div>
	</div>
	<div class="_100 margin_top_10 ">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Document No.').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtpromo_key" name="txtpromo_key" value="33101000015">
	    </div>
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Document Valid').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtdoc_valid" name="txtdoc_valid" value="Valid">
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Route').''.$this->required;?>
	    </label>
	    <div class="_25_1 margin_right_2_2">
		<select id="ddlroute" name="ddlroute" class="required">
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->route);$i++)
			{
		    ?>
			    <option value="<?php echo $this->route[$i]['id'];?>" <?php if($this->route[$i]['id']==14) { echo "selected"; }  ?> ><?php echo $this->route[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Acc Period').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtacc_period" name="txtacc_period" value="Closed">
	    </div>
	</div>
	<div class="_100 margin_bottom_10">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Salesman').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtsalesman" name="txtsalesman" value="SHAMEER"  class="">
	    </div>
	</div>
	<div class="_100">
	    <div id="loader"></div>
	    <div id="item-grid"> <!--grid load here --> </div>
	</div>

</div>
</form>
</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});

	$("#ddlroute").change(function() {
	    var str = $(this).find("option:selected").text();
	    var substr = str.split(' -- ');
	    $("#txtsalesman").attr("value",substr[1]);
	});
    });


});
</script>