<?php
/**
* @name       addunloadendinginventory.phtml
* @since      03-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');


/* $this->headScript()->appendFile($this->baseUrl().'/public/js/jquery.prettyPhoto.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/public/css/prettyPhoto.css'); */
?>
<script>
        $(document).ready(function(){
            loaddata('<?php echo $this->itemgrid; ?>','item-grid');
        })
</script>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="hhctransaction_index_addunloadendinginventory">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_10"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
        <h3><?php echo $this->translate->_('Unloaded Stock')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"unloadendinginventory"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div class="_100" >
   <div class="_20 label_text_align margin_top_7">&nbsp;</div>
		<div class="_20 label_text_align margin_top_12"><label class="advance_search_css"><?php echo $this->translate->_('Select Date').''.$this->colan;?></label></div>
		<div class="_20 margin_top_7 label_text_align"><input type="text" id="txtdate" name="txtdate" value="<?php echo date('d-m-Y');?>" class="margin_zero"></div>
		<div class="_10 margin_top_7"><input type="button" name="btnload" id="btnload" value="<?php echo $this->translate->_('OK'); ?>" class="margin_zero"></div>
                    <div class="_30">
                        &nbsp;
                    </div>
</div>
	<div class="clear space_20"></div>
	<div class="clear"></div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"unloadendinginventory"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"addunloadendinginventory"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content with-actions ie_grid min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>

	<div class="_100">
	    <div class="_5">&nbsp;</div>
	    <label class="_15 label_text_align"><?php echo $this->translate->_('Transaction Date').''.$this->colan;?></label>
	    <div class="_15"><?php echo date('d-m-Y');?></div>
	    <label class="_15 label_text_align"><?php echo $this->translate->_('Transaction Time').''.$this->colan;?></label>
	    <div class="_15"><?php echo date('h:m');?></div>
	    <label class="_15 label_text_align"><?php echo $this->translate->_('Route Start Date').''.$this->colan;?></label>
	    <div class="_15"><?php echo date('d-m-Y');?></div>
	    <div class="_5">&nbsp;</div>
	</div>
	<div class="_100 margin_top_10 ">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Document No.').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txtpromo_key" name="txtpromo_key" value="25101000060">
	    </div>
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Document Status').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txtdoc_status" name="txtdoc_status" value="Closed">
	    </div>
	</div>
	<div class="_100 ">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Route').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<select id="ddlroute" name="ddlroute" >
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->route);$i++)
			{
		    ?>
			    <option selected="selected" value="<?php echo $this->route[$i]['id'];?>"><?php echo $this->route[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Acc Period').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="txtacc_period" name="txtacc_period" value="Opened">
	    </div>
	</div>
	<div class="_100 margin_bottom_10">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Salesman').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<input type="text" id="salesman" name="salesman" value="A242 - 999 - ABDUL AMIR SUDANI"  class="">
	    </div>

	</div>
	<fieldset>
	    <legend ><?php echo $this->translate->_('Add Item');?></legend>

	    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Item').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <select id="ddlitem" name="ddlitem">
			<option value="">--- Select ---</option>
			<?php
			    for($i=0;$i<count($this->item);$i++)
			    {
			?>
				<option selected="selected" value="<?php echo $this->item[$i]['id'];?>"><?php echo $this->item[$i]['val'];?></option>
			<?php  } ?>
		    </select>
		</div>
		<label class="_25_1 label_text_align margin_top_12">
		    <?php echo $this->translate->_('Case').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <input type="text" id="txtcases" name="txtcases" value="2">
		</div>
	    </div>

	    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('UPC').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <input type="text" id="txtupc" name="txtupc" value="3"  class="">
		</div>
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Pcs').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txtpieces" name="txtpieces" value="4">
		</div>
	    </div>

	    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Sales Price').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <input type="text" id="txtsales_price" name="txtsales_price" value="700"  class="">
		</div>
		<label class="_25_1 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Quantity').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		   <input type="text" id="txt_quantity" name="txt_quantity" value="24">
		</div>
	    </div>
	    <div class="_100">
		<label class="_25_1 margin_top_10 label_text_align">

		</label>
		<div class="_25_1">
		    &nbsp;
		</div>
		<label class="_25_1 margin_top_10 label_text_align">

		</label>
		<div class="_5_3">
		   <input type="submit" id="btn_addd" name="btn_addd" value="<?php echo $this->translate->_('ADD');?>">
		</div>
	    </div>

	</fieldset>
	<div id="loader"></div>
	<div class="_100" id="item-grid">
		<?php //echo $this->partial('datagrid.phtml', $this); ?>
	</div>
</div>
</form>
</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>