<script type="text/javascript">
    jQuery(document).ready(function()
    {
        jQuery("#adduser").validationEngine();
    });

//function validateEmail(txtEmail){
//   var a = document.getElementById(txtEmail).value;
//   var filter = /^[a-zA-Z0-9]+[a-zA-Z0-9_.-]+[a-zA-Z0-9_-]+@[a-zA-Z0-9]+[a-zA-Z0-9.-]+[a-zA-Z0-9]+.[a-z]{2,4}$/;
//    if(filter.test(a)){
//        return true;
//    }
//    else{
//        return false;
//    }
//}

    
function ValidateHhctransaction()
{
    var temp = 1;
    if(jQuery('#txtfirstname').val() == '' || jQuery('#txtfirstname').val() == 'First Name')
    {
        jQuery('#msg1').validationEngine('showPrompt', 'Please Enter First Name', 'pass');
        temp = 0;
    } else {
        jQuery('#msg1').validationEngine('hidePrompt');
    }
    if(jQuery('#txtlastname').val() == '' || jQuery('#txtlastname').val() == 'Last Name')
    {
        jQuery('#msg2').validationEngine('showPrompt', 'Please Enter Last Name', 'pass');
        temp = 0;
    } else {
        jQuery('#msg2').validationEngine('hidePrompt');
    }
    if(jQuery('#ddltitle').val() == '' || jQuery('#ddltitle').val() == 'Title')
    {
        jQuery('#msg3').validationEngine('showPrompt', 'Please Enter Title', 'pass');
        temp = 0;
    } else {
        jQuery('#msg3').validationEngine('hidePrompt');
    }
    
    if(jQuery('#txtemailid').val() == '' || jQuery('#txtemailid').val() == 'Email')
    {
        jQuery('#msg4').validationEngine('showPrompt', 'Please Enter Email Address', 'pass');
        temp = 0;
    }
    else
    {   
        jQuery('#msg4').validationEngine('hidePrompt');
    }
    
    if(jQuery('#txtcompany').val() == '' || jQuery('#txtcompany').val() == 'Company')
    {
        jQuery('#msg5').validationEngine('showPrompt', 'Please Enter Company Name', 'pass');
        temp = 0;
    } else {
        jQuery('#msg5').validationEngine('hidePrompt');
    }
    if(temp == 0) {
        return false;
    } else {
        return true;
    }
}

function hideShow(objid, method, message)
{
    if(method == 'focus')
    {
        document.getElementById(objid).value = '';
    }
    
    if(method == 'blur' && document.getElementById(objid).value == '')
    {
        document.getElementById(objid).value = message;
    }
}
</script>
<div id="body_area_inner">
    <!--title start-->
    <div id="inner_title">
        <h1><?php echo $this->header_title?></h1>
    </div>
    <!--title end-->
    <div class="line_con"></div>
    
    <?php
    $msg = '';
    if($this->msg == 100) {
	$msg = 'Thank you for signing up in Material Mix. We have sent you account activation link via email.';
    }
    elseif($this->msg == 11) {
        $msg = 'Your account has been successfully activated.!';
    }
    elseif($this->msg == 12) {
        $msg = 'Sorry, this activation link is does not exist.!';
    }
    if(!empty($msg)) {
    ?>
    <div class="msg msg-ok"><p><strong><?php  echo $msg ;?></strong></p></div>
    <?php } ?>
    
    <!--content start-->            
    <div id="con_area">
        <!--contentleft start-->            
        <div id="con_arealeft">
            <?php
                /*
                 * Display page contents and replace base_url with site baseurl for sitemap
                 */
                echo str_replace('{base_url}',$this->baseUrl(),$this->pagedetail[0]['description']);
            ?>        
        </div>
        <!--contentleft end-->
        <div id="con_arearight">
            <form method="post" action="" enctype="multipart/form-data"  id="adduser">
                <?php  
                $msg = '';
                if($this->msg == '1') {
                    $msg = 'Email is already exist!';
                }
                if(!empty($msg )) {
                ?>
                <div>&nbsp;</div>
                <div class="msg msg-ok"><p><strong><?php  echo $msg ;?></strong></p></div>
                <div>&nbsp;</div>
                <?php   } ?>
                <div class="rt"></div>
                <?php
                /*
                 * Inserted by MB [Elan] - To get inputted value if error occurs
                 */
                $first_name = (!empty($this->first_name)) ? $this->first_name : 'First Name';
                $last_name = (!empty($this->last_name)) ? $this->last_name : 'Last Name';
                $title = (!empty($this->title)) ? $this->title : 'Title';
                $email = (!empty($this->email)) ? $this->email : 'Email';
                $company = (!empty($this->company)) ? $this->company : 'Company';
                /*
                 * Inserted by MB [Elan] - To get inputted value if error occurs
                 */
                ?>
                <div class="rm">
                    <div class="form_title">
                        <h4><?php echo $this->page_title; ?></h4>
                    </div>                    
                    <div class="form_link">
                    <input type="hidden" id="ddltype" name="ddltype" value="0" />
                        <!--<ul>
                            <li><input id="ddltype" name="ddltype" type="radio" checked="checked" value="1" />&nbsp;Buyer / Seller&nbsp;</li>
                            <li><input id="ddltype" name="ddltype" type="radio" value="2" />&nbsp;Transporter&nbsp;</li>
                            <li><input id="ddltype" name="ddltype" type="radio" value="3" />&nbsp;Technology Provider&nbsp;</li>
                        </ul>-->
                    </div><br />
                    <div class="form_list">
                        <div id="msg1"></div>
                        <div class="form_listcon">First Name*</div>
                        <input type="text" class="input" title="Please enter First name!" name="txtfirstname" size="54" id="txtfirstname" value="<?php echo $first_name; ?>" onblur="hideShow('txtfirstname','blur','<?php echo $first_name; ?>')" onfocus="hideShow('txtfirstname','focus')" />
                    </div>
                    <div class="form_list">
                        <div id="msg2"></div>
                        <div class="form_listcon">Last Name*</div>
                        <input type="text" class="input" title="Please enter Last name!" name="txtlastname" size="54" id="txtlastname" value="<?php echo $last_name; ?>" onblur="hideShow('txtlastname','blur','<?php echo $last_name; ?>')" onfocus="hideShow('txtlastname','focus')" />
                    </div>
                    <div class="form_list">
                        <div id="msg3"></div>
                        <div class="form_listcon">Title*</div>
                        <input type="text" class="input" title="Please enter Title!" name="ddltitle" size="54" id="ddltitle" value="<?php echo $title; ?>" onblur="hideShow('ddltitle','blur','<?php echo $title; ?>')" onfocus="hideShow('ddltitle','focus')" />
                    </div>                    
                    <div class="form_list">
                        <div id="msg4"></div>
                        <div class="form_listcon">Email*</div>
                        <input type="text" name="txtemailid" title="Please enter Email Address!" class="input" size="54" id="txtemailid" value="<?php echo $email; ?>" onblur="hideShow('txtemailid','blur','<?php echo $email; ?>')" onfocus="hideShow('txtemailid','focus')" />
                    </div>
                    <div class="form_list">
                        <div id="msg5"></div>
                        <div class="form_listcon">Company*</div>
                        <input type="text" name="txtcompany" title="Please enter Company name!" class="input" id="txtcompany" size="54" value="<?php echo $company; ?>" onblur="hideShow('txtcompany','blur','<?php echo $company; ?>')" onfocus="hideShow('txtcompany','focus')" />
                    </div>
                    
                    <div class="form_list">
                        <div class="form_listcon">&nbsp;</div><span>*Required information</span>
                    </div>                    
                        <input type="hidden" name="txtusername" id="txtusername" value="<?=time()?>" />
                        <input type="hidden" name="txtpassword" id="txtpassword" value="<?=time()?>" />
                        <input type="hidden" id="uid" name="uid" value="<?php echo $this->uid; ?>" />
                    
                    <div class="form_list">
                        <div class="form_listcon">&nbsp;</div><input type="submit" class="signup_big border_none" name="btnsubmit" id="btnsubmit" value="" onclick="return ValidateHhctransaction();" title="Sign Up" />
                    </div>
                </div>
                <div class="rb"></div>        
            </form>
        </div>
    </div>

</div>
<div class="clear">&nbsp;</div>
