<?php
/**
* @name       print.phtml
* @since      13-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  Elan Technologies
*
* 
*/

$this->translate = Zend_Registry::get('Zend_Translate');

?>


<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png" class="margin_top_10">
		<h3><?php echo $this->pagetitle; ?></h3>
	    </div>
	    <div class="_50_3">
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint" onclick="window.print()" ></div>

	    </div>
        </div>
	<div class="clear"></div>
	<div class="clear"></div>
	
	<?php echo $this->partial('print-datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->

