<?php
/**
* @name       linksurvey.phtml
* @since      31-01-12
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="hhctransaction_index_startofday">
<form id="frmdet" name="frmdet" class="validate" action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_10"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
        <h3><?php echo $this->translate->_('Route Start Of Day')?></h3>
    </div>
</div>
<div class="clear"></div>
<div class="clear"></div>


<div class="content with-actions">
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<label class="_36 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Route').''.$this->required;?>
	</label>
	<div class="_50 margin_right_1">
	    <select id="ddlroute" name="ddlroute" class="required">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->route);$i++)
		    {
		?>
			<option value="<?php echo $this->route[$i]['id'];?>"><?php echo $this->route[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>

    </div>
    <div class="_100">
	<label class="_36 margin_top_10 label_text_align">
	    <?php echo $this->translate->_('Salesman').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	  <input type="text" id="txtsalesman" name="txtsalesman" value="" class="margin_top_5" readonly="readonly" >
	</div>
    </div>
    <div class="_100">
	<label class="_36 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Date').''.$this->colan;?>
	</label>
	<div class="_15 margin_right_1" style="margin-right:2%;">
	    <input type="text" id="txtdate" name="txtdate" value="" >
	</div>
    </div>
    <div class="_100">
	<div class="_36">&nbsp;</div>
	<div class="_15 margin_right_2_2">
	  <input type="submit" id="txtok" name="txtok" value="<?php echo $this->translate->_('OK');?>" >
	</div>
	<div class="_36">&nbsp;</div>

    </div>
    <div class="space_300">

    </div>

</div>
</form>
</div> <!-- End of .box -->
</div>
</form>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});

	$("#ddlroute").change(function() {
	    var str = $(this).find("option:selected").text();
	    var substr = str.split(' -- ');
	    $("#txtsalesman").attr("value",substr[1]);
	});
    });
});
</script>