<?php
/**
* @name       transferout.phtml
* @since      03-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$Common_NameSpace = new Zend_Session_Namespace('Common');
?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png" class="margin_top_10">
		<h3><?php echo $this->translate->_('Transfer Out')?></h3>
	    </div>
	    <div class="_50_3">
		<!--<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnexport" id="btnexport"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint"></div>-->
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btndelete" id="btndelete"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnedit" name="btnedit"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnadd" name="btnadd" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"addtransferout"), "default", true);?>')"></div>
	    </div>
        </div>
	<div class="_100">
	    <div class="_10">&nbsp;</div>
	    <div class="_10 label_text_align margin_top_15"><?php echo $this->translate->_('Route');?></div>
	    <div class="_30_1 margin_top_5 margin_right_1">
		<select id="ddlroute" name="ddlroute" >
		    <option value="">--- Select ---</option>
		    <option value="">---<?php echo $this->translate->_('All');?>---</option>
		    <?php for($i=0;$i<count($this->route);$i++) {?>
		    <option value="<?php echo $this->route[$i]['id'];?>" <?php if($Common_NameSpace->ddlroute==$this->route[$i]['id']) { echo "selected"; } ?> ><?php echo $this->route[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
	    <div class="_20 label_text_align margin_top_17"><label class="advance_search_css"><?php echo $this->translate->_('Select Date').''.$this->colan;?></label></div>
	    <div class="_20 margin_top_7 label_text_align margin_right_1"><input type="text" id="txtdate" name="txtdate" value="<?php echo $Common_NameSpace->tdate; ?>"></div>
	    <div class="_5 margin_top_12 ie7marginright"><input type="submit" name="btnload" id="btnload" value="<?php echo $this->translate->_('OK'); ?>" class="margin_zero"></div>
            <div class="_20">&nbsp;</div>
	</div>
	<div class="clear space_20"></div>
	<div class="clear"></div>
<div id="nav_sub" class="ie_nav_sub">
	<div class="container_12">
	    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"transferout"),"default", true);?>"><b><?php echo $this->overview?></b></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"addtransferout"),"default", true);?>"><?php echo $this->details;?></a>
                </li>
            </ul>
        </li>
    </ul>
	</div>
	</div>
	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>