<?php
/**
* @name       unloadreturnstock.phtml
* @since      03-02-2012
* @version    Release: 1.0
* @author     M@M <miral@elantechnologies.com>
* @copyright  Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$Common_NameSpace = new Zend_Session_Namespace('Common');
?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png" class="margin_top_10">
		<h3><?php echo $this->translate->_('Damage Returns')?></h3>
	    </div>
	    <div class="_50_3">
		<!--<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnexport" id="btnexport"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint"></div>-->
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btndelete" id="btndelete"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnedit" name="btnedit"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnadd" name="btnadd" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"addunloadreturnstock"), "default", true);?>')"></div>
	    </div>
        </div>
	<div class="_100" >
            <div class="_20 label_text_align margin_top_7">&nbsp;</div>
		<div class="_20 label_text_align margin_top_10"><label class="advance_search_css"><?php echo $this->translate->_('Select Date').''.$this->colan;?></label></div>
		<div class="_20 margin_top_5 label_text_align"><input type="text" id="txtdate" name="txtdate" value="<?php echo $Common_NameSpace->tdate; ?>" class="margin_zero"></div>
		<div class="_5 margin_top_7 ie7marginright"><input type="submit" name="btnload" id="btnload" value="<?php echo $this->translate->_('OK'); ?>" class="margin_zero"></div>
                    <div class="_15">
                        &nbsp;
                    </div>
	</div>
	<div class="clear space_20"></div>
	<div class="clear"></div>
<div id="nav_sub" class="ie_nav_sub">
	<div class="container_12">
	    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"unloadreturnstock"),"default", true);?>"><b><?php echo $this->overview?></b></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"index","action"=>"addunloadreturnstock"),"default", true);?>"><?php echo $this->details;?></a>
                </li>
            </ul>
        </li>
    </ul>
	</div>
	</div>
	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>