<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>


<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({
   	url:base_url+"/reports/routedepositsummary/routedepositsummarydata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route End Date');?>','<?php echo $this->translate->_('Route Code');?>','<?php echo $this->translate->_('Invoice Type');?>','<?php echo $this->translate->_('Payment Type');?>','<?php echo $this->translate->_('Invoice Number');?>','<?php echo $this->translate->_('Transaction Time');?>','<?php echo $this->translate->_('Against Invoice');?>','<?php echo $this->translate->_('Invoiced Date');?>','<?php echo $this->translate->_('Invoiced Salesman');?>','<?php echo $this->translate->_('Customer Code');?>','<?php echo $this->translate->_('Customer Name');?>','<?php echo $this->translate->_('Bank Name');?>','<?php echo $this->translate->_('Check Number');?>','<?php echo $this->translate->_('Draw Date');?>','<?php echo $this->translate->_('Amount');?>'],
   	colModel:[
		{name:'routeenddate',index:'routeenddate', width:100},
        {name:'routecode',index:'routecode', width:120},
   		{name:'type',index:'type', width:120,align:'right'},
        {name:'paytype',index:'paytype', width:100,align:'right'},
        {name:'invoicenumber',index:'invoicenumber', width:90},
		{name:'transactiontime',index:'transactiontime', width:50,align:'right'},
        {name:'againstinv',index:'againstinv', width:70},
        {name:'saleinvoiceddate',index:'saleinvoiceddate', width:70},
        {name:'salesmancode',index:'salesmancode', width:50},
		{name:'customercode',index:'customercode', width:70},
        {name:'customername',index:'customername', width:200},
		{name:'bankname',index:'bankname', width:200,align:'right'},
        {name:'checknumber',index:'checknumber', width:100,align:'right'},
        {name:'drawdate',index:'drawdate', width:70,align:'right'},
        {name:'amount',index:'amount', width:70,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces },summaryType:'sum'}
	],
    <?php if($this->session->lang == "ar_AR") { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
   	pager: '#pagersr',
   	sortname: 'routeenddate,routecode,type,paytype',
	viewrecords:true,
	sortorder: "asc",
   	altRows : false,
    footerrow : true,
	userDataOnFooter : true,
    grouping:true,
    groupingView :
    {
        groupField : ['routeenddate','routecode','type','paytype'],
        groupColumnShow : [false,false,false,false],
        groupCollapse : true,
       // groupText : ['','<b>Total Deposit For {0} : {1}</b>','<b>Total Deposit {0} : {1}</b>','<b>Total {0} : {1}</b>'],
        groupOrder: ['asc','asc','asc','asc'],
        groupSummary : [false,false,false,true],
        groupDataSorted : true
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});

</script>
