<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({        
   	url:base_url+"/reports/soa/soadata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Customer Code');?>','<?php echo $this->translate->_('Detail Type');?>','<?php echo $this->translate->_('Detail Text');?>','<?php echo $this->translate->_('Transaction Date');?>','<?php echo $this->translate->_('Amount');?>'],
   	colModel:[
		{name:'customercode',index:'customercode', width:120,sortable: false},
   		{name:'detailtype',index:'detailtype', width:120,sortable: false},
        {name:'detailtext',index:'detailtext', width:120,sortable: false},
        {name:'transactiondate',index:'transactiondate', width:100,sortable: false},
        {name:'amount',index:'amount',align:"right", width:120,formatter:'number', summaryType:'sum',sortable: false,formatoptions: { decimalPlaces: decimalplaces }}
	],
	<?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: eval(reportwidth),
   	rowNum:eval(RP_NOOFRECORDSHOW),
    rowList:eval(RP_ROWLISTSHOW),
    pager: '#pagersr',
   	sortname: 'transactiondate',
	viewrecords:true,
	sortorder: "desc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,
	groupingView :
    {
        groupField : ['customercode'],
        groupColumnShow : [false],
        groupCollapse : true,
        groupOrder: ['asc'] ,
        groupSummary : [true],
        groupDataSorted : true,
        showSummaryOnHide: false
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});
</script>