<?php
/**
* @name       contact.phtml
* @since      03 feb, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<div class="content with-actions">
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Shop Telephone').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtshop_tel" name="txtshop_tel"  maxlength="30"  value="<?php echo $this->formdata['txtshop_tel'];?>">
	</div>
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Shop Fax').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtshop_fax" name="txtshop_fax"  maxlength="30" value="<?php echo $this->formdata['txtshop_fax'];?>">
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Owner Name').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtowner_name" name="txtowner_name"  maxlength="30" value="<?php echo $this->formdata['txtowner_name'];?>">
	</div>
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Owner Land Line').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtowner_land_line" name="txtowner_land_line"  maxlength="30"  value="<?php echo $this->formdata['txtowner_land_line'];?>">
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Owner Mobile').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtowner_mob" name="txtowner_mob"  maxlength="30" value="<?php echo $this->formdata['txtowner_mob'];?>">
	</div>
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Contact Person Name').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtcont_person_name" name="txtcont_person_name"  maxlength="30" value="<?php echo $this->formdata['txtcont_person_name'];?>">
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Contact Person Land Line').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtconta_land_line" name="txtconta_land_line"  maxlength="30" value="<?php echo $this->formdata['txtconta_land_line'];?>">
	</div>
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Contact Person Mobile').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtcontact_mobile" name="txtcontact_mobile"  maxlength="30" value="<?php echo $this->formdata['txtcontact_mobile'];?>">
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Contact Person Email').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtcontact_email" name="txtcontact_email"  maxlength="30" value="<?php echo $this->formdata['txtcontact_email'];?>">
	</div>
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Purchase Manager Name').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtmanager_name" name="txtmanager_name"  maxlength="30" value="<?php echo $this->formdata['txtmanager_name'];?>">
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Purchase Manager Landline Line').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtmanager_land_line" name="txtmanager_land_line"  maxlength="30" value="<?php echo $this->formdata['txtmanager_land_line'];?>">
	</div>
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Purchase Manager Mobile').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtmanager_mobile" name="txtmanager_mobile"  maxlength="30" value="<?php echo $this->formdata['txtmanager_mobile'];?>">
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Purchase Manager Email').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtmanager_email" name="txtmanager_email"  maxlength="30" value="<?php echo $this->formdata['txtmanager_email'];?>">
	</div>
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Warehouse Manager Name').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtware_maneger_name" name="txtware_maneger_name"  maxlength="30" value="<?php echo $this->formdata['txtware_maneger_name'];?>">
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Warehouse Manager Land Line').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtware_manager_land_line" name="txtware_manager_land_line"  maxlength="30" value="<?php echo $this->formdata['txtware_manager_land_line'];?>">
	</div>
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Ware House Manager Mobile').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtware_manager_mobile" name="txtware_manager_mobile"  maxlength="30" value="<?php echo $this->formdata['txtware_manager_mobile'];?>">
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Warehouse Manager Email').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtware_manager_email" name="txtware_manager_email"  maxlength="30" value="<?php echo $this->formdata['txtware_manager_email'];?>">
	</div>
	<label class="_25_1 margin_top_12 label_text_align">&nbsp;</label>
	<div class="_25_1">&nbsp;</div>
    </div>
</div>
