<?php
/**
* @name       index.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of website
*/
?>
<div class="clean"></div>
<div class="grid_12">
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li class="current">
		    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cpanel","action"=>"index"),"default", true);?>"><?php echo $this->general?></a>
		</li>
		<li class="current">
		    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cpanel","action"=>"route"),"default", true);?>"><?php echo $this->route?></a>
		</li>
		<li class="current">
		    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cpanel","action"=>"customer"),"default", true);?>"><?php echo $this->customer?></a>
		</li>
		<li class="last-child">
		    <a href="Javascript:void(0);"><?php echo $this->report;?></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
<div class="box">
<form method="post" action="">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	<h3><?php echo $this->route;?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btncancel" id="btncancel"></div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
    <div class="content no-padding with-actions">
        <div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100 margin_bottom_10">
	    <div class="_5_2">
                <input type="checkbox" id="chkalloradi" name="chkalloradi" value="1">
            </div>
	    <label class="_55 margin_top_10 text_align">
		<?php echo $this->allow_radius;?>
	    </label>
	    <div class="_5_2">
                <input type="checkbox" id="chkmultiload" name="chkmultiload" value="1">
            </div>
	    <label class="_40 margin_top_10 text_align">
		<?php echo $this->multi_load;?>
	    </label>
        </div>
    </div>
    <div class="actions">
        <div class="actions-left">
            <input type="reset" id="btnrst" name="btnrstsetting" value="<?php echo $this->reset;?>">
        </div>
        <div class="actions-right">
            <input type="submit" id="btnsubmit" name="btnsubmitsetting" value="<?php echo $this->submit;?>">
        </div>
    </div>
</form>
</div><!-- End of .box -->