<?php
/**
* @name       setting1.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');
?>
<div id="account_customer_setting1" class="content with-actions" style="min-height:700px;">
    <div class="_100">
	<div class="clean"></div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_10 label_text_align margin_right_1">
	    <?php echo $this->translate->_('Display Message 1').''.$this->colan;?>
	</label>
	<div class="_25_1 margin_right_1">
	    <select id="ddldis_msg_key1" name="ddldis_msg_key1" class="">
			<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->customer_messages);$i++)
		    {
		    ?>
			<option <?php echo $this->customer_messages[$i]['id'] == $this->formdata['ddldis_msg_key1'] ? 'selected' : '';?> value="<?php echo $this->customer_messages[$i]['id'];?>"><?php echo $this->customer_messages[$i]['val'];?></option>
		<?php } ?>		
	    </select>
	</div>
	<label class="_25_1 margin_top_10 label_text_align margin_right_1">
	    <?php echo $this->translate->_('Display Message 2').''.$this->colan;?>
	</label>
	<div class="_25_1 margin_right_1">
	    <select id="ddldis_msg_key2" name="ddldis_msg_key2" class="" >
			<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->customer_messages);$i++)
		    {
		    ?>
			<option <?php echo $this->customer_messages[$i]['id'] == $this->formdata['ddldis_msg_key2'] ? 'selected' : '';?> value="<?php echo $this->customer_messages[$i]['id'];?>"><?php echo $this->customer_messages[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_10 label_text_align margin_right_1">
	    <?php echo $this->translate->_('Print Message 1').''.$this->colan;?>
	</label>
	<div class="_25_1 margin_right_1">
	    <select id="ddlprnt_msg_key1" name="ddlprnt_msg_key1">
			<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->customer_messages);$i++)
		    {
		    ?>
			<option <?php echo $this->customer_messages[$i]['id'] == $this->formdata['ddlprnt_msg_key1'] ? 'selected' : '';?> value="<?php echo $this->customer_messages[$i]['id'];?>"><?php echo $this->customer_messages[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
	<label class="_25_1 margin_top_10 label_text_align margin_right_1">
	    <?php echo $this->translate->_('Print Message 2').''.$this->colan;?>
	</label>
	<div class="_25_1 margin_right_1">
	    <select id="ddlprnt_msg_key2" name="ddlprnt_msg_key2">
			<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->customer_messages);$i++)
		    {
		    ?>
			<option <?php echo $this->customer_messages[$i]['id'] == $this->formdata['ddlprnt_msg_key2'] ? 'selected' : '';?> value="<?php echo $this->customer_messages[$i]['id'];?>"><?php echo $this->customer_messages[$i]['val'];?></option>
		<?php } ?>		
	    </select>
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_10 label_text_align margin_right_1">
	    <?php echo $this->translate->_('Invoice Header Message').''.$this->colan;?>
	</label>
	<div class="_25_1 margin_right_1">
	    <select id="ddlinvo_header_msg_key" name="ddlinvo_header_msg_key">
			<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->customer_messages);$i++)
		    {
		    ?>
			<option <?php echo $this->customer_messages[$i]['id'] == $this->formdata['ddlinvo_header_msg_key'] ? 'selected' : '';?> value="<?php echo $this->customer_messages[$i]['id'];?>"><?php echo $this->customer_messages[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
	<label class="_25_1 margin_top_10 label_text_align margin_right_1">
	    <?php echo $this->translate->_('Invoice Trailor Message').''.$this->colan;?>
	</label>
	<div class="_25_1 margin_right_1">
	    <select id="ddlinvo_trailor_key" name="ddlinvo_trailor_key">
			<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->customer_messages);$i++)
		    {
		    ?>
			<option <?php echo $this->customer_messages[$i]['id'] == $this->formdata['ddlinvo_trailor_key'] ? 'selected' : '';?> value="<?php echo $this->customer_messages[$i]['id'];?>"><?php echo $this->customer_messages[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
    </div>
    <div class="_100">
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Print Sequence').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<select id="ddlprnt_seq" name="ddlprnt_seq">
			<?php
			for($i=0;$i<count($this->print_seq_data);$i++)
			{
			?>
				<option <?php echo $this->formdata['ddlprnt_seq'] == $this->print_seq_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->print_seq_data[$i]['id'];?>"><?php echo $this->print_seq_data[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>    
	<label class="_25_1 margin_top_10 label_text_align margin_right_1">
	    <?php echo $this->translate->_('Enable Stock Capture').''.$this->colan;?>
	</label>
	<div class="_25_1 margin_right_1">
	    <select id="ddlforce_stock_capture" name="ddlforce_stock_capture">
		<?php
		    for($i=0;$i<count($this->stockcapture_data);$i++)
		    {
		    ?>
			<option <?php echo $this->formdata['ddlforce_stock_capture'] == $this->stockcapture_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->stockcapture_data[$i]['id'];?>"><?php echo $this->stockcapture_data[$i]['val'];?></option>
		<?php } ?>		
	    </select>
	</div>
	</div>
	<div class="_100">
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Invoice Price Print').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<select id="ddlinvo_price_prnt" name="ddlinvo_price_prnt">
			<?php
			for($i=0;$i<count($this->priceprint_data);$i++)
			{
			?>
				<option <?php echo $this->formdata['ddlinvo_price_prnt'] == $this->priceprint_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->priceprint_data[$i]['id'];?>"><?php echo $this->priceprint_data[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Edit Price Invs').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<select id="ddlena_edit_price_invs" name="ddlena_edit_price_invs">
			<?php
			for($i=0;$i<count($this->edit_price_data);$i++)
			{
			?>
				<option <?php echo $this->formdata['ddlena_edit_price_invs'] == $this->edit_price_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->edit_price_data[$i]['id'];?>"><?php echo $this->edit_price_data[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>
	</div>
	<div class="_100">
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Sell Previous').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<select id="ddlena_sell_prev" name="ddlena_sell_prev">
			<?php
			for($i=0;$i<count($this->sell_prev_data);$i++)
			{
			?>
				<option <?php echo $this->formdata['ddlena_sell_prev'] == $this->sell_prev_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->sell_prev_data[$i]['id'];?>"><?php echo $this->sell_prev_data[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Suggest Sales').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<select id="ddlena_sugg_sales" name="ddlena_sugg_sales">
			<?php
			for($i=0;$i<count($this->sugg_sale_data);$i++)
			{
			?>
				<option <?php echo $this->formdata['ddlena_sugg_sales'] == $this->sugg_sale_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->sugg_sale_data[$i]['id'];?>"><?php echo $this->sugg_sale_data[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>		
		</div>
		<div class="_100">
			<label class="_25_1 margin_top_10 label_text_align margin_right_1">
				<?php echo $this->translate->_('Enable Auto Fill Damage').''.$this->colan;?>
			</label>
			<div class="_25_1 margin_right_1">
				<select id="ddlena_auto_fill_dmg" name="ddlena_auto_fill_dmg">
				<?php
				for($i=0;$i<count($this->autofill_dmg_data);$i++)
				{
				?>
					<option <?php echo $this->formdata['ddlena_auto_fill_dmg'] == $this->autofill_dmg_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->autofill_dmg_data[$i]['id'];?>"><?php echo $this->autofill_dmg_data[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div>
			<label class="_25_1 margin_top_10 label_text_align margin_right_1">
				<?php echo $this->translate->_('Enable Free').''.$this->colan;?>
			</label>
			<div class="_25_1 margin_right_1">
				<select id="ddlena_promo_trxn" name="ddlena_promo_trxn">
				<?php
				for($i=0;$i<count($this->sales_trxn_data);$i++)
				{
				?>
					<option <?php echo $this->formdata['ddlena_promo_trxn'] == $this->sales_trxn_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->sales_trxn_data[$i]['id'];?>"><?php echo $this->sales_trxn_data[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div>
		</div>
	<div class="_100">
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Auto Fill Returns').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<select id="ddlena_auto_fill_ret" name="ddlena_auto_fill_ret">
			<?php
			for($i=0;$i<count($this->autofill_dmg_data);$i++)
			{
			?>
				<option <?php echo $this->formdata['ddlena_auto_fill_ret'] == $this->autofill_dmg_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->autofill_dmg_data[$i]['id'];?>"><?php echo $this->autofill_dmg_data[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>    
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Sales').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1"> 
			<select id="ddlena_sales_trxn" name="ddlena_sales_trxn">
			<option <?php echo $this->formdata['ddlena_sales_trxn'] == '0' ? 'selected' : '';?> value="0"><?php echo $this->translate->_('Disable');?></option>
			<option <?php echo $this->formdata['ddlena_sales_trxn'] == '1' ? 'selected' : '';?> value="1"><?php echo $this->translate->_('Enable');?></option>
			</select>
		</div>
		
		
	</div>
    <div class="_100">
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Signature Capture').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<select id="ddlena_auto_fill_cap" name="ddlena_auto_fill_cap">
			<?php
			for($i=0;$i<count($this->sign_capt_data);$i++)
			{
			?>
				<option <?php echo $this->formdata['ddlena_auto_fill_cap'] == $this->sign_capt_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->sign_capt_data[$i]['id'];?>"><?php echo $this->sign_capt_data[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>    
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Damage Returns').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<select id="ddlena_damage_ret" name="ddlena_damage_ret">
			<?php
			for($i=0;$i<count($this->sales_trxn_data);$i++)
			{
			?>
				<option <?php echo $this->formdata['ddlena_damage_ret'] == $this->sales_trxn_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->sales_trxn_data[$i]['id'];?>"><?php echo $this->sales_trxn_data[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>
	</div>
    <div class="_100">	
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Good Returns').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<select id="ddlenable_ret_trxn" name="ddlenable_ret_trxn">
			<?php
			for($i=0;$i<count($this->sales_trxn_data);$i++)
			{
			?>
				<option <?php echo $this->formdata['ddlenable_ret_trxn'] == $this->sales_trxn_data[$i]['id'] ? 'selected' : '';?> value="<?php echo $this->sales_trxn_data[$i]['id'];?>"><?php echo $this->sales_trxn_data[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>    
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable AR Collection').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<select id="ddlena_ar_coll" name="ddlena_ar_coll">
			<option <?php echo $this->formdata['ddlena_ar_coll'] == '0' ? 'selected' : '';?> value="0"><?php echo $this->translate->_('Disable');?></option>
			<option <?php echo $this->formdata['ddlena_ar_coll'] == '1' ? 'selected' : '';?> value="1"><?php echo $this->translate->_('Enable');?></option>
			</select>
		</div>
	</div>   
	<?php if($this->status[4]['status'] == 1) { ?>
	<div class="_100">
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Exception Start Date').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<input type="text" id="txtstartdate" name="txtstartdate" readonly="readonly" maxlength="20" class="margin_top_7" value="<?php echo (isset($this->formdata['txtstartdate'])) ? date('d-m-Y',strtotime($this->formdata['txtstartdate'])) : '';?>">
		</div>
		<label class="_25_1 margin_top_10 label_text_align margin_right_1">
			<?php echo $this->translate->_('Exception End Date').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<input type="text" id="txtenddate" name="txtenddate" readonly="readonly" maxlength="20" class="margin_top_7" value="<?php echo (isset($this->formdata['txtenddate'])) ? date('d-m-Y',strtotime($this->formdata['txtenddate'])) : ''; ?>">
		</div>
    </div>
	<?php } ?>
    <div class="_100">
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Survey').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">	    
			<input type="checkbox" value="1" <?php echo $this->formdata['ddlena_survey_audit'] == '1' ? 'checked' : '';?> id="ddlena_survey_audit" name="ddlena_survey_audit"  >
		</div>
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Invoice Comment').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<input type="checkbox" value="1" <?php echo $this->formdata['ddlena_invo_comment'] == '1' ? 'checked' : '';?> id="ddlena_invo_comment" name="ddlena_invo_comment"  >
		</div>
	</div>
    <div class="_100">
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
			<?php echo $this->translate->_('Auto Settle Collection').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<input type="checkbox" id="ddlauto_set_coll" name="ddlauto_set_coll" <?php echo $this->formdata['ddlauto_set_coll'] == '1' ? 'checked' : '';?> value="1">
		</div>	
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Item Bar Code Print').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<input type="checkbox" id="ddlena_itm_barcode" name="ddlena_itm_barcode" <?php echo $this->formdata['ddlena_itm_barcode'] == '1' ? 'checked' : '';?> value="1">
		</div>
	</div>
	<div class="_100">
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Delay Print').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<input type="checkbox" id="ddlena_delay_prnt" name="ddlena_delay_prnt" <?php echo $this->formdata['ddlena_delay_prnt'] == '1' ? 'checked' : '';?> value="1">
		</div>    
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Invoice Copy').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<input type="checkbox" id="ddlena_invo_copy" name="ddlena_invo_copy" <?php echo $this->formdata['ddlena_invo_copy'] == '1' ? 'checked' : '';?> value="1">
		</div>
	</div>    
    <div class="_100">
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable Rental').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<input type="checkbox" name="chkenablerental" id="chkenablerental" value="1" <?php echo $this->formdata['chkenablerental'] == '1' ? 'checked' : '';?>>
		</div>    
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
			<?php echo $this->translate->_('Enable POS').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
			<input type="checkbox" name="chkenablepos" id="chkenablepos" <?php echo $this->formdata['chkenablepos'] == '1' ? 'checked' : '';?> value="1">
		</div>
	</div>
	<div class="_100">
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
		    <?php echo $this->translate->_('Enable Advance Payment').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <input type="checkbox" name="chkenableadvpay" id="chkenableadvpay" <?php echo $this->formdata['chkenableadvpay'] == '1' ? 'checked' : '';?> value="1">
		</div>    
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
		    <?php echo $this->translate->_('Enable Auto Fill Sales').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <input type="checkbox" name="chkenableautofillsales" id="chkenableautofillsales" value="1" <?php echo $this->formdata['chkenableautofillsales'] == '1' ? 'checked' : '';?> >
		</div>
	</div>
	<div class="_100">
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
		    <?php echo $this->translate->_('Enable Batch Selection').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <input type="checkbox" name="chkenableadvbatchsel" id="chkenableadvbatchsel" value="1" <?php echo $this->formdata['chkenableadvbatchsel'] == '1' ? 'checked' : '';?> >
		</div>    
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
		    <?php echo $this->translate->_('Enable Buy Back Free').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <input type="checkbox" name="chkenablebuybackfree" id="chkenablebuybackfree" value="1" <?php echo $this->formdata['chkenablebuybackfree'] == '1' ? 'checked' : '';?>>
		</div>
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
		    <?php echo $this->translate->_('Enable Swapping').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <input type="checkbox" name="chkenableexchangetrxn" id="chkenableexchangetrxn" value="1" <?php echo $this->formdata['chkenableexchangetrxn'] == '1' ? 'checked' : '';?>>
		</div>
		<label class="_25_1 margin_top_7 label_text_align margin_right_1">
		    <?php echo $this->translate->_('Use Password for Returns').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <input type="checkbox" name="chkenablepassrtntranxn" id="chkenablepassrtntranxn" value="1" <?php echo $this->formdata['chkenablepassrtntranxn'] == '1' ? 'checked' : '';?>>
		</div>
    </div>
</div>