<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
<div class="grid_12">
    <div class="box" id="promotion_index_addpricingkeyplan">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png" class="margin_top_7">
		<h3><?php echo $this->translate->_('Plan Defination');?></h3>
	    </div>
	    <div class="_50_3">
		<div class="_15 save_btn">
		    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"promotions","controller"=>"advancepricing","action"=>"pricingkeyplan"), "default", true);?>')" >
		</div>
		<div class="_20 save_btn"><input class="border_none" type="submit" value="" name="btnadd" id="btnadd"></div>
	    </div>
        </div>	
	<div class="clear"></div>
	<div class="clear"></div>
	<div class="_100">
	    <div class="_40 label_text_align"><input type="textbox" id="txtsearchpopup" name="txtsearchpopup" value=""></div>
	    <div class="_15_button margin_top_3 label_text_align back_btn">
		<input type="button" id="btnsearchpopup" name="btnsearchpopup"  value="<?php echo $this->translate->_('SEARCH');?>">
	    </div>
	</div>
	<div class="_100">	    
	    <?php echo $this->partial('datagrid.phtml', $this); ?>
	</div>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>
<script type="text/javascript">
$(window).load(function() {
    $("#btncancel").click(function() {
	parent.eval('$.prettyPhoto.close()');
    });
});
</script>