<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CustomerMaster extends Model
{
    protected $table = 'customermaster';

    protected $primaryKey = 'customercode';

    public $timestamps = false;

    protected $fillable = [
        'routecode',
        'headofficecode',
        'templateindicator',
        'templatename',
        'customername',
        'arbcustomername',
        'alternatecode',
        'barcode',
        'customerphone',
        'delivery_slot_from',
        'delivery_slot_to',
        'autojp_priority',
        'allow_cross_route_jp',
        'customeraddress1',
        'customeraddress2',
        'customeraddress3',
        'customercity',
        'customerzip',
        'pobox',
        'customertype',
        'channelcode',
        'customercategory',
        'pricingkey',
        'promotionkey',
        'currencycode',
        'invoicepaymentterms',
        'creditlimit',
        'creditlimitdays',
        'balance',
        'activecustomer',
        'arcustomertype',
        'tclimit',
        'messagekey1',
        'messagekey2',
        'messagekey3',
        'messagekey4',
        'messagekey5',
        'messagekey6',
        'invoiceformatoption',
        'printsequence',
        'forcestockcapture',
        'invoicepriceprint',
        'enablepriceeditinvs',
        'enablesellprevious',
        'enablesuggestsales',
        'enableautofilldamaged',
        'enablepromotrxn',
        'enableautofillreturns',
        'enablesalestrxn',
        'enablesigcapture',
        'enabledamagedreturns',
        'enablereturnstrxn',
        'enableexchangetrxn',
        'enablearcollection',
        'enablesurveyaudit',
        'enabledelivinstruct',
        'enableinvoicecomment',
        'invoicedetailentry',
        'orderdetailentry',
        'authorizeditemlistctl',
        'orderformat',
        'autosettlecollection',
        'enableupcprint',
        'enabledelayprint',
        'enableinvoicecopy',
        'enablerental',
        'enableposequipment',
        'enableadvancepayment',
        'enablebuybackfree',
        'enableautofillsales',
        'enablebatchselection',
        'enablereturnpassword',
        'invoiceformat',
        'printlanguageflag',
        'fixedlatitude',
        'fixedlongitude',
        'visualcode',
        'enablepromoeditinvs',
        'roundnetamount',
        'roundingoffvalue',
        'enablepromoeditords',
        'histmaxdeliveries',
        'forwardcoverfactor',
        'enforcepromotion',
        'invoicelimiter',
        'enabledraftcopy',
        'graceperiod',
        'printoutletitemcode',
        'allowcashoncreditexceed',
        'memo1',
        'memo2',
        'traname',
        'tranamearabic',
        'taxregistrationnumber',
        'customertaxidoptions',
        'applytax',
        'shoptelephonenumber',
        'shopfaxnumber',
        'ownername',
        'ownerlandlinenumber',
        'ownermobilenumber',
        'contactname',
        'contactpersonlandlinenumber',
        'contactpersonmobilenumber',
        'contactpersonemail',
        'purchasemanagername',
        'purchasemanagerlandlinenumber',
        'purchasemanagermobilenumber',
        'purchasemanageremail',
        'warehousemanagername',
        'warehousemanagerlandlinenumber',
        'warehousemanagermobilenumber',
        'warehousemanageremail',
        'created',
        'cdat',
        'modified',
        'mdat',
    ];
}
