<?php
/**
* @name       routestartenddays.phtml
* @since      16 feb, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10" id="for_report_only">
<div class="box" id="report_basic_commstatus">
<form id="thisform" name="thisform" onsubmit="return addhidden();"  class="validate" target="_blank" action="<?php echo $this->url(array("module"=>"reports","controller"=>"tabletsalessummary","action"=>"index"), "default", true);?>" method="post" >
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_reports.png">
        <h3><?php echo $this->translate->_('Sales Summary');?></h3>
    </div>
 </div>
<div class="content with-actions min_height_10">
    <!--TOP RADIOS-->
   <div class="_100">
	    <label class="_40_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Route').''.$this->colan;?>
	    </label>
	    <div class="_30 margin_right_1">
		<select id="ddlroute" name="ddlroute" >
		    <option value="">--- Select ---</option>
		    <?php
			for($i=0;$i<count($this->route_list);$i++)
			{
		    ?>
			    <option  value="<?php echo $this->route_list[$i]['id'];?>"><?php echo $this->route_list[$i]['val'];?></option>
		    <?php } ?>
		</select>
	    </div>
    </div>
   <div class="_100">
	    <label class="_40_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Start Date').''.$this->colan;?>
	    </label>
	    <div class="_30 margin_right_1">
            <input name="txt_route_start_date" id="txt_route_start_date" maxlength="50" type="text"  value="<?php echo date('d-m-Y');?>" class="margin_top_5" >
	    </div>
    </div>
<div class="_100">
	    <label class="_40_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('End Date').''.$this->colan;?>
	    </label>
	    <div class="_30 margin_right_1">
            <input name="txt_route_end_date" id="txt_route_end_date" maxlength="50" type="text"  value="<?php echo date('d-m-Y');?>" class="margin_top_5" >
	    </div>
    </div>
   
    <div class="clear space_20"></div>
    <div class="_100" id="ok_button">
	<div class="_45">&nbsp</div>
	<div class="_10_1">
	    <input type="submit" id="sub_ok" name="sub_ok" value="<?php echo $this->translate->_('OK');?>" />
	</div>
	
    </div>
         <div class="clear space_20"></div>
</div>
</form>
</div> <!-- End of .box -->
</div>

<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txt_route_end_date" ).datepicker({	    
		dateFormat: 'dd-mm-yy',
            changeYear:true,
            yearRange: '-10:+15'
	});
	$( "#txt_route_start_date" ).datepicker({	    
		dateFormat: 'dd-mm-yy',
            changeYear:true,
            yearRange: '-10:+15'
	});
    });

});

</script>