<?php
/**
* @name       index.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');

?>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/invoice/clear_data.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/invoice/function.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/invoice/invoice_add.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/invoice/invoice_item.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/invoice/promotion.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/invoice/payment.js"></script>

<script type="text/javascript">
//message alret
var please_wait_msg ="<h1 class='blockui_css'><?php echo $this->translate->_('Please Wait ...');?></h1>";
var load_price_value ="<h1 class='blockui_css'><?php echo $this->translate->_('Loading Price ...');?></h1>";

//url

var SaveURL = base_url+"/hhctransaction/transactionsave/saveinvoice/";
var Overview_URL = base_url+"/hhctransaction/cloudtran/invoice/";
//var customer_list_URL = base_url+"/hhctransaction/ajaxdata/customerlist/";
//var item_price_URL = base_url+"/hhctransaction/ajaxdata/itempriceinfo/";
var ajax_page_URL = base_url+"/hhctransaction/ajaxdata/";
var save_page_URL = base_url+"/hhctransaction/transactionsave/";

var Invoice_item_grid =base_url+"/hhctransaction/transaction/invoicedetail";
var Invoice_promotion_grid =base_url+"/hhctransaction/transaction/promotionplan";


$(document).ready(function() {
    
	$(".tab_content").hide();
	$("#tab1").show();
	//$("ul.tabs li").click(function() {
	//    var disable = $(this).find("a").attr("disable");
	//    if(disable != 0)
	//    {
	//	$("ul.tabs li a").removeClass("admin_active"); //Remove any "active" class
	//	$(this).find("a").addClass("admin_active");
	//	$(".tab_content").hide(); //Hide all tab content
	//	var activeTab = $(this).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
	//	$(activeTab).fadeIn(); //Fade in the active content
	//	return false;
	//	
	//    }
	//    
	//});
	//$.blockUI({ message: please_wait_msg });
	$(document).ajaxStop($.unblockUI);
});
</script>
<div class="clean"></div>
<div class="grid_12" id="hhctransaction_transaction_invoiceadd">
<div class="box" id="account_customer_addcustomer">

<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
	<h3><?php echo $this->translate->_('Invoice');?></h3>
    </div>
   
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul>
	    	<li>
		    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"cloudtran","action"=>"invoice"),"default", true);?>"><?php echo $this->translate->_('Overview');?></a>
		</li>
	    </ul>
	    <ul style="display: block; margin-left:75px;" class="tabs">
		<li> 
		    <a href="#tab1" id="t1" class="admin_active tablink"><?php echo $this->translate->_('Detail 1');?></a> |
		</li>
		<li>
		    <a href="#tab2" id="t2" class="tablink"  disable='0'><?php echo $this->translate->_('Detail 2');?></a> |
		</li>
		<li>
		    <a href="#tab3" id="t3" class="tablink"  disable='0'><?php echo $this->translate->_('Detail 3');?></a> |
		</li>
		<li >
		    <a href="#tab4" id="t4" class="tablink"  disable='0'><?php echo $this->translate->_('Detail 4');?></a> |
		</li>
                <li >
		    <a href="#tab5" id="t5" class="tablink"  disable='0'><?php echo $this->translate->_('Detail 5');?></a> |
		</li>
                <li class="last-child">
		    <a href="#tab6" id="t6" class="tablink"  disable='0'><?php echo $this->translate->_('Detail 6');?></a>
		</li>
		
	    </ul>
	</li>
    </ul>
</div>
</div>

    <div class="content with-actions  min_height_10">
		<div id="tab1" class="tab_content">
			<?php include('addinvoice.phtml');?>
		</div>
		<div id="tab2" class="tab_content">
			<?php include('invoiceitem.phtml');?>
		</div>
		<div id="tab3" class="tab_content">
			<?php include('promotion.phtml');?>
		</div>
		<div id="tab4" class="tab_content">
			<?php include('promotionreview.phtml');?>
		</div>
        <div id="tab5" class="tab_content">
			<?php include('signature.phtml');?>
		</div>
        <div id="tab6" class="tab_content">
			<?php include('cashcollection.phtml');?>
		</div>
    </div>
    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">

</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txt_date" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
     $('.sigPad').signaturePad({drawOnly:true});
   
});
function clear_sig()
{
	$('.sigPad').signaturePad({drawOnly:true}).clearCanvas();
	return false;
}
</script>



       