<style type="text/css">
#invoiceite input { padding:5px !important;}
</style>
<div id="hhctransaction_transaction_invoiceadd_detail2" >
<form id="frminvoiceitem" name="frminvoiceitem" class="validate" novalidate action="" method="post">
<div class="content with-actions" id="hhctransaction_invoiceadd_invoiceitem">
    <input type="hidden" name="hdndata" value="add_invoice_item" />
    <input type="hidden" name="hid_available_qty" id="hid_available_qty" value="" />
    <input type="hidden" name="hid_check_allowbatchentry" id="hid_check_allowbatchentry" value="" />
    
    <input type="hidden" name="hid_return_qty_val" id="hid_return_qty_val" value="0" />
    <input type="hidden" name="hid_buyback_qty_val" id="hid_buyback_qty_val" value="0" />
    <input type="hidden" name="hid_damage_qty_val" id="hid_damage_qty_val" value="0" />
    <input type="hidden" name="hid_expirey_qty_val" id="hid_expirey_qty_val" value="0" />

    <div id="settings_value" >
    </div>
      <div class="_100 margin_bottom_10">
		<label class="_15_2 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Customer Name').$this->colan;?>
		</label>
		<label class="_40 margin_top_12 margin_left_2">
		    <div id="detail_2_customer"></div>
		</label>		
      </div>
 <fieldset id="invoiceite">
	    <legend ><?php echo $this->translate->_('Add Item');?></legend>
	    <div class="_100">
		<label class="_15_2 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Item').$this->required;?>
		</label>
		<div class="_40 margin_left_1 margin_right_2_2">
		    <select id="ddlitem" name="ddlitem" class="required">
		    <option value="">--- Select ---</option>		    
		</select>
		</div>
		<label class="_20 margin_top_12 label_text_align" id="upc_label">
		    <?php echo $this->translate->_('UPC').''.$this->required;?>
		</label>
		<div class="_25 margin_top_3" >
		    <input type="text" id="txt_upc" name="txt_upc" value=""  class="invoice_qty_width_150  amount_text_align"  readonly="readonly">
		</div>
	   </div>
	      <div class="_100 ">
		<label class="_15_2 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Sales Qty').''.$this->colan;?>
		</label>
		<div class="_40 margin_left_1 margin_right_1">
            <input type="text" id="txt_sales_case" name="txt_sales_case" value=""  onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'sales');this.value = this.value.replace(/[^0-9\.]/g,'');" class="invoice_qty_width_67 invoice_margin_right_5 amount_text_align">
            <input type="text" id="txt_sales_pieces" name="txt_sales_pieces" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'sales');this.value = this.value.replace(/[^0-9\.]/g,'');" value=""  class="invoice_qty_width_67 invoice_margin_right_5 amount_text_align">
            <input type="text" id="txt_sale_price" name="txt_sale_price" value=""  onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="this.value = this.value.replace(/[^0-9\.]/g,'');" class="invoice_qty_width_67 invoice_margin_right_5 amount_text_align" readonly="readonly">
            <input type="text" id="txt_sales_pcs_price" name="txt_sales_pcs_price" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67 invoice_margin_right_5 amount_text_align" readonly="readonly">
            
            <input type="hidden" id="txt_costcaseprice" name="txt_costcaseprice" value="" readonly="readonly">
            <input type="hidden" id="txt_defaultcostprice" name="txt_defaultcostprice" value="" readonly="readonly">
		    <div class="_10 margin_top_10"><a href="javascript:;" id="avail_qty_update" onclick="addbatch('sales');" class="float_right">Batch</a></div>
		</div>
		<label class="_20 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Available Qty').''.$this->required;?>
		</label>
		<div class="_25 margin_right_1" >
		    <input type="text" id="txt_available_qty" name="txt_available_qty" value=""  readonly="readonly" class="invoice_qty_width_150  amount_text_align" >
		</div>
	    </div>
	      <div class="_100 ">
		<label class="_15_2 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Free Qty').''.$this->colan;?>
		</label>
		<div class="_40 margin_left_1 margin_right_1">
		   <input type="text" id="txt_freegood_case" name="txt_freegood_case" value=""  onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'freegood');this.value = this.value.replace(/[^0-9\.]/g,'');" class="invoice_qty_width_67 invoice_margin_right_5  amount_text_align">
		   <input type="text" id="txt_freegood_pieces" name="txt_freegood_pieces" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'freegood');this.value = this.value.replace(/[^0-9\.]/g,'');" class="invoice_qty_width_67 invoice_margin_right_5  amount_text_align">
            <div class="_10 margin_top_10"><a href="javascript:;" id="avail_qty_update" onclick="addbatch('freegood');" class="float_right"  >Batch</a></div>
		</div>
		<label class="_20 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Free Reason').''.$this->colan;?>
		</label>
		 
		<div class="_25 margin_right_1" >
		   <select id="ddfreegoodreason" name="ddfreegoodreason" class=""   >
		    <option value="">--- Select ---</option>
		    <?php
		    if(!empty($this->freegood_reason)){
		     foreach($this->freegood_reason as $val)
		     {
		      
		      ?>
		     <option value="<?php echo $val['code'];?>" ><?php echo $val['description'];?></option> 
		     <?php
		     }
		    }
		    ?>
		</select>
		</div>
	    </div>
	      <div class="_100 ">
		<label class="_15_2 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Return Qty').''.$this->colan;?>
		</label>
		<div class="_40 margin_left_1 margin_right_1">
		   <input type="text" id="txt_return_case" name="txt_return_cases" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'return');this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67 invoice_margin_right_5  amount_text_align">
		   <input type="text" id="txt_return_pieces" name="txt_return_pieces" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'return');this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67 invoice_margin_right_5  amount_text_align">
		   
		     <input type="text" id="txt_freegood_price" name="txt_freegood_price" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="this.value = this.value.replace(/[^0-9\.]/g,'');" class="invoice_qty_width_67 invoice_margin_right_5 amount_text_align" readonly="readonly">
		   <input type="text" id="txt_freegood_pcs_price" name="txt_freegood_pcs_price" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="this.value = this.value.replace(/[^0-9\.]/g,'');" value=""  class="invoice_qty_width_67 invoice_margin_right_5 amount_text_align" readonly="readonly"> 
		 <div class="_10 margin_top_10"><a href="javascript:;" id="avail_qty_update" onclick="addbatch('return');"  class="float_right"  >Batch</a></div>
		   
			
		</div>
		<label class="_20 margin_top_10 label_text_align">
		     <?php echo $this->translate->_('Return Reason').''.$this->colan;?>
		</label>
		<div class="_25 margin_right_1" >
		   <select id="ddreturnreason" name="ddreturnreason" class=""   >
		    <option value="">--- Select ---</option>
		    <?php
		    if(!empty($this->return_reason)){
		     foreach($this->return_reason as $val)
		     {?>
		     <option value="<?php echo $val['code'];?>" ><?php echo $val['description'];?></option> 
		     <?php
		     }
		    }
		    ?>
		</select>
		</div>
	    </div>
	    <div class="_100 ">
		<label class="_15_2 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('BuyBack Qty').''.$this->colan;?>
		</label>
		<div class="_40 margin_left_1 margin_right_1">
		   <input type="text" id="txt_buyback_case" name="txt_buyback_cases" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'buyback');this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67 invoice_margin_right_5  amount_text_align">
		   <input type="text" id="txt_buyback_pieces" name="txt_buyback_pieces" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'buyback');this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67 invoice_margin_right_5 amount_text_align">
		    <div class="_10 margin_top_10"><a href="javascript:;" id="avail_qty_update" onclick="addbatch('buyback');"  class="float_right" >Batch</a></div>
	          
		</div>
		<label class="_20 margin_top_10 label_text_align">
		     <?php echo $this->translate->_('BuyBack Reason').''.$this->colan;?>
		</label>
		<div class="_25 margin_right_1" >
		   <select id="ddbuybackreason" name="ddbuybackreason" class=""   >
		    <option value="">--- Select ---</option>
		    <?php
		    if(!empty($this->return_reason)){
		     foreach($this->return_reason as $val)
		     {?>
		     <option value="<?php echo $val['code'];?>" ><?php echo $val['description'];?></option> 
		     <?php
		     }
		    }
		    ?>
		</select>
		</div>
	    </div>
	       <div class="_100 ">
		<label class="_15_2 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Damage Qty').''.$this->colan;?>
		</label>
		<div class="_40 margin_left_1 margin_right_1">
		   <input type="text" id="txt_damage_case" name="txt_damage_cases" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'damage');this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67 invoice_margin_right_5  amount_text_align">
		   <input type="text" id="txt_damage_pieces" name="txt_damage_pieces" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'damage');this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67  invoice_margin_right_5 amount_text_align">
		     <input type="text" id="txt_return_price" name="txt_return_price" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="this.value = this.value.replace(/[^0-9\.]/g,'');" class="invoice_qty_width_67 invoice_margin_right_5 amount_text_align" readonly="readonly">
		   <input type="text" id="txt_return_pcs_price" name="txt_return_pcs_price" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="this.value = this.value.replace(/[^0-9\.]/g,'');" value=""  class="invoice_qty_width_67  invoice_margin_right_5  amount_text_align" readonly="readonly"> 
        <div class="_10 margin_top_10"><a href="javascript:;" id="avail_qty_update" onclick="addbatch('damage');" class="float_right"  >Batch</a></div>
		</div>
		<label class="_20 margin_top_10 label_text_align">
		     <?php echo $this->translate->_('Damage Reason').''.$this->colan;?>
		</label>
		<div class="_25 margin_right_1" >
		   <select id="dddamagereason" name="dddamagereason" class=""   >
		    <option value="">--- Select ---</option>
		     <?php
		    if(!empty($this->damage_reason)){
		     foreach($this->damage_reason as $val)
		     {?>
		     <option value="<?php echo $val['code'];?>" ><?php echo $val['description'];?></option> 
		     <?php
		     }
		    }
		    ?>
		</select>
		</div>
	    </div>
	       <div class="_100 ">
				<label class="_15_2 margin_top_12 label_text_align">
					<?php echo $this->translate->_('Expiry Qty').''.$this->colan;?>
				</label>
				<div class="_40 margin_left_1 margin_right_1">
				   <input type="text" id="txt_expirey_case" name="txt_expirey_case" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'expirey');this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67 invoice_margin_right_5  amount_text_align">
				   <input type="text" id="txt_expirey_pieces" name="txt_expirey_pieces" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'expirey');this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67 invoice_margin_right_5  amount_text_align">
                    <div class="_10 margin_top_10"><a href="javascript:;" id="avail_qty_update" onclick="addbatch('expirey');"  class="float_right"  >Batch</a></div>
				</div>
				<label class="_20 margin_top_10 label_text_align">
					 <?php echo $this->translate->_('Expiry Reason').''.$this->colan;?>
				</label>
				<div class="_25 margin_right_1" >
				   <select id="ddexpiryreason" name="ddexpiryreason" class=""   >
					<option value="">--- Select ---</option>
					 <?php
					if(!empty($this->expiry_reason)){
					 foreach($this->expiry_reason as $val)
					 {?>
					 <option value="<?php echo $val['code'];?>" ><?php echo $val['description'];?></option> 
					 <?php
					 }
					}
					?>
				</select>
				</div>
	    </div>
		   <div class="_100 margin_bottom_5">
				<label class="_15_2 margin_top_12 label_text_align">
					<?php echo $this->translate->_('Rental Qty').''.$this->colan;?>
				</label>
				<div class="_40 margin_left_1 margin_right_1">
				   <input type="text" id="txt_rental_case" name="txt_rental_case" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'rental');this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67 invoice_margin_right_5  amount_text_align">
				   <input type="text" id="txt_rental_pieces" name="txt_rental_pieces" value="" onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"  onblur="addbatchdetail(this,'rental');this.value = this.value.replace(/[^0-9\.]/g,'');"  class="invoice_qty_width_67 invoice_margin_right_5 amount_text_align">
                    <div class="_10 margin_top_10"><a href="javascript:;" id="avail_qty_update" onclick="addbatch('rental');"  class="float_right"  >Batch</a></div>
				</div>
				<label class="_20 margin_top_10 label_text_align">
					 &nbsp;
				</label>
				<div class="_25 margin_right_1" >
				  <input type="button" name="btn_save_invoice_item" id="btn_save_invoice_item" value="Add" />
				</div>
	    </div>
 </fieldset>
 <div class="_100 hhctransaction_invoiceadd_itemgrid_data" id="divid" style="display:none">
	<div class="clear"></div>
	<div id="loader"></div>
	<div id="item-grid"></div>
</div> 
 <div class="_100 margin_top_5">
	<input type="button" name="btn_next_invoice_item" class="float_right invoice_margin_right_5" id="btn_next_invoice_item" value="Next" />
	<input type="button" name="btn_previous_invoice_item" class="float_right invoice_margin_right_5" id="btn_previous_invoice_item" value="Previous" />	  
 </div>
 <div class="_100 space_20">&nbsp;</div>
</div>
</form>
</div>
<script>
$(function()
{
  //var case1  = $("#txt_sales_case").val();
  //var pces1 = $("#txt_sales_pieces").val();
  //var upc = $("#txt_upc").val();
  //
  //var s_qty = (case1 *  upc) +
  
 
    $("#avail_qty").click(function() {
    
        var s_qty = parseInt(eval(parseInt($("#txt_sales_case").val() * $("#txt_upc").val())) + eval(parseInt($("#txt_sales_pieces").val())));
        var avil_qty_URL = base_url+"/hhctransaction/ajaxdata/availableqty/salesqty/"+s_qty;
     
        var tag_url1 =avil_qty_URL+"/itemcode/"+$("#ddlitem").val()+"?iframe=true&width=600&height=500";
        $.prettyPhoto.open(tag_url1);
    });
  
    $("#avail_qty_update").click(function(){
    
    
    });
    $("#hhctransaction_transaction_invoiceadd_detail2").keypress( function(e) {
        if( e.keyCode == 13 ) return false;
    }); 
});
function addbatch(type)
{
    var caseval = 0;
    var pieceval = 0;
    if($('#txt_'+type+'_case').val() != "")
    {
        caseval = parseInt($("#txt_"+type+"_case").val() * $("#txt_upc").val());
    }
    if($('#txt_'+type+'_pieces').val() != "")
    {
        pieceval =  parseInt($("#txt_"+type+"_pieces").val());
    }
    var r_qty = parseInt(caseval + pieceval);
   // var r_qty = (parseInt($("#txt_"+type+"_case").val() * $("#txt_upc").val()) + parseInt($("#txt_"+type+"_pieces").val()));
    var avil_qty_URL = base_url+"/hhctransaction/ajaxdata/returnavailableqty/salesqty/"+r_qty+"/type/"+type;
    var tag_url1 =avil_qty_URL+"/itemcode/"+$("#ddlitem").val()+"?iframe=true&width=600&height=500";
    $.prettyPhoto.open(tag_url1);
}
function fillvalue(type,qnt)
{
    var upc = parseInt($("#txt_upc").val());
    var cases = parseInt(qnt/upc);
    if(isNaN(cases)) { cases = 0; }
    var pcs = parseInt(qnt%upc);
    if(isNaN(pcs)) { pcs = 0; }
    $('#txt_'+type+'_case').val(cases);
    $('#txt_'+type+'_pieces').val(pcs);
    if(type == "return" || type == "buyback" || type == "damage" || type == "expirey")
    {
        $('#hid_'+type+'_qty_val').val(qnt);
    }
}
</script>