<form id="frmpromotionreview" name="frmpromotionreview" class="validate" novalidate action="" method="post">
<div class="content with-actions">

<div id="review_promotion">
   
</div>

   <div class="clear"></div>
         <div class="_100">
	  
           <div class="float_right"><input type="button" name="btn_next_promotion_overview"  id="btn_next_promotion_overview" value="Next" /></div>
	   <div class="float_right">&nbsp;&nbsp;</div>
	   
	   <div class="float_right"><input type="button" name="btn_prev_promotion_overview" id="btn_prev_promotion_overview" value="Previous" /></div>
	</div>
        <div class="clear space_100"></div>
</form>
</div>

