<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<div class="content with-actions">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>

	<div class="_100">
	    <label class="_20 label_text_align margin_top_12">
		<?php echo $this->translate->_('Customer#').''.$this->colan;?>
	    </label>
	    <div class="_20 margin_right_1">
		<input type="text" id="txt_customer_no" name="txt_customer_no" value="" readonly="readonly">
	    </div>
	    <label class="_20_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Customer Name').''.$this->colan;?>
	    </label>
	    <div class="_35_1 margin_right_1">
		<input type="text" id="txt_customer_name" name="txt_customer_name" value="" readonly="readonly">
            </div>

	</div>
	<div class="_100">
	    <label class="_20 label_text_align margin_top_12">
            <?php echo $this->translate->_('Invoice Amount').''.$this->colan;?>
	    </label>
	    <div class="_20 margin_right_1">
            <input type="text" id="txt_final_amount_sig" name="txt_final_amount_sig" value="" readonly="readonly" class="number amount_text_align invoice_qty_width_150">
	    </div>
	    <label class="_20_1 label_text_align margin_top_12">
			<?php echo $this->translate->_('Amount Due').''.$this->colan;?>
	    </label>
	    <div class="_35_1 margin_right_1">
    		<input type="text" id="txt_amount_due_sig" name="txt_amount_due_sig" readonly="readonly" value="" class="number amount_text_align invoice_qty_width_150">
	    </div>
	</div>
	<div class="_100">
	    <label class="_20 label_text_align margin_top_12">
            <?php echo $this->translate->_('Discount').''.$this->colan;?>
	    </label>
	    <div class="_20 margin_right_1">
            <input type="text" id="txt_discount_amount" name="txt_discount_amount" readonly="readonly" value="" class="number amount_text_align invoice_qty_width_150">
	    </div>
        <label class="_20_1 label_text_align margin_top_12">
    		<?php echo $this->translate->_('Minimum Due').''.$this->colan;?>
	    </label>
	    <div class="_35_1 margin_right_1">
    		<input type="text" id="txt_min_amount_due_sig" name="txt_min_amount_due_sig" readonly="readonly" value="" class="number amount_text_align invoice_qty_width_150">
	    </div>
	</div>
    <div class="_100 margin_bottom_10">
        <label class="_20 label_text_align margin_top_12">
            <?php echo $this->translate->_('Final Amount').''.$this->colan;?>
	    </label>
	    <div class="_20 margin_right_1">
            <input type="text" id="txt_final_amount" name="txt_final_amount" readonly="readonly" value="" class="number amount_text_align invoice_qty_width_150">
	    </div>
        <label class="_20_1 label_text_align margin_top_12">
    		<?php echo $this->translate->_('Allowed TC').''.$this->colan;?>
	    </label>
	    <div class="_35_1 margin_right_1">
    		<input type="text" id="txt_tc_amount_sig" name="txt_tc_amount_sig" value="" readonly="readonly" class="number amount_text_align invoice_qty_width_150">
	    </div>
	</div>
	<div class="_100 margin_top_10">
		<div  id="invoice_summery_data" class="gridclass"  style="width:100%;overflow:hidden"></div>
	</div>
	<div class="clear"></div>
	<div class="_100 margin_top_15">
		<div style="float:right"><input type="button" name="btn_next_signature" id="btn_next_signature" value="Next" /></div>
		<div style="float:right">&nbsp;&nbsp;</div>
		<div style="float:right"><input type="button" name="btn_prev_signature" id="btn_prev_signature" value="Previous" /></div>
	</div>
	<div class="clear space_100"></div>
</div>
</form>