<?php
/**
* @name       addpromotionplan.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$promo_plan_url = $this->url(array("module"=>"promotions","controller"=>"advance","action"=>"promotionrange"), "default", true);
$grp_detail = $this->url(array("module"=>"promotions","controller"=>"advance","action"=>"groupdetail"), "default", true);
?>

<style>

.box .content {border:none !important;} td{padding:5px;}
._10_1 {width:8% !important;}
</style>
<script type="text/javascript">

var hdnid 	= <?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>;

$(document).ready(function(){
	
	$('#ddl_promotiontypecode_chzn .chzn-drop .chzn-search input[type="text"]').focus();
	$('#ddl_promotiontypecode_chzn').addClass('chzn-container-active');
	
	var tmp 	= '<?php echo $this->formdata['promotiontypecode']; ?>';	
	
	<?php if($this->formdata['rangebasis'] == 3 && $this->params['id'] > 0) { ?>
		$('#item-grid').html('');
		$('#sec_div').hide();
		$('#div_repeat').show();
	<?php } elseif($this->params['id'] > 0) { ?>
		$('#div_repeat').hide();
		$('#sec_div').show();
	<?php } ?>
	
	$('#btnsave').click(function(){
		$('#sec_div input[type="text"]').removeClass('required');
	})
	
	if(tmp == '0')
	{
		$("#divassignment").show();
		$("#ddl_assignmentgrp").addClass('required');
		$("#divpromoval").hide();
		$("#txt_promotionamount").removeClass('required');
		$("#promobutton").hide();
		$("#hdnassignmentgrp").val(0);
	}
	else
	{
		$("#divassignment").hide();
		$("#ddl_assignmentgrp").removeClass('required');
		$("#divpromoval").show();
		$("#txt_promotionamount").addClass('required');
		$("#promobutton").show();
		$("#hdnassignmentgrp").val(1);
	}
	
	$('#ddl_promotiontypecode').change(function() {
	    
		var flag = $('#ddl_promotiontypecode').val();
		
		if(hdnid > 0) {
			loaddata(base_url+'/promotions/advance/promotionplanitemgrid/key/'+hdnid+'/key2/'+hdnid+'/hdnassignmentgrp/'+flag,'item-grid');
		}
		
	    if($('#ddl_promotiontypecode').val() == '0') {
			$('#ddl_assignmentgroup').attr('disabled',true);
			$('#ddl_assignmentgroup').removeClass('required');
			$('#ddl_assignmentgrp').addClass('required');
			$('#divhide').show();
			$('#divshow').hide();
			$('#ddl_assignmentgroup').val('');
			$('select').trigger('liszt:updated');
			$("#divassignment").show();
			$("#divpromoval").hide();
			$("#promobutton").hide();
			$("#hdnassignmentgrp").val(0);
	    }
	    else
	    {
			$('#ddl_assignmentgroup').attr('disabled',false);
			$('#ddl_assignmentgroup').addClass('required');
			$('#ddl_assignmentgrp').removeClass('required');
			$('#divhide').hide();
			$('#divshow').show();
			$("#divassignment").hide();
			$("#divpromoval").show();
			$("#promobutton").show();
			$("#hdnassignmentgrp").val(1);
	    }
		var promocode = 0;
		//alert(flag);
		$("#chk_casepromotion").attr('checked',false);
		$("#chk_casepromotion").attr('disabled','disabled');
		if(flag==7)
		{
			$("#chk_casepromotion").attr('disabled',false);
		}
		
		<?php if($this->formdata['promotiontypecode'] == 7) { ?>
		
			promocode = 7;
		<?php } ?>
		
		if($('#ddl_promotiontypecode').val() == 7 || promocode == 7) {
			<?php if($this->fixedqualification) { ?>
				$("#ddl_rangebasis option[value='3']").remove();
				$('<option/>').val(3).html('Fixed Qualification And Fixed Assignment').appendTo('#ddl_rangebasis');
				
			<?php } ?>
			
			<?php if($this->rangedqualification) { ?>
				$("#ddl_rangebasis option[value='4']").remove();
				$('<option/>').val(4).html('Ranged Qualification on Fixed Assignment').appendTo('#ddl_rangebasis');				
			<?php } ?>
		}
		else
		{
			$("#ddl_rangebasis option[value='3']").remove();
			$("#ddl_rangebasis option[value='4']").remove();
		}
		$('select').trigger('liszt:updated');
	});
	
	$('#ddl_rangebasis').change(function(){
		
		if(this.value == '3')
		{	
			$("#ddl_qualificationgroup option[value='1']").remove();
			$("#ddl_assignmentgroup option[value='1']").remove();
			
			$('#item-grid').html('');
			$('#sec_div').hide();
			$('#div_repeat').show();
		}
		else
		{
			$('#sec_div').show();
			$('#div_repeat').hide();
			
			$("#ddl_qualificationgroup option[value='1']").remove();
			$("#ddl_assignmentgroup option[value='1']").remove();
			
			$("#ddl_qualificationgroup option[value='']").remove();
			$("#ddl_assignmentgroup option[value='']").remove();
			
			$('<option/>').val(1).html('1 -- ALL ITEMS --').prependTo('#ddl_qualificationgroup');
			$('<option/>').val(1).html('1 -- ALL ITEMS --').prependTo('#ddl_assignmentgroup');
			
			$('<option/>').val('').html('--- Select ---').prependTo('#ddl_qualificationgroup');
			$('<option/>').val('').html('--- Select ---').prependTo('#ddl_assignmentgroup');
			
			$('#ddl_qualificationgroup').val('');
			$('#ddl_assignmentgroup').val('');
		}
		$('select').trigger('liszt:updated');
	});
		<?php if($this->formdata['promotiontypecode'] == 7) {
			
			if($this->fixedqualification) {
					if($this->formdata['rangebasis'] == 3 ) { ?>
						$('<option selected />').val(3).html('Fixed Qualification And Fixed Assignment').appendTo('#ddl_rangebasis');
					<?php } else { ?>
						$('<option/>').val(3).html('Fixed Qualification And Fixed Assignment').appendTo('#ddl_rangebasis');
					<?php } ?>
				$('select').trigger('liszt:updated');
			<?php }
			if($this->rangedqualification) {
				if($this->formdata['rangebasis'] == 4 ) { ?>
					$('<option selected />').val(4).html('Ranged Qualification on Fixed Assignment').appendTo('#ddl_rangebasis');
				<?php } else { ?>
					$('<option/>').val(4).html('Ranged Qualification on Fixed Assignment').appendTo('#ddl_rangebasis');
				<?php } ?>
				$('select').trigger('liszt:updated');
			<?php }
		} ?>		 
	
	<?php if($this->formdata['promotiontypecode'] == 0) { ?>
	
	    $('#ddl_assignmentgroup').attr('disabled',true);
	    $('#ddl_assignmentgroup').val('');
	    $('#ddl_assignmentgroup').removeClass('required');
	    $('#divhide').show();
	    $('#divshow').hide();
	    $('select').trigger('liszt:updated');	
	
	<?php } ?>
	
	$('#qualilink').click(function(){
		
		var qual_val = $('#ddl_qualificationgroup').val();		
		
		if(qual_val > 0)
		{ 
			var qual_url = "<?php echo $grp_detail; ?>"+"?grptype=1&groupcode="+qual_val+"&q=prettyphoto&iframe=true&width=700&height=500";
				
			$.prettyPhoto.open(qual_url);
		}
		else
		{
			jAlert('Please Select Qualification Group.');
		}
	})
	
	$('#assignlink').click(function(){
		
		var qual_val = $('#ddl_assignmentgroup').val();
		
		if(qual_val > 0)
		{
			var qual_url = "<?php echo $grp_detail; ?>"+"?grptype=2&groupcode="+qual_val+"&q=prettyphoto&iframe=true&width=700&height=500";
				
			$.prettyPhoto.open(qual_url);
		}
		else
		{
			jAlert('Please Select Assignment Group.');
		}
		
	})

	$(".click_event").click(function(){
		
		$('#hdnadd').val('yes');
		$('#hdnadd').addClass('sec_div');
		var hdnassignmentgrp = '';
		
		var gridurl = $('#frmdet .sec_div').serialize();
	    if($('#frmdet').valid())
	    {
			var low 	= $("#txt_rangelow").val();
			var high	= $("#txt_rangehigh").val();
			
			if(parseInt(high) > parseInt(low) && $("#ddl_repeatingrange").val() == 0)
			{
				var values = $('#frmdet').serialize();
				$.ajax({
					type : "POST",
					url : base_url+"/promotions/advance/addpromotionplanajax",
					data:$("#frmdet").serialize(),
					success:function(returndata) {
						$('#hdnid').val(returndata);
						$('#txt_assignmentnumber').val(returndata);
						hdnid = returndata;
						hdnassignmentgrp = $('#hdnassignmentgrp').val();
						loaddepotdatadata(base_url+"/promotions/advance/promotionplanitemgrid/hdnassignmentgrp/"+hdnassignmentgrp+"/key/"+returndata+'/key2/'+returndata,'item-grid',gridurl);
					}
				});
			}
			else if(parseInt(high) < parseInt(low) && $("#ddl_repeatingrange").val() == 0)
			{
				jAlert('Range High Must Be Greater Than Range Low.');
			}
			else
			{
				var values = $('#frmdet').serialize();				
				$.ajax({
					type : "POST",
					url : base_url+"/promotions/advance/addpromotionplanajax",
					data:$("#frmdet").serialize(),					
					success:function(returndata) {
						$('#hdnid').val(returndata);
						$('#txt_assignmentnumber').val(returndata);
						hdnid = returndata;
						hdnassignmentgrp = $('#hdnassignmentgrp').val();
						loaddepotdatadata(base_url+"/promotions/advance/promotionplanitemgrid/hdnassignmentgrp/"+hdnassignmentgrp+"/key/"+returndata+'/key2/'+returndata,'item-grid',gridurl);						
					}
				});				
			}
	    }
	});
	
	var flag = '<?php echo $this->formdata['promotiontypecode']; ?>';
	
	//loaddata('<?php echo $this->itemgrid; ?>/hdnassignmentgrp/'+flag,'item-grid');
	if(hdnid > 0) {
		loaddata(base_url+'/promotions/advance/promotionplanitemgrid/key/'+hdnid+'/key2/'+hdnid+'/hdnassignmentgrp/'+flag,'item-grid');
	}

		$("#ddl_repeatingrange").change(function() {
			if($("#ddl_repeatingrange").val() == 1)
			{
				$("#txt_rangehigh").val(0);
			}
		})
    })    
    
	function fnload()
	{
		if($("#hdnrange_high").val() == 1) {
			$('#txt_rangelow').val('');
			$('#ddl_repeatingrange').val('');
			$('#txt_rangehigh').val('');
			$('#txt_promotionamount').val('');
			$('#ddl_assignmentgrp').val('');
			$('select').trigger('liszt:updated');
			$("#ddl_repeatingrange_chzn a span").html('0 - No');
			$("#ddl_repeatingrange_chzn .chzn-drop .chzn-results #ddl_repeatingrange_chzn_o_0 ").addClass('result-selected');						
		}
	}

	
function confirmcasepromo()
{
	var flag = $('#ddl_promotiontypecode').val();
	var isChecked = $("#chk_casepromotion").is(':checked');
	
	if(flag==7 && isChecked)
	{
	if (confirm("Do you really want to add case promotion?")) {

	$('.savethisform').click();
	} else {
	  
	}
	}
	else
		$('.savethisform').click();
		
}

</script>
<style>
#assignlink{
	text-decoration:none !important;
}
#qualilink{
	text-decoration:none !important;
}
</style>

<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="promotion_advance_addpromotionplan" >
<?php if(SFA_Message::isSetMsg()) {  ?>
<div class="alert success">
    <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
</div>
<?php } ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
<div class="alert error">
    <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
</div>
<?php } ?>
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png">
    	<h3><?php echo $this->translate->_('Promo Plan');?></h3>
    </div>
    <div class="_50_3">
	
	\
	<div class="_10 save_btn" >
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"promotions","controller"=>"advance","action"=>"promotionplan"), "default", true);?>')" >
	</div>
	<div style="display:none" class="_10 save_btn"><input class="border_none savethisform" type="submit" value="" name="btnsave" id="btnsave"></div>
	<div style="display:block;" class="_10 save_btn"><input class="border_none" type="button" value="" name="btnsave1" id="btnsave" onclick="confirmcasepromo()"></div>
    </div>
</div>
<div class="clear"></div>
<div class="clear"></div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"advance","action"=>"promotionplan"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"advance","action"=>"addpromotionplan"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>


<div class="content with-actions min_height_10">
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
			<?php echo $this->translate->_('PromotionPlan No.').''.$this->colan;?>
		</label>
		<div class="_25_1">
			<input type="text" id="txt_plannumber" name="txt_plannumber" value="<?php echo isset($this->formdata['plannumber'])?$this->formdata['plannumber']:"" ;?>" readonly="readonly" >
		</div>
		<label class="_20_2 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Promotion Type').''.$this->required;?>
		</label>
		<div class="_25_1  margin_right_2_2">	
			<select id="ddl_promotiontypecode" name="ddl_promotiontypecode" class="required">
			<option value=""> --- Select --- </option>
			<?php for($i=0;$i<count($this->promotion_type);$i++) { ?>
				<option value="<?php echo $this->promotion_type[$i]['id'];?>" <?php echo ($this->promotion_type[$i]['id'] == $this->formdata['promotiontypecode'])?'selected':''; ?> ><?php echo $this->promotion_type[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>		
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Description').''.$this->required;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txt_plandescription" maxlength="50" name="txt_plandescription" class="required margin_top_5" value="<?php echo isset($this->formdata['plandescription'])?$this->formdata['plandescription']:"" ;?>" >
	</div>
	<label class="_20_2 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Range Basis').''.$this->colan;?>
	</label>
	<div class="_25_1  margin_right_2_2">
	    <select id="ddl_rangebasis" name="ddl_rangebasis">
		<option value=""> --- Select --- </option>
		<?php for($i=0;$i<count($this->range_basis);$i++) { ?>
			<option value="<?php echo $this->range_basis[$i]['id'];?>" <?php echo ($this->range_basis[$i]['id'] == $this->formdata['rangebasis'])?'selected':''; ?> ><?php echo $this->range_basis[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txt_arbplandescription"  maxlength="50"  name="txt_arbplandescription" class="arb_text_align margin_top_5" value="<?php echo isset($this->formdata['arbplandescription'])?$this->formdata['arbplandescription']:"" ;?>" />
	</div>
	<label class="_20_2 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Amount Basis').''.$this->colan;?>
	</label>
	<div class="_25_1  margin_right_2_2">
	    <select id="ddl_amountbasis" name="ddl_amountbasis">
		<option value=""> --- Select --- </option>
		<?php for($i=0;$i<count($this->amount_basis);$i++) { ?>
			<option value="<?php echo $this->amount_basis[$i]['id'];?>" <?php echo ($this->amount_basis[$i]['id'] == $this->formdata['amountbasis'])?'selected':''; ?> ><?php echo $this->amount_basis[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
	
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align"><?php echo $this->translate->_('Status').''.$this->colan;?></label>
	<div class="_25_1  margin_right_2_2">
	    <select id="ddl_activeindicator" name="ddl_activeindicator">		
		<option value="1" <?php echo ($this->formdata['activeindicator']=='1')?'selected':''; ?> ><?php echo $this->translate->_('Active');?></option>
		<option value="0" <?php echo ($this->formdata['activeindicator']=='0')?'selected':''; ?> ><?php echo $this->translate->_('Inactive');?></option>
	    </select>
	</div>
	<!--<label class="_20_2 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Exclution Option').''.$this->colan;?>
	</label>
	<div class="_25_1  margin_right_2_2">
	    <select id="ddl_exclusionoption" name="ddl_exclusionoption">
		<option value=""> --- Select --- </option>
		<?php for($i=0;$i<count($this->exclusion_option);$i++) { ?>
			<option value="<?php echo $this->exclusion_option[$i]['id'];?>" <?php echo ($this->exclusion_option[$i]['id'] == $this->formdata['exclusionoption'])?'selected':''; ?> ><?php echo $this->exclusion_option[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>-->
	<label class="_20_2 date_color margin_top_12 label_text_align">
			<a id="qualilink" href="#" class="date_color"><?php echo $this->translate->_('Qualification Group').''.$this->required;?></a>
		</label>
		<div class="_25_1  margin_right_2_2">
			<select id="ddl_qualificationgroup" name="ddl_qualificationgroup" class="required">
			<option value=""> --- Select --- </option>
			<option value="1" <?php echo ('1' == $this->formdata['qualificationgroup'])?'selected':''; ?>>1 -- ALL ITEMS --</option>
			<?php for($i=0;$i<count($this->qualification_group);$i++) { ?>
				<option value="<?php echo $this->qualification_group[$i]['id'];?>" <?php echo ($this->qualification_group[$i]['id'] == $this->formdata['qualificationgroup'])?'selected':''; ?> ><?php echo $this->qualification_group[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>
    </div>
    <div class="_100">
		<label class="_25_1 label_text_align  margin_top_12">
			<?php echo $this->translate->_('Enforce Promotion');?>
		</label>
		<div class="_25_1 margin_top_5"><input type="checkbox" id="chk_enforcepromotion" name="chk_enforcepromotion" value="1" <?php echo (isset($this->formdata['enforcepromotion']) && $this->formdata['enforcepromotion']==1)?'checked="checked"':'' ;?> >
		</div>
		<label id="divhide" style="display:none" class="_20_2 margin_top_10 label_text_align">
	    <?php echo $this->translate->_('Assigngment Group').''.$this->colan;?>
	</label>
		<label id="divshow" class="_20_2 margin_top_10 label_text_align">
	    <a id="assignlink" href="#" class="date_color"><?php echo $this->translate->_('Assignment Group').''.$this->required;?></a>
	</label>
	<div class="_25_1  margin_right_2_2">
	    <select id="ddl_assignmentgroup" name="ddl_assignmentgroup" class="required">
		<option value=""> --- Select --- </option>
		<option value="1" <?php echo ('1' == $this->formdata['assignmentgroup'])?'selected':''; ?>>1 -- ALL ITEMS --</option>
		<?php for($i=0;$i<count($this->assignment_group);$i++) { ?>
			<option value="<?php echo $this->assignment_group[$i]['id'];?>" <?php echo ($this->assignment_group[$i]['id'] == $this->formdata['assignmentgroup'])?'selected':''; ?> ><?php echo $this->assignment_group[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
    </div>
    
	
	 <div class="_100">
		<label class="_25_1 label_text_align  margin_top_12">
			<?php echo $this->translate->_('Case Promotion');?>
		</label>
		<div class="_25_1 margin_top_5"><input type="checkbox" id="chk_casepromotion" name="chk_casepromotion" value="1" <?php echo (isset($this->formdata['casepromotion']) && $this->formdata['casepromotion']==1)?'checked="checked"':'' ;?>   <?php echo ( $this->formdata['promotiontypecode']!=7)?'disabled="disabled"':'' ;?>   
		>
		</div>
	
		
    </div>
	
	
	
    <div class="_100">
	<!--<label class="_25_1 label_text_align  margin_top_12">
		<?php echo $this->translate->_('One Time Use');?>
	</label>
	<div class="_25_1 margin_top_5"><input type="checkbox" id="chk_onetimeuse" name="chk_onetimeuse" value="1" <?php echo (isset($this->formdata['onetimeuse']) && $this->formdata['onetimeuse']==1)?'checked="checked"':'' ;?> >
	</div>	
	<label id="divhide" style="display:none" class="_20_2 margin_top_10 label_text_align">
	    <?php echo $this->translate->_('Assigngment Group').''.$this->colan;?>
	</label>-->
	
    </div>
    <div class="_100 margin_bottom_20">
		<!--<label class="_25_1 label_text_align  margin_top_12">
			<?php echo $this->translate->_('Quantity In Cases');?>
		</label>
		<div class="_25_1 margin_top_5"><input type="checkbox" id="chk_iscase" name="chk_iscase" value="1" <?php echo (isset($this->formdata['iscase']) && $this->formdata['iscase']==1)?'checked="checked"':'' ;?> ></div>
		<label class="_20_2 margin_top_10 label_text_align">
			<?php echo $this->translate->_('Assignment No.').''.$this->colan;?>
		</label>
		<div class="_25_1">
			<input type="text" id="txt_assignmentnumber"  maxlength="20"  class="margin_top_5 number" name="txt_assignmentnumber" readonly="readonly" value="<?php echo isset($this->formdata['assignmentnumber'])?$this->formdata['assignmentnumber']:"" ;?>" <?php if($this->params["id"] > 0) { ?> readonly="readonly"  <?php } ?> >
		</div>-->
    </div>
	<!--<div class="_100 margin_bottom_20" id="div_repeat">
		<label class="_25_1 label_text_align  margin_top_12">
			<?php echo $this->translate->_('Repeat Range');?>
		</label>
		<div class="_25_1 margin_top_5"><input type="checkbox" id="chk_repeatrange" name="chk_repeatrange" value="1" <?php echo (isset($this->formdata['repeatrange']) && $this->formdata['repeatrange']==1)?'checked="checked"':'' ;?> ></div>
	</div>-->
	<div class="_100 space_20 clear">&nbsp;</div>
</div>

<input type="hidden" id="hdnid" class="sec_div" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>" />
<div class="content with-actions" id="sec_div">
	<div id="loader"></div>
	<div class="_100 margin_top_25">
	    <fieldset id="a" name="a">
		<legend><?php echo $this->translate->_('Details');?></legend>
		<div class="_100">
			<input type="hidden"  id="hdnassignmentgrp" name="hdnassignmentgrp" value="" class="sec_div" >
			<input type="hidden"  id="hdnrange_high" name="hdnrange_high" value="" class="sec_div">
			<input type="hidden"  id="hdnadd" name="hdnadd" value="" class="sec_div">
		    <label class="_12 margin_top_12 label_text_align">
			 <?php echo $this->translate->_('Range Low').''.$this->required;?>
		    </label>
		    <div class="_10_1 margin_top_3  margin_right_2_2">
			<input type="text" value="" maxlength="10" name="txt_rangelow" id="txt_rangelow" class="required number sec_div" >
		    </div>
			<label class="_12 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Range High').''.$this->required;?>
		    </label>
		    <div class="_10_1 margin_top_3  margin_right_2_2">
			<input type="text" value="" name="txt_rangehigh" id="txt_rangehigh" class="required number sec_div" />
		    </div>
		    <label class="_15 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Range Repeat').''.$this->required;?>
		    </label>
		    <div class="_12 margin_top_3 margin_left_right_1 margin_right_2_2">
				<select id="ddl_repeatingrange" name="ddl_repeatingrange" class="required sec_div">
					<option value="0"><?php echo $this->translate->_('0 - No');?></option>
					<option value="1"><?php echo $this->translate->_('1 - Yes');?></option>
				</select>				
		    </div>
			<div id="divpromoval">				
				<label class="_15_3 margin_top_12 label_text_align">
					<?php echo $this->translate->_('Promo Value').''.$this->required;?>
				</label>
				<div class="_10_1 margin_top_3  margin_right_2_2">
					<input type="text" value="" name="txt_promotionamount" id="txt_promotionamount" class="sec_div required number amount_text_align" >
				</div>				
			</div>
		</div>
		<div class="_100">
			<div id="divassignment">
				<label class="_12 margin_top_12 label_text_align">
					<?php echo $this->translate->_('Assigngment').''.$this->required;?>
				</label>
				<div class="_20  margin_right_2_2">
					<select id="ddl_assignmentgrp" name="ddl_assignmentgrp" class="required sec_div">
						<option value=""> --- Select --- </option>
						<?php for($i=0;$i<count($this->assignment_group);$i++) { ?>
							<option value="<?php echo $this->assignment_group[$i]['id'];?>" ><?php echo $this->assignment_group[$i]['val'];?></option>
						<?php } ?>
					</select>
				</div>
				<div class="_10">&nbsp;</div>
				<div class="_10">
					<input type="button" value="<?php echo $this->translate->_('ADD');?>" id="sbtnadd" name="sbtnadd" class="margin_top_5 click_event sec_div">
				</div>
			</div>
			<div id="promobutton">
				<div class="_15_3">&nbsp;</div>
				<div class="_15">
					<input type="button" value="<?php echo $this->translate->_('ADD');?>" id="sbtnaddpromo" name="sbtnaddpromo" class="margin_top_5 click_event sec_div">
				</div>
			</div>
		</div>
	    </fieldset>
	<div class="_100 margin_top_25">
	    <fieldset id="ab" name="ab" class="fieldset_effect">
		<legend class="ttl"><?php echo $this->translate->_('Promotion Plan');?></legend>
		<hr id="ie_hr" >
		<div class="_5 clear_only">&nbsp;</div>
		<div class="_100">		    
		    <div id="item-grid"> <!--grid load here --> </div>
		</div>
	    </fieldset>
	</div>	
</div>
</div> <!-- End of .box -->
</form>
</div>
</div>
<script type="text/javascript">
$(window).load(function() {
    $("a[class^='ico edit']").prettyPhoto({animation_speed:'fast',theme:'light_rounded', allowresize: false});
});
</script>