<?php

/**
* @name       promotionkey.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/
?>
<form name="frmoverview" id="frmoverview" action="" method="post">
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png" class="margin_top_7">
		<h3><?php echo $this->title;?></h3>
	    </div>
	    <div class="_50_3">&nbsp;</div>
        </div>
	<div class="clear"></div>	        
	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>