<script>
        $(document).ready(function(){
            loaddata('<?php echo $this->itemgrid; ?>','item-grid');
        })
</script>

<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}

</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post" target="_parent">
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png" class="margin_top_7">
		<h3><?php echo $this->title?></h3>
	    </div>
	    <div class="_50_3">&nbsp;</div>
        </div>
	<div class="clear"></div>
	<div class="clear"></div>
	<div class="_100">
	    <div id="loader"></div>
	    <div id="item-grid"> <!--grid load here --> </div>
	</div>
        <div class="clear"></div>
	<div class="_100 margin_bottom_10">
	    <div class="_50">&nbsp;</div>
	    <div class="_50">
		<input type="submit" id="btngridsave" name="btngridsave" value="<?php echo $this->save;?>" >
	    </div>
	</div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>