<?php
/**
* @name       adddistributionkey.phtml
* @since      1 feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<script>
var decimalplaces	= '<?php echo $this->decimalplaces;?>';

$(document).ready(function() {
	
	$("#txt_description").focus();
	
	loaddata('<?php echo $this->itemgrid; ?>','item-grid');
	
	$("#btnsave").click(function(){
		$("#ddlitem_code").removeClass('required');
		$("#txtvalue").removeClass('required');
	});
	
	$("#sbtnadd").click(function(){
		
		$("#ddlitem_code").addClass('required');
		$("#txtvalue").addClass('required');
		
	    if($('#frmdet').valid())
	    {
			var values = $('#frmdet').serialize();
			$.ajax({
				type : "POST",
				url : base_url+"/promotions/discount/adddistributionkeyitemgrid/",
				data :values+'&add=yes',
				success:function(returndata) {
				   loaddata(base_url+"/promotions/discount/distributionkeyitemgrid/key/"+returndata,'item-grid');				
					$("#ddlitem_code").val("");
					$("#txtcaseprice").val("");
					$("#txtsalesprice").val("");
					$('#txtvalue').val('');
					$('select').trigger('liszt:updated');
					$("#hdnid").val(returndata); 
				}
			});
	    }
	});
})
function getiteminfo(item_id)
{
	$("#txtcaseprice").val('');
	$("#txtsalesprice").val('');		
	
	if(item_id > 0 )
	{
		var url 		= base_url+'/home/index/getiteminfo/itemid/'+item_id;
		var allow_entry = 0;
		$.ajax({
			url:url,
			data:$("#frmdet").serialize(),
			type:'post',			
			success:function(data)
			{	
				var item_info = JSON.parse(data);
				if (item_info == '')
				{
					return false;
				}					
				if(typeof(item_info[0]) == 'object')
				{
					var temp1 	= Number(item_info[0][0]['caseprice']);
					var temp1 	= temp1.toFixed(decimalplaces);
					var temp2 	= Number(item_info[0][0]['defaultsalesprice']);
					var temp2 	= temp2.toFixed(decimalplaces);					
					
					$("#txtcaseprice").val(temp1);
					$("#txtsalesprice").val(temp2);
				}
			}
		})			
	}
}
</script>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="promotion_discount_adddistributionkey">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
    <div class="header">
	<div class="_50_3 back_btn">
	    <img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png">
	    <h3><?php echo $this->translate->_('Distribution Key')?></h3>
	</div>
	<div class="_50_3">
	    <div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"promotions","controller"=>"discount","action"=>"distributionkey"), "default", true);?>')" >
	    </div>
	    <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
	</div>
    </div>
    <div class="clear"></div>
    <div class="clear"></div>
    <div id="nav_sub" class="ie_nav_sub">
    <div class="container_12">
	<ul id="nav_main">
	    <li class="current">
		<ul style="display: block;">
		   <li>
			<a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"discount","action"=>"distributionkey"),"default", true);?>"><?php echo $this->translate->_('Overview'); ?></a>
		    </li>
		    <li class="last-child">
			<a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"discount","action"=>"adddistributionkey"),"default", true);?>"><b><?php echo $this->translate->_('Details'); ?></b></a>
		    </li>
		</ul>
	    </li>
	</ul>
    </div>
    </div>
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <label class="_40 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Distribution Key').''.$this->colan;?>
	    </label>
	    <div class="_25 margin_right_1">
		<input type="text" name="txt_distributionkey" id="txt_distributionkey" readonly="readonly" value="<?php echo isset($this->formdata['distributionkey'])?$this->formdata['distributionkey']:"" ;?>"   />
	    </div>	    
	</div>
	<div class="_100">
	    <label class="_40 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Item Description').''.$this->required;?>
	    </label>
	    <div class="_25 margin_right_1">
		<input type="text"  maxlength="50" name="txt_description" id="txt_description" value="<?php echo isset($this->formdata['description'])?$this->formdata['description']:"" ;?>"  class="required" />
	    </div>	    
	</div>
	<div class="_100">
	    <label class="_40 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_25 margin_right_1">
			<input type="text"  maxlength="50" class="arb_text_align" name="txt_arbdescription" id="txt_arbdescription" value="<?php echo isset($this->formdata['arbdescription'])?$this->formdata['arbdescription']:"" ;?>" />
	    </div>
	</div>
	<div class="_100">
	    <label class="_40 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Status').''.$this->colan;?>
	    </label>
	    <div class="_25 margin_right_1">			
			<select name="ddlstatus" id="ddlstatus">
				<option <?php echo (isset($this->formdata['active']) && $this->formdata['active']=='1')?'checked="checked"':'' ;?> value="1" selected><?php echo $this->translate->_('Active');?></option>
				<option <?php echo (isset($this->formdata['active']) && $this->formdata['active']=='0')?'checked="checked"':'' ;?> value="0"><?php echo $this->translate->_('Inactive');?></option>
            </select>
	    </div>
	</div>
    </div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>" />
<div class="content with-actions min_height_10">
	<div class="_100 margin_top_25">
	     <fieldset id="a" name="a">
		<legend><?php echo $this->translate->_('Detail Section');?></legend>
		<div class="_100">		    
		    <label class="_8 margin_top_10 label_text_align">
			 <?php echo $this->translate->_('Item').''.$this->required;?>
		    </label>
		    <div class="_20_1 margin_right_1">
			<select id="ddlitem_code" name="ddlitem_code" class="required" onchange="getiteminfo(this.value)">
			    <option value="">--- Select ---</option>
			    <?php for($i=0;$i<count($this->item_master_data);$i++) { ?>
			    <option value="<?php echo $this->item_master_data[$i]['id'];?>"><?php echo $this->item_master_data[$i]['val'];?></option>
			    <?php } ?>
			</select>
		    </div>
			<label class="_12 margin_top_10 label_text_align">
				<?php echo $this->translate->_('Case Price').''.$this->colan;?>
		    </label>
		    <div class="_8 margin_left_1 margin_right_2_2">
				<input type="text" id="txtcaseprice" name="txtcaseprice" value="" readonly="readonly">
		    </div>
			<label class="_12 margin_top_10 label_text_align">
				<?php echo $this->translate->_('Sales Price').''.$this->colan;?>
		    </label>
		    <div class="_8 margin_left_1 margin_right_2_2">
				<input type="text" id="txtsalesprice" name="txtsalesprice" value="" readonly="readonly">
		    </div>
			<label class="_8 margin_top_10 label_text_align">
				<?php echo $this->translate->_('Value').''.$this->required;?>
		    </label>
		    <div class="_8 margin_left_1 margin_right_2_2">
				<input type="text" id="txtvalue" name="txtvalue" value="" class="margin_top_5 required number amount_text_align">
		    </div>			
			<div class="_5 margin_right_2_2">
			    <input type="button" value="<?php echo $this->translate->_('ADD');?>" id="sbtnadd" name="sbtnadd" class="margin_top_5">
			</div>
		</div>
	    </fieldset>
	</div>
	<div class="_100 margin_top_25">
	    <fieldset id="ab" name="ab" class="fieldset_effect">
		<legend class="ttl"><?php echo $this->translate->_('Distribution Key');?></legend>
		<hr id="ie_hr" >
		<div class="_5 clear_only">&nbsp;</div>
		<div class="_100">
		    <div id="loader"></div>
		    <div id="item-grid"> <!--grid load here --> </div>
		</div>
	    </fieldset>
	</div>        
</div>
</form>
</div> <!-- End of .box -->
</div>