<?php
/**
* @name       adddiscountkey.phtml
* @since      1 feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$url = $this->url(array("module"=>"promotions","controller"=>"customer","action"=>"discountkeyplan"), "default", true);
?>
<style>
.box .content {border:none !important;} td{padding:5px;}
</style>
<script>
$(document).ready(function(){
	
	$("#txt_description").focus();
	
	loaddata('<?php echo $this->itemgrid; ?>','item-grid');
	
	$("#btnsave").click(function(){
		$("#txtmins_disc").removeClass('required');
		$("#txtmax_disc").removeClass('required');
	});
	
	$("#sbtnadd").click(function(){
		
		$("#txtmins_disc").addClass('required');
		$("#txtmax_disc").addClass('required');
		
	    if(!$("#frmdet").valid()){
			return false;
		}else
		{
			var values = $('#frmdet').serialize();
			$.ajax({
				type : "POST",
				url : base_url+"/promotions/discount/adddiscountkeygrid/",
				data :values+'&add=yes',
				beforeSend: function() {
					$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
				},
				success:function(returndata){
					loaddata(base_url+"/promotions/discount/discountkeyitemgrid/key/"+returndata,'item-grid');
					clearForm();
					$("#hdnid").val(returndata); 
				}
			});
	    }
	});
	
});
    
    function clearForm()
    {
		$("#ddlitem_code").val("");	
		$('#txtmins_disc').val('');
		$('#txtmax_disc').val('');
		$('#chkall').attr('checked',false);
		$('select').trigger('liszt:updated');
    }
</script>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="promotion_discount_adddiscountkey">
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
    <div class="header">
	<div class="_50_3 back_btn">
	    <img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png">
	    <h3><?php echo $this->translate->_('Discount Key')?></h3>
	</div>
	<div class="_50_3">
	    <div class="_10 save_btn">
		<input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"promotions","controller"=>"discount","action"=>"discountkey"), "default", true);?>')" >
	    </div>
	    <div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
	</div>
    </div>
    <div class="clear"></div>
    <div class="clear"></div>
    <div id="nav_sub" class="ie_nav_sub">
    <div class="container_12">
	<ul id="nav_main">
	    <li class="current">
		<ul style="display: block;">
		   <li>
			<a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"discount","action"=>"discountkey"),"default", true);?>"><?php echo $this->translate->_('Overview'); ?></a>
		    </li>
		    <li class="last-child">
			<a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"discount","action"=>"adddiscountkey"),"default", true);?>"><b><?php echo $this->translate->_('Details'); ?></b></a>
		    </li>
		</ul>
	    </li>
	</ul>
    </div>
    </div>
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <label class="_25_1 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Discount Key').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" name="txt_discountkey" id="txt_discountkey" readonly="readonly" value="<?php echo isset($this->formdata['discountkey'])?$this->formdata['discountkey']:"" ;?>" />
	    </div>
	    <label class="_25_1 margin_top_15 label_text_align">&nbsp;</label>
	    <div class="_25_1 margin_right_1">&nbsp;</div>
	</div>
	<div class="_100">
	    <label class="_25_1 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Description').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text"  maxlength="50" name="txt_description" id="txt_description" value="<?php echo isset($this->formdata['description'])?$this->formdata['description']:"" ;?>" />
	    </div>
	    <label class="_25_1 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text"  maxlength="50" name="txt_arbdescription" class="arb_text_align" id="txt_arbdescription" value="<?php echo isset($this->formdata['arbdescription'])?$this->formdata['arbdescription']:"" ;?>" />
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Start Date')."".$this->required;?>
	    </label>
	    <div class="_25_1">
		<input type="text" name="txtstartdate" id="txtstartdate" class="required" value="<?php echo isset($this->formdata['startdate'])?$this->formdata['startdate']:"" ;?>" />
	    </div>
	    <label class="_25_1 margin_top_15 label_text_align">
		<?php echo $this->translate->_('End Date').''.$this->required;?>
	    </label>
	    <div class="_25_1">
		<input type="text" name="txtenddate" id="txtenddate" class="required" value="<?php echo isset($this->formdata['enddate'])?$this->formdata['enddate']:"" ;?>" />
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 margin_top_12 label_text_align">
		<?php echo $this->translate->_('Status').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<select name="ddlstatus" id="ddlstatus">
			<option <?php echo (isset($this->formdata['active']) && $this->formdata['active']=='1')?'checked="checked"':'' ;?> value="1" selected><?php echo $this->translate->_('Active');?></option>
			<option <?php echo (isset($this->formdata['active']) && $this->formdata['active']=='0')?'checked="checked"':'' ;?> value="0"><?php echo $this->translate->_('Inactive');?></option>
		</select>
	    </div>
	</div>
    </div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="returnUrl" name="returnUrl" value="<?php echo $this->returnUrl; ?>" />
<div class="content with-actions min_height_10">
	<div class="_100 margin_top_25">
	    <fieldset id="a" name="a">
		<legend><?php echo $this->translate->_('Details');?></legend>
		<div class="_100">
		    <label class="_8 margin_top_10 label_text_align">
			 <?php echo $this->translate->_('Item').''.$this->colan;?>
		    </label>
		    <div class="_30_3 margin_left_right_1">
				<select id="ddlitem_code" name="ddlitem_code" >
					 <option value="0">-- ALL ITEM --</option>
					<?php for($i=0;$i<count($this->item_master_data);$i++) { ?>
					<option value="<?php echo $this->item_master_data[$i]['id'];?>"><?php echo $this->item_master_data[$i]['val'];?></option>
					<?php } ?>
				</select>
		    </div>
			<!--  <label class="_12 margin_top_10 label_text_align">
				<?php //echo $this->translate->_('Add All Item').''.$this->colan; ?>
		    </label>
		    <div class="_3 margin_top_3 margin_left_right_1">
				<input type="checkbox" id="chkall" name="chkall" value="1" >
		    </div>	-->	
		    <label class="_12 margin_top_10 label_text_align">
			<?php echo $this->translate->_('Min Discount').''.$this->required;?>
		    </label>
		    <div class="_10_2 margin_right_2_2">
			<input type="text" value=""  maxlength="18"  name="txtmins_disc" id="txtmins_disc" class="required number" />
		    </div>
		    <label class="_15 margin_top_10 label_text_align">
			<?php echo $this->translate->_('Max Discount').''.$this->required;?>
		    </label>
		    <div class="_10_2 margin_right_2_2">
				<input type="text" value=""  maxlength="18"  name="txtmax_disc" id="txtmax_disc" class="required number" >
		    </div>
			<div class="_3">&nbsp;</div>
		    <div class="_10">
				<input type="button" value="<?php echo $this->translate->_('ADD');?>" id="sbtnadd" name="sbtnadd" class="margin_top_5">
		    </div>		    
		</div>
	    </fieldset>
	<div class="_100 margin_top_25">
	    <fieldset id="ab" name="ab" class="fieldset_effect">
		<legend class="ttl"><?php echo $this->translate->_('Discount Key');?></legend>
		<hr id="ie_hr" >
		<div class="_5 clear_only">&nbsp;</div>
		<div class="_100">
		    <div id="loader"></div>
		    <div id="item-grid"> <!--grid load here --> </div>
		</div>
	    </fieldset>
	</div>
   
</div>
</div> <!-- End of .box -->
</form>
</div>
</div>

    
