<?php
/**
* @name       index.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/
$this->translate 	= Zend_Registry::get('Zend_Translate');
?>
<script type="text/javascript">
var ajax_page_URL = base_url+"/hhctransaction/arcollection/";
var collection_item_grid = base_url+"/hhctransaction/arcollection/collectiongrid/";
var Overview_URL = base_url+"/hhctransaction/cloudtran/arcollection/";
var please_wait_msg ="<h1 class='blockui_css'><?php echo $this->translate->_('Please Wait ...');?></h1>";
$(document).ready(function() {
    $(document).ajaxStop($.unblockUI);
});
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/modules/collection/arcollection.js"></script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_customer_addcustomer">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
	<h3><?php echo $this->translate->_('AR Collection');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"cloudtran","action"=>"arcollection"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul>
	    	<li>
		    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"cloudtran","action"=>"arcollection"),"default", true);?>"><?php echo $this->translate->_('Overview');?></a>
		</li>
	    </ul>
	    <ul style="display: block; margin-left:75px;" class="tabs">
		<li> 
		    <a href="#tab1" id="t1" class="admin_active tablink"><?php echo $this->translate->_('Detail');?></a> 
		</li>
		
	    </ul>
	</li>
    </ul>
</div>
</div>
   <div class="content with-actions  min_height_10">
    <form class="validate" novalidate action="" id="add_collection">
	<div id="tab1" class="tab_content">
	   <div class="_100">
			<label class="_15 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Route').''.$this->required;?>
			</label>
			<div class="_35 margin_left_1">
				<select id="ddlroute" name="ddlroute" class="required">
				<option value="">--- Select ---</option>
				<?php
					for($i=0;$i<count($this->route);$i++)
					{
				?>
					<option <?php echo ($this->formdata['routecode']==$this->route[$i]['id']) ? 'selected' : '';?> value="<?php echo $this->route[$i]['id'];?>" ><?php echo $this->route[$i]['val'];?></option>
				<?php } ?>
				</select>
			</div>
                         <label class="_20_1 margin_top_12 label_text_align"> <?php echo $this->translate->_('Receipt No').''.$this->colan;?></label>			
                        <div class="_20_1"> <input type="text" id="txtcollection_no" name="txtcollection_no" value="" readonly="readonly"  >
                        
                        <input type="hidden" id="txtsalesman_code" name="txtsalesman_code" value="" readonly="readonly" class="padding_right_10"  >
                        </div>
                        
	    </div>
           
             <div class="_100 ">
			<label class="_15 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Salesman').''.$this->colan;?>
			</label>
			<div class="_35 margin_left_1">
				<input class="margin_top_5" name="txtsalesman" id="txtsalesman" type="text" value="" readonly="readonly" >
			</div>
                        <label class="_20_1 margin_top_12 label_text_align"> <?php echo $this->translate->_('Document No').''.$this->colan;?></label>			
                        <div class="_20_1"> <input type="text" id="txtdoc_no" name="txtdoc_no" value="<?php echo $this->formdata['documentnumber'];?>" readonly="readonly"  ></div>
                        
	    </div>
             <div class="_100">
		<label class="_15 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Customer').''.$this->required;?>
		</label>
		<div class="_35 margin_left_1">
		    <select id="ddlcustomer" name="ddlcustomer" class="required">
			 <option value="">--- Select ---</option>			
		    </select>
		</div>
                 <label class="_20_1 margin_top_12 label_text_align"> <?php echo $this->translate->_('First In First Out').''.$this->colan;?></label>			
                 <div class="_20_1  margin_top_5"> <input type="checkbox" id="chkfirstout" name="chkfirstout" value="1"></div>
                        
                
			
	    </div>
              
             <div class="_100">
			<label class="_15 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Comment').''.$this->colan;?>
			</label>
			<div class="_35 margin_left_1">
				<input name="txtremark1" id="txtremark1"  type="text" value="<?php echo $this->formdata['remarks1'];?>" >
			</div>
	    </div>
          
            <div class="_100">
                <div class="clear_only"></div>
            </div>
           
            <div class="_100">
                 <div class="clear"></div>
                 <div id="loader"></div>
                <div id="item-grid"></div>
            </div>
            <div class="_100" id="showbtn" style="float:right">
               	<div class="margin_right_1">
			<input type="button" id="btnloadtotal" name="btnloadtotal" value="<?php echo $this->translate->_('CALCULATE');?>" style="float:right">
                        
		</div>
            </div>
            
	</div>
        <input type="hidden" id="last_para" name="last_para" value="1" >
        <input type="hidden" id="last_para1" name="last_para1" value="2" >
    </form>
         <div class="_100 margin_top_10">&nbsp;</div>
  
       
  
    <fieldset style="border:1px solid #ccc;padding-bottom:5px">
         <form class="validate" novalidate action="" id="add_collection1">
            <input type="hidden" id="last_para2" name="last_para2" value="3" >
            <input type="hidden" id="last_para3" name="last_para3" value="4" >
        <div class="_100 margin_top_25">
            <label class="_25_1 label_text_align margin_top_12">
               <?php echo $this->translate->_('Payment Mode').''.$this->required;?>
            </label>
            <div class="_25_1 margin_right_1" >
                <select id="ddlpaymode" name="ddlpaymode" class="required">
                     <option value="">--- Select ---</option>
                     <option value="0">CASH</option>
                     <option value="1">CHEQUE</option>
                </select>
            </div>
                    <label class="_25_1 label_text_align margin_top_12">
                            <?php echo $this->translate->_('Amount').''.$this->required;?>
                    </label>
                    <div class="_25_1">
                            <input type="text" id="txtamount" name="txtamount" value="0" class="number required"  readonly="readonly">
                    </div>
        </div>
            
            <div id="divbank">
                    <div class="_100" style="margin-top:0px !important">
                            <label class="_25_1 label_text_align margin_top_12">
                                    <?php echo $this->translate->_('Cheque Number').''.$this->colan;?>
                            </label>
                            <div class="_25_1">
                                    <input type="text" id="txtcheckno" class="margin_top_5" name="txtcheckno" value="" maxlength="15">
                            </div>
                            <label class="_25_1 label_text_align margin_top_12  margin_right_1">
                                    <?php echo $this->translate->_('Cheque Date').''.$this->colan;?>
                            </label>
                            <div class="_25_1">
                                    <input type="text" id="txtcheckdt" name="txtcheckdt" value="" readonly="readonly">
                            </div>
                    </div>
                    <div class="_100">
                            <label class="_25_1 label_text_align margin_top_12">
                                    <?php echo $this->translate->_('Bank Name').''.$this->colan;?>
                            </label>
                            <div class="_25_1 margin_right_1">
                                    <select id="ddlbankname" name="ddlbankname">
                                    <option value="">--- Select ---</option>
                                    <?php
                                                    for($i=0;$i<count($this->bank);$i++)
                                                    {
                                            ?>
                                                    <option value="<?php echo $this->bank[$i]['id'];?>" ><?php echo $this->bank[$i]['val'];?></option>
                                            <?php } ?>
                                    </select>
                            </div>
                            <div class="_25_1">&nbsp;</div>
                            
                    </div>
            </div>
           <div class="_100" >
                        <label class="_45 label_text_align margin_top_12">
                        </label>
                          <label class="_35 label_text_align margin_top_12">
                        </label>
                        <div class="_5_button">
                          
                            </div> 
                    </div></form>
    </fieldset>
      
     <div class="_100">
                <div class="clear_only space_20"></div>
            </div>  
    </div>
  
    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</div> <!-- End of .box -->
</div>
