<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({        
   	url:base_url+"/reports/tabletfreesummary/freesum/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route');?>','<?php echo $this->translate->_('Customer Code');?>','<?php echo $this->translate->_( 'Item Code');?>','<?php echo $this->translate->_('Item Description');?>','<?php echo $this->translate->_('Quantity');?>','<?php echo $this->translate->_('Amount');?>'],
   	colModel:[
   		{name:'routecode',index:'routecode', width:100},
        {name:'customercode',index:'customercode', width:100},
        {name:'itemcode',index:'itemcode', width:120},
        {name:'itemdescription',index:'itemdescription', width:350},
		{name:'cases',index:'cases', width:90},
		{name:'value',index:'value', width:90, align:'right', width:120, formatter: 'number', formatoptions: { decimalPlaces: decimalplaces }, summaryType:'sum'}
   	],
	<?php if($this->css == 'ar_') { ?>
		direction :"rtl",
	<?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
    rowList:eval(RP_ROWLISTSHOW),
    //loadonce:true,
    pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,        
	groupingView :
    {
        groupField : ['routecode','customercode'],
        groupColumnShow : [false,false],
        groupCollapse : true,
        groupOrder: ['asc','asc'] ,
        groupSummary : [false,true],
        groupDataSorted : true,
        showSummaryOnHide: false
    }
});
jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});
</script>