<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">

jQuery("#search").jqGrid({        
   	url:base_url+"/reports/accountcustomerageing/customerage/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Type');?>','<?php echo $this->translate->_('Customer');?>','<?php echo $this->translate->_( 'Credit Days');?>','<?php echo $this->translate->_('Transaction Date');?>','<?php echo $this->translate->_('Invoice No');?>','<?php echo $this->translate->_('Route Code');?>','<?php echo $this->translate->_( 'Salesman Code');?>','<?php echo $this->translate->_('1-30');?>','<?php echo $this->translate->_('31-60');?>','<?php echo $this->translate->_('61-90');?>','<?php echo $this->translate->_('91-120');?>','<?php echo $this->translate->_('Above 120');?>','<?php echo $this->translate->_('Total');?>' ],
   	colModel:[
		{name:'hocode',index:'hocode', width:100},
   		{name:'customercode',index:'customercode', width:120},
		{name:'creditlimitdays',index:'creditlimitdays', width:120},
		{name:'transactiondate',index:'transactiondate', width:120},
		{name:'invoicenumber',index:'invoicenumber', width:120},
		{name:'routecode',index:'routecode', width:100},
        {name:'salesmancode',index:'salesmancode', width:200},                
		{name:'age',index:'age', width:120, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
		{name:'age31',index:'age31', width:120, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
		{name:'age61',index:'age61', width:120, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
   		{name:'age91',index:'age91', width:120, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},
		{name:'age121',index:'age121', width:120, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }},		
		{name:'invoicebalance',index:'invoicebalance', width:120, align:"right",summaryType:'sum', formatter: 'number',formatoptions: { decimalSeparator: ".", decimalPlaces: <?php echo $this->decimalplaces; ?>, defaultValue: '0.00' }}
   	],
    <?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
   	pager: '#pagersr',
   	sortname: 'hocode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,
	groupingView :
        {
            groupField : ['hocode','customercode'],
            groupColumnShow : [false,false],
            groupCollapse : true,
            groupOrder: ['asc','asc'] ,
            groupSummary : [false,true],
            groupDataSorted : true,
            showSummaryOnHide: false
        },
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
 

);
jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});

</script>