<?php
/**
* @name       invoicepaymentmode.phtml
* @since      19-07-2012
* @version    Release: 1.0
* @author     Rachir <kanzaria.rachir@elantechnologies.com>
* @copyright  2012 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');

$title_text = "";
$payment_mode ="";
	

$title_text = $this->translate->_('Cash Invoice') ;

if($this->paymentdata['typecode'] == 1) // Payment done by check
{
	$payment_mode = $this->translate->_('CHEQUE') ;
}
else // i.e. payment done by cash
{
	$payment_mode = $this->translate->_('CASH') ;
}

?>
<!-- Payment Details -->
<fieldset class="margin_left_0 margin_right_0">
	<legend><?php echo $title_text;?></legend>
	<div class="_100">
		<label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Invoice Amount').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1 margin_top_12">
			<b><?php echo number_format($this->formdata['totalinvoiceamount'],$this->decimalplaces); ?></b>
		</div>
		<label class="_25_1 label_text_align margin_top_12">
		    <?php echo $this->translate->_('Payment Mode').''.$this->colan;?>
		</label>
		<div class="_25_1  margin_top_12">
		    <b><?php echo $payment_mode;?></b>
		</div>
	</div>	
	<?php if($this->paymentdata['typecode'] == 0) // i.e. payment done by cash
	{	
	?>
	
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Amount Paid').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_12">
			<b><?php echo number_format($this->paymentdata['amount'],$this->decimalplaces); ?></b>
	    </div>
	    <?php if($this->formdata['totalinvoiceamount'] > $this->paymentdata['amount']){
		$outstanding_amount = 	$this->formdata['totalinvoiceamount'] - $this->paymentdata['amount'] ;
	     ?>
		<label class="_25_1 label_text_align margin_top_12">
			<?php echo $this->translate->_('Outstanding Amount').''.$this->colan;?>
		</label>
		<div class="_25_1 margin_right_1 margin_top_12">
			<b><?php echo number_format($outstanding_amount,$this->decimalplaces); ?></b>
	        </div>
	    <?php } ?>
	</div>
	<?php }else{ // Payment done by check ?>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Cheque No').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_12">
			<b><?php echo $this->paymentdata['checknumber']; ?></b>
	    </div>
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_12">
			<b><?php echo number_format($this->paymentdata['amount'],$this->decimalplaces); ?></b>
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Cheque Date').''.$this->colan;?>
	    </label>
	    <label class="_25_1  margin_top_12 margin_right_1">
			<b><?php echo date('d-m-Y',strtotime($this->paymentdata['checkdate'])); ?></b>
	    </label>
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Bank Name').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_12">
			<b><?php echo $this->paymentdata['bankname']; ?></b>
	    </div>
	</div>
	<?php  if($this->formdata['totalinvoiceamount'] > $this->paymentdata['amount']){ 
		$outstanding_amount = 	$this->formdata['totalinvoiceamount'] - $this->paymentdata['amount'] ;
	?>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Outstanding Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_12">
			<b><?php echo number_format($outstanding_amount,$this->decimalplaces); ?></b>
	    </div>
	</div>    
	<?php } ?> 
	<?php } ?>
	
	
</fieldset>
<div class="clear space_20">&nbsp;</div>
<?php
/*
if($this->formdata['signaturedata']) { ?>
<!-- INCLUDE  FOR SIGNATURE -->
<script type="text/javascript">
$(document).ready(function () {
	
	var sig = <?php echo $this->formdata['signaturedata'];?>;


	$('.sigPad').signaturePad({displayOnly:true}).regenerate(sig);
});
</script>
<!--INCLUDE FOR SIGNATURE-->
<fieldset style="height:300px">
    <legend><?php echo $this->translate->_('Signature');?></legend>
    <div class="">
	<div class="_25_1">&nbsp;</div>
	<div class="_25_1">
		
		<div class="sigPad signed">
			<div class="sigWrapper">
			  <canvas class="pad" width="600" height="250"></canvas>
			</div>
		</div>
		
	</div>
    </div>
    <div class="_100 margin_top_20">&nbsp;</div>
</fieldset>
<div class="clear space_20">&nbsp;</div>
<?php }
*/
?>

<!--Following code added by nilesh on 7Mar2016-->
<div class="clear space_20">&nbsp;</div>
<?php if($this->formdata['signaturedata']) { ?>
<!-- INCLUDE FOR SIGNATURE -->

<script type="text/javascript">
$(document).ready(function () {
	
		//-----------------
		var canvas = document.getElementById('canvasImage');
		var ctx = canvas.getContext('2d');
		var img = document.createElement('IMG');

img.onload = function () {
    ctx.drawImage(img, 0, 0);
    canvas.addEventListener("mousedown", function(event) {
        canvas.toBlob(function(blob) {
           // saveAs(blob, "exported_image.png");
        }, "image/png");
    });
}

img.src ="<?php echo $this->formdata['signaturedata'];?>";
	//-----------------
	
	//var sig = <?php echo $this->formdata['signaturedata'];?>;

	//$('.sigPad').signaturePad({displayOnly:true}).regenerate(sig);

});
</script>
<!--INCLUDE FOR SIGNATURE-->
<fieldset style="height:300px">
    <legend><?php echo $this->translate->_('Signature');?></legend>
    <div class="">
	<div class="_25_1">&nbsp;</div>
	<div class="_25_1">
		<div class="sigPad signed">
			<div class="sigWrapper">
			 <!-- <canvas class="pad" width="600" height="250"></canvas>-->
			   <canvas class="pad" width="600" height="250" id="canvasImage"></canvas>
			  <!--<canvas class="pad" width="200" height="55"></canvas>-->
			</div>
		</div>
	</div>
    </div>
    <div class="_100 margin_top_20">&nbsp;</div>
</fieldset>
<div class="clear space_20">&nbsp;</div>
<?php } ?>