<div class="content with-actions ie_grid min_height_10">
<?php /*
<fieldset>
	    <legend ><?php echo $this->translate->_('Add Item').''.$this->colan;?></legend>

	    <div class="_100 margin_bottom_10">
		<div class="_35">&nbsp;</div>
		<label class="_15_2 margin_top_12 label_text_align">
		    <?php echo $this->translate->_('Item').$this->required;?>
		</label>

		<div class="_25 margin_left_1 margin_right_1">
		    <select id="ddlitem" name="ddlitem" class="required" >
		    <option value="">--- Select ---</option>
		    <?php for($i=0;$i<count($this->item);$i++) { ?>
			    <option selected="selected" value="<?php echo $this->item[$i]['id'];?>"><?php echo $this->item[$i]['val'];?></option>
		    <?php if($i==25){ break; } } ?>
		</select>
		</div>
		<div class="_20">&nbsp;</div>
	    </div>

	    <div class="_100 margin_bottom_10">
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('UPC').''.$this->colan;?>
		</label>
		<div class="_10_2">
		    <input type="text" id="txt_upc" name="txt_upc" value="24"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Item Code').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1" >
		    <input type="text" id="txt_item_code" name="txt_item_code" value="31"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Item Description').''.$this->colan;?>
		</label>
		<div class="_25 margin_right_1">
		    <input type="text" id="txt_item_description" name="txt_item_description" value="CHIFFERINI 24X500G"  class="margin_top_3">
		</div>

	    </div>
	    <div class="_100 margin_bottom_10">
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Price (Sale)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_price_sale" name="txt_price_sale" value="3.96"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Price (Return)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_price_return" name="txt_price_return" value="3.96"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Sales (Cases)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_sales_case" name="txt_sales_case" value="1"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Sales (Pieces)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_sales_pieces" name="txt_sales_pieces" value="2"  class="margin_top_3">
		</div>
	    </div>

	    <div class="_100 margin_bottom_10">
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Expiry (Cases)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_expirey_case" name="txt_expirey_case" value="2"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Expiry (Pieces)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_expirey_pieces" name="txt_expirey_pieces" value="1"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('BuyBack (Cases)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_buyback_cases" name="txt_buyback_cases" value="1"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('BuyBack (Pieces)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_buyback_pieces" name="txt_buyback_pieces" value="2"  class="margin_top_3">
		</div>
	    </div>

	    <div class="_100 margin_bottom_10">
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('FreeGood (Cases)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_freegood_cases" name="txt_freegood_cases" value="1"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('FreeGood (Pieces)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_freegood_pieces" name="txt_freegood_pieces" value="2"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Promotion (Cases)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_promotion_cases" name="txt_promotion_cases" value="3"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Promotion (Pieces)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_promotion_pieces" name="txt_promotion_pieces" value="2"  class="margin_top_3">
		</div>
	    </div>

	    <div class="_100 margin_bottom_10" >
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Damage (Cases)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_damage_cases" name="txt_damage_cases" value="4"  class="margin_top_3">
		</div>
		<label class="_15_3 margin_top_10 label_text_align">
		    <?php echo $this->translate->_('Damage (Pieces)').''.$this->colan;?>
		</label>
		<div class="_10_2 margin_right_1">
		    <input type="text" id="txt_damage_pieces" name="txt_damage_pieces" value="1"  class="margin_top_3">
		</div>

	    </div>

	</fieldset>
*/ ?>
	<div class="clear"></div>
	<div id="loader"></div>
	<div class="_100" id="item-grid"></div>
</div>