<?php
/**
* @name       viewdamageret.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$title = 'Sales';
?>
<script>
$(document).ready(function() {
	loaddata_popup('<?php echo $this->itemgrid; ?>/key1/15','item-grid');
	$('#ddltrantyppe').change(function() {
		var val = this.value;
		$('.ttl').html($("#ddltrantyppe option:selected").text());
		loaddata_popup('<?php echo $this->itemgrid; ?>/key1/'+val,'item-grid');		
	})	
})
</script>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="hhctransaction_loadtransfer_viewdamageret">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_10"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
        <h3><?php echo $this->translate->_('Batch Detail')?></h3>
    </div>
    <div class="_50_3">
		<div class="_10 save_btn">&nbsp;</div>
		<div class="_10 save_btn">&nbsp;</div>
    </div>
</div>
<div class="content with-actions ie_grid min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
		<label class="_25_1 margin_top_12 label_text_align">
				<?php echo $this->translate->_('Transaction Type').''.$this->colan;?>
		</label>
		<div class="_40">
			<select id="ddltrantyppe" name="ddltrantyppe" class="required">
				<option value="15"><?php echo $this->translate->_('Sales');?></option>
				<option value="16"><?php echo $this->translate->_('Free');?></option>
				<option value="17"><?php echo $this->translate->_('PromoFree');?></option>
				<option value="18"><?php echo $this->translate->_('Good Return');?></option>
				<option value="19"><?php echo $this->translate->_('Buy Back Free');?></option>
				<option value="20"><?php echo $this->translate->_('Damage');?></option>
				<option value="21"><?php echo $this->translate->_('Expiry');?></option>
				<option value="22"><?php echo $this->translate->_('Rental');?></option>
			</select>
		</div>
	</div>
	<div class="_100 space_20">&nbsp;</div>
	<fieldset class="fieldset_effect">
		<legend class="ttl" ><?php echo $this->translate->_($title);?></legend>
		<hr id="ie_hr" >
		<div id="loader"></div>
	    <div class="_100" id="item-grid"></div>
	</fieldset>
</div>
</form>
</div> <!-- End of .box -->
</div>