<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Cash Description
*/
	    $this->translate = Zend_Registry::get('Zend_Translate');

?>
<style>
.table1{ border:1px solid #EEEEEE}
.table1 th{ color:#164A7E;padding:6px; background:#EEEEEE}
.table1 td{ border:1px solid #EEEEEE; padding:6px; vertical-align:middle}
</style>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="merchandize_index_addlookupindex">
<form id="frmbatch" name="frmbatch" class="validate" method="post" action="" novalidate="novalidate" >
	<input type="hidden" id="hdnid1" name="hdnid1" value="<?php echo $this->params["edit"]=="yes"?$this->params["trankey"]:0; ?>">
    <input type="hidden" id="defkey" name="defkey" value="<?php echo $this->defkey; ?>">
    <div class="header">
	<div class="_50_3 back_btn">
	    <img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
	    <h3><?php echo $this->translate->_('Available Quantity');?></h3>
	</div>
	
    </div>    
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100">
	     <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Item code').''.$this->colan;?>
	    </label>
	    <div class="_45 margin_right_1" >
		<input type="text" id="txt_item_code" name="txt_item_code" readonly="readonly" value="<?php echo $this->result[0]['new_item_code'];?>">
	    </div>
	</div>
        <div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Item Name').''.$this->colan;?>
	    </label>
	    <div class="_45 margin_right_1">
		<input type="text" id="txt_item_name" name="txt_item_name" readonly="readonly" value="<?php echo $this->result[0]['item_name'];?>">
	    </div>
	   
        </div>
         <div class="_100">
	    <label class="_25_1 label_text_align margin_top_12" >
		<?php echo $this->translate->_('Enter Quantity').''.$this->colan;?>
	    </label>
	    <div class="_45 margin_right_1">
		<input type="text" id="txt_enter_quantity" name="txt_enter_quantity" readonly="readonly" value="<?php echo $this->params['salesqty'];?>" >
	    </div>
        </div>
	
         <div class="clear space_20"></div>
     
            <div id="error_message" style="color:red">
           
                
            </div>
     <input type="hidden" name="allow_qty" value="0" id="allow_qty" />
        <div>
            <table id="table-example" class="table1" width="100%" cellpadding="2">
                    <thead>
                            <tr>
                                    <th>Batch Number</th>
                                    <th>Expiry Date</th>
                                    <th>Case</th>
                                    <th>PCS</th>
                                    <th>Unit</th>
                                    <!--<th>QTY</th>-->
                                    <th></th>
                                   
                            </tr>
                    </thead>
                    <tbody>
			<?php
			if(!empty($this->result))
			{
                             $final_amount = $this->params['salesqty'];
				foreach($this->result as $value)
				{
                                   
                                    if($final_amount > 0 )
                                    {
                                        $avilable_qty = $final_amount -  $value['quantity'];
                                        
                                        
                                        if($avilable_qty > 0 )
                                        {
                                         
                                            $quantity = $value['quantity'];
                                             $final_amount =  $final_amount -  $value['quantity'];
                                             
                                        }
                                        else
                                        {
                                            $quantity = $final_amount;
                                             $final_amount =  0;
                                        }
                                       
                                    }
                                    else
                                    {
                                        $quantity = 0;
                                    }
                                    if($quantity < 0)
                                    $quantity  =0;
                                    ?>
				
				 <tr class="gradeX">
                                    <td><?php  echo $value['batchnumber']; ?>
                                    <input type="hidden" name="batchnumber[]" value="<?php echo $value['batchnumber'];?>" />
                                    <input type="hidden" name="batchdetailkey[]" value="<?php echo $value['batchdetailkey'];?>" />
                                     <input type="hidden" name="itemcode[]" value="<?php echo $value['itemcode'];?>" />
                                    </td>
                                    <td><?php echo $value['expirydate'];?>
                                    <input type="hidden" name="expirydate[]" value="<?php echo $value['expirydate'];?>" />
                                    <input type="hidden" name="expirydate1[]" value="<?php echo $value['expirydate1'];?>" />
                                    </td>
                                    <td><?php echo $value['case_qty'];?></td>
                                    <td><?php echo $value['pcs_qty'];?></td>
                                    <td><?php echo $value['upc'];?></td>
                                 <!--   <td><?php //echo $value['quantity'];?> -->
                                    <input type="hidden" name="quantity[]" value="<?php echo $value['quantity'];?>" />
                                    </td>
                                    <?php if($this->result1[0]['enablebatchselection'] == 1 ){ ?>
                                    <td>
                                        <input type="text" id="<?php echo $value['batchnumber']; ?>"
                                               onkeypress="this.value = this.value.replace(/[^0-9\.]/g,'');"
                                                onblur="check_quantity('<?php echo $value['batchnumber']; ?>','<?php  echo $value['quantity']; ?>',this.value)"
                                               name="avail_qty[]" class="clas invoice_qty_width_67" value="<?php echo $quantity?>" /></td>
                                    <?php }else{ ?>
                                    <td>
                                        <input type="text" name="avail_qty[]" class="clas invoice_qty_width_67" value="<?php echo $quantity?>" readonly="readonly" /></td>
                                    <?php } ?>
				</tr>	
				<?php
				}
				
			}
			
			?>
                           
                           
                            
                    </tbody>
            </table>
            
        </div>
        <?php if( $final_amount > 0) {  ?>
        <script>
        $("#error_message").html("Enter Qty IS not Available");
        $("#allow_qty").val(1);
        </script>
    
    <?php } ?>
   
	<div class="_100 space_20">&nbsp;</div>
        <div class="_100">
	  
           <div style="float:right"><input type="button" name="btn_cancel" id="btn_cancel" value="Cancel" /></div>
            <div style="float:right">&nbsp;&nbsp;</div>
             <?php if( $final_amount > 0) {  ?>
            
            <?php }else{?>
            <div style="float:right"><input type="button"  name="btn_save"  id="btn_save" value="Save" /></div>
            <?php } ?>
	   
	   
	   
	</div>
        <div class="_100 space_20">&nbsp;</div>

    </div>
	
         
	 </form>

</div>
</div> <!-- End of .box -->
<script type="text/javascript">
var ajax_page_URL = base_url+"/hhctransaction/ajaxdata/";
$(window).load(function()
{
	
    parent.eval('$(".pp_close").attr("href","<?php echo $url; ?>")');
    
    $("#btn_cancel").click(function(){
        $.post(ajax_page_URL+"addbatchcancel/", $("#frmbatch").serialize(), function(data) {
           parent.eval('$.prettyPhoto.close()');
         });    
    });
    
     $("#btn_save").click(function(){
        $.post(ajax_page_URL+"addbatch/", $("#frmbatch").serialize(), function(data) {
           parent.eval('$.prettyPhoto.close()');
         });
    });
   
});
//$(document).ready(function() {
//    
//    function check_quantity(batchnumber,quantity,entrtquantity)
//    {
//        entrtquantity = entrtquantity.replace(/[^0-9\.]/g,'');
//        if(entrtquantity > quantity)
//        {
//            $("#"+batchnumber).val(0);
//        }
//    }
//
//});

function check_quantity(batchnumber,quantity,entrtquantity)
{
    entrtquantity = entrtquantity.replace(/[^0-9\.]/g,'');    
    if(entrtquantity > quantity) {
        $("#"+batchnumber).val(0);
    }
    //var date = new Date();
    //date.setTime(date.getTime()+(7*24*60*60*1000));
    //var expires = "; expires="+date.toGMTString();
    //var cookieValue = 'js';
    //var cookieName = 'available_qty';
    //document.cookie = cookieName+"="+cookieValue+expires+"; path=/";		
    
}


</script>