<input type="hidden" name="customer_payment_terms" id="customer_payment_terms" value="<?php echo $this->result['invoice_paynent_terms']?>" />
<input type="hidden" name="enforce_promotion" id="enforce_promotion" value="<?php echo $this->result['enforcepromotion']?>" />
<input type="hidden" name="customer_creditlimit" id="customer_creditlimit" value="<?php echo $this->result['customer_credit_limit']?>" />
<input type="hidden" name="Enable_Signature_Capture" id="Enable_Signature_Capture" value="<?php echo $this->result['Enable_Signature_Capture']?>" />
<input type="hidden" name="Enable_Good_Returns" id="Enable_Good_Returns" value="<?php echo $this->result['Enable_Good_Returns']?>" />
<input type="hidden" name="Enable_Free" id="Enable_Free" value="<?php echo $this->result['Enable_Free']?>" />
<input type="hidden" name="Enable_Rental" id="Enable_Rental" value="<?php echo $this->result['Enable_Rental']?>" />
<input type="hidden" name="Enable_Sales" id="Enable_Sales" value="<?php echo $this->result['Enable_Sales']?>" />
<input type="hidden" name="Enable_Damage_Returns" id="Enable_Damage_Returns" value="<?php echo $this->result['Enable_Damage_Returns']?>" />
<input type="hidden" name="Enable_invoice_comment" id="Enable_invoice_comment" value="<?php echo $this->result['Enable_invoice_comment']?>" />
<input type="hidden" name="Enable_Buy_Back_Free" id="Enable_Buy_Back_Free" value="<?php echo $this->result['Enable_Buy_Back_Free']?>" />
<input type="hidden" name="Enable_Sales_Promotion" id="Enable_Sales_Promotion" value="<?php echo $this->result['Enable_Sales_Promotion']?>" />
<input type="hidden" name="Enable_Order_Promotion" id="Enable_Order_Promotion" value="<?php echo $this->result['Enable_Order_Promotion']?>" />
<input type="hidden" name="Enable_Edit_Price_Invs" id="Enable_Edit_Price_Invs" value="<?php echo $this->result['Enable_Edit_Price_Invs']?>" />

<!--- Add invoiceRecord -->
 <input type="hidden" name="addinvoice_customer_payment_terms_text" id="addinvoice_customer_payment_terms_text"
        value="<?php echo $this->result['invoice_paynent_terms_text']?>" />
<input type="hidden" name="addinvoice_txt_customer_credit_day" id="addinvoice_txt_customer_credit_day"
       value="<?php echo $this->result['customer_credit_day']?>" />
<input type="hidden" name="addinvoice_txt_customer_address" id="addinvoice_txt_customer_address"
         value="<?php echo $this->result['customer_address']?>" />