<style>
#invoice_det1 td { font-size:10px;}
#invoice_det1 th { font-size:10px;}
</style>
<table cellpadding="0" cellspacing="0" border="0" id="invoice_det1">
    <tr>
        <th> Item Description </th>
        <th colspan="2"> Sales </th>
        <th colspan="2"> Free </th>
        <th colspan="2"> Return </th>
        <th colspan="2"> BuyBack </th>
        <th colspan="2"> Damage  </th>
        <th colspan="2"> Expiry  </th>
        <th colspan="2"> Rental   </th>
        <th colspan="2"> Promotion Free Qty  </th>
       
    </tr>
     <tr>
        <th> &nbsp;</th>
        <th > OUT</th>
        <th > PCS</th>
        <th > OUT</th>
        <th > PCS</th>
        <th > OUT</th>
        <th > PCS</th>
        <th > OUT</th>
        <th > PCS</th>
        <th > OUT</th>
        <th > PCS</th>
        <th > OUT</th>
        <th > PCS</th>
        <th > OUT</th>
        <th > PCS</th>
        <th > OUT</th>
        <th > PCS</th>
        
    </tr>
    <?php
    if(!empty($this->result))
    {
        foreach($this->result as $value)
        {
        ?>
                <tr>
                     <td><?php echo $value['itemshortdescription'];?></td>
                     <td><?php echo $value['case_sales_qty'];?></td>
                     <td><?php echo $value['pcs_sales_qty'];?></td>
                     <td><?php echo $value['case_free_qty'];?></td>
                     <td><?php echo $value['pcs_free_qty'];?></td>
                     <td><?php echo $value['case_return_qty'];?></td>
                     <td><?php echo $value['pcs_return_qty'];?></td>
                     <td><?php echo $value['case_buyback_qty'];?></td>
                     <td><?php echo $value['pcs_buyback_qty'];?></td>
                     <td><?php echo $value['case_damage_qty'];?></td>
                     <td><?php echo $value['pcs_damage_qty'];?></td>
                     <td><?php echo $value['case_expiry_qty'];?></td>
                     <td><?php echo $value['pcs_expiry_qty'];?></td>
                     <td><?php echo $value['case_rental_qty'];?></td>
                     <td><?php echo $value['pcs_rental_qty'];?></td>
                      <td><?php echo $value['case_promo_free_qty'];?></td>
                     <td><?php echo $value['pcs_promo_free_qty'];?></td>
                     
                     

                </tr>
       
<?php
        }
    }
    ?>
</table>

<input type="hidden" name="summery_fianl_total_discount" id="summery_fianl_total_discount" value="<?php echo $this->result1[0]['totaldiscount'];?>" />
<input type="hidden" name="customer_final_non_tc_amount" id="customer_final_non_tc_amount" value="<?php echo number_format($this->result2[0]['non_tc_amount'],$this->decimalplaces); ?>" />