<div id ="promotion2_<?php echo $this->plan_number ?>" class="promo">
<div class="content with-actions ie_grid min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>

	<div class="_100">
	    <label class="_15 label_text_align margin_top_12">
		<?php echo $this->translate->_('Promotion  Key').''.$this->colan;?>
	    </label>
	    <div class="_20 margin_left_1">
		<input type="text" id="txt_promo_key2" name="txt_promo_key2" readonly="readonly" value="<?php echo $this->final_arr[2][$this->plan_number][0]['promotionplannumber'];?>">
	    </div>
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Promotion Description').''.$this->colan;?>
	    </label>
	    <div class="_35_1 margin_left_1">
		<input type="text" id="txt_promo_desc2" name="txt_promo_desc2" readonly="readonly"  value="<?php echo $this->final_arr[2][$this->plan_number][0]['plandescription'];?>">
            </div>

	</div>
	<div class="_100">&nbsp;
	</div>
	<fieldset>
	    <legend>Item</legend>
	    <div class="_100">&nbsp;</div>
	<div>
	     <table id="table-example" class="table">
                    <thead>
                            <tr>
                                    <th>Item Code</th>
                                    <th>Item Description</th>
				    <th style="width:12px">Type</th>
                                    <th>Old</th>
				    <th>New</th>
                                   
                            </tr>
                    </thead>
                    <tbody>
                        
                        <?php
                        foreach($this->final_arr[2][$this->plan_number] as $value)
                        {
				//echo $this->new_amount." + ".$value['promotionamount']."<br/>";    
                           if($value['itemtransactiontype'] == 2 )
				{
					//echo $this->new_amount." + ".$value['promotionamount']."<br/>";  
						$this->new_amount =$this->new_amount + $value['promotionamount'];
				}
				else
				{	//echo $this->new_amount." - ".$value['promotionamount']."<br/>";  
						$this->new_amount =$this->new_amount - $value['promotionamount'];	
				}
                            ?>
                            
                            <tr class="gradeX">
                                    <td><?php echo $value['new_item_code'];?></td>
                                    <td><?php echo $value['item_desc'];?></td>
				     <td style="text-align:center"><?php echo ($value['itemtransactiontype'] ==2 ) ? 'R' : 'S';?></td>
                                    <td style="text-align:right"><?php echo number_format($value['oldpromotionamount'],$this->decimalplaces);?> </td>
				     <td style="text-align:right"><?php echo number_format($value['salesamount'],$this->decimalplaces);?></td>
                                    
                            </tr>
                            
                        <?php }
                        
                        ?>
                            
                          
                          
                            
                    </tbody>
            </table>
	    <div class="clear"></div>
       
        
	</div>
	<div class="clear space_20"></div>
	<div class="_100">
	    <label class="_20 label_text_align margin_top_12">
		<?php echo $this->translate->_('Current Invoice Amount').''.$this->colan;?>
	    </label>
	    <div class="_20_1 margin_left_1">
		<input type="text" id="txt_invoice_amount2" name="txt_invoice_amount2" readonly="readonly" value="<?php echo number_format($this->final_amount,$this->decimalplaces); ?>" class="number amount_text_align">
	    </div>
	    <label class="_20 label_text_align margin_top_12">
		<?php echo $this->translate->_('New Invoice Amount').''.$this->colan;?>
	    </label>
	    <div class="_20_1 margin_left_1">
		<input type="text" id="txt_invoice_amount2" name="txt_invoice_amount2" readonly="readonly" value="<?php echo number_format($this->new_amount,$this->decimalplaces); ?>" class="number amount_text_align">
	    </div>
	</div>
	<div class="clear space_20"></div>
		<div class="_100">
			<?php if($this->next !='_') {?>
				<div style="float:right"><input type="button" onclick="shownext('<?php echo $this->next;?>')" name="btn_next_promotion_overview2"  id="btn_next_promotion_overview" value="Next" /></div>
			<?php } ?>
				<div style="float:right">&nbsp;&nbsp;</div>
		   <?php if($this->previous !='') { ?>
				<div style="float:right"><input type="button" onclick="shownext('<?php echo $this->previous;?>')" name="btn_prev_promotion_overview2" id="btn_prev_promotion_overview" value="Previous" /></div>
		   <?php } ?>
		</div>
	</fieldset>        
</div>
<?php
$this->final_amount = $this->new_amount;
?>
</div>