<div id ="promotion5_<?php echo $this->plan_number ?>" class="promo">
<div class="content with-actions ie_grid min_height_10">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
    <fieldset>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Promotion  Key').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_left_5">
		<input type="text" id="txt_promo_key5" name="txt_promo_key5" readonly="readonly" value="<?php echo $this->final_arr[5][$this->plan_number][0]['promotionplannumber'];?>">
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Promotion Description').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_left_5">
		<input type="text" id="txt_promo_desc5" name="txt_promo_desc5" readonly="readonly"  value="<?php echo $this->final_arr[5][$this->plan_number][0]['plandescription'];?>">
            </div>

	</div>
	<?php

		foreach($this->final_arr[5][$this->plan_number] as $value)
		{
		?>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Type').''.$this->colan;?>
	    </label>
	    <label class="_25_1 margin_left_5 margin_top_10">
		<?php echo ($value['itemtransactiontype'] ==2 ) ? 'Return' : 'Sales';?>
	    </label>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Current Invoice Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_left_5">
		<input type="text" id="txt_invoice_amount5" name="txt_invoice_amount5" readonly="readonly" value="<?php echo number_format($this->final_amount,$this->decimalplaces); ?>" class="number amount_text_align">
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Qualified Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_left_5">
		<input type="text" id="txt_qualified_amount5" name="txt_qualified_amount5" readonly="readonly" value="<?php echo number_format($value['salesamount'],$this->decimalplaces); ?>" class="number amount_text_align">
	    </div>
	</div>
	<div class="_100">
             <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('Applied Promotion').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_left_5">
		<input type="text" id="txt_invoice_amount_per5" readonly="readonly" name="txt_invoice_amount_per5" value="<?php echo number_format($value['promotionper'],$this->decimalplaces); ?>" style=" float:left;width:23%">
		<input type="text" id="txt_invoice_amount5"  readonly="readonly" name="txt_invoice_amount5" value="<?php echo number_format($value['promotionamount'],$this->decimalplaces); ?>" style=" float:right;width:64%;margin-right:-4px" class="number amount_text_align">
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
		<?php echo $this->translate->_('New Invoice Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_left_5">
		<?php
		
		if($value['itemtransactiontype'] == 2 )
				$this->new_amount = ($this->new_amount + $value['promotionamount']);
				else
                               $this->new_amount = ($this->new_amount - $value['promotionamount']);
				
		$this->final_amount = $this->new_amount;
		?>
		<input type="text" id="txt_new_invoice_amount5" readonly="readonly" name="txt_new_invoice_amount5" value="<?php echo number_format($this->new_amount,$this->decimalplaces);?>" class="number amount_text_align">
	    </div>
	</div>
	
	<?php } ?>
        <div class="clear space_20"></div>
       
         <div class="_100">
			<?php if($this->next !='_') {?>
				<div style="float:right"><input type="button" onclick="shownext('<?php echo $this->next;?>')" name="btn_next_promotion_overview5"  id="btn_next_promotion_overview" value="Next" /></div>
			<?php } ?>	
				<div style="float:right">&nbsp;&nbsp;</div>
			<?php if($this->previous !='') {?>
				<div style="float:right"><input type="button" onclick="shownext('<?php echo $this->previous;?>')" name="btn_prev_promotion_overview5" id="btn_prev_promotion_overview" value="Previous" /></div>
			<?php } ?>	
	</div>
         </fieldset>
        
</div>
<?php

?>
</div>