<?php
/**
* @name       adddevice.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Country Details
*/

$this->translate = Zend_Registry::get('Zend_Translate');

?>
<script type="text/javascript">
    $(document).ready(function(){		
		$("#deviceid").focus();
    });
function filluseraccessgrid(access_val,user_name)
{
	$('#item-grid').html('');
	var  url = '<?php echo $this->itemgrid; ?>'+'/key/'+access_val+'/key1/'+user_name;
	$.ajax({
		url:url,
		data:$("#userform").serialize(),
		type:'post',
		beforeSend: function() {
			$("#loader").html("<img src='"+base_url+"/public/images/ajax-loader-bar.gif' alt='Loading..' />");	    
		},
		success:function(returndata){
			$('#item-grid').html(returndata);
			$("#loader").html('');
		}
	});	
}
</script>

<div class="clean"></div>
<div class="grid_12">
<div class="box" id="admin_security_adduser">
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<form id="userform" method="post" action="" class="validate" novalidate="novalidate" autocomplete="off">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_administration.png">
	<h3><?php echo $this->translate->_('Device Registration');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"deviceregistration"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li>
		    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"deviceregistration"),"default", true);?>"><?php echo $this->overview;?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"adddevice"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
    <div class="_100">
        <div class="clean"></div>
    </div>
    
    <div class="_100">
         <label class="_36 margin_top_12 label_text_align">
            <?php echo $this->translate->_('Device ID').''.$this->required;?>
        </label>
        <div class="_50 margin_right_1">
            <input name="deviceid" id="deviceid" type="text"  class="required text_align" value="<?php echo $this->formdata['deviceid']; ?>">
        </div>
    </div>
    <div class="_100">
         <label class="_36 margin_top_12 label_text_align">
            <?php echo $this->translate->_('Remarks').''.$this->required;?>
        </label>
        <div class="_50 margin_right_1">
            <input name="companyid" id="companyid" type="text"  class="required text_align" value="<?php echo $this->formdata['companyid']; ?>">
        </div>
    </div>
    <div class="clear"></div>
    <div class="_100">
	 <label class="_36 margin_top_10 label_text_align">&nbsp;</label>
	 <div id="loader">&nbsp;</div>
	 <div class="_60" id="item-grid" style="overflow-y:auto;height:250px;">
		&nbsp;
	 </div>
    </div>	
</div>
<div class="clear space_20">&nbsp;</div>
</form>
</div>
</div> <!-- End of .box -->