<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Country Details
*/

$this->translate = Zend_Registry::get('Zend_Translate');

?>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="admin_security_addusertype">
<form class="validate" method="post" action="" novalidate="novalidate">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_administration.png">
	<h3><?php echo $this->translate->_('User Type');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"usertype"),"default", true);?>')">
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
	<li class="current">
	    <ul style="display: block;">
		<li>
		    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"usertype"),"default", true);?>"><?php echo $this->overview;?></a>
		</li>
		<li class="last-child">
		    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"addusertype"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		</li>
	    </ul>
	</li>
    </ul>
</div>
</div>
<div class="content no-padding with-actions">
    <div class="_100">
        <div class="clean"></div>
    </div>
    <div class="_100">
         <label class="_36 margin_top_12 label_text_align">
            <?php echo $this->translate->_('Code').''.$this->required;?>
        </label>
        <div class="_50 margin_right_1">
            <input name="txtcode" id="txtcode" type="text" readonly="readonly" class="required text_align" value="<?php echo $this->formdata['txtcode']; ?>">
        </div>
    </div>
    <div class="_100">
         <label class="_36 margin_top_12 label_text_align">
            <?php echo $this->translate->_('Name').''.$this->required;?>
        </label>
        <div class="_50 margin_right_1">
            <input name="txtname" id="txtname" type="text" class="required margin_top_5" value="<?php echo $this->formdata['user_type']; ?>" />
        </div>
        <div class="_100">
            <label class="_36 margin_top_12 label_text_align">
                <?php echo $this->translate->_('Status').''.$this->colan;?>
            </label>
            <div class="_50 margin_right_1">
                <select id="ddlstatus" name="ddlstatus">
                <option <?php echo '1' == $this->formdata['ddlstatus'] ? 'selected' : ''; ?> value="1"><?php echo $this->translate->_('Active');?></option>
                <option <?php echo '0' == $this->formdata['ddlstatus'] ? 'selected' : ''; ?> value="0"><?php echo $this->translate->_('Inactive');?></option>
                </select>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</form>
</div>
</div> <!-- End of .box -->