<?php $this->translate = Zend_Registry::get('Zend_Translate'); ?>
 
<thead>
    <tr>
        <tr>
            <th width="25%"><a href="javascript:void(0)"><?php echo $this->translate->_('Module')?></a></th>
            <th width="35%"><a href="javascript:void(0)"><?php echo $this->translate->_('Form')?></a></th>
            <th width="10%"><a href="javascript:void(0)"><?php echo $this->translate->_('Read')?></a></th>
            <th width="10%"><a href="javascript:void(0)"><?php echo $this->translate->_('Write')?></a></th>
            <th width="10%"><a href="javascript:void(0)"><?php echo $this->translate->_('Delete')?></a></th>
            <th width="10%"><a href="javascript:void(0)"><?php echo $this->translate->_('All')?></a></th>
        </tr>
    </tr>
</thead>
<tbody>
    <?php
        $modulename = '';
        for($i=0;$i<count($this->form_data);$i++) {
            $css = $i%2 == 0 ? 'gradeC' : 'gradeA';
            $class = str_replace(" ","",$this->form_data[$i]['modulename'].$this->form_data[$i]['formname']);
    ?>
        <tr class="<?php echo $css?>">
            <td><?php echo ($modulename != $this->form_data[$i]['modulename']) ? $this->form_data[$i]['modulename'] : ''; ?></td>
            <td><?php echo $this->form_data[$i]['formname'];?></td>
            <td><input class="checkbox <?php echo $class;?> rwd" type="checkbox" name="read_chk[]" id="<?php echo $class;?>_r" onclick="toggleUnChecked(this.checked,this.value)" checked="checked" value="<?php echo $this->form_data[$i]['moduleid']."_".$this->form_data[$i]['formid'];?>" /></td>
            <td><input class="checkbox <?php echo $class;?> rwd" type="checkbox" name="write_chk[]" id="<?php echo $class;?>_w" onclick="toggleUnChecked(this.checked,this.value)" checked="checked" value="<?php echo $this->form_data[$i]['moduleid']."_".$this->form_data[$i]['formid'];?>" /></td>
            <td><input class="checkbox <?php echo $class;?> rwd" type="checkbox" name="delete_chk[]" id="<?php echo $class;?>_d" onclick="toggleUnChecked(this.checked,this.value)" value="<?php echo $this->form_data[$i]['moduleid']."_".$this->form_data[$i]['formid'];?>" /></td>
            <td><input class="checkbox all777" type="checkbox" name="all_chk[]" id="<?php echo $class;?>_a" onclick="toggleUnChecked(this.checked,this.value)" value="<?php echo $this->form_data[$i]['moduleid']."_".$this->form_data[$i]['formid'];?>" /></td>
        </tr>
    <?php
            $modulename = $this->form_data[$i]['modulename'];
        }
    ?>
</tbody>
