<?php
/**
* @name       arrangecustomer.phtml
* @since      27 Feb, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* give user permission
*/

$this->translate = Zend_Registry::get('Zend_Translate');
$child_combo = $this->url(array("module"=>"admin","controller"=>"security","action"=>"getuserandusertype"),"default", true);
$search_user_usertype_combo = $this->url(array("module"=>"admin","controller"=>"security","action"=>"searchfiltermodule"),"default", true);
?>
<script>

function toggleChecked(status) {
    
	//    if(status == true)
	//		    status = false;
	//	    else
	//		    status = true;
			    
	    $("#table-example .checkbox").each( function() {
		$(this).attr("checked",status);	    
	    });
    }
     
function toggleUnChecked(status,val) {
		var d = status;
		var tval = val;
		
		$('#chkall').attr("checked",false);
		
		var tmp_array = new Array();
		var tmp = 1;
		var j = '0';
		
		$("#table-example input:checkbox").each( function(e) {
			
			
			if(e>0 && tval!=this.value)
			{
				
				if(this.checked==false){
					tmp = 0;
				}
			}
		
		})
		if(d==true)
			tmp = 0;
		
		if(tmp == 1){
			$('#chkall').attr("checked",true);
		}
}

function allcheck(thisobj)
{
    var tid = thisobj.id;
    var xtid = tid.split("_");
    
	$('.'+xtid[0]).attr("checked",thisobj.checked);    
    
	if($('.rwd:checked').length==$('.rwd').length) {
		$('#chkallrows').attr("checked",true);
		$('.access').attr("checked",true);
	} else {
		$('#chkallrows').attr("checked",false);
		$('.access').attr("checked",false);
	}
}
function wrdcheck(thisobj)
{
    //var chid = thisobj.id;
    //var xchid = chid.split("_");
    //var mid = xchid[0];
    //
    //if(thisobj.checked && $('.'+mid+':checked').length==$('.'+ mid ).length)
    //{
    //    $('#'+mid+'_a').attr("checked",true);
    //}
    //else
    //{
    //    $('#'+mid+'_a').attr("checked",false);
    //}
    //
    //if($(".all777:checked").length==$(".all777").length)
    //{
    //    $('#chkallrows').attr("checked",true);
    //}
    //else
    //{
    //    $('#chkallrows').attr("checked",false);
    //}
	var chid = thisobj.id;
    var xchid = chid.split("_");
    var mid = xchid[0];		
	
	if($('#'+mid+'_r').is(':checked') && xchid[1] == 'r') {
		
		if($(".all777:checked").length!=$(".all777").length) {
			$('#read_access').attr("checked",false);
		}
		
		if($(".read_per:checked").length==($(".read_per").length)) {			
			$('#read_access').attr("checked",true);
			$('#'+mid+'_a').attr("checked",true);			
		} else {
			$('#read_access').attr("checked",false);
			$('#'+mid+'_a').attr("checked",false);			
		}
	} else if(xchid[1] == 'r') {		
		$('#read_access').attr("checked",false);
		$('#'+mid+'_a').attr("checked",false);
	}
	
	if($('#'+mid+'_w').is(':checked') && xchid[1] == 'w') {
			
		if($(".all777:checked").length!=$(".all777").length) {			
			$('#write_access').attr("checked",false);
		}
		
		if($(".write_per:checked").length==($(".write_per").length)) {			
			$('#write_access').attr("checked",true);
			$('#'+mid+'_a').attr("checked",true);			
		} else {
			$('#write_access').attr("checked",false);
			$('#'+mid+'_a').attr("checked",false);			
		}
	} else if(xchid[1] == 'w') {		
		$('#write_access').attr("checked",false);
		$('#'+mid+'_a').attr("checked",false);
	}
	
	if($('#'+mid+'_d').is(':checked') && xchid[1] == 'd') {
		
		if($(".all777:checked").length!=$(".all777").length) {
			$('#delete_access').attr("checked",false);
		}
		
		if($(".delete_per:checked").length==($(".delete_per").length)) {			
			$('#delete_access').attr("checked",true);
			$('#'+mid+'_a').attr("checked",true);			
		} else {
			$('#delete_access').attr("checked",false);
			$('#'+mid+'_a').attr("checked",false);			
		}
	} else if(xchid[1] == 'd') {		
		$('#delete_access').attr("checked",false);
		$('#'+mid+'_a').attr("checked",false);
	}
		
	if($('#'+mid+'_r').is(':checked') && $('#'+mid+'_w').is(':checked') && $('#'+mid+'_d').is(':checked')) {
		$('#'+mid+'_a').attr("checked",true);
	} else {
		$('#'+mid+'_a').attr("checked",false);
	}
	
	if($('.access:checked').length==$('.access').length) {
		$('#chkallrows').attr("checked",true);
	} else {
		$('#chkallrows').attr("checked",false);
	}
}

function changeuseracl(val)
{
    if(val != "")
    {
        var user_usertype = $('#ddlpermissionby').val();
        var url = '<?php echo $search_user_usertype_combo; ?>';
        url += "?searchval="+val+"&type="+user_usertype;
        
        $.blockUI();
        $.ajax({
            url:url,
            data:$("#frmomoduleverview").serialize(),
            type:'post',
            success:function(data) {
                $.unblockUI();
                $("#table-example").html(data);
                
                $('.all777').unbind('click').bind('click',function(){
                    allcheck(this);
                });
                $('.rwd').unbind('click').bind('click',function(){
                    wrdcheck(this);
                });
				
				if($('.rwd:checked').length==$('.rwd').length) {
					$('#chkallrows').attr("checked",true);
					$('.access').attr("checked",true);
				}
            }
        });
        $('#ddlchoose_hid').val(val);
    }
}

$(function(){
	$("select#ddlpermissionby").change(function(){
        if($(this).val() != "")
        {
            $.getJSON("<?php echo $child_combo;?>",{id: $(this).val()}, function(j){			
                $("#ddlchoose").html('');
                $('<option/>').val("").html("--- Select ---").appendTo('#ddlchoose');
                for (var i = 0; i < j.length; i++) {
                    $('<option/>').val(j[i].id).html(j[i]['val']).appendTo('#ddlchoose');
                }            
                $('select').trigger('liszt:updated');
            });
            $('#ddlpermissionby_hid').val($(this).val());
        }
	});
	
	// #########  NOTE : THE chzn CHECKBOXS BEHAVIOUR IS OPPOSITE. WHEN YOU CHECKED, IT RETURN FALSE IN this.checked  #######
	
	// when checked 'Select All Modules'
	$('#chkallmodule').click(function(){
		
		$('.moduleChks').attr("checked",this.checked);
	});
	
	// when click on any modules checkbox
	$('.moduleChks').click(function(){
		
		// if current is CHECKED & ALL other are checked - 
		if(this.checked && $(".moduleChks:checked").length==$(".moduleChks").length)
		{
			$('#chkallmodule').attr("checked",true);
		}
		else
		{
			$('#chkallmodule').attr("checked",false);
		}
		
	});
	
	// when click on any All permission checkbox
	$('.all777').click(function() {
		
		var tid = this.id;
		var xtid = tid.split("_");
		
		if($(".all777:checked").length==$(".all777").length-1) {
			$('#chkallrows').attr("checked",false);
			$('#read_access').attr("checked",false);
			$('#write_access').attr("checked",false);
			$('#delete_access').attr("checked",false);
			$('.'+xtid[0]).attr("checked",false);
		} else {
			$('#chkallrows').attr("checked",true);			
			$('#read_access').attr("checked",true);
			$('#write_access').attr("checked",true);
			$('#delete_access').attr("checked",true);
			$('.'+xtid[0]).attr("checked",true);
		}		
	});	
	
	$('.read_per').click(function() {
		
		var chid = this.id;
		var xchid = chid.split("_");
		var mid = xchid[0];		
		
		if(this.checked == true) {
			
			if($(".all777:checked").length==$(".all777").length) {
				$('#chkallrows').attr("checked",true);
			} else {
				$('#chkallrows').attr("checked",false);
				$('#read_access').attr("checked",false);
			}
			
			if($(".read_per:checked").length==($(".read_per").length)) {			
				$('#read_access').attr("checked",true);
				$('#'+mid+'_a').attr("checked",true);
				$('#chkallrows').attr("checked",true);
			} else {
				$('#read_access').attr("checked",false);
				$('#'+mid+'_a').attr("checked",false);
				$('#chkallrows').attr("checked",false);
			}
		} else {
			$('#chkallrows').attr("checked",false);
			$('#read_access').attr("checked",false);
			$('#'+mid+'_a').attr("checked",false);
		}
		
		if($('#'+mid+'_r').is(':checked') && $('#'+mid+'_w').is(':checked') && $('#'+mid+'_d').is(':checked')) {
			$('#'+mid+'_a').attr("checked",true);
		} else {
			$('#'+mid+'_a').attr("checked",false);
		}
	});
	
	$('.write_per').click(function(){
		var chid = this.id;
		var xchid = chid.split("_");
		var mid = xchid[0];
		
		
		if(this.checked == true) {
			
			if($(".all777:checked").length==$(".all777").length) {
				$('#chkallrows').attr("checked",true);
			} else {
				$('#chkallrows').attr("checked",false);
				$('#write_access').attr("checked",false);
			}
			
			if($(".write_per:checked").length==($(".write_per").length)) {			
				$('#write_access').attr("checked",true);
				$('#'+mid+'_a').attr("checked",true);
				$('#chkallrows').attr("checked",true);
			} else {
				$('#write_access').attr("checked",false);
				$('#'+mid+'_a').attr("checked",false);
				$('#chkallrows').attr("checked",false);
			}
		} else {
			$('#chkallrows').attr("checked",false);
			$('#write_access').attr("checked",false);
			$('#'+mid+'_a').attr("checked",false);
		}
		
		if($('#'+mid+'_r').is(':checked') && $('#'+mid+'_w').is(':checked') && $('#'+mid+'_d').is(':checked')) {
			$('#'+mid+'_a').attr("checked",true);
		} else {
			$('#'+mid+'_a').attr("checked",false);
		}
		
	});
	
	
	$('.delete_per').click(function(){
		var chid = this.id;
		var xchid = chid.split("_");
		var mid = xchid[0];
		
		if(this.checked == true) {
			
			if($(".all777:checked").length==$(".all777").length) {
				$('#chkallrows').attr("checked",true);
			} else {
				$('#chkallrows').attr("checked",false);
				$('#delete_access').attr("checked",false);
			}
			
			if($(".delete_per:checked").length==($(".delete_per").length)) {			
				$('#delete_access').attr("checked",true);
				$('#'+mid+'_a').attr("checked",true);
				$('#chkallrows').attr("checked",true);
			} else {
				$('#delete_access').attr("checked",false);
				$('#'+mid+'_a').attr("checked",false);
				$('#chkallrows').attr("checked",false);
			}
		} else {
			$('#chkallrows').attr("checked",false);
			$('#delete_access').attr("checked",false);
			$('#'+mid+'_a').attr("checked",false);
		}
		
		if($('#'+mid+'_r').is(':checked') && $('#'+mid+'_w').is(':checked') && $('#'+mid+'_d').is(':checked')) {
			$('#'+mid+'_a').attr("checked",true);
		} else {
			$('#'+mid+'_a').attr("checked",false);
		}
	});
	
	$('#btnpopulate').click(function() {
		
		if($('#frmomoduleverview_permission').valid()) {
			changeuseracl($('#ddlchoose').val())
		} else {
			return false;
		}
	});
    
    $('#btnsave').click(function() {
        
        if($("#frmomoduleverview_permission").valid()) {
            if($("#frmoverview").valid()) {
                $("#frmoverview").submit();
            }
        }
    });
})
function read_accessclick(thisobj) {	
	if(thisobj.checked) {
		$('#table-example input:checkbox.rwd').each(function() {			
			var chid = this.id;
			var xchid = chid.split("_");
			var mid = xchid[0];			
			$('#'+mid+'_r').attr("checked",true);
		});
	} else {
		$('#table-example input:checkbox.rwd').each(function() {			
			var chid = this.id;
			var xchid = chid.split("_");
			var mid = xchid[0];			
			$('#'+mid+'_r').attr("checked",false);
		});
	}
	
	if($(".access:checked").length==$(".access").length) {
		$('.all777').attr("checked",true);
		$('#chkallrows').attr("checked",true);
	} else {
		$('.all777').attr("checked",false);
		$('#chkallrows').attr("checked",false);
	}
}

function write_accessclick(thisobj) {	
	if(thisobj.checked) {
		$('#table-example input:checkbox.rwd').each(function() {			
			var chid = this.id;
			var xchid = chid.split("_");
			var mid = xchid[0];			
			$('#'+mid+'_w').attr("checked",true);
		});
	} else {
		$('#table-example input:checkbox.rwd').each(function() {			
			var chid = this.id;
			var xchid = chid.split("_");
			var mid = xchid[0];			
			$('#'+mid+'_w').attr("checked",false);
		});
	}
	if($(".access:checked").length==$(".access").length) {
		$('.all777').attr("checked",true);
		$('#chkallrows').attr("checked",true);
	} else {
		$('.all777').attr("checked",false);
		$('#chkallrows').attr("checked",false);
	}
}
function delete_accessclick(thisobj) {
	//alert(thisobj.checked);
	if(thisobj.checked) {
		$('#table-example input:checkbox.rwd').each(function() {
			var chid = this.id;
			var xchid = chid.split("_");
			var mid = xchid[0];
			$('#'+mid+'_d').attr("checked",true);
		});
	} else {
		$('#table-example input:checkbox.rwd').each(function() {
			var chid = this.id;
			var xchid = chid.split("_");
			var mid = xchid[0];
			$('#'+mid+'_d').attr("checked",false);
		});
	}
	if($(".access:checked").length==$(".access").length) {
		$('.all777').attr("checked",true);
		$('#chkallrows').attr("checked",true);
	} else {
		$('.all777').attr("checked",false);
		$('#chkallrows').attr("checked",false);
	}
}
</script>
<div class="clean"></div>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="grid_12">
<div class="box" id="admin_security_userpermission">

<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_4"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_administration.png">
	<h3><?php echo $this->translate->_('User Permission');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"admin","controller"=>"security","action"=>"user"),"default", true);?>')">
	</div>
    <?php if($this->checkaccess("update")) { ?>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    <?php } ?>
    </div>
    
</div>
    <div class="content with-actions" style="">
        
	<form name="frmomoduleverview_permission" id="frmomoduleverview_permission" class="validate" novalidate="novalidate" action="" method="post">
    <div class="_100">            
		<label class="_25_1 margin_top_10 label_text_align">
		   <?php echo $this->translate->_('Permission By').''.$this->required;?>
	   </label>
	   <div class="_25_1 margin_right_1">
		   <select id="ddlpermissionby" name="ddlpermissionby" class="required">
			   <option value="">--- Select ---</option>
			   <?php
			   for($i=0;$i<count($this->permissionby);$i++)
			   {
				?>
			   <option value="<?php echo $this->permissionby[$i]['id'];?>"><?php echo $this->permissionby[$i]['val'];?></option>
		   <?php } ?>
		   </select>
	   </div>    
		<label class="_15 margin_top_10 label_text_align">
		   <?php echo $this->translate->_('Choose').''.$this->required;?>
	   </label>
	   <div class="_25_1 margin_left_right_1">
		   <select id="ddlchoose" name="ddlchoose" class="required" onchange="changeuseracl(this.value);">
			   <option value="">--- Select ---</option>
		   </select>
	   </div>
    </div>
    </form>
    
    <form name="frmomoduleverview" id="frmomoduleverview" class="validate" novalidate action="" method="post">
    <input type="hidden" id="hdDelete" name="hdDelete" value="" />
	<div class="_100" id="allmodule">
		<div class="_5"><input type="checkbox" name="chkallmodule" id="chkallmodule" <?php if((isset($this->formdata["chkallmodule"]) && $this->formdata["chkallmodule"]==1)){ echo 'checked'; }  ?>   value="1"  /></div>
		<label class="_15 margin_top_10 userpermission_lable">
		   <?php echo $this->translate->_('Select All Modules');?>
		</label>
		<div class="_80">&nbsp;</div>
    </div>
	<div class="_100" id="module_list">
		<fieldset class="fieldset_effect">
			<legend class="ttl"><?php echo $this->translate->_('Modules');?></legend>
			<hr id="ie_hr">
				<div class="_100">
					<?php
                        $selected = '';
						for($i=0;$i<count($this->allmodules);$i++) {
                            $selected = 'checked';
							if($i%4 == 0){
								$str .= "</div><div id='checkbox_loop' class='_100'><label class='_10 label_text_align'>&nbsp;</label>";
							}
							$str .= "<div class='_5 margin_bottom_10'><input type='checkbox' class='moduleChks' name='modules[]' value='".$this->allmodules[$i]['id']."' /></div><div class='_20 margin_bottom_10 userpermission_checkbox'> <label class='label_text_align' style='display:inline !important;'>".$this->allmodules[$i]['val']."</label></div>";
						}
						echo $str;
                    ?>
				</div>
		</fieldset>
	</div>
	<div class="_100" style="text-align:center">
		<div class="_40">&nbsp;</div>
		<div class="_20">
			<input type="button" id="btnpopulate" name="btnpopulate" value="<?php echo $this->translate->_('POPULATE');?>">
		</div>
		<div class="_40">&nbsp;</div>
	</div>
    <div class="clear"></div>
    </form>
    
    
    <form name="frmoverview" id="frmoverview" class="validate" method="post" action="" novalidate="novalidate">
    <input type="hidden" id="hdDelete" name="hdDelete" value="" />
    <input type="hidden" id="ddlpermissionby_hid" name="ddlpermissionby_hid" value="" />
    <input type="hidden" id="ddlchoose_hid" name="ddlchoose_hid" value="" />
    <div class="_100">
	    <div class="clean">&nbsp;</div>
        <div class="clean">&nbsp;</div>
	</div>
	
    
	<div class="_100" id="allrow">
		<div class="_5"><input type="checkbox" name="chkallrows" id="chkallrows" value="1" onclick="toggleChecked(this.checked);" ></div>
		<label class="_15 margin_top_10 userpermission_lable">
		   <?php echo $this->translate->_('Select All Rows');?>
		</label>
		<div class="_80">&nbsp;</div>
    </div>
	<div class="_100" id="custom_grid">  
	<!-- Content -->
	<div id="content">
	    <div class="box">
	    <div id="paging_grid" class="padding_zero">
		<div class="grid_12">
		    <div class="box">
			<div style="height:500px;overflow-y:scroll;" class="content min_height_10">
				<table class="table" id="table-example" width="100%">
					<thead>
					    <tr>
							<th width="25%"><a href="javascript:void(0)"><?php echo $this->translate->_('Module')?></a></th>
							<th width="35%"><a href="javascript:void(0)"><?php echo $this->translate->_('Form')?></a></th>
							<th width="10%"><a href="javascript:void(0)" class="_70" ><?php echo $this->translate->_('Read')?></a>
								<input class="save_btn checkbox margin_0 access" type="checkbox" onclick="read_accessclick(this)" name="read_access" id="read_access"></th>
							<th width="10%"><a href="javascript:void(0)" class="_70"><?php echo $this->translate->_('Write')?></a>
								<input class="save_btn checkbox margin_0 access" type="checkbox" onclick="write_accessclick(this)" name="write_access" id="write_access"></th>
							<th width="10%"><a href="javascript:void(0)" class="_70"><?php echo $this->translate->_('Delete')?></a>
								<input class="save_btn checkbox margin_0 access " type="checkbox" onclick="delete_accessclick(this)" name="delete_access" id="delete_access"></th>
							<th width="10%"><a href="javascript:void(0)"><?php echo $this->translate->_('All')?></a></th>
					    </tr>
					</thead>
					<tbody>
						<?php
							$modulename = '';
							for($i=0;$i<count($this->form_data);$i++)
                            {
                                $newformname = str_replace("/","-",$this->form_data[$i]['formname']);
                                $css = $i%2 == 0 ? 'gradeC' : 'gradeA';
                                $class = str_replace(" ","",$this->form_data[$i]['modulename'].$newformname);
                        ?>
                                <tr class="<?php echo $css?>">
                                    <td><?php echo ($modulename != $this->form_data[$i]['modulename']) ? $this->form_data[$i]['modulename'] : ''; ?></td>
                                    <td><?php echo $this->form_data[$i]['formname'];?></td>
                                    <td><input class="read_per checkbox <?php echo $class;?> rwd" type="checkbox" name="read_chk[]" id="<?php echo $class;?>_r" onclick="toggleUnChecked(this.checked,this.value)" value="<?php echo $this->form_data[$i]['moduleid']."_".$this->form_data[$i]['formid'];?>" /></td>
                                    <td><input class="write_per checkbox <?php echo $class;?> rwd" type="checkbox" name="write_chk[]" id="<?php echo $class;?>_w" onclick="toggleUnChecked(this.checked,this.value)" value="<?php echo $this->form_data[$i]['moduleid']."_".$this->form_data[$i]['formid'];?>" /></td>
                                    <td><input class="delete_per checkbox <?php echo $class;?> rwd" type="checkbox" name="delete_chk[]" id="<?php echo $class;?>_d" onclick="toggleUnChecked(this.checked,this.value)" value="<?php echo $this->form_data[$i]['moduleid']."_".$this->form_data[$i]['formid'];?>" /></td>
                                    <td><input class="all_per checkbox all777" type="checkbox" name="all_chk[]" id="<?php echo $class;?>_a" onclick="toggleUnChecked(this.checked,this.value)" value="<?php echo $this->form_data[$i]['moduleid']."_".$this->form_data[$i]['formid'];?>" /></td>
                                </tr>
                        <?php
                                $modulename = $this->form_data[$i]['modulename'];
							}
						?>
					</tbody>
				</table>
			</div>
		    </div> <!-- End of .box -->
		</div>    
		<div class="clean"></div>
	    </div>
        </form>
    
	    </div>
	</div>
	</div>	
        <div class="clear"></div>
    </div>
    <input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?'edit':'add'; ?>">

	<div class="clear"></div>
</div> <!-- End of .box -->
</div>
<script>
    $(window).load(function(){
        $("#close").click(function() {
            parent.eval('$.prettyPhoto.close()');
        });
    });
</script>