<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({
   	url:base_url+"/reports/pricingsummary/pricingsummarydata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Transaction Date');?>','<?php echo $this->translate->_('Transaction Time');?>','<?php echo $this->translate->_('Invoice Number');?>','<?php echo $this->translate->_( 'Customer Code');?>','<?php echo $this->translate->_('Customer Name');?>','<?php echo $this->translate->_('Sales Amount');?>','<?php echo $this->translate->_('Free Amount');?>','<?php echo $this->translate->_('Net Amount');?>'],
   	colModel:[
		{name:'transactiondate',index:'transactiondate', width:75},
        {name:'transactiontime',index:'transactiontime', width:75,align:'center'},
   		{name:'invoicenumber',index:'invoicenumber', width:80,align:'right'},
        {name:'customercode',index:'customercode', width:80},
        {name:'customername',index:'customername', width:250},
		{name:'salesamount',index:'salesamount', width:90,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces }},
        {name:'freeamount',index:'freeamount', width:90,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces }},
        {name:'netamount',index:'netamount', width:90,align:'right',formatter: 'number', formatoptions: { decimalPlaces: decimalplaces }}
	],
    <?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
   	pager: '#pagersr',
   	sortname: 'transactiondate',
	viewrecords:true,
	sortorder: "asc",
   	altRows : false,
    multiselect: false,
	subGrid : true,
	subGridUrl: base_url+"/reports/pricingsummary/pricingsummarysubgriddata/",
    subGridModel: [{ name  : ['<?php echo $this->translate->_('Item Code');?>','<?php echo $this->translate->_('Item Description');?>','<?php echo $this->translate->_('Sales Qty');?>','<?php echo $this->translate->_('Sales Case Price');?>','<?php echo $this->translate->_('Sales Pcs Price');?>','<?php echo $this->translate->_('Std.Case Price');?>','<?php echo $this->translate->_('Std. Pcs Price');?>'], 
                    width : [75,250,60,85,60,85,85],
                    params: ['transactiondate','transactiontime','invoicenumber'],
                    formatter: ['','','','number','number','number','number'],
                    formatoptions: { decimalPlaces: decimalplaces }
                   } 
                  ]
    /*grouping:true,
    groupingView :
    {
        groupField : ['transactiondate'],
        groupColumnShow : [true],
        groupCollapse : true,
        groupOrder: ['asc']
    }*/
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,
);

jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});

</script>