<table>
    <tr>
        <th>Payment Mode</th>
        <th>Cheque Number</th>
        <th>Amount</th>
        <th>Cheque Date</th>
        <th>Bank Code</th>
        <th>Bank Name</th>
    </tr>
    <?php
    
    if(!empty($this->result))
    {
        foreach($this->result as $value)
        {
            
            
            
            ?>
        <tr>
            <?php
            if($value['typecode'] == 1)
            {?>
            
            <td style="text-align:center">Cheque
            <input type="hidden" name="payment_type_detail_7" id="payment_type_detail_7" value="4"/>
            </td>
            <td style="text-align:center">&nbsp;<?php echo $value['checknumber'];?></td>
            <td style="text-align:right"><?php echo $value['amount'];?></td>
            <td style="text-align:center">&nbsp;<?php echo $value['checkdate'];?></td>
            <td style="text-align:center">&nbsp;<?php echo $value['bankcode'];?></td>
            <td style="text-align:center">&nbsp;<?php echo $value['bank_name'];?></td>
            <?php
            }
            else
            {?>
            <td style="text-align:center">Cash
            <input type="hidden" name="payment_type_detail_7" id="payment_type_detail_7" value="0"/>
            </td>
            <td >&nbsp;</td>
            <td style="text-align:right"><?php echo $value['amount'];?></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          <?php   }
            
            ?>
        </tr>        
        <?php
        }
        
    }
    ?>
    
</table>