<?php
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({        
   	url:base_url+"/reports/routesyncstatus/routesyncstatusdata/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Route');?>','<?php echo $this->translate->_('Salesman');?>','<?php echo $this->translate->_('Sync Date');?>','<?php echo $this->translate->_('Sync Time');?>','<?php echo $this->translate->_('Sync Type');?>','<?php echo $this->translate->_('Route Status');?>'],
   	colModel:[
		{name:'routecode',index:'routecode', width:150},
        {name:'salesmanname1',index:'salesmanname1', width:350},
   		{name:'syncdate',index:'syncdate', width:120,align:'center'},
        {name:'synctime',index:'synctime', width:120,align:'center'},
		{name:'synctype',index:'synctype', width:120,align:'center'},
        //{name:'routestatus',index:'routestatus', width:120, formatter:myformatter}
        {name:'routestatus',index:'routestatus', width:120,align:'center'}
	],
    <?php if($this->session->lang == "ar_AR") { ?>
        direction :"rtl", 
    <?php } ?>
	height: 'auto',
    width: eval(reportwidth),
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
    pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "asc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:true,
	groupingView :
    {
        groupField : ['routecode'],
        groupColumnShow : [false],
        groupCollapse : true,
        groupOrder: ['asc'] ,
        groupSummary : [false],
        groupDataSorted : true,
      //  groupText : ['<b>{0}</b> - {routestatus}'],
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,

);


jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    //document.location.href = exporturl;
    return false;
});

//function myformatter ( cellvalue, options, rowObject )
//{
//    if (cellvalue == "LIVE")
//        return '<font color="red">' + cellvalue + '</font>';//or use classes
//}
</script>