<?php
/**
* @name       page.phtml
* @since      13 Oct, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add Customer Debit Note
*/
$this->translate = Zend_Registry::get('Zend_Translate');
$date = $this->date != '' ? $this->date : date('d-m-Y');
?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<script type="text/javascript">
var decimal_places = '<?php echo $this->decimalplaces; ?>';
$(document).ready(function() {
	
	$('#ddlroute_chzn .chzn-drop .chzn-search input[type="text"]').focus();
	$('#ddlroute_chzn').addClass('chzn-container-active');

	$('#ddlroute').change(function(){		
		$.blockUI();		
		getsalesman($('#ddlroute').val(),'');
		$.unblockUI();
	})
	
	$('#ddlcustomer').change(function(){
		
		var customerid 	= $('#ddlcustomer').val();
		var trandate 	= $('#txtdate').val();
		
		$('#txtinvamt').val('0.00');
		$('#txtinvbal').val('0.00');
		$('#txtamount').val('0.00');		
		
		$.blockUI();		
		getinvoices(customerid,trandate,'');
		$.unblockUI();		
		$('#chkfirstout').attr('checked',false);
	})
	
	$('#ddlinvo_num').change(function(){		
		var invoiceno 	= $('#ddlinvo_num').val();
		$.blockUI();		
		getinvoicedetail(invoiceno);
		$.unblockUI();
	})
	
	<?php if($this->params["id"] > 0) { ?>
		getsalesman('<?php echo $this->formdata['routecode'];?>','<?php echo $this->formdata['customercode'];?>');
		getinvoices('<?php echo $this->formdata['customercode'];?>','<?php echo $date;?>','<?php echo $this->formdata['dd_invoicenumber'];?>');
		getinvoicedetail('<?php echo $this->formdata['dd_invoicenumber'];?>');
		$('input[type=text]').attr('readonly',true);
		$('select').attr('disabled',true);
		$('select').trigger('liszt:updated');
	<?php } ?>
	
})
function getinvoices(customerid,trandate,invoiceno)
{
	$('#ddlinvo_num').html('');
	$('#ddlinvo_num').trigger('liszt:updated');
	
	var  url = base_url+'/home/index/getinvoicesfromcustomercode/customerid/'+customerid+'/trandate/'+trandate;
	$.ajax({
		url:url,
		data:$("#frmdetsec").serialize(),
		type:'post',
		success:function(data) {
			var invoice_info = JSON.parse(data);
			if (invoice_info == '')
			{
				return false;
			}
			if(typeof(invoice_info[0]) == 'object')
			{
				$('<option/>').val('').html('--- Select ---').appendTo('#ddlinvo_num');
				for (i=0;i<invoice_info[0].length;i++) {					
					if(invoiceno > 0 && invoiceno == invoice_info[0][i]['id']) {
						$('<option selected />').val(invoice_info[0][i]['id']).html(invoice_info[0][i]['val']).appendTo('#ddlinvo_num');
					}
					else {
						$('<option/>').val(invoice_info[0][i]['id']).html(invoice_info[0][i]['val']).appendTo('#ddlinvo_num');
					}
				}
			}
			$('#ddlinvo_num').trigger('liszt:updated');
		}
	})
}
function getinvoicedetail(invoiceno)
{	
	var  url = base_url+'/home/index/getinvoicedetail/invoiceid/'+invoiceno;
	$.ajax({
		url:url,
		data:$("#frmdetsec").serialize(),
		type:'post',
		success:function(data) {
			var invoice_info = JSON.parse(data);
			if (invoice_info == '')
			{
				return false;
			}			
			var a1 = addCommas(Number(invoice_info[0][0]['totalinvoiceamount']),decimal_places);
			var a2 = addCommas(Number(invoice_info[0][0]['invoicebalance']),decimal_places);
			
			$('#txtinvamt').val(a1);
			$('#txtinvbal').val(a2);			
		}
	})
}
function getsalesman(routeid,customerid)
{
	$('#txtsalesman').val('');
	$('#hdnsalesman').val('');
	$('#ddlinvo_num').val('');
	$('#ddlcustomer').html('');	
	$('#ddlinvo_num').html('');
	$('select').trigger('liszt:updated');
	
	var  url = base_url+'/home/index/getdccustomerfromroutecode/routeid/'+routeid;
	
	$.ajax({
		url:url,
		data:$("#frmdetsec").serialize(),
		type:'post',		
		success:function(data) {
			var salesman_info = JSON.parse(data);
			if (salesman_info == '')
			{
				return false;
			}			
			$('#txtsalesman').val(salesman_info[0][0]['salesmanname1']);
			$('#hdnsalesman').val(salesman_info[0][0]['salesmancode']);
			if(customerid == '')
			{
				$('#hdnmaxid').val(salesman_info[2][0]['lastid']);
				var doc_invo = routeid+''+$('#hdnmaxid').val();
				$('#txtdoc_no').val(doc_invo);
				$('#txtinvo_no').val(doc_invo);
			}
			if(typeof(salesman_info[1]) == 'object')
			{
				$('<option/>').val('').html('--- Select ---').appendTo('#ddlcustomer');
				for (i=0;i<salesman_info[1].length;i++) {
					if(customerid > 0 && customerid == salesman_info[1][i]['id']) {
						$('<option selected />').val(salesman_info[1][i]['id']).html(salesman_info[1][i]['val']).appendTo('#ddlcustomer');
					}
					else {
						$('<option/>').val(salesman_info[1][i]['id']).html(salesman_info[1][i]['val']).appendTo('#ddlcustomer');
					}
				}
			}
			$('#ddlcustomer').trigger('liszt:updated');
		}
	})
}
</script>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_notes_adddebitcustomer">
<form class="validate" method="post" action="" novalidate="novalidate">
    <div class="header">
	<div class="_50_3 back_btn">
	    <img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	    <h3><?php echo $this->translate->_('Debit Note (Customer)');?></h3>
	</div>
	<div class="_50_3">
	    <div class="_10 save_btn">
		    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"notes","action"=>"debitcustomer"),"default", true);?>')">
	    </div>
	    <div class="_10 save_btn">
		<?php if($this->params["id"] > 0) { ?>
			<input class="border_none" type="button" value="" alt="<?php echo $this->baseUrl()."/account/notes/debitcustomer/delid/".$this->params["id"]?>" name="btndeletetran" id="btndeletetran" >
		<?php } else { ?>
			<input class="border_none" type="submit" value="" name="btnsave" id="btnsave">
		<?php } ?>
		</div>
	</div>
    </div>
    <div class="_100" style="text-align:center">
		<div class="_20 label_text_align margin_top_7">&nbsp;</div>
		<div class="_20 label_text_align margin_top_5"><label class="advance_search_css"><?php echo $this->translate->_('Selected Date').''.$this->colan;?></label></div>
		<div class="_20 label_text_align"><input type="text" id="txtdate" name="txtdate" value="<?php echo $date;?>" class="margin_zero"></div>
		<div class="_10 margin_top_3">&nbsp;</div>
		<div class="_30">&nbsp;</div>
	</div>
    <div class="clear space_20"></div>
    <div class="clear"></div>
    <div id="nav_sub" class="ie_nav_sub">
    <div class="container_12">
	<ul id="nav_main">
	    <li class="current">
		<ul style="display: block;">
		    <li>
			<a href="<?php echo $this->url(array("module"=>"account","controller"=>"notes","action"=>"debitcustomer"),"default", true);?>"><?php echo $this->overview?></a>
		    </li>
		    <li class="last-child">
			<a href="<?php echo $this->url(array("module"=>"basic","controller"=>"notes","action"=>"adddebitcustomer"),"default", true);?>"><b><?php echo $this->details;?></b></a>
		    </li>
		</ul>
	    </li>
	</ul>
    </div>
    </div>
    <div class="content with-actions">
	<div class="_100">
	    <div class="clean"></div>
	</div>
	<div class="_100 ">
		<label class="_20_2 label_text_align margin_top_12"><?php echo $this->translate->_('Doc Date').''.$this->colan;?></label>
		<div class="_25_1 margin_right_1 margin_top_10"><?php echo $date;?></div>
	</div>
	<div class="_100">
	     <label class="_20_2 label_text_align margin_top_12">
		<?php echo $this->translate->_('Document No').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
			<input name="txtdoc_no" id="txtdoc_no" type="text" readonly="readonly"  value="<?php echo $this->formdata['documentnumber'];?>" />
	    </div>	
	     <label class="_20_2 label_text_align margin_top_12  margin_right_1">
		<?php echo $this->translate->_('Invoice Number').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">			
			<input name="txtinvo_no" id="txtinvo_no" type="text" readonly="readonly" value="<?php echo $this->formdata['invoicenumber'];?>">
	    </div>
	</div>
	<div class="_100">
	     <label class="_20_2 label_text_align margin_top_12">
		<?php echo $this->translate->_('Route').''.$this->required;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<select id="ddlroute" name="ddlroute" class="required">
		    <option value="">--- Select ---</option>
		    <?php
			    for($i=0;$i<count($this->route);$i++)
			    {
			?>
				<option value="<?php echo $this->route[$i]['id'];?>" <?php if($this->formdata['routecode'] == $this->route[$i]['id']) { echo 'selected';}?> ><?php echo $this->route[$i]['val'];?></option>
			<?php } ?>
		</select>
	    </div>	
	     <label class="_20_2 label_text_align margin_top_12  margin_right_1">
		<?php echo $this->translate->_('Salesman').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
			<input class="margin_top_5" name="txtsalesman" id="txtsalesman" type="text" value="" readonly="readonly" >
	    </div>
	</div>
	<div class="_100 ">
	     <label class="_20_2 label_text_align margin_top_12">
		<?php echo $this->translate->_('Customer').''.$this->required;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<select id="ddlcustomer" name="ddlcustomer" class="required">
		    <option value="">--- Select ---</option>                     
		</select>
	    </div>	
	     <label class="_20_2 label_text_align margin_top_12  margin_right_1">
		<?php echo $this->translate->_('Invoice Number').''.$this->required;?>
	    </label>
	    <div class="_25_1 margin_right_1">
		<select id="ddlinvo_num" name="ddlinvo_num" class="required ">
		    <option value="">--- Select ---</option>		     
		</select> 
	    </div> 
	</div>
	<div class="_100">
	    <label class="_20_2 label_text_align margin_top_12">
			<?php echo $this->translate->_('Invoice Amount').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
			<input name="txtinvamt" id="txtinvamt"  type="text" value=""  readonly="readonly">
	    </div>	
	    <label class="_20_2 label_text_align margin_top_12  margin_right_1">
			<?php echo $this->translate->_('Present Balance').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
			<input name="txtinvbal" id="txtinvbal"  type="text" value="" readonly="readonly" class="margin_top_5">
	    </div>
	</div>
	<div class="_100">
	    <label class="_20_2 label_text_align margin_top_12">
			<?php echo $this->translate->_('Amount').''.$this->required;?>
	    </label>
	    <div class="_25_1 margin_right_1">
			<input name="txtamount" id="txtamount" class="number margin_top_5"  type="text" value="<?php echo number_format($this->formdata['amountpaid'],$this->decimalplaces);?>">
	    </div>	
	    <label class="_20_2 label_text_align margin_top_12  margin_right_1">
			<?php echo $this->translate->_('ERP Reference No.').''.$this->colan;?>	
	    </label>
	    <div class="_25_1 margin_right_1">
			<input name="txterprefnum" id="txterprefnum" class="margin_top_3" type="text" value="<?php echo $this->formdata['erpreferencenumber'];?>" >
	    </div>
	</div>
	<div class="_100">
	     <label class="_20_2 label_text_align margin_top_12">
		<?php echo $this->translate->_('Remark 1').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
			<input name="txtremark1" id="txtremark1" class="margin_top_5" type="text" value="<?php echo $this->formdata['remarks1'];?>" >
	    </div>	
	     <label class="_20_2 label_text_align margin_top_12  margin_right_1">
		<?php echo $this->translate->_('Remark 2').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1">
			<input name="txtremark2" id="txtremark2" class="margin_top_3 type="text" value="<?php echo $this->formdata['remarks2'];?>" >
	    </div>
	</div>		
    </div>
	<input type="hidden" id="hdnsalesman" name="hdnsalesman" value="">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
<input type="hidden" id="hdnmaxid" name="hdnmaxid" value="<?php echo $this->formdata['hdnmaxid'];?>">
</form>
</div>
</div> <!-- End of .box -->