<?php
$this->translate = Zend_Registry::get('Zend_Translate');
$date = $this->date != '' ? $this->date : date('d-m-Y');
?>
<style>
.margin_zero {margin-top:0px !important;}
</style>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png" class="margin_top_7">
		<h3><?php echo $this->translate->_('Credit Note (Route)');?></h3>
	    </div>
	    <div class="_50_3">
		<!--<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnexport" id="btnexport"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint"></div>-->
		<?php if($this->checkaccess("delete")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" name="btndelete" id="btndelete"></div><?php } ?>		
		<?php if($this->checkaccess("insert")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnadd" name="btnadd" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"notes","action"=>"addcreditroute"), "default", true);?>')"></div><?php } ?>
	    </div>
        </div>
	<div class="_100" style="text-align:center">
		<div class="_20 label_text_align margin_top_7">&nbsp;</div>
		<div class="_20 label_text_align margin_top_7"><?php echo $this->translate->_('Select Date');?></div>
		<div class="_15 label_text_align"><input type="text" id="txtdate" name="txtdate" value="<?php echo $date; ?>" class="margin_zero"></div>
		<div class="_10"><input type="submit" name="btnload" id="btnload" value="<?php echo $this->translate->_('OK');?>" class="margin_zero"></div>
		<div class="_30">&nbsp;</div>
	</div>
	<div class="clear space_20"></div>
	<div class="clear"></div>
	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>