<?php
/**
* @name       modeof payment.phtml
* @since      19-07-2012
* @version    Release: 1.0
* @author     Rachir <kanzaria.rachir@elantechnologies.com>
* @copyright  2012 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');

$payment_mode ="";

if($this->paymentdata['typecode'] == 0) // i.e. payment done by cash
{
	$payment_mode = $this->translate->_('CASH') ;
}
else // Payment done by check
{
	$payment_mode = $this->translate->_('CHEQUE') ;
}

?>
<!-- Payment Details -->
<fieldset class="margin_left_0 margin_right_0">
	<legend><?php echo $this->translate->_('Payment Details');?></legend>	
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
			<?php echo $this->translate->_('Amount Paid').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_12">		
			<b><?php echo number_format($this->paymentdata['amount'],$this->decimalplaces); ?></b>
	    </div>
		<label class="_25_1 label_text_align margin_top_12">
		    <?php echo $this->translate->_('Payment Mode').''.$this->colan;?>
		</label>
		<div class="_25_1  margin_top_12">
		    <b><?php echo $payment_mode;?></b>
		</div>
	</div>	
	<?php if($this->paymentdata['typecode'] == 1) { // Payment done by check ?>
	<div class="_100">
	    <label class="_25_1 label_text_align margin_top_12">
			<?php echo $this->translate->_('Cheque No').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_12">
			<b><?php echo $this->paymentdata['checknumber']; ?></b>
	    </div>
	    <label class="_25_1 label_text_align margin_top_12">
			<?php echo $this->translate->_('Cheque Date').''.$this->colan;?>
	    </label>
	    <label class="_25_1  margin_top_12 margin_right_1">
			<b><?php echo date('d-m-Y',strtotime($this->paymentdata['checkdate'])); ?></b>
	    </label>
	</div>
	<div class="_100">	    
	    <label class="_25_1 label_text_align margin_top_12">
			<?php echo $this->translate->_('Bank Name').''.$this->colan;?>
	    </label>
	    <div class="_25_1 margin_right_1 margin_top_12">
			<b><?php echo $this->paymentdata['bankname']; ?></b>
	    </div>
	</div>	
	<?php } ?>
</fieldset>