<?php
/**
* @name       addcustomer.phtml
* @since      17 Feb, 2012
* @version    Release: 1.0
* @author     PM <pankit@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="account_settlement_addcashreceipt">
<form name="frmoverview" id="frmoverview" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png">
	<h3><?php echo $this->translate->_('Batch Detail');?></h3>
    </div>
    <div class="_50_3">
	&nbsp;
    </div>
</div>
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clean"></div>
	</div>	
	<div class="_100">
	    <div class="clean"></div>
	</div>
		<div class="_100">
            <?php echo  $this->partial('datagrid.phtml', $this); ?>
        </div>        
    </div>
    <div class="clear"></div>
    <div class="clear"></div>    
</form>
 </div><!-- End of .box -->
</div>