<?php
/**
* @name       viewcustomerinventory.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<script>
        $(document).ready(function(){
            loaddata_popup('<?php echo $this->itemgrid; ?>','item-grid');
        })
    </script>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="hhctransaction_load_viewcustomerinventory">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>" />
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_10"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_hhctransaction.png">
        <h3><?php echo $this->translate->_('Inventory Summary')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"inventory","action"=>"customerinventory"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn">&nbsp;</div>
    </div>
</div>
<div id="nav_sub" class="ie_nav_sub" >
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"hhctransaction","controller"=>"inventory","action"=>"inventorysummary"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="javascript:;" class="admin_active"><?php echo $this->details;?></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>
<div class="content with-actions ie_grid min_height_10" style="padding-bottom: 20px;">
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="_100">
	    <div class="clear"></div>
	</div>
	<div class="clear space_20">&nbsp;</div>
	<div id="loader"></div>
	<div class="_100">
		<div id="item-grid" style="overflow-x:auto;">&nbsp;</div>
	</div>
	<div class="clear space_20">&nbsp;</div>
</div>
</form>
</div> <!-- End of .box -->
</div>