<?php
/**
* @name       addqualificationgrp.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<script>
        $(document).ready(function(){
		$('#txtgrp_desc').focus();
		loaddata('<?php echo $this->itemgrid; ?>','item-grid');
		$("#sbtnadd").click(function(){
			if(!$("#frmdet").valid()){
			    return false;
			}else{
				var values = $('#frmdet').serialize();
				$.ajax({
				    type : "POST",
				    url : base_url+"/promotions/index/qualificationgrpitemgrid/key/<?php echo $this->params["id"]; ?>",
				    data :values+'&add=yes',
				    success:function(returndata){
					$("#ddlitem_code").val("");
					$("#txtquantity").val("");
					$('select').trigger('liszt:updated');
					$('#item-grid').html(returndata); 
				    }
				});
			}
		});
		$("#btnsave").click(function(){
		    $("#ddlitem_code").removeClass('required');
		});
        })
</script>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="promotion_index_qualigrp">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png">
        <h3><?php echo $this->translate->_('Qualification Group')?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"promotions","controller"=>"index","action"=>"qualificationgrp"), "default", true);?>')" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div class="clear"></div>
<div class="clear"></div>
<div id="nav_sub" class="ie_nav_sub">
<div class="container_12">
    <ul id="nav_main">
        <li class="current">
            <ul style="display: block;">
                <li>
                    <a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"index","action"=>"qualificationgrp"),"default", true);?>"><?php echo $this->overview?></a>
                </li>
                <li class="last-child">
                    <a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"index","action"=>"addqualificationgrp"),"default", true);?>"><b><?php echo $this->details;?></b></a>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>

<div class="content with-actions min_height_10">
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<label class="_40 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Group Number').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtgrp_num" name="txtgrp_num" value="<?php echo $this->formdata['txtgrp_num']; ?>" readonly="readonly">
	</div>

    </div>
    <div class="_100">
	<label class="_40 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Description').''.$this->required;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text"  maxlength="50" id="txtgrp_desc" name="txtgrp_desc" value="<?php echo $this->formdata['txtgrp_desc']; ?>" class="required margin_top_5">
	</div>

    </div>
    <div class="_100 ">
	<label class="_40 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text"  class="arb_text_align margin_top_5"  maxlength="50"  id="txtgrp_arb" name="txtgrp_arb" value="<?php echo $this->formdata['txtgrp_arb']; ?>">
	</div>

    </div>
    <div class="_100">
		<label class="_40 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Item Code').''.$this->colan;?>
		</label>
		<div class="_50 margin_right_1">
			<select id="ddlitem_code" name="ddlitem_code" class="required">
			<option value="">--- Select ---</option>
			<?php
			for($i=0;$i<count($this->itemcode);$i++)
			{
			?>
				<option <?php echo $this->itemcode[$i]['id'] == '1' ? 'selected' : '' ;?> value="<?php echo $this->itemcode[$i]['id'];?>"><?php echo $this->itemcode[$i]['val'];?></option>
			<?php } ?>
			</select>
		</div>
	</div>
	 <div class="_100 ">
	<label class="_40 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text"  class="arb_text_align margin_top_5"  maxlength="50"  id="txtgrp_arb" name="txtgrp_arb" value="<?php echo $this->formdata['txtgrp_arb']; ?>">
	</div>

    </div>
	<?php if($this->add_quantity) { ?>
	<div class="_100">
		<label class="_40 margin_top_12 label_text_align">
			<?php echo $this->translate->_('Quantity').''.$this->colan;?>
		</label>
		<div class="_50 margin_right_1">
			<input type="text" id="txtquantity" name="txtquantity" value="" class="number margin_top_5" />
		</div>
	</div>
	<?php } ?>
	<div class="_100">
		<div class="_90">&nbsp;</div>
		<div class="_5_3">
			<input type="button" name="sbtnadd" id="sbtnadd" value="<?php echo $this->translate->_('ADD'); ?>" class="margin_top_5">
		</div>
    </div>
	<div class="_100">
		<?php if($this->params["edit"]=="yes") { ?>
		<label class="_40 margin_top_10 label_text_align">
          		<?php echo $this->translate->_('Created Date').''.$this->colan;?>
		</label>
			<div class="_50 margin_top_10 date_color margin_right_1">
				<?php echo  $this->formdata['createddate'];?></div>
		<?php } else { ?>
			<div class="_50">&nbsp;</div>
		<?php } ?>
	</div>

</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:$this->formdata['txtgrp_num']; ?>">
</form>
<div class="content with-actions min_height_10">
    <form id="frmdetsec" name="frmdetsec" class="validate" novalidate action="" method="post">
	<div class="_100 margin_top_25">
	    <fieldset id="ab" name="ab" class="fieldset_effect">
		<legend class="ttl"><?php echo $this->translate->_('Qualification Group');?></legend>
		<hr id="ie_hr" >
		<div class="_5 clear_only">&nbsp;</div>
		<div class="_100">
		    <div id="loader"></div>
		    <div id="item-grid"> <!--grid load here --> </div>
		    <input type="hidden" id="hdngroupno" name="hdngroupno" value="<?php echo $this->params["id"]; ?>">
		</div>
		</div>
	    </fieldset>
	</div>
    </form>
</div>
</div> <!-- End of .box -->
</div>