<style>
.margin_zero {margin-top:0px !important;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
    <input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
		<img src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png" class="margin_top_7">
		<h3><?php echo $this->title?></h3>
	    </div>
	    <div class="_50_3">
		<!--<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnexport" id="btnexport"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btnprint" id="btnprint"></div>-->
		<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btndelete" id="btndelete"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnedit" name="btnedit"></div>
		<div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnadd" name="btnadd" onclick="winloc('<?php echo $this->url(array("module"=>"promotions","controller"=>"index","action"=>"addcustomerpromo"), "default", true);?>')"></div>
	    </div>
        </div>
	<div class="clear"></div>
	<div class="clear"></div>
        <div id="nav_sub" class="ie_nav_sub">
	<div class="container_12">
	    <ul id="nav_main">
		<li class="current">
		    <ul style="display: block;">
			<li>
			    <a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"index","action"=>"customerpromo"),"default", true);?>"><b><?php echo $this->overview?></b></a>
			</li>
			<li class="last-child">
			    <a href="<?php echo $this->url(array("module"=>"promotions","controller"=>"index","action"=>"addcustomerpromo"),"default", true);?>"><?php echo $this->details;?></a>
			</li>
		    </ul>
		</li>
	    </ul>
	</div>
	</div>
	<?php echo $this->partial('datagrid.phtml', $this); ?>
        <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>
<script type="text/javascript">
$(window).load(function() {
    $(function() {
	$( "#txtdate" ).datepicker({
	    dateFormat: 'dd-mm-yy'
	});
    });
});
</script>