<?php
/**
* @name       index.phtml
* @since      19 Dec, 2011
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
* Add setting of customer
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12">
<div class="box" id="promotion_index_addcustomerpricingheader">
<form id="frmdetail" name="frmdetail" class="validate" novalidate action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png">
	<h3><?php echo $this->translate->_('Pricing Control Header');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn"><input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"customer","action"=>"template"),"default", true);?>')"></div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>    
</div>
<?php if($this->success) { ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo $this->success?></strong>
    </div>
<?php } ?>
    <div class="content with-actions min_height_10">
	<div class="_100">
	    <div class="clean"></div>
	</div>	
	<div class="_100 margin_top_10">
	    <label class="_25_1 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Detail Key').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtpromo_key" name="txtpromo_key" value="">
	    </div>	    
	    <label class="_25_1 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Start Date').''.$this->required;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtstartdate" name="txtstartdate" value="" class="required">
	    </div>
	</div>
	<div class="_100">
	    <label class="_25_1 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Description').''.$this->required;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtdesc" name="txtdesc" value="" class="required">
	    </div>
	    <label class="_25_1 margin_top_15 label_text_align">
		<?php echo $this->translate->_('End Date').''.$this->required;?>
	    </label>
	    <div class="_25_1">
		<input type="text" id="txtenddate" name="txtenddate" value="" class="required">
	    </div>
	</div>
	<div class="_100 margin_bottom_10">
	    <label class="_25_1 margin_top_15 label_text_align">
		<?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
	    </label>
	    <div class="_25_1">
		<input type="text"  class="arb_text_align"  id="txtdesc_arb" name="txtdesc_arb" value="">
	    </div>	    
	</div>
    </div>
</form>
<form id="frmsec" name="frmsec" class="validate" novalidate action="" method="post">
    <div class="content with-actions">	
	<fieldset>
	    <legend><?php echo $this->translate->_('Item Price')?></legend>
	    <div class="_100">
		<label class="_25_1 margin_top_12 label_text_align _23">
		   <?php echo $this->translate->_('Item Code').''.$this->required;?>
		</label>
		<div class="_25_1 margin_right_1">
		    <select id="ddlitem_code" name="ddlitem_code" class="required">
			<option value="">--- Select ---</option>
		    </select>
		</div>
		<label class="_25_1 margin_top_15 label_text_align ">
		   <?php echo $this->translate->_('%on Sales Piece Price').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtpiece_price" name="txtpiece_price" value="">
		</div>
	    </div>
	    <div class="_100">
		<label class="_25_1 margin_top_15 label_text_align _23">
		   <?php echo $this->translate->_('UPC').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtupc" name="txtupc" value="">
		</div>
		<label class="_25_1 margin_top_15 label_text_align ">
		    <?php echo $this->translate->_('%on Return Piece Price').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtreturn_price" name="txtreturn_price" value="">
		</div>		
	    </div>
	    <div class="_100">
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('Price Tax 1').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtpricetax1" name="txtpricetax1" value="">
		</div>
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('Sales Piece Price').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtsls_piece" name="txtsls_piece" value="">
		</div>
	    </div>
	    
	    <div class="_100">
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('Price Tax 2').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtpricetax2" name="txtpricetax2" value="">
		</div>
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('Return Piece Price').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtreturn_piece" name="txtreturn_piece" value="">
		</div>
	    </div>
	    
	    <div class="_100">
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('Price Tax 3').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtpricetax3" name="txtpricetax3" value="">
		</div>
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('Sales Case Price').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtsls_case" name="txtsls_case" value="">
		</div>
	    </div>	    
	    <div class="_100">
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('StdUnitSalesPrice').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtstdsalesprice" name="txtstdsalesprice" value="">
		</div>
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('Return Case Price').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtret_case" name="txtret_case" value="">
		</div>
	    </div>
	    
	    <div class="_100">
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('StdUnitReturnPrice').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtstdreturnprice" name="txtstdreturnprice" value="">
		</div>		
	    </div>
	    <div class="_100">
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('StdSaleCasePrice').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtstdsalescase" name="txtstdsalescase" value="">
		</div>		
	    </div>
	    <div class="_100">
		<label class="_25_1 margin_top_15 label_text_align _23">
		    <?php echo $this->translate->_('StdReturnCasePrice').''.$this->colan;?>
		</label>
		<div class="_25_1">
		    <input type="text" id="txtstdreturncase" name="txtstdreturncase" value="">
		</div>
		<label class="_25_1 margin_top_15 label_text_align _23">&nbsp;</label>
		<div class="_5_button">
		    <input type="submit" id="txtsubadd" name="txtsubadd" value="<?php echo $this->translate->_('ADD');?>">
		</div>
	    </div>
	    
	</fieldset>
    </div>
</form>
</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
    $("a[class^='ico edit']").prettyPhoto({animation_speed:'fast',theme:'light_rounded', allowresize: false});
    
    $("#btncancel").click(function() {
	winloc('<?php echo $this->url(array("module"=>"promotions","controller"=>"index","action"=>"customerpriceplan"), "default", true)?>')
    });
});
</script>