<?php
/**
* @name       addcustomerpromo.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');

/* $this->headScript()->appendFile($this->baseUrl().'/public/js/jquery.prettyPhoto.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/public/css/prettyPhoto.css'); */
$promo_plan_url = $this->url(array("module"=>"promotions","controller"=>"index","action"=>"customerpriceheader"), "default", true);
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="promotion_index_addcustomerpricingplan">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post" target="_parent">
<div class="header ie_header_height">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png">
        <h3><?php echo $this->translate->_('Customer Pricing Plan');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>

<div class="content with-actions ie_grid min_height_10">
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<div class="clear"></div>
    </div>

    <div class="_100 margin_top_10">
	<label class="_40 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Customer Pricing Plan Key').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtplan_key" name="txtplan_key" value="">
	</div>
    </div>
    <div class="_100">
	<label class="_40 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Description').''.$this->required;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtdesc" name="txtdesc" value="" class="required">
	</div>
    </div>
    <div class="_100 margin_bottom_5">
	<label class="_40 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text"  class="arb_text_align"  id="txtdesc_arb" name="txtdesc_arb" value="">
	</div>
    </div>
    <div class="clear"></div>
    <div class="clear"></div>

    <fieldset class="fieldset_effect">
	<legend class="ttl" ><?php echo $this->translate->_('Customer Pricing Plan');?></legend>
	<hr id="ie_hr" >
	<div class="_5 clear_only">
	    <input class="border_none" type="button" value="" id="btnadd" onclick="winloc('<?php echo $promo_plan_url;?>');">
	</div>
	<div class="_100">
	    <?php echo $this->partial('datagrid.phtml', $this); ?>
	</div>
    </fieldset>
    <div class="clear"></div>
    <div class="clear"></div>

</div>
</form>
</div> <!-- End of .box -->
</div>
<script type="text/javascript">
$(window).load(function() {
    $("#btncancel").click(function() {
	parent.eval('$.prettyPhoto.close()');
    });
});
</script>