<?php
/**
* @name       addcustomerpromo.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');

/* $this->headScript()->appendFile($this->baseUrl().'/public/js/jquery.prettyPhoto.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/public/css/prettyPhoto.css'); */

$promo_plan_url = $this->url(array("module"=>"promotions","controller"=>"index","action"=>"promotionrange"), "default", true);

?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
<script>
    $(document).ready(function(){
	loaddata('<?php echo $this->itemgrid; ?>','item-grid');
    })
</script>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<div class="grid_12">
<div class="box" id="promotion_index_custpromoplan">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post" target="_parent">
<div class="header ie_header_height">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png">
        <h3><?php echo $this->translate->_('Customer Promotion Plan');?></h3>
    </div>
    <div class="_50_3">
	<div class="_10 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="parent.$.prettyPhoto.close();" >
	</div>
	<div class="_10 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>
<div id="ie_spacer" ></div>
<div class="content with-actions ie_grid min_height_10">
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<div class="clear"></div>
    </div>

    <div class="_100 margin_top_10">
	<label class="_25_1 margin_top_17 label_text_align">
	    <?php echo $this->translate->_('Promotion Key').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtpromo_key" name="txtpromo_key" value="92">
	</div>
	<label class="_25_1 margin_top_17 label_text_align">
	    <?php echo $this->translate->_('Start Date').''.$this->required;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtstartdate" name="txtstartdate" value="18/01/2012" class="required">
	</div>
    </div>
    <div class="_100 margin_bottom_5">
	<label class="_25_1 margin_top_17 label_text_align">
	    <?php echo $this->translate->_('PromotionPlan No.').''.$this->required;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtplanno" name="txtplanno" value="22" class="required">
	</div>

	<label class="_25_1 margin_top_17 label_text_align">
	    <?php echo $this->translate->_('End Date').''.$this->required;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtenddate" name="txtenddate" value="29/02/2012" class="required">
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Description').''.$this->required;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtdesc" name="txtdesc" value="7% OFF ON SALE" class="required margin_top_5">
	</div>
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Exclution Option').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <select id="ddlexcl_opt" name="ddlexcl_opt">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->exclution_option);$i++)
		    {
		?>
			<option value="<?php echo $this->exclution_option[$i]['id'];?>" <?php echo ($this->exclution_option[$i]['id'] == 1)? 'selected' : ''; ?> ><?php echo $this->exclution_option[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Description ('.$this->sec_lang.')').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text"  class="arb_text_align"  id="txtdesc_arb" name="txtdesc_arb" value="" class="margin_top_3">
	</div>
	<!--<div class="_25_1 label_text_align  margin_top_10"><input type="checkbox" id="chkactive" name="chkactive" value="1" ></div>
	<label class="_25_1 margin_top_20">
	    <?php //echo $this->translate->_('Active');?>
	</label>-->
    </div>
    <div class="_100 margin_top_3">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Promotion Type').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <select id="ddlpromo_type" name="ddlpromo_type">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->promotion_type);$i++)
		    {
		?>
			<option value="<?php echo $this->promotion_type[$i]['id'];?>" <?php echo ($this->promotion_type[$i]['id'] == 5)? 'selected' : ''; ?>><?php echo $this->promotion_type[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>

	<label class="_25_1 margin_top_17 label_text_align">&nbsp;</label>
	<div class="_25_1">&nbsp;</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Range Basis').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <select id="ddlrange_basis" name="ddlrange_basis">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->range_basis);$i++)
		    {
		?>
			<option value="<?php echo $this->range_basis[$i]['id'];?>" <?php echo ($this->range_basis[$i]['id'] == 3)? 'selected' : ''; ?> ><?php echo $this->range_basis[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>

	<label class="_25_1 margin_top_17 label_text_align">&nbsp;</label>
	<div class="_25_1">&nbsp;</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Amount Basis').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <select id="ddlamt_basis" name="ddlamt_basis">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->amount_basis);$i++)
		    {
		?>
			<option value="<?php echo $this->amount_basis[$i]['id'];?>" <?php echo ($this->amount_basis[$i]['id'] == 1)? 'selected' : ''; ?> ><?php echo $this->amount_basis[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
	<label class="_25_1 margin_top_17 label_text_align">&nbsp;</label>
	<div class="_25_1">&nbsp;</div>
    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Qualification Group').''.$this->required;?>
	</label>
	<div class="_25_1">
	    <select id="ddlquali_grp" name="ddlquali_grp" class="required">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->quali_grp);$i++)
		    {
		?>
			<option selected="selected" value="<?php echo $this->quali_grp[$i]['id'];?>"><?php echo $this->quali_grp[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
	<div class="_5">&nbsp;</div>
	<div class="_10"><input type="submit" id="btnshow" name="btnshow" value="<?php echo $this->translate->_('Show');?>"></div>

    </div>
    <div class="_100">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Assigngment Group').''.$this->required;?>
	</label>
	<div class="_25_1">
	    <select id="ddlassign_grp" name="ddlassign_grp" class="required">
		<option value="">--- Select ---</option>
		<?php
		    for($i=0;$i<count($this->assign_grp);$i++)
		    {
		?>
			<option selected="selected" value="<?php echo $this->assign_grp[$i]['id'];?>"><?php echo $this->assign_grp[$i]['val'];?></option>
		<?php } ?>
	    </select>
	</div>
	<div class="_5">&nbsp;</div>
	<div class="_10"><input type="submit" id="btnshow" name="btnshow" value="<?php echo $this->translate->_('Show');?>"></div>
    </div>
    <div class="_100 margin_bottom_20">
	<label class="_25_1 margin_top_12 label_text_align">
	    <?php echo $this->translate->_('Assignment No.').''.$this->colan;?>
	</label>
	<div class="_25_1">
	    <input type="text" id="txtassign" class="margin_top_5" name="txtassign" value="1008" >
	</div>
	<label class="_15 label_text_align  margin_top_17">
	    <?php echo $this->translate->_('Case Only');?>
	</label>
	<div class="_5 margin_top_5 margin_right_1"><input type="checkbox" id="chkiscase" name="chkiscase" value="1" checked="checked" ></div>	
	<label class="_15 label_text_align  margin_top_17">
	    <?php echo $this->translate->_('One Time Use');?>
	</label>
	<div class="_5 margin_top_5 margin_right_1"><input type="checkbox" id="chkonetimeuse" name="chkonetimeuse" value="1" checked="checked" ></div>
    </div>

    <div class="clear space_50"></div>
    <fieldset class="fieldset_effect">
	<legend class="ttl" ><?php echo $this->translate->_('Customer Promotion Plan');?></legend>
	<hr id="ie_hr" >
	<div class="_5 clear_only">
	    <input class="border_none" type="button" value="" id="btnadd" onclick="winloc('<?php echo $promo_plan_url;?>');">
	</div>
	<div class="_100">
	    <div id="loader"></div>
	    <div id="item-grid"> <!--grid load here --> </div>
	</div>
    </fieldset>
    <div class="clear"></div>
    <div class="clear"></div>

</div>
</form>
</div> <!-- End of .box -->
</div>