<?php
/**
* @name       addcustomerpromo.phtml
* @since      26 jan, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/

$this->translate = Zend_Registry::get('Zend_Translate');
?>
<div class="clean"></div>
<div class="grid_12 margin_bottom_10">
<div class="box" id="promotion_index_custpromorange">
<form id="frmdet" name="frmdet" class="validate" novalidate action="" method="post">
<div class="header">
    <div class="_50_3 back_btn">
	<img class="margin_top_7"  alt="" src="<?php echo $this->baseUrl()?>/public/images/icon_promotions.png">
        <h3><?php echo $this->translate->_('Promotion Range');?></h3>
    </div>
    <div class="_50_3">
	<div class="_15 save_btn">
	    <input class="border_none" type="button" value="" name="btncancel" id="btncancel" onclick="winloc('<?php echo $this->url(array("module"=>"promotions","controller"=>"index","action"=>"customerpromoplan"), "default", true);?>');" >
	</div>
	<div class="_15 save_btn"><input class="border_none" type="submit" value="" name="btnsave" id="btnsave"></div>
    </div>
</div>

<div class="content with-actions min_height_10">
    <div class="_100">
	<div class="clear"></div>
    </div>
    <div class="_100">
	<div class="clear"></div>
    </div>

    <div class="_100 margin_top_10">
	<label class="_40 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Range Low').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtrange_low" name="txtrange_low" value="">
	</div>
    </div>
    <div class="_100 margin_top_10">
	<label class="_40 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Range High').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtrange_high" name="txtrange_high" value="">
	</div>
    </div>
    <div class="_100 margin_top_10">
	<label class="_40 margin_top_10 label_text_align">
	    <?php echo $this->translate->_('Repeating Range').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <div class="_10 margin_right_1" id="en_margin_right">
		<input type="checkbox" id="chkcheck" name="chkcheck" value="1">
	    </div>
	    <div class="_25 margin_top_10 margin_right_1" >
		<?php echo $this->translate->_('Check');?>
	    </div>
	    <div class="_10">
		<input type="checkbox" id="chkuncheck" name="chkuncheck" value="0">
	    </div>
	    <div class="_20_2 margin_top_10">
		<?php echo $this->translate->_('Uncheck');?>
	    </div>
	</div>
    </div>
    <div class="_100 margin_top_10">
	<label class="_40 margin_top_15 label_text_align">
	    <?php echo $this->translate->_('Promotion Amount').''.$this->colan;?>
	</label>
	<div class="_50 margin_right_1">
	    <input type="text" id="txtpromo_amt" name="txtpromo_amt" value="">
	</div>
    </div>
    <div class="margin_bottom_15">&nbsp;</div>
</div>
<input type="hidden" id="hdnid" name="hdnid" value="<?php echo $this->params["edit"]=="yes"?$this->params["id"]:0; ?>">
</form>
</div> <!-- End of .box -->
</div>